### ISSUE TITLE
Impossible to open hOCR file

### ISSUE THREAD

**Issue by CharlesNepote** [manisandro/gImageReader#100]
1. Launch a recognition in hOCR mode
2. Save as hOCR text
3. Open hOCR file (the one previously saved):
```
The file does not appear to contain valid hOCR HTML:
```

It seems to come from the new DTD (HTML 5). The file can be reloaded if I modify by hand the code at the beginning of the hOCR file. This following code is ok:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title></title>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
```

**Comment by CharlesNepote** [comment]
Tested from last git sources.

(By the way, thank you very much Sandro for the improvments you've made!)

**Comment by manisandro** [comment]
Oh indeed, that broke it with qt... Should be fixed with b834d5 and cdc903.
Thank you for all the testing and suggestions!
