### ISSUE TITLE
hocr-check complain assert doc.xpath("//meta[@name='ocr-id']")!=[]

### ISSUE THREAD

**Issue by CharlesNepote** [manisandro/gImageReader#101]
I was trying to play with hocr-tools -- https://github.com/tmbdev/hocr-tools -- to merge hOCR and jpeg in a single PDF and notice that the hocr-check tools complains when I feed it with an hOCR file produced by gImageReader.
```
$ hocr-check 20160815.html
Traceback (most recent call last):
  File "/usr/local/bin/hocr-check", line 85, in <module>
    assert doc.xpath("//meta[@name='ocr-id']")!=[]
AssertionError
```

I'm not sure it's an issue because hOCR spec doesn't talk about 'ocr-id' tag...

**Comment by manisandro** [comment]
Well I suppose I could add it - what value to other OCR applications set for `ocr-id`?

**Comment by CharlesNepote** [comment]
I close the issue as hocr-check developpers agreed `ocr-id` is not in the spec and should not be used.
They are going to correct hocr-check code.
