### ISSUE TITLE
scripting with gimagereder

### ISSUE THREAD

**Issue by grauschnabel** [manisandro/gImageReader#103]
Hi there,

gImageReaer does what I want, and its really great, with a view steps i get the result I want (scanned pdf to pdf with hidden text, so its searchable by recoll).

BUT:  Can I make that scriptable?  I would like to do this now with about 300 documents, so a script to start and go for a coffee would be great,  any Ideas?

Thanks,
Martin

**Comment by manisandro** [comment]
Thanks for the suggestion. Currently there is no scripting capability built into gImageReader. I have some ideas how it could be done, but it will require some effort. Definitely won't be part of the 3.2.x release cycle though.

**Comment by doplu** [comment]
I second Martin's idea : select a source folder and process the OCR automatically, one by one, for all the pdf files contained inside even its sub folders. Thanks in advance and congrats for all the job already done. ;)

**Comment by grauschnabel** [comment]
i would like to have that too

**Comment by shajanjp** [comment]
Thats a great idea @grauschnabel That feature will save valuable hours of humans ;)

**Comment by grauschnabel** [comment]
interesting, I answered on 2017-01-21 to my own issue from 2016-09-30, without mention that this was I who created this.

**Comment by manisandro** [comment]
I'm currently too busy to do some serious work on gImageReader, things should be a bit calmer in fall/winter. If anyone wants to have a shot at implementing this, I'm happy to answer questions about the codebase etc.

**Comment by manisandro** [comment]
I've now implemented a batch mode (Qt interface only at the moment): when you select multiple sources, you can now process them on-block source-wise, the output is saved side-by-side to each source file.

**Comment by manisandro** [comment]
I'll close this, I believe the batch has addressed the main request here. Otherwise, feel free to reopen.

**Comment by tukusejssirs** [comment]
@manisandro, is this ported to the GTK version too? I use that one, but when I press `Recognize` without selected an image (from multiple loaded), it processes only the open image; and when I select all of them, none is recognised.
