### ISSUE TITLE
Is it possible to open tif files?

### ISSUE THREAD

**Issue by CharlesNepote** [manisandro/gImageReader#105]
A small issue: with latest git sources I'm not able to open tif files. Clicking on "add images" button, jpeg and files are shown in the dialog box but none of the .tiff files. If it's normal, it could be interesting to be more precise in the documentation and maybe, even in the interface. Something like "gImageReader can open jpeg and pdf files".

**Comment by manisandro** [comment]
gImageReader supports and raster file format which is supported by the respective toolkit, so:
- qt: basically each format for which there is a plugin installed in `/usr/lib64/qt5/plugins/imageformats/` or similar. Typically provided by the `qt5-qtimageformats` package
- gtk: each format for which there is a plugin installed in `/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders` or similar. Typically provided by the `gdk-pixbuf2-modules` package

(Note: above are Fedora paths and package names, may vary on other distros).

I've tweaked the debian control file to add a suggests on qt5-image-formats-plugins (c9494eb), but beyond that it's a matter of distro setup which formats are supported.

**Comment by CharlesNepote** [comment]
Thanks Sandro! I installed qt5-image-formats-plugins and it worked: I can now open .tif files.
Putting `Suggests: qt5-image-formats-plugins` in debian/control is good. I would also suggest to add a notice somewhere in the documentation.
Or maybe we could open the wiki pages on github to add informations such as a FAQ and so on.

**Comment by manisandro** [comment]
Yeah it might be a cool thing to have a FAQ section on the wiki, and perhaps even put the manual there with some screenshots. If you have any ideas for FAQ etc, happy to hear them (users perspective is always better than developers perspective ;))

**Comment by CharlesNepote** [comment]
Below, some Q&A that can make a good start?

Q: When will the next version be released?
A: When it's ready. gImageReader is open source software and rely on the community's efforts. There is no engagement for the next release, even if we're doing our best.

Q: I found a bug! Where can I give feedback?
A: The bug tracker on github is the place to do so: https://github.com/manisandro/gImageReader/issues

Q: Can you implement XXXXXX functionnality?
A: Each request is discussed via the issue-tracker system: just suggest a new one: https://github.com/manisandro/gImageReader/issues/new

Q: I want to help testing last functionalities: how can I compile the software?
A: link

Q: What format can I use for input documents?
PDF and JPEG files should be ok whatever configuration you have. On Linux Debian/Ubuntu, you'll have to install qt5-image-formats-plugins to deal with TIFF files.

Q: Is it possible to use different Recognition engines?
A: Not at that time. Tesseract is the only recognition engine supported.

Q: In hOCR mode a word is split in two parts "commu" "nication", how can I fix that?
A: Select the two boxes, right-clic whith the mouse and use "merge" option.

**Comment by manisandro** [comment]
(That said, if you find any nasty issues with the current master, please alert me ;))
