### ISSUE TITLE
Use XXX dpi for recognition and then ouput PDF at yyy dpi

### ISSUE THREAD

**Issue by CharlesNepote** [manisandro/gImageReader#106]
To reproduce the issue.
1. Open a PDF document at 600 dpi (in fact with background images at 600 dpi).
2. OCR this document (by default it has been converted by gImageReader at 300 dpi but one can change to 600 dpi for example)
3. Change resolution to 150 dpi
4. Choose Export PDF option => the document is exported at 300 dpi and not at 150 dpi.

For me it's important because I produce documents in two flavours:
* one to be red (150 dpi or less)
* one to be printed (600 dpi)
But I don't want to have to OCR at 150 dpi to produce PDF at 150 dpi. I would like to OCR the document at 300 or 600 dpi, and then export to 75, 150 or whatever resolution.

**Comment by manisandro** [comment]
Fair point, I'll add an additional DPI combo in the PDF export settings dialog.

**Comment by manisandro** [comment]
Please test latest master.

**Comment by CharlesNepote** [comment]
Works great! It's perfect for me.
Tested with multiple combinations: ZIP or JPEG, 600-300-150 dpi, JPEG 100-95-90-85, etc.
Thanks Sandro!

**Comment by manisandro** [comment]
Thanks for testing!
