### ISSUE TITLE
GTK: UTF-8 issues with the language selector

### ISSUE THREAD

**Issue by danpla** [manisandro/gImageReader#107]
In GTK backend, I have garbage in the language selector, regardless of `LANG`. At the same time, all is OK with Qt backend. For every item, the following warning is printed to console:

```
Pango-WARNING **: Invalid UTF-8 string passed to pango_layout_set_text()
```

![2016-10-09-233411_1600x900_scrot](https://cloud.githubusercontent.com/assets/10910745/19223462/54e64896-8e79-11e6-8329-a655b3b6a013.png)

Xubuntu 14.04, x86_64
gImageReader 3.1.91 from the PPA

**Comment by manisandro** [comment]
Hi, this is caused by an old version of gtkspell (to be exact, older than 3.0.9) which suffered from a memory corruption issue which would result in such garbage strings. I forgot to update gtkspell in the PPA for some ubuntu releases, I'll push the update now.

**Comment by manisandro** [comment]
Updated package is now available. Please update and test.

**Comment by danpla** [comment]
Now everything is fine. Thanks!
