### ISSUE TITLE
"Display whitespace characters" view mode in output pane

### ISSUE THREAD

**Issue by ferdnyc** [manisandro/gImageReader#11]
The output pane's intelligent newline removal and whitespace cleanup functions are incredibly handy for reflowing paragraphs of text from the OCR'd document. However, especially since the output pane comes up rather narrow by default (so that nearly all recognized text is displayed wrapped, in the pane), it can sometimes be difficult to determine the line length of the text or where the existing hard newlines are.

I wonder if it wouldn't be helpful to have a display mode (either optional, or just the standard view) which displays "hidden" whitespace characters — something similar to GEdit's "Draw Spaces" plugin, perhaps.

I have my GEdit configured so that:
  * All breaks, tabs, and non-breaking spaces are shown,
  * Leading and trailing spaces on each line are also drawn,
  * Spaces within the line are *not* displayed. (I find the visible dots between words distracting, and they make the text harder to read. Plus, inline spaces are generally less of a formatting concern.)

If the output pane had a display mode similar to the GEdit screenshot below (I'm not sure that line numbers are necessary), it would make it much easier to locate areas in the text where there are hard line breaks and other whitespace issues present that need to be cleaned up with the "Strip line breaks..." tool, as well as visibly see the effects of using it on the text. Manual cleanup and editing would also be easier with visible formatting characters.

![screenshot from 2014-12-25 03 17 32](https://cloud.githubusercontent.com/assets/538020/5553203/12c82ac8-8be8-11e4-8568-9b0c96b91d43.png)

**Comment by manisandro** [comment]
This is implemented in gimagereader-3.1, thanks for the suggestion!
