### ISSUE TITLE
Text is not included in PDF if Use detected font sizes is checked

### ISSUE THREAD

**Issue by danpla** [manisandro/gImageReader#110]
If "Use detected font sizes" is checked, the exported PDF has no text. The funny thing is the text is shown in preview.

Steps to reproduce:

1. Recognize an image or PDF in "hOCR, PDF" mode
2. In the pdf export dialog, check Use detected font sizes
3. Enable the preview to ensure that text exists
4. Save the PDF => no text in the file

Xubuntu 14.04 x86_64
gImageReader 3.1.99
The issue exists both in Gtk and Qt versions.

**Comment by danpla** [comment]
Actually, the preview works only in Qt version. Gtk version honestly shows an empty page.

**Comment by manisandro** [comment]
Odd, cannot reproduce here... Can  you share more details, i.e. the image, which DPI and which PDF settings?

**Comment by danpla** [comment]
This happens with any image.

Github does not allow to upload PDFs, so here is a [Dropbox link](https://www.dropbox.com/sh/tifovjp7tamnupz/AABwynzCMpIz45XyenQ1R9xda?dl=0) to example. `img.pdf` is a result with the checked option, `img_normal.pdf` - with unchecked. Note that the file size is almost the same in both cases.

Here is a screenshot of my export dialog, but I tried many different combinations, and Use detected font sizes the only that makes a difference.
![2016-10-14-154912_413x476_scrot](https://cloud.githubusercontent.com/assets/10910745/19388035/463cb20c-9226-11e6-836f-c6a362d764c4.png)

Also, when I check Use detected font sizes, the Qt version prints:
```
QFont::setPointSize: Point size <= 0 (0), must be greater than 0
```
But the Gtk one doesn't print anything.

**Comment by manisandro** [comment]
I'll set up a 14.04 VM and do some testing, I suspect it may be related to some older libraries which are shipped with that version.

**Comment by danpla** [comment]
Yes, it's likely to be a problem with libraries. On my 16.04 VM everything is fine, and the text has a correct size (see `img_16.04.pdf` in the link above).

**Comment by manisandro** [comment]
Yep I can reproduce the problem on 14.04...

**Comment by danpla** [comment]
That's because `hocr_font_info` was added in tesseract v3.04.00. 14.04 uses v3.03.02. SA https://github.com/tesseract-ocr/tesseract/issues/309

**Comment by manisandro** [comment]
Ah bingo, so
a) ship tesseract 3.04.00 in the PPA
b) disable the setting on 14.04
What's more sensible in your view?

**Comment by danpla** [comment]
Of course, it would be nice to have a new tesseract, because the feature is extremely useful. But what about all the language packs?

**Comment by manisandro** [comment]
Well that's a matter of building all of them in the PPA. I'm more worried about compability with other applications since tesseract is notoriously unstable API/ABI-wise (and don't do soname bumps). So actually I rather tend on disabling the setting...

**Comment by danpla** [comment]
Fortunately, it seems like language packs are independent from the tesseract itself (all of them v3.02 on my machine).

Another variant is to link the new tesseract statically with 14.04 build, but that's probably too problematic.

Anyway, it's not a big issue to handle font size manually.

**Comment by manisandro** [comment]
Well langpacks are often more dependent on the tesseract version that one wishes them to be... Using a traineddata generated for an other version can lead to tesseract segfaulting. If recall correctly it was indeed the 3.03 -> 3.04 transition which resulted in many people sending gimagereader crash reports because of that issue.

**Comment by manisandro** [comment]
`gimagereader - 3.1.99-1~trustyppa3` is building. I don't think there is much more that can be done for this  issue. Again thanks for the report and investigation.

**Comment by danpla** [comment]
The fix was not included in `trustyppa3` (see the [diff](https://launchpadlibrarian.net/289537457/gimagereader_3.1.99-1~trustyppa2_3.1.99-1~trustyppa3.diff.gz)). It seems like there are no version macros in 3.03.02, so a runtime workaround is needed.

**Comment by manisandro** [comment]
Oh joy

**Comment by manisandro** [comment]
Should be correct now with `gimagereader-3.1.99-1~trustyppa4`
