### ISSUE TITLE
Preview DPI and JPEG quality

### ISSUE THREAD

**Issue by danpla** [manisandro/gImageReader#114]
It would be very useful to see an image in given DPI and (if any) JPEG compression in preview. Without this, the preview only half helpful, because it doesn't actually show the final PDF's look.

If that's a reasonable feature, I can create pull request.

**Comment by manisandro** [comment]
Sure, I'm ok with such a feature!

**Comment by manisandro** [comment]
By the way concerning your question about code style in the other ticket: I've now added a `formatSourceFiles.sh` which autoformats all source files with astyle.

**Comment by danpla** [comment]
I'm starting to doubt that this was a good idea. gImageReader manipulates files in memory, and saving a PDF in high DPI usually leads to an out-of-memory crash. The same story will be with jpeg preview, because, in this case, it's not possible to honestly render an image in the final DPI right into memory.

The problem is that it's not possible to make any optimizations, like only crop the visible part of the image and the encode-decode it, or limit its scale factor to a current viewport's zoom ratio: because of how jpeg's algorithm works, such an image will look different from the full one that will be saved in PDF (both artifacts and colors).

Of course, the difference is not noticeable with small viewport's zoom ratios, but the whole point of jpeg preview is to see small details of compression.

**Comment by manisandro** [comment]
I was thinking that jpeg might give you a rough idea about how noisy the resulting image would get, without giving you a 100% accurate preview. OTOH to actually see the fine details one needs to remove modality from the save PDF dialog so that the user can pan and zoom around, while still handling the case where the user picks a different image or so (which needs to be disallowed or the export aborted). So question is whether it is worth the effort.
About the out-of-memory crash: would be nice to actually catch those instead of having the application crash.

**Comment by danpla** [comment]
It seems like the only sane solution is to make the preview to draw only parts of PDF asynchronously. For example, in case of Qt, to make a subclass of `QGraphicsItem` that will use `QPainterPDFPainter`. While the requested part being rendered, it can draw a rect from a cached low-res version, or just do nothing.

It will allow pan and zoom, and constant memory usage at the same time (except of jpeg conversion, of course).

**Comment by danpla** [comment]
Threaded renderer will not draw text on systems without fontconfig. However, I think it's very difficult to find a modern desktop system that doesn't use it.

http://doc.qt.io/qt-4.8/threads-modules.html#painting-in-threads:
> Note that on X11 systems without FontConfig support, Qt cannot render text outside of the GUI thread. You can use the QFontDatabase::supportsThreadedFontRendering() function to detect whether or not font rendering can be used outside the GUI thread.

**Comment by manisandro** [comment]
Jpeg preview implemented in ac42605c0f1f91b020319283fa22118aa01c1994

I suppose one could also do some hackish-downscale-previewing for the DPI, but I don't think it is worth the trouble really.
