### ISSUE TITLE
Add information about dependencies and building

### ISSUE THREAD

**Issue by imsodin** [manisandro/gImageReader#118]
I just discovered this nice piece of software and wanted to give 3.1.99 a try. However there was no instruction to be found in the repo. I searched the issues and came up with the instructions you gave [here](https://github.com/manisandro/gImageReader/issues/95#issuecomment-246123422).
Please provide this information about dependencies and/or instructions for building either in the README or in separate DEPENDENCIES and INSTALL files. One should not have to look for that information in the github issues.
Once I succeed at building, I can also do this myself via a PR if this is welcomed.

**Comment by imsodin** [comment]
And maybe related to missing information, maybe a different bug (sorry in that case): I get the following error when compiling:

```
/home/simon/Linux/source/gImageReader/gtk/src/OutputEditorHOCR.cc:1117:14: error: ‘class GtkSpell::Checker’ has no member named ‘add_to_dictionary’
      m_spell.add_to_dictionary((*it)[m_itemStoreCols.text]);
              ^
/home/simon/Linux/source/gImageReader/gtk/src/common.hh:49:68: note: in definition of macro ‘CONNECT’
 #define CONNECT(src, signal, ...) (src)->signal_##signal().connect(__VA_ARGS__)
                                                                    ^~~~~~~~~~~
/home/simon/Linux/source/gImageReader/gtk/src/OutputEditorHOCR.cc: In lambda function:
/home/simon/Linux/source/gImageReader/gtk/src/OutputEditorHOCR.cc:1123:14: error: ‘class GtkSpell::Checker’ has no member named ‘ignore_word’
      m_spell.ignore_word((*it)[m_itemStoreCols.text]);
              ^
/home/simon/Linux/source/gImageReader/gtk/src/common.hh:49:68: note: in definition of macro ‘CONNECT’
 #define CONNECT(src, signal, ...) (src)->signal_##signal().connect(__VA_ARGS__)
                                                                    ^~~~~~~~~~~
CMakeFiles/gimagereader.dir/build.make:359: recipe for target 'CMakeFiles/gimagereader.dir/gtk/src/OutputEditorHOCR.cc.o' failed
make[2]: *** [CMakeFiles/gimagereader.dir/gtk/src/OutputEditorHOCR.cc.o] Error 1
CMakeFiles/Makefile2:136: recipe for target 'CMakeFiles/gimagereader.dir/all' failed
make[1]: *** [CMakeFiles/gimagereader.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by manisandro** [comment]
Hi, I'll write up an official compilation howto in the wiki (was on my list, but I gave priority to actually releasing the latest version).

In the meantime: the current list of dependencies is always available in `packaging/debian/control` or `packaging/gimagereader.spec`. The first compilation error is because you are missing the podofo development files (package like `podofo-devel` or `libpodofo-dev`). The second compilation error is because your gtkspell/gtkspellmm version is too old (you need gtkspell3-3.0.9 and gtkspelmm-3.0.5).

**Comment by manisandro** [comment]
I've written down an initial page [here](https://github.com/manisandro/gImageReader/wiki/Compiling-gImageReader).

**Comment by imsodin** [comment]
The wiki page is great, thanks. I would add this info to the readme or at least a reference to it.

I compiled your qtspell library as gtkspellmm-3.0.5 is not packaged for debian and it worked.

**Comment by manisandro** [comment]
Added the link to the readme.
