### ISSUE TITLE
Split multipage pdfs on import

### ISSUE THREAD

**Issue by imsodin** [manisandro/gImageReader#119]
Currently a multipage pdf is represented as one entry in the left pane. Thus pages cannot be rotated individually. It would be really useful to have an option to split the pdf into one entry per page on import.

In my case I get flatbed scans of books as pdfs and they are very often a mess, pages flipped, huge useless borders, erratically skewed. Presently I fix the flipping with pdftk, borders with briss and then startup gImageReader to make it searchable. With the proposed functionality the job of pdftk could be taken over by gImageReader. It would be great if the functionality of briss (selecting useful regions and splitting double pages into two single pages) could be added as well, but that would probably be a major undertaking.

**Comment by manisandro** [comment]
I can see the point however if it's only about keeping rotations for individual pages instead of the entire document, perhaps it would just make sense to make the rotation setting page-specific instead of adding possibly hundreds of pages to the sources list. Still the question would remain how to handle this UI-wise, because I believe that a document-wide rotation setting still makes sense for certain documents.

**Comment by imsodin** [comment]
That is a point. Maybe a checkbox called "Apply changes to single page" or conversely "Apply changes to entire document". Thus the rest of the UI did not have to be altered and the color settings could also be set individually or globally.

**Comment by manisandro** [comment]
Well thing is you then get corner cases such as what happens when you first rotate globally and then set the checkbox to rotate individually: should the local rotation be in addition to the global rotation? What happens if you rotate locally, then switch to global and rotate then? On possibility I can see is that it is always local, but if the initial setting for each page is the same as the setting of the page before. So if you rotate the first page and then browse through the document, subsequent pages would have the same rotation unless you alter it. It's would introduce a bit of hidden magic but keep the UI clean.

**Comment by imsodin** [comment]
In the way I imagined it I cannot see any problem with such a case, I didn't imagine it as a "global" checkbox. So you can happily switch between global and local, all changes are "cumulative". So if I e.g. rotate right while in global mode all pages are rotated to the right, then I switch to local and rotate left only this page is rotated left (so in original position again) and last I switch back to global and rotate right again  all pages are rotated right from there individual starting position. So now everything is rotated 180deg except the one page that has been rotated left in local mode.

**Comment by manisandro** [comment]
Ok I suppose the option which wouldn't take up too much space in the (already crammed) toolbar would be an icon-combobox like the one in the plain-text editor which allows you to specify the append mode.

**Comment by manisandro** [comment]
I've implemented this in 90fbb11 (Qt interface only for the moment), could you please give it a try? Let me know if you need a Windows build.

**Comment by imsodin** [comment]
I just wanted to have a look at it, but apparently some dependency changed and I need to go. I will probably build on Monday to look at this. Thanks!
And no, no Windows required :)

**Comment by imsodin** [comment]
I am stuck with the following problem while running `cmake -DINTERFACE_TYPE=qt5 ..`:

```
-- Checking for module 'tesseract'
--   Package 'lept', required by 'tesseract', not found
```

The build dependencies according to the wiki respectively the debian packaging control file are fulfilled. Unfortunately I didn't find out which file/library it is missing and where it is looking exactly. Any pointers?

**Comment by manisandro** [comment]
lept is leptonica. Looks like your tesseract pkgconfig file requires the leptonica pkgconfig file, but it can't find it. If you are using a somewhat older version of debian, it might be that the leptonica version shipped there does not yet provide the pkgconfig file (though in that case the debian tesseract maintainer should patch tesseract to not make it require the leptonica pkgconfig file).

**Comment by imsodin** [comment]
The problem is that libtesseract-dev is not a build dependency of gimagereader (or libtesseract-dev). Now that is fine, but instead on executing the binary I get 
```
Failed to open /usr/local/share/xml/iso-codes/iso_639.xml for reading
Failed to open /usr/local/share/xml/iso-codes/iso_3166.xml for reading
```
because these files are in `/usr/share/...`. I set `CMAKE_INSTALL_PREFIX` to /usr/ but that doesn't help.

**Comment by manisandro** [comment]
Uhm `libtesseract-dev` is listed as a dependency in both my sample debian control [1] and in the debian package [2]?

The isocodes dependency comes from either gtkspell/qtspell, so you'll need to check the prefixes there.

[1] https://github.com/manisandro/gImageReader/blob/master/packaging/debian/control#L12
[2] http://http.debian.net/debian/pool/main/g/gimagereader/gimagereader_3.2.0-1.debian.tar.xz

**Comment by imsodin** [comment]
I seem to be a little bit distracted, sorry: It wasn't libtesseract-dev, but libleptonica-dev, as you suggested...
I unfortunately have no clue how I can check the prefix for qtspell. Gimagereader starts ok, but UI elements are missing. I attributed this to these error messages, but if they are about qtspell this is probably not the case?
[Screenshot](http://i.imgur.com/kAKEU2n.png)

**Comment by manisandro** [comment]
Leptonica should be a build-dep of tesseract - gImageReader does not directly require it.

iso-codes is only used to transform language-culture codes to human readable strings (i.e. en_US -> English (United States)), it should not have any other consequences. In your case, it appears that all icon-theme icons are missing. Not sure why - gImageReader uses the stock qt5 code for loading icons from the system icon theme. You can try running gimagereader through strace to check where it searches for the icons. I.e. to check where the rotate-left icon comes from:

    $ strace -e trace=stat gimagereader-qt5 2>&1 | grep rotate-left
    stat("/usr/share/icons/oxygen/base/8x8/emblems/object-rotate-left.png", 0x7ffeb1671d90) = -1 ENOENT (No such file or directory)
    stat("/usr/share/icons/oxygen/base/16x16/actions/object-rotate-left.png", {st_mode=S_IFREG|0644, st_size=721, ...}) = 0
    stat("/usr/share/icons/oxygen/base/22x22/actions/object-rotate-left.png", {st_mode=S_IFREG|0644, st_size=1168, ...}) = 0
    stat("/usr/share/icons/oxygen/base/32x32/actions/object-rotate-left.png", {st_mode=S_IFREG|0644, st_size=1547, ...}) = 0

**Comment by imsodin** [comment]
There is an open bug asking for libleptonica-dev to be a dependency of libtesseract-dev, so that should happen there.

```
$ strace -e trace=stat gimagereader-qt5 2>&1 | grep rotate
stat(":/icons/rotate_page", 0x7ffe58461340) = -1 ENOENT (No such file or directory)
stat(":/icons/rotate_pages", 0x7ffe58461340) = -1 ENOENT (No such file or directory)
stat(":/icons/rotate_pages", 0x7ffe58461340) = -1 ENOENT (No such file or directory)
```
It is looking for icons in root???

**Comment by manisandro** [comment]
Those icons are icons the application bundles, where `:/` denotes that they are in the bundled resources. It appears that it does not even look for the other icons?! Perhaps you have configured qt to now show any icons in toolbars, just text?

**Comment by imsodin** [comment]
I did not (consciously) configure anything about qt and I have other qt applications running fine with icons. Searching for `object-rotate-left.png` I don't find it in either `build` nor the installation directory, only in the git repo under `packaging/win32/...`. The only icons found in the installation directory are `gimagereader.png` icons.

**Comment by manisandro** [comment]
`object-rotate-left.png` (as well as loads of other icons) are not bundled with gImageReader but are expected to be provided by your system icon theme (in `/usr/share/icons/<theme_name`). Can you post the output saved in strace.log produced by

strace -ostrace.log gimagereader-qt5

**Comment by imsodin** [comment]
These icons are there, sorry...
The log is pretty long, so due to pastebins size limit I removed some lines at the end, I hope the relevant part is in there: http://pastebin.com/iSn4jFSc

**Comment by manisandro** [comment]
It looks like the application is looking for an icon theme called `Cheser`, but it can't find it anywhere (see all the `No such file or directory` lines). Perhaps the other qt applications where icons work Qt4 based which has another logic for determining the icon theme and other settings. This ArchLinux wiki page [1] might give you some pointers on where to look. But this is not a gImageReader issue.

You could also compile gImageReader with -DINTERFACE_TYPE=qt4 or -DINTERFACE_TYPE=gtk to switch toolkit.

[1] https://wiki.archlinux.org/index.php/qt#Configuration_of_Qt5_apps_under_environments_other_than_KDE

**Comment by imsodin** [comment]
I had this icon theme in ~/.local/share/icons where apparently gtk apps look, but qt doesn't. Sorry for wasting your time with this completely unrelated problem...

The functionality is exactly what I needed. Some minor comments:
It is somewhat hidden. I guess someone who does not know that this option exists might not find it.
I wouldn't expect PgUp/PgDn to modify the orientation value even when the focus is on the orientation box.
As the rotate current page/all pages is persistent, it would be great if there was a visual clue which one is active. Maybe a tickbox or background shading of the currently active option.
I don't know whether this is new, I just didn't notice it before: Switching pages is very slow.

**Comment by manisandro** [comment]
> It is somewhat hidden. I guess someone who does not know that this option exists might not find it.

Yeah, I suppose though this applies to many other aspects of the application... But in my view it is the cleanest option to integrate the control.

> I wouldn't expect PgUp/PgDn to modify the orientation value even when the focus is on the orientation box.

You mean, you would expect it to switch the pages instead? It is standard behaviour for spin-boxes to react on PageUp and PageDown keys (there is actually even a special increment value to handle that key, i.e. `page-size` as opposed to the regular `step` which is the increment when pressing on the arrows)

> As the rotate current page/all pages is persistent, it would be great if there was a visual clue which one is active. Maybe a tickbox or background shading of the currently active option.

The icon in the button changes based on the active option, but perhaps the icons aren't sufficiently recognizable one from the other.

> I don't know whether this is new, I just didn't notice it before: Switching pages is very slow.

It might depend on which flags you have used to compile the application. And clearly also on the document you are using. For the compile flags, try

    export CFLAGS="-O2"
    export CXXFLAGS="-O2"

before running cmake.

**Comment by imsodin** [comment]
> 
>>  It is somewhat hidden. I guess someone who does not know that this option exists might not find it.
> 
> Yeah, I suppose though this applies to many other aspects of the application... But in my view it is the cleanest option to integrate the control.

True, this is perfectly fine.

> 
>> I wouldn't expect PgUp/PgDn to modify the orientation value even when the focus is on the orientation box.
> 
> You mean, you would expect it to switch the pages instead? It is standard behaviour for spin-boxes to react on PageUp and PageDown keys (there is actually even a special increment value to handle that key, i.e. page-size as opposed to the regular step which is the increment when pressing on the arrows)

That's what I meant, yes. But the current behaviour is fine with me as well, but then I would like to be able to get out of rotating by pressing ESC. Currently the only way to switch a page after rotating is by using the mouse.

>> As the rotate current page/all pages is persistent, it would be great if there was a visual clue which one is active. Maybe a tickbox or background shading of the currently active option.
> 
> The icon in the button changes based on the active option, but perhaps the icons aren't sufficiently recognizable one from the other.

Now that I know it is clear, the icons very nicely convey their meaning. The problem is just to spot they are different in the first place, as the icons are rather small and similar.

>> I don't know whether this is new, I just didn't notice it before: Switching pages is very slow.
> 
> It might depend on which flags you have used to compile the application. And clearly also on the document you are using. For the compile flags, try
> 
> ```
> export CFLAGS="-O2"
> export CXXFLAGS="-O2"
> ```
> 
> before running cmake.

That didn't (perceivably) change anything. It is a 1-2s delay on a 2MB pdf that e.g. zathura has no problems with. However this is not really a problem, just something I noticed.

**Comment by manisandro** [comment]
> That's what I meant, yes. But the current behaviour is fine with me as well, but then I would like to be able to get out of rotating by pressing ESC. Currently the only way to switch a page after rotating is by using the mouse.

Or by using tab a couple of times. 

> Now that I know it is clear, the icons very nicely convey their meaning. The problem is just to spot they are different in the first place, as the icons are rather small and similar.

I'll need to look whether my artist skills are able to produce something better ;) Or feel free to make a suggestion if you have an idea!

> That didn't (perceivably) change anything. It is a 1-2s delay on a 2MB pdf that e.g. zathura has no problems with. However this is not really a problem, just something I noticed.

Can you share the PDF?

**Comment by SantosSi** [comment]
Didn't get the outcome of this request: was unable to rotate single pages from a multipage PDF.

**Comment by manisandro** [comment]
Right to the left of the rotate spinbox there is a combo which allows you to switch between rotating the current page only or all pages in the selected sources.

**Comment by SantosSi** [comment]
Found the button and it worked as expected. Anyway I did not expect it returns rotation to original when I go to another page and return.
I was mislead by the layout: the button looked like an icon, like the icon left of the page selector. Maybe it is better to move it away from the angle frame, to the left of the rotation buttons, like in the GTK version?
