### ISSUE TITLE
Add whitespace in between when merging multiple Textboxes

### ISSUE THREAD

**Issue by imsodin** [manisandro/gImageReader#120]
I get many lines that are made up of many adjacent textboxes (probably because of them being skewed). If I want to edit the whole line and thus merge these boxes all strings are concatenated without a whitespace in between.

On a sidenote: I hope you don't take the many opened issues wrongly, the software is great and your work very much appreciated.

**Comment by manisandro** [comment]
First off, I definitely welcome all feedback, so open as many issues as you please ;)

Concerning the issue: the merge feature was added for the cases where tesseract erroneously splits a word into two word boxes. But word boxes are still meant to represent individual words, not entire text lines. The question is rather why do you want to merge words to one single block representing the entire line?

**Comment by imsodin** [comment]
I wanted to merge because a whole line was erroneous and editing them all together was easier. But now I see that I clearly did not get the concept and it should have been obvious as there is a "Textline" object.
