### ISSUE TITLE
Error loading user-defined replacements

### ISSUE THREAD

**Issue by bmix** [manisandro/gImageReader#130]
Please consider a textfile, containing the following (see also attached file 'stringfaults.txt'):
```
vv w
VV W
iii m
l< k
lx h
xn m
a1 al
e1 el
1e le
u11 ull
u1 ul
i11 ill
<< «
>> »
lš E
Iå E
ın m
ıı n
›› »
'/. Z
ıl D
]e Je
crhält erhält
ﬁbnäre tionäre
flllt fällt
ii ö
jéiher jäher
frﬁhen frühen
```
It errors out, when loading. As far as I have understood, the format I am using, seperation of string-fault from correction by a single whitespace, is correct.
[stringfaults.txt](https://github.com/manisandro/gImageReader/files/567314/stringfaults.txt)

**Comment by manisandro** [comment]
The separation character needs to be a tab, that is likely the issue with your file.

**Comment by bmix** [comment]
You were right. Therefore I close it as a non-issue.
