### ISSUE TITLE
Templating for the text-reflow feature

### ISSUE THREAD

**Issue by bmix** [manisandro/gImageReader#132]
This is not really needed. It's just an idea, once you are satisfied with the basics and may find yourself bored ;-)

As you seem to be able to recognize paragraphs with the reflow-feature, maybe these paragraphs could be extracted and passed to some templates.

The user may create an XHTML1 (for ePub2) or XHTML5 (for ePub3) template with a '${placeholder}' string in the body. Your app now would allow to define a container, that gets wrapped around the paragraph, which gets sequenced into the template at the placeholder.

So, let's assume I create some XHTML boilerplate, and somewhere in the BODY element I place the '${placeholder}' like this:
```HTML
<html>
 <head></head>
 <body>
  <div>
   ${placeholder}
  </div>
 </body>
</html>
```
Now, in your app, I define a container, to surround each paragraph:
```HTML
<p class="foo-bar" id="${iteration-counter}">
 ${ocr'ed paragraph}
</p>
```
The resulting file then could be passed to some `exec` function, which may invoke a script, that does automate as much as possible for semi-automatic ePub output. This may be an idea for a scripting interface, should one emerge.

**Comment by manisandro** [comment]
I'm not sure I follow. I assume the feature you describe would work in hOCR mode - wouldn't it be sufficient to just be able to assign custom IDs to the various blocks in the hOCR tree, and then an external script can process the hOCR html file and extract the various blocks of interest and process them as desired?

**Comment by bmix** [comment]
No, I did not think about hOCR. I did not really look into hOCR till now. From a quick check on this formart, I see, that you are right. If using hOCR (and as long that is being available as XHTML), one can write an external XSL Transform to do this. Thanks for the idea!
