### ISSUE TITLE
gimagereader will can version appimage?

### ISSUE THREAD

**Issue by manuelsongokuh** [manisandro/gImageReader#136]
hi
appimage is comfortable for all distros, not needed installing with various librery..
so is it possible version for appimage?

**Comment by manisandro** [comment]
Do you mean flatpack?

**Comment by manuelsongokuh** [comment]
see  link:
http://appimage.org/

**Comment by manisandro** [comment]
Looking at how things are evolving, I'm rather considering flatpack than appimage.

**Comment by manisandro** [comment]
Tracked in #156
