### ISSUE TITLE
Redetect languages not working in 3.2

### ISSUE THREAD

**Issue by Shreeshrii** [manisandro/gImageReader#137]
I installed the latest version 3.2.0 under windows 10. I also downloaded the traineddata files for hin and kan from https://github.com/tesseract-ocr/tessdata as mentioned in help file.

However the program does not seem to detect the languages even after restart.

Is it related to the new traineddata files for 4.0 alpha of tesseract-ocr?

**Comment by manisandro** [comment]
I'll need to check whether 4.0 traineddata are incompatible... If you use

https://github.com/tesseract-ocr/tessdata/raw/3.04.00/kan.traineddata

does it work?

**Comment by Shreeshrii** [comment]
No, that also does not work. Please see the following for the preference settings (default) and downloaded files.

![gimage-error](https://cloud.githubusercontent.com/assets/5095331/20885348/5b06bd9a-bb16-11e6-9668-e5f91a99dd72.png)
![gimage-prefs](https://cloud.githubusercontent.com/assets/5095331/20885349/5b07230c-bb16-11e6-87f4-7f5672ed0f0b.png)

**Comment by manisandro** [comment]
Strange, it is working fine here, also simply via redetect-languages without restarting. Do you have a 
`C:\Users\<username>\AppData\Local\VirtualStore` folder with a gImageReader folder somehwere below?

**Comment by Shreeshrii** [comment]
![gimage-new](https://cloud.githubusercontent.com/assets/5095331/20886151/a34cbee8-bb1a-11e6-9181-494909f21d16.png)

**Comment by manisandro** [comment]
If you replicate the share/tessdata folder structure in there and place the traineddata file inside that folder, does it work? Alternatively, does it work if you use user local paths (you can choose between system-wide paths and user-local paths in the gimagereader preferences dialog).

**Comment by Shreeshrii** [comment]
I replicated the share/tessdata folder structure in "C:\Users\User\AppData\Local\VirtualStore\Program Files (x86)\gImageReader" and place the traineddata file inside that folder. It is working now, thanks.

What version of tesseract is included with gimagereader?

The new 4.0 traineddata has better accuracy for complex scripts such as Hindi, Kannada etc, but would also need the latest source from the master branch.

**Comment by manisandro** [comment]
Uhm, I assume the link to the tesseract traineddata folder in the start menu does not point to the VirtualStore location though, right? Its quite tricky to deal with this VirtualStore since the program has no clue whether it is actually enabled or not...

gImageReader currently uses tesseract 3.04.01. I could do a test build compiling against 4.0 when I have a couple of spare minutes.

**Comment by Shreeshrii** [comment]
Thanks, that would be great!

**Comment by manisandro** [comment]
Here you go:
https://smani.fedorapeople.org/tmp/gImageReader_3.2.0_qt5_i686.exe
https://smani.fedorapeople.org/tmp/gImageReader_3.2.0_qt5_x86_64.exe

Pretty much untested, and the bundled eng.traineddata is still the one from 3.04, so you might need to update it manually.

**Comment by Shreeshrii** [comment]
Thanks. I will uninstall old version and install this and get back to you.

What is the git revision number of the Tesseract code that you used?

**Comment by manisandro** [comment]
I used [798d79a](https://github.com/tesseract-ocr/tesseract/commit/798d79a)

**Comment by Shreeshrii** [comment]
There have been a lot more changes made to the master branch. Please let me
know when you make a newer version available.

Also, a question ...

does the program allow for user selection of --psm and --oem for choosing
between the LSTM and Tesseract engines?

- sent from mobile phone

**Comment by manisandro** [comment]
Updated builds (using [c1ee2fe](https://github.com/tesseract-ocr/tesseract/commit/c1ee2fe)) are at 
https://smani.fedorapeople.org/tmp/gImageReader_3.2.0_qt5_i686.exe
https://smani.fedorapeople.org/tmp/gImageReader_3.2.0_qt5_x86_64.exe

No currently user selection between `--psm` and `--oem` is not implemented. I'm not actually familiar with those switches. Would this be something for the preferences dialog or better in the recognition menu, i.e. where the OSD support checkbox is?)

**Comment by Shreeshrii** [comment]
Thanks for your prompt response.

On command line, you can check on the --psm and --oem options by

tesseract --help

Psm is page segmentation mode. Values range from 0 to 13.

OEM values
0 - tesseract
1 - LSTM neural network
2 - Tess+LSTM
3 - based on what is available

For complex scripts such as hindi, kannada etc LSTM engine has better
accuracy and speed.

- excuse the brevity, sent from mobile

**Comment by Shreeshrii** [comment]
Hi,

I downloaded and tested the new version now. It works with the included
english traineddata (3.04) and also with hindi traineddata from version
3.04. However, when trying to use any of the traineddata from version 4.0,
the program dies.

Could it be that you are building the 3.05 branch and not master? If not,
there must be some problem in the tesseract repo.

If possible, please keep date/git tag as part of exe naming for testing the
different versions.

Thanks!

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by Shreeshrii** [comment]
correction - I tested with sanskrit traineddata for 3.04 (not Hindi).

>>No currently user selection between --psm and --oem is not implemented.
I'm not actually familiar with those switches.
>>Would this be something for the preferences dialog or
>>better in the recognition menu, i.e. where the OSD support checkbox is?)

These can be set for each document, so it will be great if you have them
after the dropdown for OCR mode (text, hocr, pdf). The defaults for these
could be set via preferences.

Thanks!

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by manisandro** [comment]
Closing this in favor of #141

Feel free to PM me if you'd like refreshed tesseract-4.0 builds.
