### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by zbgns** [manisandro/gImageReader#140]
Hello,
I really appreciate the project, it is very useful. I use gImageReader under Win7 and Ubuntu 16.04. I have some issue, which appears under Ubuntu. 
In case I choose "automatic area recognition" the program closes with no warning. Message in terminal is following:
`gimagereader-gtk: symbol lookup error: gimagereader-gtk: undefined symbol: _ZN9tesseract11TessBaseAPI13AnalyseLayoutEv'
What it may be?

**Comment by manisandro** [comment]
Hi
What Ubuntu version are you using? Which version of tesseract do you have installed?

The problem is that the version of the tesseract library on your system does not match the version against which gImageReader was compiled. If you installed tesseract from an external source, you'll need to recompile gImageReader. Unfortunately tesseract tends to break binary compatibility without bumping the library version, otherwise the package manager should have reported the broken dependency when either installing gImageReader or installing the incompatible tesseract version.

**Comment by zbgns** [comment]
I use Ubuntu 16.04.1 (Xenial Xerus). The Tesseract version is standard 3.04.01 from official repositories. gImageReader was installed via official PPA. I have no any report on unsolved dependencies, although there were some dependencies problems with earlier versions of gImageReader, when I tried to install it from standard Ubuntu repositories.
I will try test the compilation from sources, but it is of low priority for me as automatic recognition of areas is not what I'm going to use very often (on the other hand it is very good that this function is implemented anyway). I use rather manual rectangular selection. It is extremely useful as it comes to extraction of data from tables and in order to omit OCR of headers and footers in multipage documents. It is difficult to obtain the same result in Tesseract CLI mode. And this manual selection works like a charm for me.

**Comment by manisandro** [comment]
So `gimagereader_3.2.0-1~xenialppa1` was compiled against `libtesseract_3.04.01-4`. If you can confirm you are using these two versions, I'll need to investigate.

**Comment by zbgns** [comment]
It seems yes, however I must check it. Currently I have no access to my linux computer, I will be able to confirm this today afternoon. 
Thank you for your swift assistance.

**Comment by zbgns** [comment]
The gImageReader version is this one mentioned by you. As regards libtesseract I realized I had two versions installed at the same time: 3.04.01-4 from official system repositories and 3.04.01-1 from some PPA. After uninstalling the latter one the automatic area recognition seems to work fine. Thank you once again for your support. The problem was apparently a mess in my system.

**Comment by manisandro** [comment]
Ok glad it's solved.
