### ISSUE TITLE
Expose Page Segmentation Mode

### ISSUE THREAD

**Issue by manisandro** [manisandro/gImageReader#141]
Allow for user selection of --psm and --oem for choosing
between the LSTM and Tesseract engines.

Page segmentation modes:
  0    Orientation and script detection (OSD) only.
  1    Automatic page segmentation with OSD.
  2    Automatic page segmentation, but no OSD, or OCR.
  3    Fully automatic page segmentation, but no OSD. (Default)
  4    Assume a single column of text of variable sizes.
  5    Assume a single uniform block of vertically aligned text.
  6    Assume a single uniform block of text.
  7    Treat the image as a single text line.
  8    Treat the image as a single word.
  9    Treat the image as a single word in a circle.
 10    Treat the image as a single character.

These can be set for each document, so it will be great if you have them
after the dropdown for OCR mode (text, hocr, pdf). The defaults for these
could be set via preferences.

**Comment by manisandro** [comment]
@Shreeshrii Please test
https://smani.fedorapeople.org/tmp/gImageReader_3.2.0_qt5_i686_tesseract_c1ee2fe.exe
https://smani.fedorapeople.org/tmp/gImageReader_3.2.0_qt5_x86_64_tesseract_c1ee2fe.exe

**Comment by Shreeshrii** [comment]
I tried the x86_64 version on windows 10.

1. This version also works only with the 3.04 traineddata not with 4.0
alpha.

2. Please change 'About program' to show tesseract version as 3.05 dev - It
may be released as 3.05 - as bug fix release for 3.04.
https://github.com/tesseract-ocr/tesseract/tree/3.05

3. Change readme.txt regarding downloading traineddata to use 3.04 tag of
tessdata repo.
https://github.com/tesseract-ocr/tessdata/tree/3.04.00

4. In case the master branch of tesseract (c1ee2fe) is using the 3.0x
version of traineddata instead of 4.0alpha, please file an issue.

Thanks!


ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by Shreeshrii** [comment]
Page segmentation options work from the dropdown.  You may want to get feedback from other users too.

There have been a number of new commits, including requiring leptonica 1.74 - you could rebuild with latest sources.

I have usually been uninstalling the old version and then installing the new one. It wipes out the share/tessdata directory ... is it possible to save the user's tessdata directory?

**Comment by manisandro** [comment]
> 1. This version also works only with the 3.04 traineddata not with 4.0
alpha.

I don't know what I could do differently on my part, except building a different snapshot of tesseract

> 2. Please change 'About program' to show tesseract version as 3.05 dev - It
> may be released as 3.05 - as bug fix release for 3.04.
> https://github.com/tesseract-ocr/tesseract/tree/3.05

I use the `TESSERACT_VERSION_STR` exposed in the tesseract header, but I could build a snapshot against 3.05.00 if you wish

> 3. Change readme.txt regarding downloading traineddata to use 3.04 tag of
> tessdata repo.
> https://github.com/tesseract-ocr/tessdata/tree/3.04.00

Ah yes

> 4. In case the master branch of tesseract (c1ee2fe) is using the 3.0x
version of traineddata instead of 4.0alpha, please file an issue.

I'll have a look

> I have usually been uninstalling the old version and then installing the new one. It wipes out the share/tessdata directory ... is it possible to save the user's tessdata directory?

Just install the new version directly without explicitly uninstalling the old one. The installer for the new version will launch the uninstaller of the previous version, but will also back up and restore the tessdata directory.

**Comment by Shreeshrii** [comment]
I have filed an issue at
https://github.com/tesseract-ocr/tesseract/issues/609

You could try building with the latest snapshot. Hopefully that will be
compatible with the 4.0 traineddata.

I am interested in trying out the new version traineddata. Thanks!

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by Shreeshrii** [comment]
Which OEM , ocr engine mode are you using for gimagereader

- excuse the brevity, sent from mobile

**Comment by manisandro** [comment]
That would be `OEM_DEFAULT`.

Updated builds:
https://smani.fedorapeople.org/tmp/gImageReader_3.2.0_qt5_x86_64_tesseract-25fed52.exe
https://smani.fedorapeople.org/tmp/gImageReader_3.2.0_qt5_i686_tesseract-25fed52.exe

**Comment by Shreeshrii** [comment]
Thanks, It is working now.

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by Shreeshrii** [comment]
Please include the gitversion or date as part of the about info. There are
a number of users interested in using this for Hindi. It will be a useful
way to identify whether they have the correct version installed.

See https://groups.google.com/forum/#!topic/technical-hindi/AznbemnXeoU to
basic info for people to try this out.

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com
