### ISSUE TITLE
output not saved in utf8 encoding

### ISSUE THREAD

**Issue by Shreeshrii** [manisandro/gImageReader#142]
I am testing the 4.0alpha version of gimagereader.

When doing OCR on a page with French and Hindi text, the OCR happens correctly and output window shows the OCRed text ok. However, when the file is saved it does not seem to be in utf-8 encoding and Hindi is displayed as ?.

If I copy the text and paste in text file then it works fine.

Original image, saved text (gi.txt) and copied text (gimagereader.txt) files are attached.

[24-gimagereader.txt](https://github.com/manisandro/gImageReader/files/680027/24-gimagereader.txt)

[24-gi.txt](https://github.com/manisandro/gImageReader/files/680028/24-gi.txt)

![24](https://cloud.githubusercontent.com/assets/5095331/21581612/a570f618-d05e-11e6-8492-4d55544d849e.png)

**Comment by manisandro** [comment]
Did you select UTF-8 as text file encoding in the program settings?

**Comment by Shreeshrii** [comment]
It was at the default value of system encoding. I changed it to utf-8 and it works now. Appreciate your prompt response. Thanks!
