### ISSUE TITLE
Is gImagereader available for ubuntu?

### ISSUE THREAD

**Issue by Shreeshrii** [manisandro/gImageReader#143]
I would like to test gImagereader using the new 4.0alpha version of tesseract on on ubuntu 14.04 (bash on windows 10). Is there a package that is available for this?

Thanks!

**Comment by manisandro** [comment]
The official builds from my [PPA](https://launchpad.net/~sandromani/+archive/ubuntu/gimagereader) all use the tesseract version available in the official Ubuntu repositories (with 14.04 shipping with tesseract 3.03.02).
I'm curious though what's the reason for using the Ubuntu version via bash on top of Windows when there already exists a native Windows version.

**Comment by Shreeshrii** [comment]
I do not have access to Linux, but want to test it for a few others who
want to use it on Ubuntu 14.04.

The bash environment on Windows provides an environment similar to Ubuntu
14.04, hence I asked for that version.

Since Indic language accuracy is much improved in the 4.0alpha, the old ppa
won't work.

I have built leptonica and Tesseract from source on this. I will look at
compiling instructions for gimagereader to try and build it. Will let u
know if I run into problems.

- excuse the brevity, sent from mobile

**Comment by Shreeshrii** [comment]
If you have a list of Ubuntu packages that you used for the ppa, that will
be helpful. I tried with the debian package names linked from the wiki but
got stuck at gtkmm itself.

- excuse the brevity, sent from mobile

**Comment by manisandro** [comment]
The packages I use are exactly those listed in the debian control file (in fact, that is one of the package source files). What error do you get?

**Comment by Shreeshrii** [comment]
shree@ALL-IN-1-TOUCH:/mnt/c/Users/User/shree$ sudo add-apt-repository
ppa:sandromani/gimagereader
sudo: unable to resolve host ALL-IN-1-TOUCH
 A graphical GTK/Qt frontend to tesseract-ocr
 More info: https://launchpad.net/~sandromani/+archive/ubuntu/gimagereader
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keyring `/tmp/tmphpgkc68c/secring.gpg' created
gpg: keyring `/tmp/tmphpgkc68c/pubring.gpg' created
gpg: requesting key B4591784 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmphpgkc68c/trustdb.gpg: trustdb created
gpg: key B4591784: public key "Launchpad PPA for Sandro Mani" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
shree@ALL-IN-1-TOUCH:/mnt/c/Users/User/shree$ sudo apt-get update
sudo: unable to resolve host ALL-IN-1-TOUCH
Hit http://ppa.launchpad.net trusty InRelease
Hit http://ppa.launchpad.net trusty InRelease
Ign http://archive.ubuntu.com trusty InRelease
Hit http://security.ubuntu.com trusty-security InRelease
Hit http://ppa.launchpad.net trusty InRelease
Hit http://archive.ubuntu.com trusty-updates InRelease
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Hit http://ppa.launchpad.net trusty/main Translation-en
Hit http://security.ubuntu.com trusty-security/main amd64 Packages
Hit http://archive.ubuntu.com trusty-backports InRelease
Hit https://deb.nodesource.com trusty InRelease
Hit https://deb.nodesource.com trusty InRelease
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Hit http://security.ubuntu.com trusty-security/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty Release.gpg
Hit https://deb.nodesource.com trusty/main amd64 Packages
Hit http://ppa.launchpad.net trusty/main Translation-en
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Hit http://security.ubuntu.com trusty-security/universe amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/main amd64 Packages
Hit http://ppa.launchpad.net trusty/main Translation-en
Hit http://security.ubuntu.com trusty-security/multiverse amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/restricted amd64 Packages
Get:1 https://deb.nodesource.com trusty/main Translation-en_IN
Hit https://deb.nodesource.com trusty/main Sources
Hit http://security.ubuntu.com trusty-security/main Translation-en
Hit http://archive.ubuntu.com trusty-updates/universe amd64 Packages
Hit https://deb.nodesource.com trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/multiverse amd64 Packages
Hit http://security.ubuntu.com trusty-security/multiverse Translation-en
Get:2 https://deb.nodesource.com trusty/main Translation-en_IN
Hit http://archive.ubuntu.com trusty-updates/main Translation-en
Hit http://security.ubuntu.com trusty-security/restricted Translation-en
Hit http://archive.ubuntu.com trusty-updates/multiverse Translation-en
Hit http://security.ubuntu.com trusty-security/universe Translation-en
Hit http://archive.ubuntu.com trusty-updates/restricted Translation-en
Hit http://archive.ubuntu.com trusty-updates/universe Translation-en
Hit http://archive.ubuntu.com trusty-backports/main amd64 Packages
Hit http://archive.ubuntu.com trusty-backports/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty-backports/universe amd64 Packages
Hit http://archive.ubuntu.com trusty-backports/multiverse amd64 Packages
Hit http://archive.ubuntu.com trusty-backports/main Translation-en
Hit http://archive.ubuntu.com trusty-backports/multiverse Translation-en
Hit http://archive.ubuntu.com trusty-backports/restricted Translation-en
Hit http://archive.ubuntu.com trusty-backports/universe Translation-en
Hit http://archive.ubuntu.com trusty Release
Hit http://archive.ubuntu.com trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty/universe amd64 Packages
Hit http://archive.ubuntu.com trusty/multiverse amd64 Packages
Ign https://deb.nodesource.com trusty/main Translation-en_IN
Ign https://deb.nodesource.com trusty/main Translation-en
Hit http://archive.ubuntu.com trusty/main Translation-en
Ign https://deb.nodesource.com trusty/main Translation-en_IN
Hit http://archive.ubuntu.com trusty/multiverse Translation-en
Ign https://deb.nodesource.com trusty/main Translation-en
Hit http://archive.ubuntu.com trusty/restricted Translation-en
Hit http://archive.ubuntu.com trusty/universe Translation-en
Ign http://archive.ubuntu.com trusty/main Translation-en_IN
Ign http://archive.ubuntu.com trusty/multiverse Translation-en_IN
Ign http://archive.ubuntu.com trusty/restricted Translation-en_IN
Ign http://archive.ubuntu.com trusty/universe Translation-en_IN
Reading package lists... Done
shree@ALL-IN-1-TOUCH:/mnt/c/Users/User/shree$ sudo apt-get install qtspell
sudo: unable to resolve host ALL-IN-1-TOUCH
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package qtspell
shree@ALL-IN-1-TOUCH:/mnt/c/Users/User/shree$ sudo apt-get install
gtkspellmm
sudo: unable to resolve host ALL-IN-1-TOUCH
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package gtkspellmm
shree@ALL-IN-1-TOUCH:/mnt/c/Users/User/shree$ sudo apt-get install gtkspell3
sudo: unable to resolve host ALL-IN-1-TOUCH
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package gtkspell3
shree@ALL-IN-1-TOUCH:/mnt/c/Users/User/shree$


ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by Shreeshrii** [comment]
ok, it works now, when I gave

sudo apt-get libgtkspellmm-3.0-dev



ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by Shreeshrii** [comment]
shree@ALL-IN-1-TOUCH:/mnt/c/Users/User/shree$ cd gImageReader
shree@ALL-IN-1-TOUCH:/mnt/c/Users/User/shree/gImageReader$ mkdir build
shree@ALL-IN-1-TOUCH:/mnt/c/Users/User/shree/gImageReader$ cd build
shree@ALL-IN-1-TOUCH:/mnt/c/Users/User/shree/gImageReader/build$ cmake
-DINTERFACE_TYPE=qt5
CMake Error: The source directory
"/mnt/c/Users/User/shree/gImageReader/build" does not appear to contain
CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

I tried copying CMakeLists.txt to build directory, but that did not work.
So I gave the command from the main gImageReader directory. That started
the process but got an error later -- here is the relevant portion

[ 10%] Built target gimagereader_automoc
[ 11%] Generating qrc_gimagereader.cpp
Scanning dependencies of target gimagereader
[ 12%] Building CXX object
CMakeFiles/gimagereader.dir/common/CCITTFax4Encoder.cc.o
[ 14%] Building CXX object CMakeFiles/gimagereader.dir/qt/src/Acquirer.cc.o
[ 15%] Building CXX object CMakeFiles/gimagereader.dir/qt/src/Config.cc.o
[ 17%] Building CXX object
CMakeFiles/gimagereader.dir/qt/src/ConfigSettings.cc.o
[ 18%] Building CXX object
CMakeFiles/gimagereader.dir/qt/src/CrashHandler.cc.o
[ 20%] Building CXX object
CMakeFiles/gimagereader.dir/qt/src/DisplayRenderer.cc.o
[ 21%] Building CXX object CMakeFiles/gimagereader.dir/qt/src/Displayer.cc.o
[ 22%] Building CXX object
CMakeFiles/gimagereader.dir/qt/src/DisplayerToolHOCR.cc.o
[ 24%] Building CXX object
CMakeFiles/gimagereader.dir/qt/src/DisplayerToolSelect.cc.o
[ 25%] Building CXX object
CMakeFiles/gimagereader.dir/qt/src/MainWindow.cc.o
[ 27%] Building CXX object
CMakeFiles/gimagereader.dir/qt/src/OutputEditor.cc.o
[ 28%] Building CXX object
CMakeFiles/gimagereader.dir/qt/src/OutputEditorHOCR.cc.o
/mnt/c/Users/User/shree/gImageReader/qt/src/OutputEditorHOCR.cc: In
constructor ‘OutputEditorHOCR::OutputEditorHOCR(DisplayerToolHOCR*)’:
/mnt/c/Users/User/shree/gImageReader/qt/src/OutputEditorHOCR.cc:279:67:
error: ‘Format_Grayscale8’ is not a member of ‘QImage’
  m_pdfExportDialogUi.comboBoxImageFormat->addItem(_("Grayscale"),
QImage::Format_Grayscale8);
                                                                   ^
make[2]: *** [CMakeFiles/gimagereader.dir/qt/src/OutputEditorHOCR.cc.o]
Error 1
make[1]: *** [CMakeFiles/gimagereader.dir/all] Error 2
make: *** [all] Error 2
shree@ALL-IN-1-TOUCH:/mnt/c/Users/User/shree/gImageReader$


ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by manisandro** [comment]
Probably a too old qt5 version, use qt4 instead.

**Comment by Shreeshrii** [comment]
shree@ALL-IN-1-TOUCH:/mnt/c/Users/User/shree/gImageReader$ cmake
-DINTERFACE_TYPE=qt4
-- GSettings schemas will be installed locally.
-- GSettings shemas will be compiled.
-- qt4 interface will be built
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such
file or directory
CMake Error at /usr/share/cmake-2.8/Modules/FindQt4.cmake:1386 (message):
  Found unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x
Call Stack (most recent call first):
  CMakeLists.txt:118 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/mnt/c/Users/User/shree/gImageReader/CMakeFiles/CMakeOutput.log".


ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by manisandro** [comment]
Install the qt4 dependency set:
    
    libqt4-dev libqtspell-qt4-dev libpoppler-qt4-dev

**Comment by Shreeshrii** [comment]
Thanks. Next error ..

-- Found Qt4: /usr/bin/qmake (found version "4.8.6")
-- checking for module 'QJson'
--   package 'QJson' not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:283
(message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:337
(_pkg_check_modules_internal)
  CMakeLists.txt:121 (PKG_CHECK_MODULES)


-- Configuring incomplete, errors occurred!


ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by manisandro** [comment]
libqjson-dev

**Comment by Shreeshrii** [comment]
Thanks. I will continue tomorrow. Appreciate your prompt help.

- excuse the brevity, sent from mobile

**Comment by Shreeshrii** [comment]
Thanks, I tried with gt4, it is not finding the poppler files, probably missing some include path

shree@ALL-IN-1-TOUCH:/mnt/c/Users/User/shree/gImageReader/build$ cmake ../ -DINTERFACE_TYPE=qt4
-- GSettings schemas will be installed locally.
-- GSettings shemas will be compiled.
-- qt4 interface will be built
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found Qt4: /usr/bin/qmake (found version "4.8.6")
-- checking for module 'QtSpell-qt4>=0.8.0'
--   found QtSpell-qt4, version 0.8.2
-- checking for module 'QJson'
--   found QJson, version 0.8.1
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/c/Users/User/shree/gImageReader/build
shree@ALL-IN-1-TOUCH:/mnt/c/Users/User/shree/gImageReader/build$ make
Scanning dependencies of target gettextizeui
[  1%] Generating ui_PdfExportDialog.h
[  2%] Generating ui_AboutDialog.h
[  4%] Generating ui_ConfigDialog.h
[  5%] Generating ui_CrashHandler.h
[  7%] Generating ui_MainWindow.h
[  8%] Generating ui_PageRangeDialog.h
-- Gettextizing /mnt/c/Users/User/shree/gImageReader/build/ui_AboutDialog.h
-- Gettextizing /mnt/c/Users/User/shree/gImageReader/build/ui_ConfigDialog.h
-- Gettextizing /mnt/c/Users/User/shree/gImageReader/build/ui_CrashHandler.h
-- Gettextizing /mnt/c/Users/User/shree/gImageReader/build/ui_MainWindow.h
-- Gettextizing /mnt/c/Users/User/shree/gImageReader/build/ui_PageRangeDialog.h
-- Gettextizing /mnt/c/Users/User/shree/gImageReader/build/ui_PdfExportDialog.h
[  8%] Built target gettextizeui
Scanning dependencies of target gimagereader_automoc
[ 10%] Automoc for target gimagereader
Generating moc_Acquirer.cpp
Generating moc_Config.cpp
Generating moc_ConfigSettings.cpp
Generating moc_CrashHandler.cpp
Generating moc_Displayer.cpp
Generating moc_DisplayerToolHOCR.cpp
Generating moc_DisplayerToolSelect.cpp
Generating moc_MainWindow.cpp
Generating moc_OutputEditor.cpp
Generating moc_OutputEditorHOCR.cpp
Generating moc_OutputEditorText.cpp
Generating moc_OutputTextEdit.cpp
Generating moc_Recognizer.cpp
Generating moc_Scanner.cpp
Generating moc_SourceManager.cpp
Generating moc_SubstitutionsManager.cpp
Generating moc_TessdataManager.cpp
Generating moc_ScannerSane.cpp
[ 10%] Built target gimagereader_automoc
[ 11%] Generating qrc_gimagereader.cxx
Scanning dependencies of target gimagereader
[ 12%] Building CXX object CMakeFiles/gimagereader.dir/common/CCITTFax4Encoder.cc.o
[ 14%] Building CXX object CMakeFiles/gimagereader.dir/qt/src/Acquirer.cc.o
[ 15%] Building CXX object CMakeFiles/gimagereader.dir/qt/src/Config.cc.o
[ 17%] Building CXX object CMakeFiles/gimagereader.dir/qt/src/ConfigSettings.cc.o
[ 18%] Building CXX object CMakeFiles/gimagereader.dir/qt/src/CrashHandler.cc.o
[ 20%] Building CXX object CMakeFiles/gimagereader.dir/qt/src/DisplayRenderer.cc.o
/mnt/c/Users/User/shree/gImageReader/qt/src/DisplayRenderer.cc:22:25: fatal error: poppler-qt4.h: No such file or directory
 #include <poppler-qt4.h>
                         ^
compilation terminated.
make[2]: *** [CMakeFiles/gimagereader.dir/qt/src/DisplayRenderer.cc.o] Error 1
make[1]: *** [CMakeFiles/gimagereader.dir/all] Error 2
make: *** [all] Error 2

**Comment by Shreeshrii** [comment]
I tried the gtk version also. It built fully but gives error during execution.

shree@ALL-IN-1-TOUCH:/mnt/c/Users/User/shree/gImageReader/build$ sudo make install
sudo: unable to resolve host ALL-IN-1-TOUCH
[sudo] password for shree:
[ 42%] Built target gimagereader
[100%] Built target potfiles_1
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/share/glib-2.0/schemas/org.gnome.gimagereader.gschema.xml
-- Compiling GSettings schemas
-- Installing: /usr/local/share/locale/cs/LC_MESSAGES/gimagereader.mo
-- Installing: /usr/local/share/locale/de/LC_MESSAGES/gimagereader.mo
-- Installing: /usr/local/share/locale/el/LC_MESSAGES/gimagereader.mo
-- Installing: /usr/local/share/locale/es_ES/LC_MESSAGES/gimagereader.mo
-- Installing: /usr/local/share/locale/fr/LC_MESSAGES/gimagereader.mo
-- Installing: /usr/local/share/locale/it/LC_MESSAGES/gimagereader.mo
-- Installing: /usr/local/share/locale/pl/LC_MESSAGES/gimagereader.mo
-- Installing: /usr/local/share/locale/pt_BR/LC_MESSAGES/gimagereader.mo
-- Installing: /usr/local/share/locale/ru/LC_MESSAGES/gimagereader.mo
-- Installing: /usr/local/share/locale/sl/LC_MESSAGES/gimagereader.mo
-- Installing: /usr/local/share/locale/sv/LC_MESSAGES/gimagereader.mo
-- Installing: /usr/local/share/locale/tr/LC_MESSAGES/gimagereader.mo
-- Installing: /usr/local/share/locale/uk/LC_MESSAGES/gimagereader.mo
-- Installing: /usr/local/share/locale/zh_TW/LC_MESSAGES/gimagereader.mo
-- Installing: /usr/local/share/locale/zh_HK/LC_MESSAGES/gimagereader.mo
-- Installing: /usr/local/share/locale/zh_CN/LC_MESSAGES/gimagereader.mo
-- Installing: /usr/local/bin/gimagereader-gtk
-- Installing: /usr/local/share/icons/hicolor/48x48/apps/gimagereader.png
-- Installing: /usr/local/share/icons/hicolor/128x128/apps/gimagereader.png
-- Installing: /usr/local/share/icons/hicolor/256x256/apps/gimagereader.png
-- Installing: /usr/local/share/appdata/gimagereader-gtk.appdata.xml
-- Installing: /usr/local/share/applications/gimagereader-gtk.desktop
-- Installing: /usr/local/share/doc/gimagereader/manual-cs.html
-- Installing: /usr/local/share/doc/gimagereader/manual.html
shree@ALL-IN-1-TOUCH:/mnt/c/Users/User/shree/gImageReader/build$ gimagereader-gtk

(gimagereader-gtk:798): Gtk-WARNING **: Unknown property: gtkmm__GtkMenuButton.use-popover

(gimagereader-gtk:798): Gtk-WARNING **: /build/gtk+3.0-3sSotQ/gtk+3.0-3.10.8/./gtk/gtkcontainer.c:1166: child property `position' of container class `gtkmm__GtkHeaderBar' is not writable

(gimagereader-gtk:798): Gtk-WARNING **: Unknown property: gtkmm__GtkMenuButton.use-popover

(gimagereader-gtk:798): Gtk-WARNING **: Unknown property: gtkmm__GtkSpinButton.max-width-chars

(gimagereader-gtk:798): Gtk-WARNING **: /build/gtk+3.0-3sSotQ/gtk+3.0-3.10.8/./gtk/gtkcontainer.c:1166: child property `position' of container class `gtkmm__GtkHeaderBar' is not writable

(gimagereader-gtk:798): Gtk-WARNING **: /build/gtk+3.0-3sSotQ/gtk+3.0-3.10.8/./gtk/gtkcontainer.c:1166: child property `position' of container class `gtkmm__GtkHeaderBar' is not writable

(gimagereader-gtk:798): Gtk-WARNING **: /build/gtk+3.0-3sSotQ/gtk+3.0-3.10.8/./gtk/gtkcontainer.c:1166: child property `position' of container class `gtkmm__GtkHeaderBar' is not writable

(gimagereader-gtk:798): Gtk-WARNING **: Unknown property: gtkmm__GtkMenuButton.use-popover

(gimagereader-gtk:798): Gtk-WARNING **: /build/gtk+3.0-3sSotQ/gtk+3.0-3.10.8/./gtk/gtkcontainer.c:1166: child property `position' of container class `gtkmm__GtkHeaderBar' is not writable

(gimagereader-gtk:798): Gtk-WARNING **: /build/gtk+3.0-3sSotQ/gtk+3.0-3.10.8/./gtk/gtkcontainer.c:1166: child property `position' of container class `gtkmm__GtkHeaderBar' is not writable

(gimagereader-gtk:798): Gtk-WARNING **: /build/gtk+3.0-3sSotQ/gtk+3.0-3.10.8/./gtk/gtkcontainer.c:1166: child property `position' of container class `gtkmm__GtkHeaderBar' is not writable
Error opening data file /usr/local/share/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!

(gimagereader-gtk:798): dconf-WARNING **: failed to commit changes to dconf: Failed to execute child process "dbus-launch" (No such file or directory)

(gimagereader-gtk:798): dconf-WARNING **: failed to commit changes to dconf: Failed to execute child process "dbus-launch" (No such file or directory)

(gimagereader-gtk:798): Gtk-WARNING **: Unknown property: gtkmm__GtkMenuButton.use-popover

(gimagereader-gtk:798): Gtk-WARNING **: Unknown property: gtkmm__GtkMenuButton.use-popover

(gimagereader-gtk:798): dconf-WARNING **: failed to commit changes to dconf: Failed to execute child process "dbus-launch" (No such file or directory)

(gimagereader-gtk:798): dconf-WARNING **: failed to commit changes to dconf: Failed to execute child process "dbus-launch" (No such file or directory)

**Comment by manisandro** [comment]
Is libpoppler-qt4-dev installed?

**Comment by Shreeshrii** [comment]
Yes, and I see the file in /use/include/popper/qt4

I thought maybe there was a conflict because of qt5 and uninstalled the qt5
packages, but same error.

I was able to build the gtk version but getting some run time errors. The
icons are also not displaying. I will send a screenshot.

- excuse the brevity, sent from mobile

**Comment by Shreeshrii** [comment]
![gi-gtk](https://cloud.githubusercontent.com/assets/5095331/21601319/382cd368-d1af-11e6-8e31-5ab967fdacb1.png)

**Comment by manisandro** [comment]
Did you start from a fresh build directory when compiling against qt4?

As for the icons, you'll need to install an icon theme, i.e. for the gtk interface `adwaita-icon-theme` should work.

**Comment by Shreeshrii** [comment]
Thanks so much for your help.

Since I am running under windows bash environment, Based on some forum
posts I also did the following:

sudo sed -i
's$<listen>.*</listen>$<listen>tcp:host=localhost,port=0</listen>$'
/etc/dbus-1/session.conf

I rebuilt using qt4 in a fresh build directory and also installed the
following

sudo apt-get install dbus-x11 packagekit

packagekit setup gave some error during install

Preparing to unpack .../packagekit_0.8.12-1ubuntu5_amd64.deb ...
Unpacking packagekit (0.8.12-1ubuntu5) ...
Processing triggers for shared-mime-info (1.2-0ubuntu3) ...
Setting up packagekit (0.8.12-1ubuntu5) ...
initctl: Unable to connect to Upstart: Failed to connect to socket
/com/ubuntu/upstart: Connection refused
runlevel:/var/run/utmp: No such file or directory
invoke-rc.d: policy-rc.d denied execution of force-reload.
Failed to open connection to "system" message bus: Failed to connect to
socket /var/run/dbus/system_bus_socket: No such file or directory

I am still getting some related errors during execution of gimagereader on
the console, though the OCR is happening

$ gimagereader-qt4
Could not find PackageKit on DBus, dictionary autoinstallation will not work
Failed to load dictionary:
QInotifyFileSystemWatcherEngine::addPaths: inotify_add_watch failed:
Invalid argument
QFileSystemWatcher: failed to add paths: /home/shree
QInotifyFileSystemWatcherEngine::addPaths: inotify_add_watch failed:
Invalid argument
QFileSystemWatcher: failed to add paths: /home/shree/tmp
QInotifyFileSystemWatcherEngine::addPaths: inotify_add_watch failed:
Invalid argument
QFileSystemWatcher: failed to add paths: /
QInotifyFileSystemWatcherEngine::addPaths: inotify_add_watch failed:
Invalid argument
QFileSystemWatcher: failed to add paths: /home/shree
QInotifyFileSystemWatcherEngine::addPaths: inotify_add_watch failed:
Invalid argument
QFileSystemWatcher: failed to add paths: /home
QInotifyFileSystemWatcherEngine::addPaths: inotify_add_watch failed:
Invalid argument
QFileSystemWatcher: failed to add paths: /tmp
QInotifyFileSystemWatcherEngine::addPaths: inotify_add_watch failed:
Invalid argument
QFileSystemWatcher: failed to add paths: /tmp/tmp.iSObdyXnWn
QInotifyFileSystemWatcherEngine::addPaths: inotify_add_watch failed:
Invalid argument
QFileSystemWatcher: failed to add paths: /tmp/tmp.iSObdyXnWn/bih
QInotifyFileSystemWatcherEngine::addPaths: inotify_add_watch failed:
Invalid argument
QFileSystemWatcher: failed to add paths:
/tmp/tmp.iSObdyXnWn/bih/bih.Adobe_Devanagari.exp0.tif


--------------
I am trying to OCR a multipage tif. In case of pdf file I got a dropdown
choice asking to choose between current page and multiple pages (windows
version) but I am not seeing the same for multipage tif.







ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by manisandro** [comment]
Multipage tiff support is currently not complete, I've submitted a patch to upstream Qt to enable this: https://codereview.qt-project.org/#/c/181043/

As for the various errors, I guess they are limitations / rough edges of ubuntu-on-windows. Not much the application can do about that.

If you want to test with a proper Ubuntu environment without a bare-metal install, I'd suggest you just installed VirtualBox and installed a full Ubuntu virtual machine.

**Comment by Shreeshrii** [comment]
​OK.

I am listing below the commands required for building on ubuntu 14.04 - in
my case qt4 worked out best.

sudo add-apt-repository ppa:sandromani/gimagereader
sudo apt-get update
sudo apt-get install cmake g++ debhelper   libsane-dev   libpodofo-dev
sudo apt-get install libqt4-dev libqtspell-qt4-dev libpoppler-qt4-dev
libqjson-dev

sudo apt-get install qt4-dev-tools
sudo apt-get install dbus-x11 packagekit

sudo apt-get install libgtkspellmm-3.0-dev  libgtkmm-3.0-dev
 libgtksourceviewmm-3.0-dev  libcairomm-1.0-dev  libpoppler-glib-dev
libjson-glib-dev  libxml++2.6-dev

sudo apt-get install qtbase5-dev  qttools5-dev  qttools5-dev-tools
 libqtspell-qt5-dev libpoppler-qt5-dev
​

**Comment by Shreeshrii** [comment]
Hi,
I tried installing on a ubuntu machine today. I had installed tesseract using a ppa.
The process went smoothly till the end... when I got the error related to ltesseract

Please let me know what to change to fix it. I want to use the 4.0 version. Thanks.

```
Linking CXX executable gimagereader-qt4
/usr/bin/ld: cannot find -ltesseract
collect2: error: ld returned 1 exit status
make[2]: *** [gimagereader-qt4] Error 1
make[1]: *** [CMakeFiles/gimagereader.dir/all] Error 2
make: *** [all] Error 2
sanskrit@sanskrit:~/gImageReader/build$ ls /usr/lib/*tess*
/usr/lib/libtesseract.so.3  /usr/lib/libtesseract.so.3.0.3  /usr/lib/libtesseract.so.4  /usr/lib/libtesseract.so.4.0.0
sanskrit@sanskrit:~/gImageReader/build$ ls /usr/lib/*tess* -la
lrwxrwxrwx 1 root root      21 Feb 12  2014 /usr/lib/libtesseract.so.3 -> libtesseract.so.3.0.3
-rw-r--r-- 1 root root 2979880 Feb 12  2014 /usr/lib/libtesseract.so.3.0.3
lrwxrwxrwx 1 root root      21 Feb 23 11:54 /usr/lib/libtesseract.so.4 -> libtesseract.so.4.0.0
-rw-r--r-- 1 root root 3217240 Feb 23 11:54 /usr/lib/libtesseract.so.4.0.0
sanskrit@sanskrit:~/gImageReader/build$ ls /usr/local/lib/*tess* -la
ls: cannot access /usr/local/lib/*tess*: No such file or directory
sanskrit@sanskrit:~/gImageReader/build$

```

**Comment by manisandro** [comment]
Hi
You need to install libtesseract-dev for the version you want to use.

**Comment by Shreeshrii** [comment]
Thanks. I tried with tesseract 4.0, getting the following error

```
Linking CXX executable gimagereader-qt4
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libtesseract.a(svutil.o): undefined reference to symbol 'sem_post@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [gimagereader-qt4] Error 1
make[1]: *** [CMakeFiles/gimagereader.dir/all] Error 2
make: *** [all] Error 2
```

Can you tell me what file the program looks for. I want to make sure that there are no old versions around, because cmake reports 'found tesseract 3.05-dev' while I have tried installing 4.0-alpha.

**Comment by manisandro** [comment]
Hi
Which package are you using for 4.0? Depending on how it is packaged you may need to adjust the CMakeLists file to ensure it picks up the correct headers. And the pthread error is because the tesseract.so was not linked against libpthread despite requiring a symbol of it. You can workaround this by adding `-lpthread` to the `TARGET_LINK_LIBRARIES(gimagereader [...]` in CMakeLists.txt

**Comment by Shreeshrii** [comment]
I was trying to use https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr

But gImagereader build was not finding leptonica related files.

So, finally, I built both leptonica and tesseract from github source. Was able to build ok after that.

Thanks for your help.
