### ISSUE TITLE
newest version gets stuck on Windows

### ISSUE THREAD

**Issue by narayaan** [manisandro/gImageReader#144]
I just tried the newest version on Windows 7. Everything went fine, but after I downloaded the newest tessdata file for Dutch gImagereader  gets stuck every time I try to use this language.

**Comment by manisandro** [comment]
Can you try using
https://github.com/tesseract-ocr/tessdata/raw/3.04.00/nld.traineddata
instead?
Looks like the traineddatas have been updated for the upcoming 4.00.00 release and they might be incompatible with tesseract 3.04.00.

**Comment by narayaan** [comment]
Hi, using the older traineddata solves the issue. I'll stick with this until tesseract gets an update.

**Comment by manisandro** [comment]
I'm preparing for a 3.2.1 release in the coming weeks (mainly waiting for updated translations to come in), and that version will ensure that the downloaded traineddata file is compatible with the tesseract version in use.
