### ISSUE TITLE
gtkspell-error-quark: Enchant error

### ISSUE THREAD

**Issue by urosjarc** [manisandro/gImageReader#147]
How to resolve this error?
```
(gimagereader-gtk:24029): glibmm-CRITICAL **: 
unhandled exception (type Glib::Error) in signal handler:
domain: gtkspell-error-quark
code  : 0
what  : enchant error for language: vi_VN
```

**Comment by manisandro** [comment]
This error originates from the gtkspell library and happends when the dictionary corresponding to the specified language code cannot be loaded. Reasons for that can be multiple, common reasons might be that the dictionary files are missing, corrupt, empty or not readable by the user.
How did you install the dictionary?

**Comment by urosjarc** [comment]
I have install it with `apt-get install tesseract-ocr-vie `

**Comment by manisandro** [comment]
That's the tesseract language definition, not the spelling dictionary. For the spelling dictionary you'll want the `hunspell-vi` package.

**Comment by urosjarc** [comment]
One more question, I have pdf with hinduism to english translation and there are words with [diacritic signs](https://en.wikipedia.org/wiki/Diacritic), curently I use vietnam signs to do this, but its not perfect translation.
How can I translate text with full diacritic support?

**Comment by manisandro** [comment]
That's really a matter of finding an appropriately trained tesseract language definition. Not sure if a standard one exists for english + diacritic signs though. If not, you might want to look at training yourself: https://github.com/tesseract-ocr/tesseract/wiki/Training-Tesseract
