### ISSUE TITLE
Merge textlines in hOCR editor

### ISSUE THREAD

**Issue by foghawk** [manisandro/gImageReader#149]
Merge erroneously-broken adjacent textlines (analogously to the merge words feature).

**Comment by diegodlh** [comment]
And maybe merging paragraphs as well. At times, paragraphs are broken up. Merging them would be neat (though the broken lines issue has actually greater impact on the final result).

**Comment by manisandro** [comment]
This is now implemented in master for the Qt interface. Testing feedback welcome.

**Comment by foghawk** [comment]
My build merges selections of 3 or more items incorrectly: missing some items from the selection, merging subsequent siblings instead, and segfaulting if there are not enough subsequent siblings. If you or someone else can confirm (the last three words in a line should crash if merged), I have a fix.

The merge option will also happily merge graphics regions with text blocks, which is probably undesirable. I have a fix for this too, but it's tangled up in a feature addition I haven't finished testing yet.

**Comment by foghawk** [comment]
Oops, looks like the crash I described is the same as #250. Fix is in #261.

**Comment by foghawk** [comment]
Graphics/text merges are fixed in #272.

**Comment by manisandro** [comment]
Implemented in Gtk and disallowed merging of items which are not of the same HOCR class.
