### ISSUE TITLE
Please provide a silent install option for Windows

### ISSUE THREAD

**Issue by luca76** [manisandro/gImageReader#15]
Hi,

we would like to develop gImageReader, but it seems that the installer can't be run unattended.

Coult you make a installer with silent option or a .zip to extract to a folder without installing it?

**Comment by manisandro** [comment]
Hello,

NSIS (the install system used by gImageReader) supports silent installs via the `/S` switch (case sensitive). What however needs to be done is to allow installation configuration (i.e. standard vs multilingual) as well as possibly install location to be configured via switches from the command line also.

**Comment by luca76** [comment]
Thank you

**Comment by delboni** [comment]
Is there a way to install the multilingual version silently?
