### ISSUE TITLE
gImageReader hang with Japanese (jpn)

### ISSUE THREAD

**Issue by knightzx** [manisandro/gImageReader#152]
gImageReader hang when working with Japanese (jpn).
Sometimes, it hang with Korean (ko) and Chinese (Traditional) - zh_TW too.
Work fine with Tesseract though.
Tested with 3.2.0 on Windows 10 x64 and Fedora 25 x64.

**Comment by manisandro** [comment]
Can you try manually downloading the tessdata and ensuring they are for the tesseract-3.04 release, i.e. from 
https://github.com/tesseract-ocr/tessdata/tree/3.04.00
?
I'm hoping to make a new release today, which should ensure that the tessdatas downloaded via the tessdata manager are compatible with the tesseract version in use (the background is that some tessdatas for tesseract-4.0.0 have started to appear which are incompatible with 3.04).

**Comment by knightzx** [comment]
Sorry for the late reply.
It's working fine now with tessdatas from tesseract-3.04 release.
Thanks for your work!
