### ISSUE TITLE
Spellcheck: use Hunspell instead of myspell

### ISSUE THREAD

**Issue by cmrdt** [manisandro/gImageReader#153]
currently does not detect/recognize 
`that’s` (U+2019 right single quotation mark)  but does for `that's`  (U+0027 apostrophe)
also `nut—free`  vs `nut-free` 

but hunspell does https://en.wikipedia.org/wiki/Hunspell https://github.com/hunspell/hunspell https://abiword.github.io/enchant/

**Comment by manisandro** [comment]
I suppose you are using the Qt interface? This is a matter for the spelling library. GtkSpell should handle U+2019 correctly, but looks like this logic is missing in QtSpell. As for `—`, as I read the description (
"may be used in pairs to offset parenthetical text"), I don't think it is actually a legal hyphenation character?

**Comment by ZaMaZaN4iK** [comment]
But why do you use QtSpell instead of Hunspell? e.g. Libreoffice using Hunspell as spellchecker.

**Comment by manisandro** [comment]
GtkSpell/QtSpell are wrappers around various spelling libraries, hunspell among others, so hunspell is used if you supply corresponding dictionaries.

**Comment by manisandro** [comment]
Both gtkspell and qtspell pass `that’s` to enchant as a whole word, which then checks it according to the selected dictionary. I don't think that the spelling libraries should split `that’s` to two words `that` and `s`, as far as I understand it should be up to the dictionary file to handle this.
In any event there is nothing to do in gImageReader itself about this.
