### ISSUE TITLE
Request new version of gimagereader for tesseract 4.0.0-alpha

### ISSUE THREAD

**Issue by Shreeshrii** [manisandro/gImageReader#155]
I noticed that you have released a new version of gimagereader.

Please update the version with 4.0.0-alpha tesseract-ocr with the latest git version also.

Thanks!

**Comment by manisandro** [comment]
Please try:
https://smani.fedorapeople.org/tmp/gImageReader_3.2.1_qt5_i686_tesseract4.0.0.git2f10be5.exe
https://smani.fedorapeople.org/tmp/gImageReader_3.2.1_qt5_x86_64_tesseract4.0.0.git2f10be5.exe

If these work I'll upload them to the official releases page.

**Comment by Shreeshrii** [comment]
Thank you. It is working fine.

Earlier, there were blue selection areas shown on the page. Now it does not do so. Is that intentional?

**Comment by manisandro** [comment]
Uhm, can you give more details? The selection behaviour should be the same as before!

**Comment by Shreeshrii** [comment]
If I remember correctly, loading an image automatically came with text
areas selected in blue.

Now, it doesn't happen. I can select areas with mouse.

I was wondering whether it was an effect of adding the psm modes .

- excuse the brevity, sent from mobile

**Comment by manisandro** [comment]
From my quick check I see the behaviour unaltered:
- In plain text mode, either you drag the areas manually or pick autodetect layout
- In hOCR mode, selection areas are only drawn when browsing though the result tree to mark the corresponding region in the source image.

Am I missing something?

**Comment by Shreeshrii** [comment]
I am processing a large pdf right now. Will test after that.

Question, in the pdf, different pages are skewed at different angles. Do I
need to preprocess using scantailor, or go thru each page in giamgereader
to change the angle, or does the program handle it automatically?

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by manisandro** [comment]
Tesseract does this to a certain degree, but I'm not sure by how much. Might be worth investigating.

**Comment by Shreeshrii** [comment]
You are right. Autodetect layout, which is indicated by the icons after OCR mode is what I remembered from before. It is creating the blue selection areas.

I was confusing it with the Automatic Page Segmentation under the psm menu.

Thanks for clarifying.

**Comment by manisandro** [comment]
Builds added to the releases page.

**Comment by Shreeshrii** [comment]
Thanks. I have added a link in
https://github.com/tesseract-ocr/tesseract/wiki/4.0-with-LSTM

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com
