### ISSUE TITLE
Evaluate flatpack / appimage / etc

### ISSUE THREAD

**Issue by Shreeshrii** [manisandro/gImageReader#156]
tesseract and leptonica are available from ppa at

https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr

**Comment by manisandro** [comment]
I suppose I should have a look at flatpack for a solution which covers most distros.

**Comment by Shreeshrii** [comment]
gimagereader seems to give better result than using command line tesseract and it is able to take pdf file as input. Hence, it will be great if you can figure out ways to make it available in most distros.

Thanks for your good work!

**Comment by akuckartz** [comment]
Debian package, please!

**Comment by kerimlcr** [comment]
[gimagereader.zip](https://github.com/manisandro/gImageReader/files/802289/gimagereader.zip)

**Comment by kerimlcr** [comment]
Hi @akuckartz 
I saw you wrote yesterday
if u want https://github.com/kerimlcr/gImageReader-3.2.1-debian-package
regards

**Comment by manisandro** [comment]
FWIW, PPA-style debian packages are hard since I don't see debian offering any such service?

**Comment by innir** [comment]
@akuckartz: A Debian package of gimagereader exists since 2014: https://tracker.debian.org/pkg/gimagereader

**Comment by ZaMaZaN4iK** [comment]
@manisandro What is the status of the task?

**Comment by innir** [comment]
Close it I'd say, there are packages for many Linux distributions and that's the preferred way of distributing software on Linux desktops.

**Comment by manisandro** [comment]
I suppose at one stage flatpack could be looked at although personally I also prefer the traditional packages.

**Comment by manisandro** [comment]
Closing in favor of #396
