### ISSUE TITLE
[feature request] picture settings recognize

### ISSUE THREAD

**Issue by Golddouble** [manisandro/gImageReader#157]
Hello,

I have the following file which a want to convert to a file with hidden text:
[extrahiert 19.pdf](https://github.com/manisandro/gImageReader/files/784933/extrahiert.19.pdf)

So unfortunately I do not know the settings of the picture in the pdf above.  I was not able to convert the above file with gImageReader to get an output file with the same quality and the same space (KB) like the input file.

So what I want, is to get the best quality with a minimum of space (KB).
I think if I want reach this, most often this is the case when I convert the pdf with the same settings as the input file has. For example the same dpi and if it is jpg the same compression (for example 70%) and the same picture format.

I mean settings like this:
![grafik](https://cloud.githubusercontent.com/assets/13977359/23092329/72560ad6-f5c8-11e6-8047-2a20a3445614.png)

So my suggestion is, that gImageReader can recognize this settings and then make suggestions for the saving-settings. 

Maybe in a further development stage gImageReader can be run in an automatic mode in which gImageReader recognizes the settings for each page of the input pdf and then takes this setting to convert this site.

Would be great if you could implement this.

**Comment by manisandro** [comment]
I don't think it is possible to read all settings from the PDF, i.e. the JPEG compression quality is not stored in the image metadata AFAIK. Also, in the general case you can have a PDF with various images encoded and compressed differently. The basic logic for a PDF with all images stored the same way should be fairly easy, but the corner cases can become quite tedious.

**Comment by Golddouble** [comment]
> I don't think it is possible to read all settings from the PDF, i.e. the JPEG compression quality is not stored in the image metadata AFAIK. 

Only when gImageReader can recognize the dpi, format and compressionmode and gives this data as a suggestion to the user this would be a great information.

> Also, in the general case you can have a PDF with various images encoded and compressed differently.

As I said above:  In a further development stage gImageReader can be run in an automatic mode in which gImageReader recognizes the settings for each page of the input pdf and then takes this setting to convert this site. So in this case it doesn't matter if each page has an other setting in the input file.

> The basic logic for a PDF with all images stored the same way should be fairly easy, but the corner cases can become quite tedious.

I do not understand what you want to say with this sentence, because my english is not as good. Can you formulate it in an other way?

**Comment by manisandro** [comment]
German: Was ich damit meine, is dass obschon die Grundlogik ziemlich einfach sein sollte, kann es mühsam werden alle Spezialfälle abzudecken, z.B.:
- Mehrere Bilder innerhalb einer Seite, wobei die Bilder unterschiedlich kodiert sind
- Kein Bild (sondern z.B. nur Text) auf der ersten Seite

**Comment by Golddouble** [comment]
If there are various pictures with different settings on the same page, gImageReader could give the user the settings of the picture with the highest quality of this PDF page.

If there is no picture on a page, gImageReader can indicate: "no picture".

**Comment by Golddouble** [comment]
> you can have a PDF with various images encoded and compressed differently.

In the later auto mode maybe each image should be handled separate.

---------------------------------------------------------------------------------------------------------

> kann es mühsam werden alle Spezialfälle abzudecken

Maybe you should implement a option dialog window, where the user can tune the behaviour of this "Spezialfälle."

---------------------------------------------------------------------------------------------------------

> I mean settings like this:
![grafik](https://cloud.githubusercontent.com/assets/13977359/23092329/72560ad6-f5c8-11e6-8047-2a20a3445614.png)

> So my suggestion is, that gImageReader can recognize this settings and then make suggestions for the saving-settings.

Of course there must also be a recognization for this setting:
![grafik](https://cloud.githubusercontent.com/assets/13977359/23250042/9ffbfe40-f9a7-11e6-8576-64d51e02a0af.png)

**Comment by manisandro** [comment]
> In the later auto mode maybe each image should be handled separate.
That would give unexpected results in the case there are different images on the same page

> Maybe you should implement a option dialog window, where the user can tune the behaviour of this "Spezialfälle."
Not sure how this would simplify things as opposed to just reading the output of pdfimages and picking the options.

> Of course there must also be a recognization for this setting:
The goal of that setting is being a sane default for the OCR, not being equal to the resolution of the input PDF.

(And keep in mind that this is a hobby project of mine, so "Of course there must also be [...]" -> "It would be nice if there were [...]")

**Comment by Golddouble** [comment]
> That would give unexpected results in the case there are different images on the same page.

Ah I see. It is not possible to produce a PDF page with hidden text and different settings for different images behind this page.

> Not sure how this would simplify things as opposed to just reading the output of pdfimages and picking the options.

Maybe you are right.

> (And keep in mind that this is a hobby project of mine, so "Of course there must also be [...]" -> "It would be nice if there were [...]")

Sorry. If you feel a little bothered: It was not my intention. It is already a great peace of software. Thank you for programming it for free.  :-)

**Comment by manisandro** [comment]
I'm closing this because I really don't see the effort of covering all the corner cases worthwhile.
