### ISSUE TITLE
putting together words with hyphen

### ISSUE THREAD

**Issue by Golddouble** [manisandro/gImageReader#158]
I have a A4 document with **two pages on one page**.
I mark each region blue.
![two pages on one site](https://cloud.githubusercontent.com/assets/13977359/23096065/8956793a-f615-11e6-8db0-0aa24c27b4e1.PNG)

Then I start text recognition. 
So my expectation was that gImageReader merges together the two word parts. For example Wo-che or vor-stellen. But it does not.
![two pages on one site 2](https://cloud.githubusercontent.com/assets/13977359/23096137/bc83a034-f616-11e6-96fe-293bdbfb193d.PNG)

**Comment by manisandro** [comment]
Well that's what the join hyphenated words function is there for? Or you you mean that that function does not work?

**Comment by Golddouble** [comment]
Sorry. It was my fault. I made further tests. It works.
