### ISSUE TITLE
[feature request] merge PDF's with hidden text

### ISSUE THREAD

**Issue by Golddouble** [manisandro/gImageReader#159]
Hello,

Sometimes I scan a part of a book and make a text recognization of this part, so that I get a PDF with hidden Text of this part. 
Some days later I scan the next part of the book and I again make a text recognization. And so on.

Problem: Now I have several seperate PDF's. But I want to have one PDF.
Yes, I have a programme to merge PDF's. But after the merging process with this programme the hidden text is deleted. So I have to run again the text recognization process of gImageReader through this merged PDF.

Suggestion: Would be grat, if it would be possible to merge PDF's with gImageReader without losing the hidden Text. Could you please implement this?

**Comment by manisandro** [comment]
Is the scenario that you are always appending to an existing PDF, or would you need to insert the new pages at a random position inside the existing document?

**Comment by Golddouble** [comment]
It is appending to an existing PDF.

**Comment by Golddouble** [comment]
@manisandro 
I have found an external solution for this.
You can close this issue.

**Comment by manisandro** [comment]
Ok cool.
