### ISSUE TITLE
Automatic spellchecking doesn't always update properly

### ISSUE THREAD

**Issue by ferdnyc** [manisandro/gImageReader#16]
I noticed (this is in the QT port, 3.0.1, from Fedora package `gimagereader-qt-3.0.1-1.fc20.x86_64`) that there's an issue with how the automatic spellchecking updates when making edits in the middle of the text. The easiest way to see this in action is to join two valid words together into an invalid word, then separate them again.

When the invalid compound word is created, it's flagged as misspelled:

![screenshot from 2015-03-29 20 22 01](https://cloud.githubusercontent.com/assets/538020/6888632/2202d074-d652-11e4-8a45-ab7788c9c634.png)

After the space is reinserted, the word ahead of the cursor is updated, but the word following the cursor is still flagged (incorrectly) as misspelled:

![screenshot from 2015-03-29 20 22 11](https://cloud.githubusercontent.com/assets/538020/6888641/54920744-d652-11e4-845f-5a2793338b09.png)

Any editing within or immediately following the second word (even, say, replacing a letter with itself) will cause the red squiggle to disappear. Deactivating and reactivating automatic spellcheck also clears it.

Right-clicking on the red-squiggled word shows a context menu with no suggestions, _and_ without the Add/Ignore items, so it seems the system doesn't "really" think the word is misspelled. The red squiggle is just a graphical anomaly.

**Comment by manisandro** [comment]
Thanks for reporting, I'll take a look (this is most likely a bug in qtspell [1]).

[1] https://github.com/manisandro/qtspell

**Comment by manisandro** [comment]
Fixed in qtspell-0.7.2, F20 update will be in testing shortly [1].

[1] https://admin.fedoraproject.org/updates/qtspell-0.7.2-1.fc20

**Comment by ferdnyc** [comment]
Ayup! Just pulled the new version from the build page and the issue cleared right up. I'll keep an eye out for when it officially pushes to f20-updates-testing, and then provide the requisite positive karma.
