### ISSUE TITLE
jp2 files not displaying in windows version

### ISSUE THREAD

**Issue by Shreeshrii** [manisandro/gImageReader#161]
I am using the tess 4.0 version of giamgereader on windows.

When opening jp2 files, the image is displayed momentarily and then disappears. Still, if OCR option is chosen, the page is OCRed correctly, just there is no visible image.

![jp2-not-displayed](https://cloud.githubusercontent.com/assets/5095331/23396895/f63d1dee-fdbb-11e6-8a7d-925f5df2330c.png)

**Comment by manisandro** [comment]
Can you share the image?

**Comment by Shreeshrii** [comment]
zip file with sample jp2 file.

[pushti_margiya_stotra_ratnakara_0016.zip](https://github.com/manisandro/gImageReader/files/806542/pushti_margiya_stotra_ratnakara_0016.zip)

**Comment by Shreeshrii** [comment]
The jp2 files are from the tar file for some old books at archive.org. I could download the pdf version and use that also, just wanted to check whether accuracy would be better with the original jp2 images.

**Comment by manisandro** [comment]
Looks like rendering the jp2 below a certain resolution fails (low-resolution rendering is used to ensure the image is more readable when zoomed out). 4364135 avoid the empty image replacing the original full-resolution image.
