### ISSUE TITLE
Hindi spelling dictionaries

### ISSUE THREAD

**Issue by Shreeshrii** [manisandro/gImageReader#163]
You can use

https://github.com/Shreeshrii/hindi-hunspell/blob/master/dict-hi_IN.zip

hunspell dictionaries to use with Hindi  language.

Please add \u0964 \u0965 \u0966 \u0967 \u0968 \u0969 \u096A \u096B \u096C \u096D \u096E \u096F to the delimiters, so that hindi numerals (० १ २ ३ ४ ५ ६ ७ ८ ९) and punctuation (। and ॥) are also recognized.

(i had to make the above change in the advanced tab when using dspellcheck plugin with notepad++.

**Comment by Shreeshrii** [comment]
The sanskrit dictionary is too big. Hence, deleted the link above.

**Comment by manisandro** [comment]
This needs to be implemented in GtkSpell / QtSpell.

**Comment by manisandro** [comment]
Actually I think it should be up to the dictionary file to configure the spelling engine tokenizer accordingly. I can't imagine that the library is supposed to specially handle all possible delimiters of all possible languages. I'd ask the hi_IN dictionary maintainer. In any event, nothing that should be done in gImageReader itself.

**Comment by Shreeshrii** [comment]
Ok. Thanks!
