### ISSUE TITLE
EN spelling dictionary indispensable?

### ISSUE THREAD

**Issue by eemantsal** [manisandro/gImageReader#165]
Hi again.

When I start gImageReader I get this warning, and the language selector is greyed and disabled.

![captura_20170315_185634](https://cloud.githubusercontent.com/assets/18057272/23963121/978078e0-09b0-11e7-9b7d-223eca5b8bea.png)

I have Hunspell only in my native language, and Teseract correctly installed in my language too. In order to being able to use gImageReader is mandatory to install the amercian version of Hunspell?

**Comment by manisandro** [comment]
Hi, you need to load an image before you can proceed select the language (problem is that the OCR is a button with a menu, and the OCR button needs to be disabled when no image is loaded, so the menu gets disabled as well as a side consequence).

**Comment by manisandro** [comment]
So in hOCR mode recognition is always performed on the entire page. From a UI perspective it is easier to have the entire page recognized and then allow the user to throw away the parts it does not want in the recognized document tree than having the user select single portions of the image and then attempting to reassemble these portions to a page. Which regions are text and which are images is detected automatically. If an image region is misdetected as text, you can remove the corresponding items in the document tree and add a manually defined image region.
ODT is something I'd like to support in the future, however the lack of a decent c++ library for writing the format is a hindrance.

**Comment by eemantsal** [comment]
That would be a perfect approach if things were perfect, heheh, but sadly they aren't, and automatic layout detection usually fails miserably in every single OCR software I have ever known, even the famous Omnipage for Windows, when images are B/W and/or graphics with lots of lines (photos and drawings are usually correctly detected, that's right).
Try to OCR a page with texts and diagrams (especially in black and white, as I said), or music, try to recognize a page with a score and the lyrics below. Automatic detection in cases like these are, almost always, a disaster, the diagrams or the musical symbols are interpreted a alphabetic characters, or some parts as text and some as images, and you end losing more time repairing the mess that defining the frames by hand and how the OCR must consder then from the beginning.

Anyway, I agree that when it works well, it's handier an automatic process, and it probably should be the per default behavior; but I think there should be the option for the user to define zones by hand and to tell the program which ones are text and which are image. That's more or les the habitual behavior in most OCR software, for example the mentioned Omnipage, or the other open source app I mentioned yesterday, OCRFeeder.

> If an image region is misdetected as text, you can remove the corresponding items in the document tree and add a manually defined image region.

Didn't tried that. I will. But anyway, woudln't it be easier to have a selector to just change a correctly framed area that on the other hand might be wrongly identified as text or image, instead having to delete it and manually define again? Something like those two buttons in OCRFeeder. Please look at the screenshots:
Here you can see how the text column at the very left is indentified as text, colored with a bluish shade:
![captura_20170316_150759](https://cloud.githubusercontent.com/assets/18057272/23999889/f6dfac3a-0a59-11e7-9d9b-367ed1065686.png)

Notice the two buttons at the right, «Texto» and «Imagen» (this is the hispanic verision of the interface, obviously if you try it in other language the buttons text will vary), and how I clicked on «Imagen» after selecting that first text column mantioned before. If you look at it you can see now its greenish shade, which indicates it will be treated as an image and won't be "OCRed". The »Propiedades del texto» area (low right of the screenshot) becomes inactive too.
![captura_20170316_150842](https://cloud.githubusercontent.com/assets/18057272/23999926/1dcb72fc-0a5a-11e7-8b48-e45654c852f8.
I don't mean this interface should be copied, in fact I think it wastes much space just for a pair of buttons, it's design could be better, but the idea of some kind of selector that permits the user correct the automatic zone identification.

> ODT is something I'd like to support in the future, however the lack of a decent c++ library for writing the format is a hindrance.
I know nothing about coding, but coudln't you take the same library other similar programs do? I know I sound soomehow obssesive, heheh, but what library uses OCRFeeder? I suppose you could use the same, no?

**Comment by manisandro** [comment]
Ok so defining the regions beforehand and then recognizing the page should be doable, I'll need to look into it as time allows.

About the library: there is a good python library, but gImageReader is c++ based, and I'd rather not have to depend on the entire python interpreter just to be able to use this library.

**Comment by eemantsal** [comment]
> gImageReader is c++ based, and I'd rather not have to depend on the entire python interpreter just to be able to use this library
Theres an open source ODT editor from an office suite for Linux calle Calligra Words. I think it's written in C or C++, or something with C, xD. Don't know if it could be any helpful. This the technical part, for which I declare myself totally incompetent, sorry. But just in case, here's the code, if you want to have a look on it:
https://community.kde.org/Calligra/Building/2#Latest_Stable_Version

**Comment by manisandro** [comment]
Yes I'm aware of calligra, thanks, problem is needing pick out the code from a large application vs just having a handly library one can use in the program. As always, it's a question of time and effort.

**Comment by eemantsal** [comment]
I understand. And what about "QTextDocumentWriter class"? Excuse if my question is a nonsense, it's fruit of this coding illiterate that I am, heheh: are classes and libraries any similar in their functionality, I mean, even if they weren't the same, could a class like that by QT be easily implemented to provide this export to ODT feature?

**Comment by manisandro** [comment]
Problem is that QTextDocumentWriter is Qt which isn't really usable for the Gtk variant of gImageReader (and I really want to keep the Qt and Gtk variants equivalent). Probably the simplest approach is if I code a minimal ODT exporter which just supports the necessary parts of the ODT format. If you want to help, you could look up the ODT spec and collect the minimal set of XML tags (ODT ist just an XML format) which allows for paragraphs, images, font size and family as well as bold/italic. If you can provide a sample XML which includes these elements, I would be able to do the actual coding fairly quickly.

**Comment by eemantsal** [comment]
> QTextDocumentWriter is Qt which isn't really usable for the Gtk 
Ah. I didn't know there were a GTK version of gImageReader, sorry.

> you could look up the ODT spec and collect the minimal set of XML tags (ODT ist just an XML format) which allows for paragraphs, images, font size and family as well as bold/italic. If you can provide a sample XML which includes these elements
About making that XML thing... I think that falls far beyond my technical skills.
I've tried to do some search even if I wasn't really understanding what I was seeing, but I've found this, that seems a sort of list of tags; don't know if it's what you were asking for (the page is in spanish, but the tags list is in english):
https://wiki.dolibarr.org/index.php/Crear_un_modelo_de_documento_ODT#Tags

Another source concerning tags I've read, Wikipedia, says:
> OpenDocument reuses existing open XML standards whenever they are available, and it creates new tags only where no existing standard can provide the needed functionality. Thus OpenDocument uses a subset of DublinCore for metadata, MathML for displayed formulas, SMIL for multimedia, XLink for hyperlinks etc.
Source: https://en.wikipedia.org/wiki/OpenDocument_technical_specification#Reuse_of_existing_formats

Sorry for not being more helpful :-/

**Comment by manisandro** [comment]
I've opened #171 and #172 to track the features we ended up discussing here. Closing this ticket.
