### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by HazTuNido** [manisandro/gImageReader#167]
I'm using 3.1.2 version which is the last one Ubuntu installs so maybe some / all the things I'm going to talk about you maybe correct them if that's the case sorry for bothering you. 

Errors found:
a) the program remembers the "Output pane orientation" but despite that always starts with vertical.
b) when selected several areas and click "recognise selection" icon the program delete the areas and instead recognises the whole page.

Suggestions:
a) it would be very nice if as the cursor moves on the text editing zone the corresponding character on the image would highlight somehow.
b) right now, I've been using your program for OCR some Chinese text with pin yin transcription on it. So, I'd like the character as big as possible. For that:
   ba) it would be nice an "adjust to the width zoom option"
   bb) the images panel has a minimum width restriction. it would be nice to go beyond that so that the image would occupy all the program window width and at the same time it would align the characters on the image with the  just recognised ones bellow when "output pane orientation " is horizontal.

Thanks for your very useful program.

**Comment by manisandro** [comment]
Is that with the gtk or qt interface? Btw you can get the latest version for ubuntu from my PPA:
https://launchpad.net/~sandromani/+archive/ubuntu/gimagereader

As for your suggestions:
a) This is only possible in hOCR mode (available in the 3.2.x series). In plain text mode, the information about the source image is not available in the OCR result
ba) That would be the "Best fit" zoom option which is already available?
bb) It isn't actually the image widget which as a minimum width, but the application toolbar which determines how far the size of the window can be shrinked.

**Comment by HazTuNido** [comment]
gtk or qt? Good question. I actually don't know. How to know?

For some reason I cannot get pass the 3.1.2 version. I tried to update several times, with no result.

ba) No, the "Best fit" would work as the "adjust to the image width" that I have in mind only when the image width is bigger than it's height, but I'm working with a book, so...

bb) if that is so, then what about if the image widget expands over the image and the output text? That would also do the trick, since the program windows can be bigger than the actual screen, i could move it out of the sight that part and focus on getting the text right. Something like this:

![captura de pantalla de 2017-04-07 14-59-00](https://cloud.githubusercontent.com/assets/26999743/24801069/f99118f6-1ba2-11e7-866c-c8f7b9d0cbb7.png)

**Comment by manisandro** [comment]
Judging from the screenshot, you are using the gtk version.

What specifically does not work with the PPA? Are you sure you added the PPA and that it is enabled in the software sources?

ba) Ah I see. Yeah I suppose this could be done.
bb) Uhm I'm not sure I understand what you mean. With images panel, do you mean the sources panel (i.e. where the list of open files is shown) or the actual image canvas? If the former, you can just close the sources panel by clicking on the top-left most icon in the top toolbar.

**Comment by manisandro** [comment]
By the way, the output orientation issues was indeed a bug! Fixed in 80764f5c4c530d45a466a160c0f92b834577c1f9

**Comment by HazTuNido** [comment]
What a muddlehead fellow I am! You are right, the top-left icon "Sources" collapses that "at times annoying" panel :) 

As for the PPA, this is what I get when I try to install it:

`jaime@jaime-A55F2-M3:~$ sudo add-apt-repository ppa:sandromani/gimagereader
[sudo] password for jaime: 
 A graphical GTK/Qt frontend to tesseract-ocr
 Más información: https://launchpad.net/~sandromani/+archive/ubuntu/gimagereader
Pulse [Intro] para continuar o ctrl-c para cancelar

gpg: anillo «/tmp/tmpmveadjrx/secring.gpg» creado
gpg: anillo «/tmp/tmpmveadjrx/pubring.gpg» creado
gpg: solicitando clave B4591784 de hkp servidor keyserver.ubuntu.com
gpg: /tmp/tmpmveadjrx/trustdb.gpg: se ha creado base de datos de confianza
gpg: clave B4591784: clave pública "Launchpad PPA for Sandro Mani" importada
gpg: Cantidad total procesada: 1
gpg:               importadas: 1  (RSA: 1)
OK
jaime@jaime-A55F2-M3:~$ sudo apt-get update
Obj:1 http://ppa.launchpad.net/sandromani/gimagereader/ubuntu xenial InRelease 
Obj:2 http://es.archive.ubuntu.com/ubuntu xenial InRelease                     
Obj:3 http://security.ubuntu.com/ubuntu xenial-security InRelease
Obj:4 http://es.archive.ubuntu.com/ubuntu xenial-updates InRelease
Obj:5 http://es.archive.ubuntu.com/ubuntu xenial-backports InRelease
Leyendo lista de paquetes... Hecho                    
jaime@jaime-A55F2-M3:~$ 
`
Apparently everything goes well, doesn't it? But I'm still with the 3.1.2.

**Comment by manisandro** [comment]
I think the problem is that the ubuntu package is called `gimagereader`, whereas the PPA offers both `gimagereader-gtk` and `gimagereader-qt`. Try removing `gimagereader` and then installing `gimagereader-gtk`. You should then get the version from the PPA.

**Comment by HazTuNido** [comment]
Yes, that was indeed the problem. But contrary to expectations my version is running qt, gtk look awkward and shut down when recognizing to hocr, pdf.

Thanks a lot. I'll let you know if I find any more issues. 

Btw, scanning to hOCR didn't turn to be as useful as I expected.

**Comment by manisandro** [comment]
If by "shut down" you mean crash, I'd be interested in getting stack-trace for that from the crash reporting dialog which should show up.

And hOCR is mainly used for scanning books to PDFs with text overlay. If there is a specific feature you are missing, feel free to open a ticket.

**Comment by HazTuNido** [comment]
Yes I mean crash. That was the gtk version, then the qt freezed when I tried to edit the Chinese text I'm working with (but so many installations and installations went by that it's likely to be due to that) so I went back to the "safe haven" 3.1.2. version. Let me finish OCRing that book, in a few days I'm back to you with that crah log. 

About the hOCR... It's just that I expected to move character by character, but instead moves, every phrase, or even every line. But, since I did played a little myself with tesseract I know that engine doesn't return much detail info, besides the Chinese language is a pain in the ass,  no one knows where a word starts or end, so... It's all quite alright.

**Comment by HazTuNido** [comment]
Should I close this ticket?

**Comment by manisandro** [comment]
There is still the open issue about the fit to width zoom. If that still something you'd like to see, I'd recommend you opend a separate ticket for that specific issue, so that it does not fall off my radar, and then yes, close this one.

**Comment by HazTuNido** [comment]
The zoom was just a suggestion, it's not a vital feature. It's up to you to implement it or not. 
Thank very much for you attention, and for the useful program.
