### ISSUE TITLE
Cannot locate spelling dictionaries for Japanese

### ISSUE THREAD

**Issue by lulubea** [manisandro/gImageReader#169]
I've managed to find the necessary .dic and .aff files for all the other languages I've needed but I can't seem to find Japanese ones. 

Every time I try to install through the application I get an error message that says "No spelling dictionaries found for 'ja_JP'.

**Comment by manisandro** [comment]
Japanese seems indeed hard to find, there is a jp.dic file here [1], no idea whether it is usable though.

Btw, the "no spelling dictionaries" message is just informative, you can ignore it, the program will work regardless, it will just not offer any spell checking for the output without the dictionary.

[1] https://cgit.freedesktop.org/libreoffice/core/tree/i18npool/source/breakiterator/data
