### ISSUE TITLE
Windows installer issue

### ISSUE THREAD

**Issue by jjurkus** [manisandro/gImageReader#170]
To choose a installation directory with NSIS one can use the /D switch. One would use this:

`"gImageReader-setup.exe" /S /D=%InstallDir%`

However, this does not work. The installation directory is given without quotes, this is normal. It works fine on other applications with a NSIS installer.

**Comment by manisandro** [comment]
Mh, by no means an NSIS expert, not sure what's breaking it. `/D` is supposed [1] to set INSTDIR which is used in the NSIS script [2]. A quick google doesn't return much, will need to investigate.

[1] http://nsis.sourceforge.net/Which_command_line_parameters_can_be_used_to_configure_installers
[2] https://github.com/manisandro/gImageReader/blob/master/packaging/win32/installer.nsi.in

**Comment by jjurkus** [comment]
It's only a minor issue to me, so feel free to ignore it a bit. I wish I could point out what should be changed, but nsis scripts are gobbledygook to me :-(
I thought it could be an older issue with nsis, but you have already used 3.01 for the installer, so that shouldn't be it.

**Comment by jjurkus** [comment]
[https://github.com/OpenVPN/openvpn-build/blob/master/windows-nsis/openvpn.nsi](https://github.com/OpenVPN/openvpn-build/blob/master/windows-nsis/openvpn.nsi)

A few things that might help:
they use this:
`InstallDir "$PROGRAMFILES\${PACKAGE_NAME}"`
gImageReader uses this:
`InstallDir @PROGRAMFILES@`
I can't find the explanation for the at-characters. This might be why the 64-bit version installs itself in C:\Program Files (x86)\gImageReader.

In the OpenVPN intaller they use this in the beginning of the onInit function:
`Function .onInit
	${GetParameters} $R0
	ClearErrors`

**Comment by manisandro** [comment]
The `@PROGRAMFILES@` is a substitution placeholder which is replaced by the build script [1]. That the 64-bit version still installs itself to `C:\Program Files (x86)\gImageReader` is odd, according to [2] `$PROGRAMFILES64` should point to `C:\Program Files` on 64-bit Windows. Unless you already had a previous installation of gImageReader < 3.2.0 (which didn't use `$PROGRAMFILES64`) and the new version is re-using the same installation directory. Or perhaps something is wrong in the nsi file...

[1] https://github.com/manisandro/gImageReader/blob/master/packaging/win32/makeinstaller.sh#L182
[2] http://nsis.sourceforge.net/Reference/$PROGRAMFILES

**Comment by manisandro** [comment]
Ok so it looks like `MultiUser.nsh` ignores the `/D` option. Workaround implemented in 2c8250f, and also fixed the `$PROGRAMFILES64` logic to work with `MultiUser.nsh`.

Test builds at
https://smani.fedorapeople.org/tmp/gImageReader_3.2.1_qt5_i686.exe
https://smani.fedorapeople.org/tmp/gImageReader_3.2.1_qt5_x86_64.exe
