### ISSUE TITLE
hOCR: Add ODT export support

### ISSUE THREAD

**Issue by manisandro** [manisandro/gImageReader#171]

**Comment by ZaMaZaN4iK** [comment]
What is status of the issue?

**Comment by manisandro** [comment]
I've done some initial investigation of the ODT format, but currently am too busy with other projects to continue work on this. If anyone wants to give it a shot, feel free ;) I don't think I'll realistically have time before next year.

**Comment by ZaMaZaN4iK** [comment]
I found Qt supports wrinting to ODF format: http://doc.qt.io/qt-5/qtextdocumentwriter.html#setFormat.
Also OCRfeeder supports export to ODT format.

**Comment by manisandro** [comment]
Yes but it assumes you use a QTextEdit, which gImageReader does not.

**Comment by manisandro** [comment]
Initial implementation done for qt

**Comment by manisandro** [comment]
gtk done also. Need to figure out if/how I can set per-page page-sizes.

**Comment by manisandro** [comment]
Initial implementation is fairly complete - obviously still lots of potential improvements.
