### ISSUE TITLE
Error during configure

### ISSUE THREAD

**Issue by Jallot** [manisandro/gImageReader#174]
How can I fix this error during cmake? I have installed all dependencies, but it still doesn't work

`CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
-ltesseract_OUTPUT_NAME
    linked by target "gimagereader" in directory /home/zerogoki/progs/gImageReader

-- Configuring incomplete, errors occurred!
`

**Comment by manisandro** [comment]
You need to install the tesseract development files (tesseract-devel or libtesseract-dev, depending on your distro).

**Comment by Jallot** [comment]
Thank you, now it works
