### ISSUE TITLE
Filter or sort words by confidence

### ISSUE THREAD

**Issue by diegodlh** [manisandro/gImageReader#175]
It would be very useful if confidence value for each word could be shown in the tree view, and sort or filter them by confidence value. This way, along with spellchecking, proofreading the document would be much more straightforward.

**Comment by manisandro** [comment]
I'm a bit skeptical about sorting, the treeview would become quite chaotic to manage... But I've added a button to allow toggling whether to display the confidence values in treeview.

**Comment by manisandro** [comment]
wconf column also implemented in gtk.
