### ISSUE TITLE
Djvu reading support? [Feature 

### ISSUE THREAD

**Issue by Wacek** [manisandro/gImageReader#176]
This is probably a niche feature, but if thats not a lot of work it would be nice to have> Some countries have a system of national institutions (say a network of digital libraries for example) that all use Djvu as a standard for releasing houndreds of thousands of documents online. So it would be nice to have it anyway.

**Comment by ZaMaZaN4iK** [comment]
@manisandro Does gImageReader support reading DjVu format? if not can you add it?

I agree with @Wacek - there are a lot of DjVu documents, which aren't searchable (without recognized text).

**Comment by manisandro** [comment]
It shouldn't be terribly difficult to add (basically adding a DjVu renderer in `{gtk/qt}/src/DisplayRenderer.cc`, but I haven't yet had the time to look at it.

**Comment by ZaMaZaN4iK** [comment]
Yes, but we should choose DjVu renderer. I tried to find any in Google - unfortunately i didn't find any populer library for DjVu rendering.

**Comment by manisandro** [comment]
Okular and evince use djvulibre: http://djvu.sourceforge.net/

**Comment by ZaMaZaN4iK** [comment]
Ok, i will look into djvulibre and, possibly, add support for djvu format.

**Comment by ZaMaZaN4iK** [comment]
I am working on adding DjVu support to gImageReader. I looked into Okular project - they have nice C++ wrapper on DjVuLibre. I think we can simply copy&paste it, refactor, remove useless stuff and use it.

First prototype works on pure C API.

**Comment by manisandro** [comment]
Cool!

**Comment by ZaMaZaN4iK** [comment]
@manisandro https://github.com/manisandro/gImageReader/pull/191

**Comment by manisandro** [comment]
Implemented for Qt and Gtk.
