### ISSUE TITLE
"Keep line break" does not work for all quote characters

### ISSUE THREAD

**Issue by innir** [manisandro/gImageReader#177]
Hi,

when using the option "Keep line break if preceded or succeeded by quote" only ' and " are taken into account but not » and «.
I think it's just adding them here: https://github.com/manisandro/gImageReader/blob/master/gtk/src/OutputEditorText.cc#L177-#L180 and there: https://github.com/manisandro/gImageReader/blob/master/qt/src/OutputEditorText.cc#L138-#L141.

Should I just file a PR?

Best,

Philip

**Comment by manisandro** [comment]
Hi
Yes please - and you could also fix the comment while at it, should be quote, not dot ;)
Thanks

**Comment by innir** [comment]
Done: PR #178
