### ISSUE TITLE
Using Conan as dependency manager

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [manisandro/gImageReader#179]
Hello

Did you try to use Conan as dependency manager for gImageReader? For developer will be easier to manage and setup dev-environment.

Do you need it? Can i help you with it.

P.S. About Image processing library - i am working on it.

**Comment by manisandro** [comment]
Personally I'm perfectly happy with the distribution's package manager.

**Comment by ZaMaZaN4iK** [comment]
Yeah, it's good. If you have package manager in your OS :) E.g. developers on Windows haven't it. And will not have in near future.

Conan is already standard package manager for C++ now, has really nice integration with Cmake. 

And in ubuntu i didn't find qtspell in standard repo.

**Comment by manisandro** [comment]
So how does conan work? Do you need to supply build scripts for all possible operating systems?

**Comment by ZaMaZaN4iK** [comment]
http://conanio.readthedocs.io/en/latest/

Your question: Conan has own store for packages (you can use your own, but you don't need do it for gImageReader, just use supposed store).

You should create package with library in conan store (you can simply do it). In our case, you should create package with qtspell. After that in gImageReader you should create file conanfile.txt with all dependencies. After that you should add to CMakeLists.txt smth like conan_basic_setup() and target_link_libraries(${CONAN_LIBS}).

Before building project for downloading all dependencies before make you should use conan install .. -build=missing

How it works: conan tries to download already precompiled packages from online store. If there is not already build package for your OS/compiler/flags/etc, conan automatically tries to download sources and build it. 

You can read documentation for brief explanation.

**Comment by manisandro** [comment]
Hi, I'm currently pretty busy with other stuff, so no I didn't do much reading.

**Comment by manisandro** [comment]
Hi, do see this as worth keeping open? Personally I don't have a need for this.
