### ISSUE TITLE
Image preprocessing status

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [manisandro/gImageReader#180]
Hello.

Added DeSkew support to gImageReader.

**Comment by ZaMaZaN4iK** [comment]
I integrated inside gImageReader some image preprocessing. I don't use for now external libray - just created 'preprocess' folder inside, and put all image processing allgorithms in this folder. Is it ok?

**Comment by manisandro** [comment]
Sure, fine for me. Thanks!

**Comment by ZaMaZaN4iK** [comment]
Hello @manisandro,
you can check current status of the preprocessing library here: https://github.com/ZaMaZaN4iK/PRLib

**Comment by manisandro** [comment]
@ZaMaZaN4iK I suppose this is now tracked in #195?

**Comment by manisandro** [comment]
Closing since tracked elsewhere.
