### ISSUE TITLE
hOCR export broken with 3.2.2

### ISSUE THREAD

**Issue by andrewcchen** [manisandro/gImageReader#181]
Saving output in hOCR mode in 3.2.2 will result in a skeleton html without any content. This feature was functional in 3.2.1.

**Comment by manisandro** [comment]
Argh! Thanks for reporting.

**Comment by manisandro** [comment]
Fixed in version 3.2.3, thanks agains for reporting.

**Comment by andrewcchen** [comment]
That was fast, thanks!
