### ISSUE TITLE
Unhandled exception in first use

### ISSUE THREAD

**Issue by innir** [manisandro/gImageReader#182]
Hi,

I got the following bug report in Debian - it's rather vague so the reporter might need to share some more info, could you help?

The full report is at: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=861377

> On my first attempt to use the program I got
> 
> 
> --8<---------------cut here---------------start------------->8---
> 
> ```
> (gimagereader-gtk:5289): Gtk-WARNING **: Allocating size to gtkmm__GtkViewport 0x559a83e73d90 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
> 
> (gimagereader-gtk:5289): glibmm-CRITICAL **: 
> unhandled exception (type Glib::Error) in signal handler:
> domain: gtkspell-error-quark
> code  : 0
> what  : enchant error for language: pl_PL
> 
> ```
> --8<---------------cut here---------------end--------------->8---

**Comment by manisandro** [comment]
Hi
Looks like something went wrong in gtkspell territory. Ask your reporter to run the application inside gdb as follows

    G_DEBUG=fatal-criticals gdb gimagereader-gtk
    [... wait for program to abort ...]
    bt

Ideally he should have gimagereader and gtkspell3 debug symbols installed.

(The warning about the size allocation is harmless).

**Comment by innir** [comment]
The reporter can't reproduce the problem now.
