### ISSUE TITLE
Mirrored text layer (hebrew, and probably other rtl languages)

### ISSUE THREAD

**Issue by usharf** [manisandro/gImageReader#183]
I think I saw a discussion here before, but I can't find it.
OCR'ed images containing text in Hebrew seem to be recognised perfectly with tessarect 4.0alpah, though the problem with the pdf preduced (also visible when previewing) persists. 
The text is flipped/mirroed... is there a simple solution for this using the GUI or command line?

10x

![screenshot from 2017-07-28 17-37-37](https://user-images.githubusercontent.com/1701421/28724876-d97d1dc8-73bb-11e7-8116-cb09a685a78b.png)

**Comment by manisandro** [comment]
Is this only with the PDF output? I would need to check whether the PDF library (PoDoFo) supports RTL text layouts...

**Comment by usharf** [comment]
Yes. When I choose to recognise/to clipboard, text seems ok.

**Comment by manisandro** [comment]
PoDoFo does not appear to provide any out-of-the-box support for complex scripts like arabic or hebrew. So this is probably requires quite a lot of work...

**Comment by manisandro** [comment]
Tracking in #291

**Comment by Asquator** [comment]
Any solutions by now?

**Comment by Asquator** [comment]
Here are some examples:
Original image:
![heb](https://github.com/manisandro/gImageReader/assets/92979391/dd8f07b4-dae3-40b8-880f-efabf75ffad8)

Non-uniformized output (reversed when copied):
[heb_nu.pdf](https://github.com/manisandro/gImageReader/files/12422800/heb_nu.pdf)

Uniformized output (text location shifted):
[heb_u.pdf](https://github.com/manisandro/gImageReader/files/12422804/heb_u.pdf)
