### ISSUE TITLE
Remember source/output folders across sessions

### ISSUE THREAD

**Issue by manisandro** [manisandro/gImageReader#186]

**Comment by ZaMaZaN4iK** [comment]
I think we should store this info in QSettings (i mean here of course only Qt version). And in the next startup just load this info. 

I want prepare prototype for the Qt version.

**Comment by manisandro** [comment]
I've actually got some work in progress here which I just need to finish...

**Comment by ZaMaZaN4iK** [comment]
Ok. Please assign the task to you. Because i wanted to start work on the issue.

**Comment by manisandro** [comment]
61c84dc6f2564af1a57efacda7b63387a93e285c
852716d008f67255ae9c5f5f4a07a5996b642a17
