### ISSUE TITLE
No red undelinings in the output area for misspelled words

### ISSUE THREAD

**Issue by zbgns** [manisandro/gImageReader#187]
I like gImageReader very much and really appreciate that there is constant development on it.  I use Ubuntu 16.04 and I have latest gImageReader 3.2.3 version installed. I compiled it from source as I want to use it with the latest alpha Tesseract 4.00 version. Everything works as expected apart of the spellcheck tool. Misspelled words are not red underlined, however if I'm clicking with right mouse button on such word there is suggestion from the dictionary as well as menu for choosing language. It work like this with English and other languages I have installed and tested. I also checked if myspell is correctly installed and everything seems to be fine. 
It is minor issue for me, and expect that it is may be not a problem with gImageReader directly, but with other software underneath. Nevertheless I would be grateful for any suggestion what should I check to make this working.

**Comment by manisandro** [comment]
Did you compile the gtk, qt4 or qt5 interface?

**Comment by zbgns** [comment]
qt5

**Comment by manisandro** [comment]
If you compile https://github.com/manisandro/qtspell, does the example application provided there work?

**Comment by zbgns** [comment]
Well, I need to check it later on. How to use this application? Do I need to compile qtspell first and gImageReader afterwards?

**Comment by manisandro** [comment]
qtspell is a library, you probably already have it installed from my PPA since otherwise you wouldn't have been able to compile gimagereader. But if you compile qtspell from source, you'll also compile a small standalone example application I ship with qtspell, and the interesting thing to verify is whether that one works.

**Comment by zbgns** [comment]
Understand. Later on today I will be able to check it and confirm.

**Comment by zbgns** [comment]
I would like to confirm that the example application works after compiling. Please find below the printscreen of it.
![qtspell_example](https://user-images.githubusercontent.com/24705368/29689895-1be0e13a-8925-11e7-9269-1c4362ce27a3.png)
No matter what language is installed. Do you think that next compilation of qImageReader may help?

**Comment by manisandro** [comment]
Hmm, not what I expected... Yeah try recompiling gImageReader against your own qtspell build.

**Comment by zbgns** [comment]
I have this error message during the new gImageReader compilation: 
`usr/include/tesseract/unichar.h:164:10: error: ‘string’ does not name a type static string UTF32ToUTF8(const std::vector<char32>& str32);`
I suppose that there is something wrong with nightly builds of tesseract that I get from unofficial and "untrusted" [PPA.](https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr)

**Comment by manisandro** [comment]
Looks like they forgot the `std::` namespace prefix.

**Comment by zbgns** [comment]
OK. So I need to wait until they fix it.

**Comment by Shreeshrii** [comment]
Please see https://github.com/tesseract-ocr/tesseract/pull/1082 regarding discussion about std::string

**Comment by manisandro** [comment]
Ugh that's just plain ugly.

**Comment by manisandro** [comment]
I've addressed the std issue in 1b8dc31b450f060038c7c5985c332c2f58524409.

**Comment by zbgns** [comment]
Now I'm able to recompile gImageReader using my of qtspell build, but apparently it doesn't help. Still no red underlinings.

**Comment by manisandro** [comment]
Just to be sure: did you check with ldd gimagereader-qt5.exe that it is indeed using qtspell so you built yourself?

**Comment by zbgns** [comment]
Well, I checked that my qt5 version compiled by myself is dependent on` libqtspell-qt5.so.0` from your PPA, whereas example program depends on `libqtspell-qt4.so.0` from my qtspell build. So I compiled gimagereader-qt4 version which has `libqtspell-qt4.so.0` in its dependencies and it does work as expected. I'm not able to build `libqtspell-qt5.so.0` library from source.

By the way I tried also to compile GTK gImageReader version but I have this error message after `make`:
```
[ 57%] Building CXX object CMakeFiles/gimagereader.dir/gtk/src/MainWindow.cc.o
/home/zbgns/Pobrane/gImageReader-master/gtk/src/MainWindow.cc: In lambda function:
/home/zbgns/Pobrane/gImageReader-master/gtk/src/MainWindow.cc:455:125: error: ‘gtk_show_uri_on_window’ was not declared in this scope
 =]{ gtk_show_uri_on_window(static_cast<Gtk::Window*>(m_window)->gobj(), DOWNLOADURL, GDK_CURRENT_TIME, 0); return f
```

**Comment by manisandro** [comment]
What error do you get compiling qtspell-qt5 from source?

**Comment by zbgns** [comment]
I'm not sure whether there is any error message during compilation. I followed build instructions (`cmake ..` then `make` from build folder) but only qtspell-qt4 libraries are built. No qtspell-qt5 files in the build folder. I suppose I'm doing something wrong.

**Comment by manisandro** [comment]
Ah, I forgot to document the `USE_QT5` switch. I've updated the qtspell README, and also changed to Qt5 by default.

**Comment by zbgns** [comment]
OK, thanks. I will try the new qtspell compilation.

**Comment by zbgns** [comment]
I built qtspell with qt5 this time. The example app does not not underline misspelled words. So qt4version  works correctly whereas qt5 does not.

**Comment by manisandro** [comment]
Are you using a particular Qt5 theme?

**Comment by zbgns** [comment]
I didn't change anything so it should be standard Qt5 theme provided by Ubuntu.

**Comment by manisandro** [comment]
This looks to me like a bug in the Qt5 theme that ubuntu uses by default. If you use

    gimagereader-qt5 -style fusion

I imagine it will display correctly. You could also try experimenting with the underline format in qtspell [1]: try using some other underline style listed in [2] and check with the qtspell example whether it makes any difference.

[1] https://github.com/manisandro/qtspell/blob/master/src/TextEditChecker.cpp#L188
[2] http://doc.qt.io/qt-5/qtextcharformat.html#UnderlineStyle-enum

**Comment by zbgns** [comment]
Thanks, `gimagereader-qt5 -style fusion` indeed corrects the problem. I will also try to change underline style and provide my feedback.

**Comment by zbgns** [comment]
I changed the underline style to "WaveUnderline", compiled `qtspell` once again and end `example` underline function started to work. So I installed this compilation of qtspell and gImageReader spellcheck function underlines misspelled words. Many thanks.

**Comment by manisandro** [comment]
I've changed QtSpell to use WaveUnderline. Thanks for reporting and testing!

**Comment by amitdo** [comment]
Tesseract is now at beta 1 stage. 

This version uses std:string everywhere.   `USE_STD_NAMESPACE` is not needed anymore.

**Comment by manisandro** [comment]
@amitdo Thanks for the heads up

**Comment by amitdo** [comment]
Also see: https://github.com/ropensci/tesseract/issues/24#issuecomment-373133986
