### ISSUE TITLE
Windows 10 requires compatibility mode

### ISSUE THREAD

**Issue by Shreeshrii** [manisandro/gImageReader#188]
I am forwarding error report as received

```
gImageReader

Windows binaries of tesseract-ocr 4.0.0-alpha with GUI interface are available for gImageReader from

gImageReader_3.2.1_qt5_i686_tesseract4.0.0.git2f10be5.exe
This GUI has to be set each time for compatibility for W10.settings do not stay.
Somehow I am managing, but a permanent solution is really needed.
Thanks in advance for help.
MNS Rao 
```

**Comment by manisandro** [comment]
I need more details as to what "compatibility for W10" means. (I've never used W10 and don't have access to such a system).

**Comment by Shreeshrii** [comment]
I am guessing the problem maybe related to using 32 bit program on 64 bit
machine with Windows 10.

I have asked him to try with the latest version

-
https://github.com/manisandro/gImageReader/releases/download/v3.2.3/gImageReader_3.2.3_qt5_x86_64_tesseract4.0.0.git2b854e3.exe

**Comment by Shreeshrii** [comment]
>>gimagereader: fortunately now it doesnot show error. Repeated attempts reg compatibility might have done some trick. No guarantee it stays. No worry as  I can work around. Still Sandra Mani may be notified.

It seems to work with the current version.

Closing issue. Thanks!

**Comment by Shreeshrii** [comment]
![to sreedevi kumar](https://user-images.githubusercontent.com/5095331/29975984-1bc31e16-8f56-11e7-9dee-176e4c49df7b.jpg)

>gimagereader -error reappeared. s/s of notice attached

**Comment by manisandro** [comment]
Can you tell the user to open a command line (cmd), then
- cd ..\path\to\gImageReader\bin
- gdb gimagereader-qt5.exe
- set logging on
- run
- > wait for crash
-> backtrace full
-> quit
And then submit gdb.txt which was created in the \gImageReader\bin folder (if the user does not have write access to that folder by default, he will need to start the command line as administrator)

**Comment by Shreeshrii** [comment]
He says no log file was created. Screenshot with error messages is attached.
![cmd1](https://user-images.githubusercontent.com/5095331/30003089-263649f0-90d6-11e7-9576-571493979a5c.png)

**Comment by manisandro** [comment]
He wrote `-> backtrace full`, not `backtrace full`. Gdb reported `Copying output to gdb.txt`, so a log file should have been created in `C:\Program Files\gImageReader\bin`.

**Comment by Shreeshrii** [comment]
> Namaste,
> I find now gimagereader is not showing error.
> I will have to wait for that to happen and collect crash report. 
> will revert when it does.
> MNS Rao
>

**Comment by manisandro** [comment]
Closing given the lack of news, feel free to reopen if it is still an issue.
