### ISSUE TITLE
Request new 4.0.0alpha version to support best traineddata

### ISSUE THREAD

**Issue by Shreeshrii** [manisandro/gImageReader#190]
Ray had uploaded new set of traineddata in https://github.com/tesseract-ocr/tessdata/tree/master/best on August 1.

Does the latest experimental version of gimagreader support these?

If not, I request for a new version for 4.0.0alpha, since the best traineddata has improved recognition for complex script languages.

Thanks!

**Comment by Shreeshrii** [comment]
Please note that the best traineddata only supports --oem 1 (LSTM engine).

**Comment by manisandro** [comment]
Here are builds with latest tesseract git master:

https://smani.fedorapeople.org/tmp/gImageReader_3.2.3_qt5_i686_tesseract4.0.0.git9c2fa0d.exe
https://smani.fedorapeople.org/tmp/gImageReader_3.2.3_qt5_x86_64_tesseract4.0.0.git9c2fa0d.exe

**Comment by Shreeshrii** [comment]
Thanks so much!!!

**Comment by Shreeshrii** [comment]
The default tessedit_ocr_engine_mode is incorrect for Hindi, Sanskrit, Marathi and Nepali in the best traineddatas. best/Devanagari.traineddata works fine.

See the following for a fix.

https://github.com/tesseract-ocr/tessdata/issues/79
