### ISSUE TITLE
New UI windows for image preprocessing step

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [manisandro/gImageReader#195]
Hello @manisandro . 

I want to start work with integrating my image preprocessing result to gImageReader.

Of course i want to start my work on Qt gimagereader's version.

It's very important topic, so at first i have to show you some screenshots from Abbyy fine reader application.

![image](https://user-images.githubusercontent.com/7355383/31638313-96ab387c-b2db-11e7-84f7-63acf3f7cc35.png)

As you on the right side of the application there are some options for manual image preprocessing: deskew, cropping, splitting, some photo corrections, etc.

I recommend create one more tab (is it "tab" right word here?) for image preprocessing only. User will be able to use some algorithms, and after that run OCR on already preprocessed images. What do you think about it? Can we do it in feature branch as experiment? I am not so familiar with Qt's UI part and i don't know gImageReader's internal structure so well as you :-)

**Comment by manisandro** [comment]
Hi @ZaMaZaN4iK 
Cool, looking forward to it! I'd recommend adding the UI in a QDockWidget - they are these dockable portions of the UI such as the sources and output pane. When creating a QDockWidget, you can also specify which regions of the MainWindow are allowed, so you can allow the user to freely move around the pane as he or she prefers.

**Comment by ZaMaZaN4iK** [comment]
Ok. I will start work on integration image preprocessing algorithms to gImageReader ASAP.

**Comment by manisandro** [comment]
Closing since this looks abandoned, feel free to submit a PR if you want to resume working on it.
