### ISSUE TITLE
installing gImageReader 3.2.3 still have version 3.2.1 listed in Windows add-remove program

### ISSUE THREAD

**Issue by sharuzzaman** [manisandro/gImageReader#196]
After installing gImageReader 3.2.3, I can see version 3.2.1 listed in Windows add-remove program.

If I select the version 3.2.1 and click uninstall, it will remove the 3.2.1 version but retain the list of 3.2.3, but the application will be broken. 

Need to uninstall 3.2.3 which add-remove will say that the application was not there and clean up the list.

After that install 3.2.3 again to get a working application

**Comment by manisandro** [comment]
@sharuzzaman Did you perhaps have the 32bit installed before and then installed a 64bit version, or vice versa?

**Comment by manisandro** [comment]
Closing due to no feedback, feel free to reopen if it is still an issue.

**Comment by manisandro** [comment]
@sharuzzaman, I discovered that there were indeed some errors in the installer script. With 3524c814c7024b740e3072db9d9acb52d6ec33c9 the installer should now also work correctly when installing for the current user only and subsequent calls to the installer now correctly detect an installed version regardless of whether it was installed for the current user or for all users.

Test builds with the fix are at

32bit: https://smani.fedorapeople.org/tmp/gImageReader_3.2.3_qt5_i686.exe
64bit: https://smani.fedorapeople.org/tmp/gImageReader_3.2.3_qt5_x86_64.exe
