### ISSUE TITLE
Create searchable Djvu

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [manisandro/gImageReader#197]
Hello.

I know we support creating searchable PDF. Can we add support for creating searchable Djvu?

Djvulibre can do it according to the link https://unix.stackexchange.com/questions/158921/how-to-make-a-djvu-file-searchable

**Comment by manisandro** [comment]
Should be doable, in essence it means implementing a DjvuPDFPainter analogous to https://github.com/manisandro/gImageReader/blob/master/qt/src/OutputEditorHOCR.cc#L186

**Comment by ZaMaZaN4iK** [comment]
Ok, understand. from your point of view - is it needed in gImageReader or not?

**Comment by manisandro** [comment]
Suppose it could be nice to have, but personally have hardly ever encountered a djvu document out there. Probably depends a bit on the field you are active in.

**Comment by manisandro** [comment]
Not planning to work on this.
