### ISSUE TITLE
Add jbig2 compression for PDF

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [manisandro/gImageReader#199]
Hello,

jBig2 compression is very popular for black-and-white compression. jBig is widely-used for PDF-compression. 

https://en.wikipedia.org/wiki/JBIG2

Can we add this algorithm to gImageReader?

**Comment by manisandro** [comment]
Should be doable. The location where images are added to the PDF is
https://github.com/manisandro/gImageReader/blob/master/qt/src/OutputEditorHOCR.cc#L213
and PoDoFo (which gImageReader uses for PDF output) appears to have some knowledge about JBIG2 (i.e. ePdfFilter_JBIG2Decode), though it does not necessarily mean that the encoder and or decoder are implemented in the library, but one may have to supply the compressed data (via SetImageDataRaw, like in the JPEG and Fax cases).

**Comment by manisandro** [comment]
PoDoFo does not support this and generally lossy JBIG2 is not recommended (and even in certain occasions forbidden) due to character substitution issues caused by pattern matching. So I'm not keen on adding this to gImageReader.
