### ISSUE TITLE
Add MRC compression

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [manisandro/gImageReader#200]
MRC is another way for PDF compression. About this method you can read here:
https://www.abbyy.com/ocr-sdk-embedded/pdf-mrc/
https://en.wikipedia.org/wiki/Mixed_raster_content

By this nethod we can reduce PDF output size.

What do you think about it?

**Comment by manisandro** [comment]
AFAICS PoDoFo has no knowledge of the MRC compression, perhaps at a lower level one can manually define a PDF object which contains such a compressed image, but one would need to investigate.

**Comment by manisandro** [comment]
Don't see anything usable out there for implementing MRC compression.
