### ISSUE TITLE
Add barcode and QR-code recognition

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [manisandro/gImageReader#202]
Hello, 
Abbyy FineReader can recognize barcodes and QR-codes. Is it possible for gImageReader?

**Comment by manisandro** [comment]
A quick google search for tesseract + qrcode / barcode does not reveal much, don't know to what extent tesseract is capable to process these. Or one would need to add support for another OCR engine or library which can process these, so potentially lots of work.

**Comment by ZaMaZaN4iK** [comment]
No, tesseract cannot recognize barcodes. But we can use for this e.g. Z-Bar library.
https://github.com/ZBar/ZBar

**Comment by manisandro** [comment]
I suppose that would mean adding an additional processing mode (in addition to "Plain text" and "hOCR + PDF") for barcodes.

**Comment by ZaMaZaN4iK** [comment]
I think, yes. We will have to add additional mode.

But i ask to only about the feature: is it good addition to gImageReader? About implementation we can chat later after deeper research.

**Comment by manisandro** [comment]
Well as far as my own usage is concerned (actually I developed the application for my dad who is a teacher and does lots of OCR) the goals have already been reached long time ago, I've since just implemented what people were requesting. So far I've never received a request for qrcodes or barcodes, so don't know how much demand there is for this.

**Comment by ZaMaZaN4iK** [comment]
I can ask to some people, who use often OCR engines. BTW, on my work we develop our own document managemnt syste. And we have barcodes recognition in our OCR solution.

**Comment by amitdo** [comment]
Leptonica has some code for barcode recognition. I don't know how good is it.

**Comment by ZaMaZaN4iK** [comment]
@amitdo Leptonica has very poor barcode recognizer.

**Comment by ZaMaZaN4iK** [comment]
I suggest use this library: https://github.com/zxing/zxing/tree/00f634024ceeee591f54e6984ea7dd666fab22ae/cpp

FMPOV it's the most powerful open-source in this area.

**Comment by ZaMaZaN4iK** [comment]
@manisandro can we try as experiment use this library?
https://github.com/ftylitak/qzxing

But i am not sure about port to gIR GTK...

**Comment by ZaMaZaN4iK** [comment]
Some results: there is no good library for working with barcodes/QR-codes.

ZBar library is dead; Zxing library (port to C++) is dead. QZxing is based on zxing 2.4, but qzxing isn't high-quality library.

Zbar works faster Zxing, but Zxing hasn't porblems with large QR-codes.

For QR-codes only there are two libraries: quirc ( https://github.com/dlbeer/quirc )

**Comment by ZaMaZaN4iK** [comment]
After discussions with other developers i suggest use ZBar for barcode recognition. It has quite good C++ interface, so you can try to use it

**Comment by manisandro** [comment]
I don't plan to add support for any other engines than tesseract.
