### ISSUE TITLE
Add encryption/decryption support

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [manisandro/gImageReader#205]
As you know PDF supports encryption. With gImageReader we can't AFAIK open encrypted PDF document, OCR it and after that save as encrypted document. 

FMPOV, it's real life use case and we can add it later.

**Comment by ZaMaZaN4iK** [comment]
I tried to show password dialog in PdfRenderer ctor. Unfortunately, it's wrong way because during opening the file we construct more than one time PdfRenderer class.

Also we probably should create all renderers by fabric pattern.

**Comment by manisandro** [comment]
You could query for the password when adding the source in the source manager and then store it in the Source structure, so that the PdfRenderer can use it without having to query the user each time.

**Comment by ZaMaZaN4iK** [comment]
Added opening and saving encrypted PDF files.
