### ISSUE TITLE
Сonverting pages to one format

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [manisandro/gImageReader#206]
As input we can have images with different sizes. So Abbyy FineReader has option for converting all input images to one of the format: A4, A5, etc. Also user can define own format and automatically convert images  before export to PDF.

**Comment by ZaMaZaN4iK** [comment]
Which paper size should be supported?

**Comment by manisandro** [comment]
Gimp has: A3, A5, A5, A6, B4, B5, US-Letter, US-Legal
Inkscape has many many more

I suppose the Gimp set is a good start.

**Comment by ZaMaZaN4iK** [comment]
according to wikipedia, we can support a lot of formats :-)

**Comment by manisandro** [comment]
no question about that, if you want to add 2000 lines of code of predefined paper sizes be my guest ;)

**Comment by manisandro** [comment]
Tracked in #273
