### ISSUE TITLE
Windows: wrong spellchecker chosen for hOCR

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#208]
On Windows the hOCR spellchecker does not correspond to the language chosen for the recognition (German). The text obviously was recognized in German though. Seems to be the English spellchecker. No problem on Debian Buster 9 (testing).
OS: Windows 7 64 bit
gIR: 3.2.3
Tesseract: 3.05.01

**Comment by manisandro** [comment]
Thanks for the report, this was recently fixed in ceef0ade0f9207746a18f08ce0da1bd70408fb1a, you can try these test builds:

32bit: https://smani.fedorapeople.org/tmp/gImageReader_3.2.3_qt5_i686.exe
64bit: https://smani.fedorapeople.org/tmp/gImageReader_3.2.3_qt5_x86_64.exe

**Comment by SantosSi** [comment]
Confirming: this is resolved in the mentioned build.
