### ISSUE TITLE
Save output, Copy text to clipboard

### ISSUE THREAD

**Issue by efa** [manisandro/gImageReader#21]
happy to see the:
Add image, image Paste
and 
Add image, Capture screenshot
feature. Work well and is very useful.

Can you please add a:
Save output, Copy text to clipboard
feature?

thank you in advance, Valerio

**Comment by manisandro** [comment]
Could you describe more in detail what you mean by "Save output, Copy text to clipboard"? There is a save output button in the output pane. There is also a function to recognize a selection directly to clipboard, in the menu which appears when you right-click a selection. So I'm not sure I understand what you are requesting.

**Comment by efa** [comment]
solved, I found the functions, very well!
I thounght there should be a button, but as so is OK
thank you
