### ISSUE TITLE
No folding/unfolding with cursor keys on Linux

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#211]
On Linux folding/unfolding does not work with the cursor keys in hOCR output.
OS: Debian Buster 9 (testing)
gIR: 3.2.3 GTK

**Comment by manisandro** [comment]
Apparently this is intentional, i.e. you need to use the + and - keys... [1]

[1] https://bugzilla.gnome.org/show_bug.cgi?id=679294

**Comment by manisandro** [comment]
Closing since it is an upstream Gtk "feature".
