### ISSUE TITLE
Add text to wrong language's dictionary when open existing hOCR file

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#216]
When opening an hOCR .html file to resume spellchecking, words are added to the wrong "sub-language's" dictionary. Not sure what language is used for spellchecking because of too little differences within de_ languages.
In this case the hOCR file has lang=deu and the detect selector is set to de_DE, but instead of adding the word to de_DE it is added to de_AT.

**Comment by manisandro** [comment]
Can you try this with latest master? Should be addressed by various fixes committed recently in this area.

**Comment by SantosSi** [comment]
That was resolved with your new build as discussed via PM.
