### ISSUE TITLE
Improvement: Delete nodes with Del key and add undo delete

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#217]
Right-clicking is time consuming, using a keyboard key is quicker.
To restore mistakenly deleted nodes, create an undo at least for deleted nodes. Best would be to have an undo for all activities.

**Comment by ZaMaZaN4iK** [comment]
Nice idea. @manisandro what do you think about it?

**Comment by manisandro** [comment]
Keyboard shortcut is fairly easy. Undo-redo requires more work (basically you need to introduce undo/redo commands which contain the xml snippet changed and the position in the dom tree where the snippet belongs).

**Comment by manisandro** [comment]
Delete key is implemented. Undo/redo is something to look at in the future, tracked in #305.
