### ISSUE TITLE
Improvement: Remove red color from unrecognized text after that text was added to dictionary.

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#218]
When text was added to the dictionary, the same text still stays marked red = not found by spellchecker.

**Comment by manisandro** [comment]
What OS is this on? Gtk or Qt? Works as far as I can see on Linux with latest master.

**Comment by SantosSi** [comment]
Linux, Gtk. Is this maybe connected somehow to #216 ?

**Comment by manisandro** [comment]
Possibly also to #208. Did you try compiling the latest git master?

**Comment by SantosSi** [comment]
No, I just used the package from Debian (Testing).

**Comment by manisandro** [comment]
Can you try compiling the latest master? `apt-get build-dep gimagereader` and the following https://github.com/manisandro/gImageReader/wiki/Compiling-gImageReader should suffice.

**Comment by SantosSi** [comment]
Discussed the issue via PM.

**Comment by manisandro** [comment]
@SantosSi Please try with the latest master with the Qt interface (see compile HOWTO).

**Comment by SantosSi** [comment]
Working as expected in there.

**Comment by manisandro** [comment]
Done also for gtk.
