### ISSUE TITLE
Check if input PDF has already text inside

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [manisandro/gImageReader#219]
Hello @manisandro 

Finereader has interesting feature - if input PDF is already searchable, it suggests don't recognize any  stuff. Can you add smth similar? Google says me, that we can do it with Poppler library.

**Comment by manisandro** [comment]
Uhm sure, I suppose. Possibly an info dialog when opening the source, at the same stage as the password query is performed.

**Comment by ZaMaZaN4iK** [comment]
Found in Poppler method, which returns all text on a page.

**Comment by SantosSi** [comment]
Is this a possibility to embed OCR'ed text into the orginal PDF?

**Comment by manisandro** [comment]
No, see https://github.com/manisandro/gImageReader/issues/235. But you should have all options available to re-create a PDF with the same image format as the original.

**Comment by manisandro** [comment]
Done in c39f8b168dae1a792d7e41741b2be6c54657f33c
