### ISSUE TITLE
Add option for sending anonymous statistic of program using

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [manisandro/gImageReader#223]
If we want to know, how our users use gIR, we can add OPT-IN option in settings for anonymous statistic sharing. And e.g. during the first run we can just show messagebox with asking about this question.

It can help us to understand the most useful cases for our users.

**Comment by manisandro** [comment]
I'm against this and am pretty sure the backlash would be much greater than any theoretical benefit. I believe users should speak up if they want something.

Closing.
