### ISSUE TITLE
Find / Replace, substitution list in hOCR mode

### ISSUE THREAD

**Issue by manisandro** [manisandro/gImageReader#225]

**Comment by ZaMaZaN4iK** [comment]
Can you write please explanation, what is it?

**Comment by manisandro** [comment]
Same functionality as in plain-text mode for hOCR mode.

**Comment by manisandro** [comment]
Implemented for Qt

**Comment by manisandro** [comment]
Done also for gtk.

**Comment by SantosSi** [comment]
Qt: Replace all and Substitutions do not replace text, while Replace does.

**Comment by manisandro** [comment]
More details please, works fine here.

**Comment by SantosSi** [comment]
When clicking Replace all the search textbox's background becomes red and no text is found and replaced.
Clicking Apply in Substitutions simply does nothing: no replacements, no error message, no output on the console.

**Comment by manisandro** [comment]
Well all this works with my test documents... I don't really see anything language and document dependent here, but just in case, can you send me a minimal example document which causes the errors? Or does it really never work?

**Comment by SantosSi** [comment]
Only in Qt, but happens always and document independent.

**Comment by manisandro** [comment]
What qt version do you have?

**Comment by SantosSi** [comment]
5.9.2

**Comment by manisandro** [comment]
So I set up a debian testing virtual box and tried to reproduce the issue there, but also there everything works. Perhaps try doing a clean build.

**Comment by SantosSi** [comment]
Have you installed Debian Testing "Buster"?
Did a make clean, cmake and make cycle.

**Comment by manisandro** [comment]
I downloaded the current debian-live-testing-amd64-kde.iso

**Comment by manisandro** [comment]
What locale do you use? I.e. what is the output of

    env | grep -E '(LC|LANG)'

**Comment by SantosSi** [comment]
LANG=de_DE.UTF-8

**Comment by manisandro** [comment]
Works.. No idea what the issue. I suppose at this stage the we need to fire up the debugger. If you install qt-creator, create a new project and then import the existing qt5 build, then open qt/src/hocr/OutputEditorHOCR.cc, click to the left of [line 751](https://github.com/manisandro/gImageReader/blob/master/qt/src/hocr/OutputEditorHOCR.cc#L751) to set a breakpoint, then press F5 to start the application inside the debugger, do replace all, and then you should hit the breakpoint, at which you can step through the code and see whether line 760 is ever reached.
Make sure to set `CMAKE_BUILD_TYPE=RelWithDebInfo`

**Comment by SantosSi** [comment]
Instead of the application I get a bunch of warnings and these two errors. Not sure they are the reason for not executing the application or it's because how I handled qtcreator, unknown to me...
![screenshot_20171230_090840](https://user-images.githubusercontent.com/31543615/34452501-2510c682-ed41-11e7-83ea-5cae6fea2134.png)
