### ISSUE TITLE
hOCR mode in GTK: make properties area resizable

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#227]
or auto-resizing depending on the space it needs, to avoid wasting space

**Comment by SantosSi** [comment]
Resizing possible now, but multipage PDF's pages are not displayed correctly.
Error messages on the console:
(gimagereader-gtk:18382): GLib-GObject-CRITICAL **: g_value_transform: assertion 'G_IS_VALUE (src_value)' failed

(gimagereader-gtk:18382): GLib-GObject-WARNING **: unable to set property 'active' of type 'gboolean' from value of type '(null)'

(gimagereader-gtk:18382): GLib-GObject-CRITICAL **: g_value_transform: assertion 'G_IS_VALUE (src_value)' failed

(gimagereader-gtk:18382): GLib-GObject-WARNING **: unable to set property 'pixbuf' of type 'GdkPixbuf' from value of type '(null)'

(gimagereader-gtk:18382): GLib-GObject-CRITICAL **: g_value_transform: assertion 'G_IS_VALUE (src_value)' failed

(gimagereader-gtk:18382): GLib-GObject-WARNING **: unable to set property 'foreground' of type 'gchararray' from value of type '(null)'

(gimagereader-gtk:18382): GLib-GObject-CRITICAL **: g_value_transform: assertion 'G_IS_VALUE (src_value)' failed

(gimagereader-gtk:18382): GLib-GObject-WARNING **: unable to set property 'editable' of type 'gboolean' from value of type '(null)'

(gimagereader-gtk:18382): GLib-GObject-CRITICAL **: g_value_transform: assertion 'G_IS_VALUE (src_value)' failed

(gimagereader-gtk:18382): GLib-GObject-WARNING **: unable to set property 'text' of type 'gchararray' from value of type '(null)'

(gimagereader-gtk:18382): GLib-GObject-CRITICAL **: g_value_transform: assertion 'G_IS_VALUE (src_value)' failed

(gimagereader-gtk:18382): GLib-GObject-WARNING **: unable to set property 'text' of type 'gchararray' from value of type '(null)'

(gimagereader-gtk:18382): GLib-GObject-CRITICAL **: g_value_transform: assertion 'G_IS_VALUE (src_value)' failed

(gimagereader-gtk:18382): GLib-GObject-WARNING **: unable to set property 'active' of type 'gboolean' from value of type '(null)'

(gimagereader-gtk:18382): GLib-GObject-CRITICAL **: g_value_transform: assertion 'G_IS_VALUE (src_value)' failed

(gimagereader-gtk:18382): GLib-GObject-WARNING **: unable to set property 'pixbuf' of type 'GdkPixbuf' from value of type '(null)'

(gimagereader-gtk:18382): GLib-GObject-CRITICAL **: g_value_transform: assertion 'G_IS_VALUE (src_value)' failed

(gimagereader-gtk:18382): GLib-GObject-WARNING **: unable to set property 'foreground' of type 'gchararray' from value of type '(null)'

(gimagereader-gtk:18382): GLib-GObject-CRITICAL **: g_value_transform: assertion 'G_IS_VALUE (src_value)' failed

(gimagereader-gtk:18382): GLib-GObject-WARNING **: unable to set property 'editable' of type 'gboolean' from value of type '(null)'

(gimagereader-gtk:18382): GLib-GObject-CRITICAL **: g_value_transform: assertion 'G_IS_VALUE (src_value)' failed

(gimagereader-gtk:18382): GLib-GObject-WARNING **: unable to set property 'text' of type 'gchararray' from value of type '(null)'

(gimagereader-gtk:18382): Gtk-CRITICAL **: ../../../../gtk/gtktreeview.c:5559 (gtk_tree_view_bin_draw): assertion `has_next' failed.
There is a disparity between the internal view of the GtkTreeView,
and the GtkTreeModel.  This generally means that the model has changed
without letting the view know.  Any display from now on is likely to
be incorrect.

**Comment by manisandro** [comment]
Mhh not directly related to the resizing, but something is corrupting the tree model.

**Comment by manisandro** [comment]
Do you remember whether you did some particular manipulation (like merging items) before these messages appeared?

**Comment by SantosSi** [comment]
Not exactly. It happened today after I 
played with the open and save 
requesters without data manipulation.

**Comment by manisandro** [comment]
Ok could reproduce after opening a couple of files.

**Comment by manisandro** [comment]
Should be fixed.
