### ISSUE TITLE
hOCR mode: add button to jump to next unknown (red) word

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#228]

**Comment by manisandro** [comment]
Done for qt

**Comment by SantosSi** [comment]
Was it intended to stay only on the current page for all node types below 
page? Since this surely has its advantages, can you implement to go to the 
next occurrence on the next page?
Bug: The next page function always highlights the first page instead of 
jumping to the next page.

**Comment by manisandro** [comment]
These should now be addressed in latest master, see #246

**Comment by manisandro** [comment]
Done for gtk
