### ISSUE TITLE
Jump to a specific page in hOCR

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#229]
... not only from the image. E.g. by selecting a page in the image view in a synchronized mode or with a page selector for the hOCR part.

**Comment by manisandro** [comment]
Added a toggle button to activate syncing between the displayed page and the selected page in the hOCR tree. It's the least invasive approach I can think of. It won't work correctly if you recognize the same page multiple times, but I suppose one shouldn't be doing that anyway.

**Comment by manisandro** [comment]
I've gone further and added in 439bc034b2898dddc38362a7a2cc343cda52073a a button to pick an arbitrary position inside an image, which will search for the corresponding item in the hOCR tree and select it. At this point I'm thinking of removing the page sync button again to avoid cluttering the UI. What do you think?

**Comment by SantosSi** [comment]
That's great!
Can you make that a mode, so it does not have to be clicked once per selection in the image? That would have to be automatically and temporarily disabled when drawing a rectangle to define a new image.

**Comment by manisandro** [comment]
That's pretty hard to do. You'll notice that, when you invoke the pick tool, image angle and resolution are automatically set to the values at which the image was OCRed, and as soon as you rotate or change the resolution of the image, the picking tool is automatically disabled. This is to ensure that the coordinate space used when picking matches the one of the bounding boxes in the hOCR data.

If the picking tool were to be always enabled, the only solution would be to disable the angle and resolution controls to prevent the user from changing the values. But I'd rather not do that.

In any event, do you agree that the page sync button is superfluous with the picking tool?

**Comment by SantosSi** [comment]
Yes, the Sync button becomes useless through clicking a page's subordinate element.

**Comment by manisandro** [comment]
Actually after thinking about it for a sec, I realized I could just transform the picked coordinate based on the current angle/resolution and the angle/resolution at OCR time. I've pushed a commit which makes picking always enabled (unless when drawing/modifying a bbox). Please test ;)

**Comment by SantosSi** [comment]
Working fine, even when the word and an image are overlapping or at the same place.

**Comment by SantosSi** [comment]
Correction: when the whole page is selected, a subordinate element is not selectable in the image.
And to be exact: it is working fine on the Qt5 interface, not in GTK.

**Comment by manisandro** [comment]
It isn't yet ported to Gtk, so that's expected.

**Comment by manisandro** [comment]
Done also for gtk.

**Comment by manisandro** [comment]
> Correction: when the whole page is selected, a subordinate element is not selectable in the image.
This is now also fixed.
