### ISSUE TITLE
When the last node was deleted ask the user if empty parent nodes should be deledted too.

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#230]
If the last word of a textline is deleted, then check if it also the last textline in a paragraph. Then ask the user if he wants to have those empty ones deleted too.

**Comment by ZaMaZaN4iK** [comment]
I also suggest add new option in the settings like "Automatically delete paragraph node if the the last word was deleted". Reason: ask every time about this can be annoying to user

**Comment by manisandro** [comment]
Given that deleting nodes is now super-fast with the Delete shortcut, I'd say we can do without annoying popup dialogs.

**Comment by SantosSi** [comment]
Part of the idea was to avoid unwanted orphan nodes not noticed by the user. As on the contrary this could be intended for adding words/textlines/paragraphs the user should be asked. This should not be very annoying as it is not expected the user deletes last elements too often.
