### ISSUE TITLE
Scroll image to bbox when hOCR node selected.

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#231]
If zoom is set to higher than page size, selecting an item in hOCR should automatically change the image pane to where the item is located, so it can be seen by the user. This obviously also is a kind of synchronization between image view and hOCR view.

**Comment by manisandro** [comment]
@SantosSi Please try with the latest master with the Qt interface (see compile HOWTO).

**Comment by SantosSi** [comment]
It scrolls the image vertically, but not horizontally, e.g. it scrolls to the beginning or the end of the image, but not to the right when the visible area is on the left and the node is outside on the right.
Also there are no scroll bars for the zoomed image, neither horizontal nor vertical. However, it scrolls vertically using mouse scrolling.

**Comment by manisandro** [comment]
Wierd, I definitely see scrollbars here...

**Comment by SantosSi** [comment]
I got only an horizontal scrollbar and no vertical scrollbar when I clicked the Normal size button. The other modes create not scrollbars.

**Comment by manisandro** [comment]
What qt version and theme?

**Comment by SantosSi** [comment]
Qt 5.9.1, Theme Breeze

**Comment by manisandro** [comment]
So like regardless of how much you zoom around the scrollbar does not appear? Tried with plasma-breeze-5.11.3 and qt5-qtbase-5.9.2 and can't spot any issue ...

**Comment by SantosSi** [comment]
I found the problem: there is a "close button" in the upper right edge of the hOCR area. That toggles between a larger and a smaller hOCR area. The larger one covers parts of the image, including the vertical scrollbar.

**Comment by manisandro** [comment]
Ah that's simply the fact that the output pane is undockable, you can detach it from the window or place it in the corner of your choice.

**Comment by manisandro** [comment]
Scrolling also implemented in Gtk.

**Comment by SantosSi** [comment]
Does not scroll for me.

**Comment by manisandro** [comment]
latest master?... I mean, ok a bit of randomness, but computers should still be pretty deterministic, and it definitely works here...

**Comment by SantosSi** [comment]
Yes, latest master.

**Comment by manisandro** [comment]
Please try again with current master

**Comment by SantosSi** [comment]
OK now, thanks.
