### ISSUE TITLE
Create hOCR files with relative image file paths, so they become portable.

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#232]
If the image and the hOCR file are in the same folder, there's no need for a full path. This is to make hOCR + image files portable, also between OS families (e.g. Windows and Linux)

**Comment by SantosSi** [comment]
It can first check if the path is absolute, if not it looks for the image file in the hOCR folder.

**Comment by manisandro** [comment]
Done

**Comment by SantosSi** [comment]
The image file cannot be opened, the file name is enclosed with " after the folder path, like: /home/user/Documents/"filename.png"

**Comment by manisandro** [comment]
Uhm what does your source HTML file look like? The `title` attribute of the page element should be like

    title="bbox 0 0 1024 800; image './eurotext.tif'; ppageno 1; res 100; rot 0"

i.e. the filename enclosed in single quotes.

**Comment by manisandro** [comment]
And which interface were you using? If you were using the gtk one, please try again.

**Comment by SantosSi** [comment]
Interface is Qt5.
`title='image "LPIC303-Kap1-3_07.png"; bbox 0 0 1242 1755; ppageno 0'`
The difference is: this is from the command line tesseract, but gIR should better also handle that.

**Comment by manisandro** [comment]
Uh true, I forgot about the fact that single quotes for xml attributes are also legal. Fixed.

**Comment by SantosSi** [comment]
Created the file on Linux, then edited and saved on Windows. The file is saved with 
`image '.\imagename'`
not accepted on Linux.

**Comment by manisandro** [comment]
Good point, fixed in 4fbd75fd9653693abff07718659696cdb6dc6d25
