### ISSUE TITLE
Open hOCR document from the OS.

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#234]
Open hOCR .html files from file management, e.g. Windows Explorer on Windows or Dolphin on KDE/Linux. At the moment an error message is displayed: the file is not an image.

**Comment by ZaMaZaN4iK** [comment]
Possibly right MIME-type should be setted.

**Comment by manisandro** [comment]
It's more complicated than that, currently the logic is only implemented for opening source files (managed by SourceManager). One thing in particular is that while you can open multiple (source-)files at once, you can only have one hOCR HTML file loaded at a time. So you'd have to like load the first one and ignore the other ones.

**Comment by manisandro** [comment]
Implemented
