### ISSUE TITLE
Convert hOCR files to plain text

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#236]
Instead of only OCRing to text **or** hOCR take the format with more metadata and easier reviewable/correctable, make hOCR the default and then not only export as PDF but also as plain text and possibly other formats.

**Comment by manisandro** [comment]
Plain-text mode has the advantage of being much simpler for users just needing the text. And in those cases it is easier to post-process the output in a regular text field than in the hOCR tree.

**Comment by SantosSi** [comment]
Why not display both in parallel? I prefer hOCR because it is linked to and shows the original text in the image and also provides spellchecking. However, sometimes it would be necessary to save the reviewed content as plain text.

**Comment by manisandro** [comment]
You'd have to implement a very complex text area model which for each text block stores a reference to the corresponding item in the hOCR tree or something similar, otherwise there is no way to keep them in sync. But this is very very hard to implement robustly.

**Comment by SantosSi** [comment]
Can you reuse the hOCR structure linked in the background instead of a complex  text area model

**Comment by manisandro** [comment]
And what do you do when the user arbitrarily selects a chunk of text and presses delete?

**Comment by SantosSi** [comment]
Good question, but I am not proficient enough in programming to answer that detail.
What about just saving (converting) the hOCR to plain text, like for PDF?

**Comment by manisandro** [comment]
Implemented for Qt in 6414bd7

**Comment by SantosSi** [comment]
Great.
Found only one issue: there are extra blank lines just because there is a different paragraph. Not sure if the y-distance in pixel can be used, but surely a different paragraph is not the only indicator for an extra blank line.

**Comment by manisandro** [comment]
Mhh dunno, it makes sense to me to add an empty line between paragraphs?

**Comment by SantosSi** [comment]
Yes, it would be logical if OCR would identify it correctly, but it often does not.
Maybe this can be amended with my "extended" request for improvement in #226: to redefine the sequence of texts and: to reassign words to different textlines or paragraphs.

**Comment by manisandro** [comment]
Done also fro gtk.
