### ISSUE TITLE
hOCR: Change common properties for multiple nodes

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#237]
Change common properties for multiple nodes on the same level (e.g. all contained words, when paragraphs were selected). Present only possible properties, e.g. x_fsize on all words within the selected paragraph (most wanted!), or vertical alignment in bbox on different levels: paragraph, line or word.

**Comment by manisandro** [comment]
Implemented for Qt. Please test thoroughly (and the hOCR functionality in general) since I moved around quite a lot of code...

**Comment by SantosSi** [comment]
Problem: only the first selected page of a PDF is displayed no matter what page else is selected in the hOCR output pane, all pages have a [0] page number appended in the hOCR output pane and there arr lots of the following lines on the command line output.

**Comment by manisandro** [comment]
I believe you opened an existing file? There was a typo (`pageno` should have been `ppageno` according to the hOCR spec). So the existing file probably has the wrong attribute name. I could add some fallback code, but no released version of gImageReader had this typo. So if you change `pageno` with `ppageno` with a text editor you should be good.

**Comment by manisandro** [comment]
Oh actually no there is still one location where it is wrong...

**Comment by SantosSi** [comment]
Changing from pageno to ppageno did the trick.

**Comment by manisandro** [comment]
I've added some code which should convert the incorrect attribute in old files in 1e2494153fd932dd5f035c12adfda383dd3b18a7.

**Comment by SantosSi** [comment]
Common properties improvement: perfect handling and working fine. Well done.
pageno -> ppageno: fine.

**Comment by SantosSi** [comment]
Can you separate bbox into the distinct coordinates, so they can be edited separately.
Can you also provide common coordinates for the subordinate levels, so they can be aligned (x-coordinate)?

**Comment by manisandro** [comment]
Mh so you mean `x-coordinate` would be `bbox[0]` and you'd want to be able to mass-edit it?

**Comment by SantosSi** [comment]
Yes, for the left boundary and also bbox[2] for the right.

**Comment by manisandro** [comment]
I suppose this only makes sense for text lines, paragraphs?

**Comment by SantosSi** [comment]
Right.
For words in a textline bbox[1] and [3] would make sense to align y.

**Comment by manisandro** [comment]
Done also fro gtk.

**Comment by SantosSi** [comment]
Tested: OK.
