### ISSUE TITLE
hOCR: Detect overlapping words and suggest making x_fsize smaller

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#238]

**Comment by manisandro** [comment]
Until the user has actually selected a font to use (which only happens in the PDF export dialog), you can't really know if the words really overlap.

**Comment by SantosSi** [comment]
OK, so the detected font does not play a role?
Can we select the font before exporting?

**Comment by manisandro** [comment]
The information about the detected font is far to imprecise to be usable.
I'll need to think about font selection.

**Comment by manisandro** [comment]
Tracking in #356
