### ISSUE TITLE
Unblock text editing while recognizing.

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#239]
When text is recognized the UI freezes. Can text editing be made available while a recognition job is running?

**Comment by manisandro** [comment]
I don't see how it could work, you don't want the program to suddenly insert text into the output field while you are working in it.

**Comment by SantosSi** [comment]
With a page wise locking mechanism?

**Comment by manisandro** [comment]
There is no concept of pages in the plain text output. Or did you mean hOCR?

**Comment by SantosSi** [comment]
Yes, actually it is for hOCR.
Regarding text output: Don't know how the OCR module delivers the results. If it delivers pagewise, would it be too much effort to buffer a pagewise OCR output and then attach to the text output window?

**Comment by manisandro** [comment]
Results are delivered for each selected area, but I still see the risk of confusing the user and messing up the entire output. Say the user does CTRL+A followed by Delete to delete the current text, but right between the CTRL+A and the Delete new text arrives.

**Comment by manisandro** [comment]
Or actually worse right between the moment he plans to press CTRL+A and actually finishes pressing the key sequence.
