### ISSUE TITLE
HOCR spellchecker: Suggest more words based on usual mistakes in a language

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#240]
OCR makes the following mistakes in German within words:
- the letter i (as in India) or uppercase I instead of the letters l (as in Lima) or t (as in Tango).
- the special character ﬁ instead of fi and  ﬂ instead of fl
- @, 5, S and others instead of §
- A long hyphen instead of a minus

**Comment by manisandro** [comment]
As mentioned in another ticket, I want to keep gImageReader as language agnostic as possible. This particular issues should be addressed either with better training, or by using a global replacement list (see #225).
