### ISSUE TITLE
hOCR spellchecker in German: suggest hyphen as special character at the end of a line

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#241]
At the end of a line it very probably is a separated word (see also #226 for spellchecking through lines).

**Comment by manisandro** [comment]
There already is a logic which replaces - by the appropriate hyphen character if it appears in the last word of a lie.

**Comment by SantosSi** [comment]
In reality I often get a @ sign at the end of the line.

**Comment by manisandro** [comment]
I don't see this as feasible. The only logic I can image is "if word ends with an odd character and is incorrectly spelled, add a hyphen", but if you are unlucky, the OCR engine might place just about anything as last character, and the word might be misspelled in any case...
