### ISSUE TITLE
hOCR spellchecker in German: regard / character as a word delimiter

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#242]
Similar to the whitespace character.

**Comment by manisandro** [comment]
This really is the task of the tesseract traineddata. Adding language specific workarounds in gImageReader is a "fass ohne boden" to use the german expression.

**Comment by SantosSi** [comment]
Danke. :-)

**Comment by SantosSi** [comment]
FYI: Created https://github.com/tesseract-ocr/tesseract/issues/1221 for this.
