### ISSUE TITLE
When saving an hOCR document with several PDF documents as the source keep the original .html file name

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#244]
When saving an hOCR document with several PDF documents as the source keep the original .html file name, not the current page's input pdf file name
Situation: Copied from multiple hOCR files with the same amount of input PDF files into a single hOCR file.

**Comment by manisandro** [comment]
@SantosSi Please try with the latest master with the Qt interface (see compile HOWTO).

**Comment by SantosSi** [comment]
The newest master lists only the hOCR of the first page of the mulipage PDF input file. Cannot test this issue as long as that problem exists.

**Comment by manisandro** [comment]
Looks like using the HTML5 doctype broke it, since QDomDocument writes self-closing non-void elements... Change which I though was harmless but obviously didn't properly test >.<

**Comment by manisandro** [comment]
Actually no the reason was another one. Fixed in 9122695dd45253b48565e8c36851b8884068011c

**Comment by SantosSi** [comment]
The problem does not exist for the hOCR file anymore, but can you do the same for the PDF export, please?

**Comment by manisandro** [comment]
Done, try latest master.

**Comment by SantosSi** [comment]
Working fine, issue resolved.

**Comment by manisandro** [comment]
Done also for gtk.
