### ISSUE TITLE
Use Boost.Stacktrace for stackraces

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [manisandro/gImageReader#245]
Hello @manisandro 
In the project we have own written backtrace generator from gdb_process.

FYI, in Boost we already have cross-platform library for working with stacktraces: http://www.boost.org/doc/libs/1_65_1/doc/html/stacktrace.html

Maybe will be better, if we will use this for working with stacktraces in gImageReader.

**Comment by manisandro** [comment]
I prefer the gdb approach for the simple reason that it does not require full debuginfo compiled into the binary, but allows debuginfos to be installed separately. Possibly I'll replace the building crash handler with https://github.com/manisandro/GdbCrashHandler which I've written as a standalone library for a separate project.

**Comment by manisandro** [comment]
"require full debuginfo" -> that is to say, to obtain stacktraces which are not number-only
