### ISSUE TITLE
hOCR on Qt5: Edit word instead of having to enter it completely.

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#248]
When doubleclicking or pressing F2 on a word the text field is empty. Instead it should be prefilled with the previous text, e.g. what the OCR engine recognized.
Gtk version not affected.

**Comment by manisandro** [comment]
That's a bug introduced by the hOCR rewrite, I'll investigate.

**Comment by manisandro** [comment]
Fixed in 5c01d6b.
