### ISSUE TITLE
Memory leak after scanning 200p book

### ISSUE THREAD

**Issue by ouillepouille** [manisandro/gImageReader#249]
1. start app
2. open pdf
3. recognize via OCR
4. save to pdf as invisible text
5. remove document from interface (list views become empty, as on startup)
6. ram use still 657mb
7. need to restart app to use again

BTW thanks for the excellent work. this is the only issue I found, and is admitedly easily fixed by restarting the app

![capture d ecran de 2017-12-04 14-41-47](https://user-images.githubusercontent.com/34250447/33572705-b2d2d9d2-d901-11e7-9b51-b750683bdcd5.png)

**Comment by manisandro** [comment]
Thanks - I'll do some inspection with valgrind once I've ported the new hOCR code to gtk.

**Comment by manisandro** [comment]
If you are comfortable compiling, can you try the latest git master? I did a couple of tests, and memory usage stabilized at around 200-250MB after a while. It doesn't free more memory, but also memory usage doesn't increase after subsequent recognitions, so it looks more like some component is caching stuff rather than memory leaking.

**Comment by SantosSi** [comment]
Tested with latest Qt master with tesseract 4. 
Used 121 MB after starting the application and always got back to around 265 MB after scanning and removing a 68 page and then a 52 page input PDF and the hOCR output.
Loading the hOCR without recognizing increases memory use to 180 MB with the 68 and 52 page files, but to 479 MB with a 369 page hOCR file. Recognizing then the 68 page PDF again left the application using 523 MB in the end.
This seems to be somehow bound to the hOCR data.

**Comment by manisandro** [comment]
And if you clear the hOCR tree, does memory get released again?

**Comment by SantosSi** [comment]
No

**Comment by manisandro** [comment]
I've investigated this with `valgrind --tool=massif` and `massif-visualizer`, and the memory profile is as expected, see below. (Testcase: loading hOCR file of a 20p document, and then clearing the output, repeated twice).

A technical remark: you can't trust your system monitor or top to give you the *actual* memory usage of a process, they just report the memory which was assigned to the process. In particular if your system is not under memory pressure, the OS may opt to keep memory assigned to the process, and reclaim in only when the process exits. So it is not un-typical that process memory usage will stay near the the process effectively used over its runtime. A clear sign of a memory leak is if the memory keeps increasing when repeating the same operation over and over again, which I could not observe in the case of gimagereader (gtk and qt).

Closing.

qt:
![qt](https://user-images.githubusercontent.com/1298852/34587501-dce66828-f1a8-11e7-86d2-34a3941ebcca.png)

gtk:
![gtk](https://user-images.githubusercontent.com/1298852/34587505-e0b6397e-f1a8-11e7-86b7-f4460ec9e246.png)
