### ISSUE TITLE
Debian: /usr/local/share/xml/iso-codes/iso_639.xml not found

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#251]
On Debian the file is /usr/share/xml/iso-codes/iso_639-5.xml

**Comment by manisandro** [comment]
You need to specify the correct prefix when building qtspell, see https://github.com/manisandro/qtspell/blob/master/CMakeLists.txt#L18

**Comment by SantosSi** [comment]
I was unaware of the prefix, created an [initial Wiki page](https://github.com/manisandro/qtspell/wiki) to document what I learnt.
But the issue is still not resolved: the file name is still not matched: there is an extra `-5` before the extension.

**Comment by manisandro** [comment]
In theory the iso-codes package should contain:

    /usr/share/xml/iso-codes/iso_15924.xml
    /usr/share/xml/iso-codes/iso_3166-1.xml
    /usr/share/xml/iso-codes/iso_3166-2.xml
    /usr/share/xml/iso-codes/iso_3166-3.xml
    /usr/share/xml/iso-codes/iso_3166.xml
    /usr/share/xml/iso-codes/iso_3166_2.xml
    /usr/share/xml/iso-codes/iso_4217.xml
    /usr/share/xml/iso-codes/iso_639-2.xml
    /usr/share/xml/iso-codes/iso_639-3.xml
    /usr/share/xml/iso-codes/iso_639-5.xml
    /usr/share/xml/iso-codes/iso_639.xml
    /usr/share/xml/iso-codes/iso_639_3.xml
    /usr/share/xml/iso-codes/iso_639_5.xml

**Comment by SantosSi** [comment]
Sorry, you are right: I have not seen all the files. Some of them are even _x softlinks to the corresponding -x files. After re-building and installing qtspell it did not look for the file in the right path. My fault, let me retry that.
