### ISSUE TITLE
How to compile gImageReader in ubuntu 16.04

### ISSUE THREAD

**Issue by napasa** [manisandro/gImageReader#252]
I tried to cross compile gImageReader in ubuntu 16.04 distro to windows and meet some obstacle. I modify your **makeinstaller.sh** as below
1. I am a newbie of mingw, I didn`t find similarly **MINGWROOT=/usr/$arch-w64-mingw32/sys-root/mingw** directory in ubuntu after I installed **mingw32-runtime**, **ming-w64**,** mingw-w64-common**, **mingw-264-tools**.
2. I treat **mingw$bits-cmake -DINTERFACE_TYPE=$iface ../../** as cmake command **cmake -DINTERFACE_TYPE=$iface CMAKE_TOOLCHAIN_FILE=mingw32_toolchain.cmake ../../**,  of which param CMAKE_TOOLCHAIN_FILE value is [this](https://github.com/zyga/cmake-toolchains.git).
3. replace **mingw$bits-make -j4 DESTDIR="${installroot}_" install VERBOSE=1** with **make -j4 DESTDIR="${installroot}_" install VERBOSE=1**

After I run makeinstall.sh,
Then Generate a error  shows not having ${installroot}_$MINGWROOT directory  from this command **mv ${installroot}_$MINGWROOT $installroot**

**Comment by manisandro** [comment]
Hi
If I look at all matches for mingw ubuntu packages [1], the number of packages offered seems very very limited, i.e. not much else beyond the compiler. So you'll need to compile all dependencies for mingw first (qt, tesseract, etc etc). Then the mingwroot is the prefix you use when installing these dependencies (i.e. what you pass to `./configure --prefix=<...>`).

Possibly it is quicker to just use a Fedora Docker / VM.

[1] https://packages.ubuntu.com/search?keywords=mingw&searchon=names&suite=artful&section=all

**Comment by napasa** [comment]
Hi.
Thanks your answer. now I try your method.
