### ISSUE TITLE
mingw-extras repo seems not woking

### ISSUE THREAD

**Issue by napasa** [manisandro/gImageReader#253]
As [smani/mingw-extras](https://copr.fedorainfracloud.org/coprs/smani/mingw-extras/) requests, I run **dnf copr enable smani/mingw-extras** CMD, then run **dnf list twaism***,, fedora 23 reports Error **Failed to synchronize cache for repo 'smani-mingw-extras', disabling.** .

**Comment by manisandro** [comment]
Fedora 23 is like very, very old. Use Fedora 27.
