### ISSUE TITLE
unable to pull mingw-twaindsm package

### ISSUE THREAD

**Issue by napasa** [manisandro/gImageReader#254]
# First:
 I add and enable **smani/mingw-extras** by
 dnf copr enable smani/mingw-extras
# second:
 I comfirm I add it by
  [yu@localhost etc]$ dnf repolist --enabled
Last metadata expiration check: 1:10:06 ago on Fri 15 Dec 2017 04:20:53 PM CST.

repo id| repo name| status
--- | --- | ---
*fedora |  Fedora 27- x86_64 | 54,801
smani-mingw-extras | Copr repo for mingw-extras owned by smani | 0
*updates | Fedora 27 - x86_64 - Updates  | 7,690

## third:
  I try install mingw-twaindsm by 
  dnf install mingw-twaindsm
  shows error: No match for argument: mingw-twaindsm

## Fourth
  I figure out smani-mingw-extras detail info by
  dnf repolist -v --enabled smani-mingw-extras
  show messages:

Loaded plugins: builddep, config-manager, copr, debug, debuginfo-install, download, generate_completion_cache, needs-restarting, playground, repoclosure, repograph, repomanage, reposync
DNF version: 2.7.5
cachedir: /var/tmp/dnf-yu-b0hojmo5
Repository smani-mingw-extras is listed more than once in the configuration
Cannot download 'https://copr-be.cloud.fedoraproject.org/results/alonid/llvm-5.0.1/fedora-27-x86_64/': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried.
repo: using cache for: smani-mingw-extras
not found deltainfo for: Copr repo for mingw-extras owned by smani
not found updateinfo for: Copr repo for mingw-extras owned by smani
smani-mingw-extras: using metadata from Mon 04 Dec 2017 10:07:04 PM CST.
repo: using cache for: updates
updates: using metadata from Thu 14 Dec 2017 10:30:23 PM CST.
repo: using cache for: fedora
not found deltainfo for: Fedora 27 - x86_64
not found updateinfo for: Fedora 27 - x86_64
fedora: using metadata from Sun 05 Nov 2017 01:51:47 PM CST.
Failed to synchronize cache for repo 'alonid-llvm-5.0.1', disabling.
Last metadata expiration check: 1:30:14 ago on Fri 15 Dec 2017 04:20:53 PM CST.

Repo-id      : smani-mingw-extras
Repo-name    : Copr repo for mingw-extras owned by smani
Repo-status  : enabled
Repo-revision: 1512396424
Repo-updated : Mon 04 Dec 2017 10:07:04 PM CST
Repo-pkgs    : 0
Repo-size    : 0
Repo-baseurl : https://copr-be.cloud.fedoraproject.org/results/smani/mingw-extras/fedora-27-x86_64/
Repo-expire  : 172,800 second(s) (last: Fri 15 Dec 2017 04:16:57 PM CST)
Repo-filename: /etc/yum.repos.d/_copr_smani-mingw-extras.repo
Total packages: 0

**Comment by manisandro** [comment]
You need to use either mingw32-twaindsm or mingw64-twaindsm, depending on whether you want to compile for 32bit or 64bit windows.

**Comment by manisandro** [comment]
By the way, I'm preparing an example dockerfile which I'll add to the repo.

**Comment by manisandro** [comment]
I've added a sample Docker image and updated the instructions in the Wiki [1].

[1] https://github.com/manisandro/gImageReader/wiki/Compiling-gImageReader

**Comment by napasa** [comment]
Hi Sir. It seems to come closer to cross compile it successfully. But mingw$bits-cmake always complain that It can`t found tesseract and  cmake could find out tesseract in contrast   Here is output when I run **./makeinstaller.sh**
[yu@localhost win32]$ ./makeinstaller.sh x86_64
-- GSettings schemas will be installed locally.
-- GSettings shemas will be compiled.
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/x86_64-w64-mingw32-gcc
-- Check for working C compiler: /usr/bin/x86_64-w64-mingw32-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/x86_64-w64-mingw32-g++
-- Check for working CXX compiler: /usr/bin/x86_64-w64-mingw32-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- qt5 interface will be built
-- Found Gettext: /usr/bin/msgmerge (found version "0.19.8.1") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.3.12") 
-- Checking for module 'tesseract'
--   Package 'tesseract', required by 'virtual:world', not found
-- Checking for module 'ddjvuapi'
--   Package 'ddjvuapi', required by 'virtual:world', not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:593 (_pkg_check_modules_internal)
  CMakeLists.txt:58 (PKG_CHECK_MODULES)

**Comment by napasa** [comment]
I built gImageReaded for Fedora Successfully. yep, I  will try docker now
