### ISSUE TITLE
Use unpaper utility for image processing

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [manisandro/gImageReader#256]
Hello @manisandro 

As far as my work with my document preprocessing library is frozen, i suggest you use already workable solution - unpaper.

unpaper is a post-processing tool for scanned sheets of paper, especially for book pages that have been scanned from previously created photocopies.

https://github.com/Flameeyes/unpaper

This tool already exist in linux distros. We can write simple wrapper around unpaper and process images via unpaper by our interface. In future we will be able just replace unpaper by document-preprocessing library.

What do you think?

**Comment by ZaMaZaN4iK** [comment]
Another possible option is implementing image processing algorithms inside gImageReader with OpenCV. It will be some general part for GTK and Qt versions. And after some months of work i will release this part of gImageReader as separate library. 

I prefer way with OpenCV inside gIR :-)

**Comment by manisandro** [comment]
If you want to give it a shot, sure, no objections here!

**Comment by SantosSi** [comment]
Knowing it is work in prgress, checked out the feature/image_processing_fresh branch for testing as it sounds promising.
How is this supposed to work? In my superficial and initial tests with a multipage PDF the image enhancements disappear when changing page. Will the changes persist in the background for a multipage OCR?
After closing the Enhance area, there is no option to open it again.

**Comment by ZaMaZaN4iK** [comment]
On UI side i just added showing intermediate result on UI. Currently image processing doesn't influence on image which goes to OCR engine. There are a lot of work here.

If you have any suggestions/ideas, you are welcome to bring it to us :-)

**Comment by SantosSi** [comment]
So the intermediate result is a preview? 
Then what about a commit button to 
transfer the image into a set of images 
the OCR will use instead?

**Comment by ZaMaZaN4iK** [comment]
I think will be better way without additional "Transfer" button. Just use default OCR button, and gIR will take already preprocessed image.

**Comment by ZaMaZaN4iK** [comment]
Unpaper has very low-quality source code. And i suggest use algorithms from OpenCV - it's more maintainable.
