### ISSUE TITLE
gimagereader main toolbar

### ISSUE THREAD

**Issue by klausert** [manisandro/gImageReader#26]
I can't find the "main toolbar" anymore. It got lost when moving the "source pane" and "output pane"  from the image.
Where is it?

**Comment by manisandro** [comment]
I'd be curious to know how you got it to vanish, but to restore the default window geometry, you can edit the gImageReader configuration:
- On Linux, edit `$HOME/.config/gImageReader/gImageReader.conf` and delete the lines `wingeom` and `winstate`
- On Windows, run `regedit` and browser to `HKEY_CURRENT_USER/Software/gImageReader/gImageReader` and delete the entries `wingeom` and `winstate`.

Hope this helps.
