### ISSUE TITLE
Automatically enlarge superordinate/reduce subordinate areas.

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#263]
E.g. enlarge paragraphs when a subordinate textline is enlarged or reduce a paragraph when all subordinate textlines were made smaller.

**Comment by manisandro** [comment]
I don't think the "reduce subordinate areas" point is doable. Say you reduce the width of a paragraph to zero, then all contained areas will inevitably become degenerate and there is no way to enlarge them again.
What could work is that you are only allowed to shrink leaf node, whereas you can only enlarge other nodes (which will in turn enlarge affected child nodes). But say you enlarge too much, then you have to manually reduce all child elements correct the size of the parent node.
All in all, I think there are too many corner cases.
What could work is a button you need to explicitly call "re-compute bounding boxes". It could be global, or in the context menu of each node level. What do you think?

**Comment by SantosSi** [comment]
I thought it the other way round. Think of it as no need to have a larger superordinate node if all subordinate nodes are smaller and a superordinate node should be large enough to host subordinate nodes.
E.g. if all textlines are smaller alltogether, then shrink the paragraph and the text blocks to exactly fit all textlines.
And if textlines were enlarged, then its surounding paragraph and text block should also be enlarged, if the new textline size supersedes them.

**Comment by manisandro** [comment]
So what should happen if the user manually reduces the size of the paragraph?

**Comment by SantosSi** [comment]
Then the text block should be checked if its size can be reduced too to not be bigger than all contained paragraphs.

**Comment by SantosSi** [comment]
So both reducing and enlarging only affects superordinate nodes.

**Comment by manisandro** [comment]
So basically you just recompute the superordinate bounding boxes between the affected node and the root node.

**Comment by manisandro** [comment]
Done: parent bboxes are recomputed when a child bbox changes, and parent bboxes cannot be shrunk below the bbox of the children.

**Comment by SantosSi** [comment]
Can you also recompute parent nodes when a node is deleted (and maybe later when a new one is created)?

**Comment by manisandro** [comment]
Good point, done
