### ISSUE TITLE
hOCR: Make words bold.

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#265]
Making text bold is similarly important to the layout as text size is.

**Comment by ZaMaZaN4iK** [comment]
Probably you are right. But we should balance between simple HOCR utility and LibreOffice Writer :-)

**Comment by SantosSi** [comment]
Let's prioritize hOCR utility and to 
discriminate against LibreOffice: I 
did not request italic :-)

**Comment by manisandro** [comment]
Done for Qt

**Comment by manisandro** [comment]
Done for Gtk also. Testing welcome.

**Comment by SantosSi** [comment]
Cool: you also implemented italic...
Bold and italic are exported to ODT, but not to PDF.

**Comment by manisandro** [comment]
What font are you using? In some cases I have also observed bold and or italic not being honoured in the PDF, but for others it works fine. I suspect it has something to do with the PoDoFo font matching internals.

**Comment by SantosSi** [comment]
Not working with Oxygen-Sans, Arial, DejaVu Sans.

**Comment by manisandro** [comment]
Ah maybe you have a font family override active in the PDF export dialog? Actually I could look at ensuring that the bold and italic properties work even if a fallback family is set.

**Comment by SantosSi** [comment]
Yes, I have to override and hoped bold and italic are respected nevertheless.
If I don't override the error appears: "The PDF export failed: ePdfError_UnsupportedFontFormat."

**Comment by manisandro** [comment]
I've pushed a change that bold and italic are respected even with a font family override.

About the error: can you send me the hocr file which causes the issue? Cause the idea is that it falls back to the fallback font if a font cannot be loaded...

**Comment by manisandro** [comment]
Odd, works fine here (podofo-0.9.5). By the way, did you set the font family to `x_font` on purpose or did the program mess something up in the HOCR document?

**Comment by SantosSi** [comment]
I did not set the font in the hOCR document, must have been the program.

**Comment by manisandro** [comment]
Is this a hOCR document which was generated by gImageReader or directly by tesseract and subsequently edited with gImageReader?

**Comment by SantosSi** [comment]
All pure "homegrown" gImageReader results.
