### ISSUE TITLE
hOCR: Merge and separate nodes.

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#266]
E.g. merge text blocks and paragraphs, separate words.
Is it also possible to reassign nodes, e.g. assign a textline including words to a different paragraph.

**Comment by manisandro** [comment]
Merging should already be implemented, or is something missing?

**Comment by SantosSi** [comment]
Consecutive nodes can merge, but non-consecutive ones not. This is mainly to reorganize wrongly assembled paragraphs and the like.

**Comment by manisandro** [comment]
I'd handle that by allowing to drag and drop nodes around, but still only allow to merge consecutive nodes.

**Comment by SantosSi** [comment]
For the separation a function to find blank spaces followed by a letter or a figure within the ocrx_word nodes would be helpful. We should not use other word delimiters, as commas or points are usually attached to the last word, except for French and the like.
In general separation requires a marker where to separate nodes, but all the node types except word are self-contained, so drag-and-drop would suffice for those.

**Comment by manisandro** [comment]
Tracking in #438
