### ISSUE TITLE
hOCR: Display progress bar for PDF exports or at least a complete message. 

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#267]
The application window just freezes, sometimes it refreshes an input image.

**Comment by manisandro** [comment]
Implemented for Qt

**Comment by SantosSi** [comment]
Working in Qt5 as expected.
As a side effect all input images are also 
displayed sequentially, optically quite 
entertaining.

**Comment by manisandro** [comment]
Done also for Gtk. Side note: I'd appreciate some thorough testing of the Gtk interface which has lots of very new code.
