### ISSUE TITLE
hOCR: After exported to PDF with a different name, the suggested hOCR .html file name is that too.

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#268]
E.g. Ch1.html exported to Ch1-OCR.pdf: subsequent saving the hOCR file suggests Ch1-OCR.html

**Comment by manisandro** [comment]
That was kinda on purpose, shouldn't it be so?

**Comment by SantosSi** [comment]
Well, no. Imagine: the html file is named after the input PDF, then the suggested output PDF would be named after the file that is not allowed to be overwritten. Exporting the PDF to a different name is a must, but the html file name should be the name of the opened html file name.

**Comment by manisandro** [comment]
OTOH when re-exporting the PDF you'd want to re-use the name previously used when exporting I suppose.

**Comment by SantosSi** [comment]
Right, so there should be a file name for the html and a separate one for the export PDF.

**Comment by manisandro** [comment]
And what about text export? I mean, sure it's all easy, but it sounds a bit an overkill to keep a separate variable for each possible exporter...

**Comment by SantosSi** [comment]
The full text file path does not 
collide, but PDF is both an input 
and an output format.

**Comment by manisandro** [comment]
Kinda addressed in 3c462768c74c0cca7c6c226e1f74d97fcf93bcc2, the name picked when exporting does not change the used to save the hOCR document.
