### ISSUE TITLE
hOCR: merge hOCR .html files to one.

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#269]
Some scanning devices limit the size of output PDF files, but those separate files still form the same document.

**Comment by manisandro** [comment]
You mean that the "Open" functionality should allow appending to the current document?

**Comment by SantosSi** [comment]
Not only appending. I had the case that my scanner skipped pages. So I scanned those missing pages into another PDF and had to insert into within the first one. gIR is able to handle that afterwards, I just inserted manually with a text editor.

**Comment by bmix** [comment]
[hocr-tools](https://github.com/tmbdev/hocr-tools) can do what you want.

**Comment by SantosSi** [comment]
@bmix I did not look for a different tool, but to have it in this one. The goal is to not change the interface, the tool, the environment. This is a matter of workflow.

**Comment by manisandro** [comment]
Implemented - you can now choose whether to insert new output or a document before a selected page or at the end.
