### ISSUE TITLE
hOCR: Display overall page number.

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#270]
Currently only the current image docment's page number is shown, please show also the overall page number. The page selector cycles through an image file's page and skips inserted files.

**Comment by manisandro** [comment]
What do you mean by "page selector"?

**Comment by SantosSi** [comment]
"page selector" was my attempt to name the page number widget to select the input image page, to the left of the image controls toggle button. Sorry for that, there is no denomination or help when I hover the mouse over the control.

**Comment by manisandro** [comment]
Hmm then I don't understand what you mean by "The page selector cycles through an image file's page and skips inserted files". As it stands, the page selector has no effect on the HOCR editor?

**Comment by SantosSi** [comment]
See the situation described in #269.
Imagine the following page sequence:Doc1p1, Doc1p2, Doc2p1, Doc1p3
Starting at Doc1p1 when increasing the page in the selector it opens: Doc1p1, then Doc1p2 and then Doc1p3. So Docp1 is not opened with the selector.
An overall page selector would open the pages in the right sequence.

**Comment by manisandro** [comment]
Can't you just click on the pages in the HOCR tree?

**Comment by SantosSi** [comment]
Yes, that's what I did in the past. But that makes it 
error prone to skip whole inserted documents, as it 
happened to me.
And there is another advantage to my suggestion: 
the overall page selector replicates the page 
numbering of the output PDF, really useful for 
reviewing.

**Comment by manisandro** [comment]
The thing is that the page selector operates on the selected sources, not on the hOCR document tree. And I can't really imagine a way to combine the two. What I can do is add the effective page number in the labels of the page nodes.

**Comment by SantosSi** [comment]
What about counting pages when reading the file? When inserting another hOCR, then all consecutive pages have to be added with the amount of inserted pages.
This could be a hOCR property in that area, so not displayed for text output.

**Comment by manisandro** [comment]
Well yes, that would be "add the effective page number in the labels of the page nodes".

**Comment by manisandro** [comment]
Done
