### ISSUE TITLE
Remember "Show output PDF" option

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [manisandro/gImageReader#274]
During export PDF we have option "Show output PDF". But if i checked it in one export dialog, exported PDF and call export dialog one more time, i should again check this checkbox. It's very annoying.

What we can do:
* Remember user choice (even remember between gIR launches (extend Settings))
* Also remember user choice during one gIR instance.

**Comment by manisandro** [comment]
I'd just bind the checkbox to a setting, i.e

    MAIN->getConfig()->addSetting(new SwitchSetting("<name>", ui.checkBoxXXX, <default>));

**Comment by ZaMaZaN4iK** [comment]
In which file it should added properly? Because i see at least two files with addSetting code.

**Comment by manisandro** [comment]
Add it in HOCRPdfExporter and remove it in ~HOCRPdfExporter. Settings are always placed in the class where they are relevant. Classes which remain alive for the lifetime of the program don't need to delete their settings, classes which are instantiated on-demand do.

**Comment by ZaMaZaN4iK** [comment]
Ok. I will create PR for this feature.

**Comment by manisandro** [comment]
If you haven't already started, I can take care of this one, since I'd like to do some general setting related changes anyway.

**Comment by ZaMaZaN4iK** [comment]
Oh, of course. I am working on paper sizes now.

**Comment by manisandro** [comment]
Done

**Comment by SantosSi** [comment]
In the newest GTK both the Save 
and the Export buttons are 
disabled.

**Comment by manisandro** [comment]
Uh? Despite having a document loaded?

**Comment by manisandro** [comment]
Actually, yes I just found a sequence where this can happen...

**Comment by manisandro** [comment]
Was an oversight from my previous attempt to properly clear the document model... Should be good now.

**Comment by SantosSi** [comment]
Now when clicking the export to PDF button the GTK version crashes:
(gimagereader-gtk:13965): Gtk-WARNING **: Allocating size to gtkmm__GtkViewport 0x55e048af6f30 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(gimagereader-gtk:13965): GLib-GIO-ERROR **: Settings schema 'org.gnome.gimagereader' does not contain a key named 'pdfimagedithering'
./run-gtk.sh: Zeile 1: 13965 Trace/Breakpoint ausgelöst   XDG_DATA_DIRS=~/source/gImageReader/build:/usr/share ./gimagereader-gtk

**Comment by manisandro** [comment]
The Gtk-WARNINGs can be ignored.
As far as pdfimagedithering, it looks like for some reason it isn't picking up the correct schema... I take that the build folder contains a glib-2.0 directory with the schemas inside?

**Comment by SantosSi** [comment]
$ ls /usr/share/glib-2.0/schemas/org.gnome.gimage*
/usr/share/glib-2.0/schemas/org.gnome.gimagereader.gschema.xml

**Comment by manisandro** [comment]
That's the one for the debian package I suppose, if you run it from the build tree then you should have something like

    $ find build/linux-gtk/glib-2.0/
    build/linux-gtk/glib-2.0/
    build/linux-gtk/glib-2.0/schemas
    build/linux-gtk/glib-2.0/schemas/gschemas.compiled
    build/linux-gtk/glib-2.0/schemas/org.gnome.gimagereader.gschema.xml

Here I compiled the gtk interface in build/linux-gtk and run the application as

    cd build/linux-gtk
    XDG_DATA_DIRS=$PWD:$XDG_DATA_DIRS ./gimagereader-gtk

**Comment by SantosSi** [comment]
I ran from the build subfolder:
`XDG_DATA_DIRS=source/gImageReader/build:/usr/share ./gimagereader-gtk`
Don't have linux-gtk in build. Running your command above from build outputs the same error.

**Comment by manisandro** [comment]
Yeah but do you have a `build/glib-2.0/schemas/gschemas.compiled`?

**Comment by SantosSi** [comment]
No glib-2.0 subfolder at all in build.

**Comment by manisandro** [comment]
Well that explains the failure. Do you have a `glib-compile-resources` in your PATH? On Fedora it is 
installed by glib2-devel. In theory the build should fail if it fails to compile the schemas.

**Comment by manisandro** [comment]
Actually that was only half the story, you also need `glib-compile-schemas`, and this command should be printed out if your run `pkg-config  gio-2.0 --variable glib_compile_schemas`

**Comment by manisandro** [comment]
I've added a commit which makes the build fail if `glib-compile-schemas` is missing.

**Comment by SantosSi** [comment]
Both glib-compile-resources and glib-compile-schemas are installed. 
pkg-config command result:
```
$ pkg-config gio-2.0 --variable glib_compile_schemas
/usr/lib/x86_64-linux-gnu/glib-2.0/glib-compile-schemas
```

**Comment by manisandro** [comment]
Ok, I've added a helper script which compiles the schemas locally, and updated the compiling wiki. Basically:
