### ISSUE TITLE
Add more information for exported PDF

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [manisandro/gImageReader#275]
We can add more information to exported PDF: author, creator, producer, keywords. It can be useful for manipulating and categorizing output PDF by other programs.

It should be easy, because PoDoFo provides to us this functionality.

**Comment by ZaMaZaN4iK** [comment]
@manisandro Do you have any suggestions?

**Comment by manisandro** [comment]
Well, there is not much else besides the name of the application that generated the PDF to add as information automatically.

**Comment by ZaMaZaN4iK** [comment]
Will not create PR with UI changes before paper_size merge into master. I don't want to merge two XML files :-)

**Comment by ZaMaZaN4iK** [comment]
https://github.com/manisandro/gImageReader/pull/282

**Comment by manisandro** [comment]
Done for qt

**Comment by manisandro** [comment]
Done also for gtk.
