### ISSUE TITLE
newest master code occur exception  when export pdf 

### ISSUE THREAD

**Issue by napasa** [manisandro/gImageReader#276]
gImageReader 3.2.3 ()

#1  0x00007f9ce3a6de5f in qt_safe_select(int, fd_set*, fd_set*, fd_set*, timespec const*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00007f9ce3a6df4a in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007f9ce39b15a2 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007f9ce394c2bf in QProcess::waitForFinished(int) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00000000004b3d8a in MainWindow::signalHandler(int) ()
#6  0x00000000004b4004 in terminateHandler() ()
#7  0x00007f9ce34a16b6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007f9ce34a1701 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007f9ce34a1716 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007f9ce34a1342 in __cxa_call_unexpected () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007f9ce34a1f31 in operator new[](unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#12 0x00007f9ce4f1c717 in PoDoFo::PdfFontTTFSubset::BuildFont(PoDoFo::PdfOutputDevice*) () from /usr/lib/libpodofo.so.0.9.3
#13 0x00007f9ce4f0f1d0 in PoDoFo::PdfFontCache::GetFontSubset(char const*, bool, bool, bool, PoDoFo::PdfEncoding const*, char const*) () from /usr/lib/libpodofo.so.0.9.3
#14 0x00000000005041ae in HOCRPdfExporter::run(QString&) ()
#15 0x0000000000517259 in OutputEditorHOCR::exportToPDF() ()
#16 0x000000000052c0aa in OutputEditorHOCR::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#17 0x00007f9ce3a4ad2a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007f9ce4305412 in QAction::triggered(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007f9ce4307898 in QAction::activate(QAction::ActionEvent) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007f9ce4489e52 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007f9ce44900ec in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007f9ce4494060 in QMenu::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007f9ce4351fc8 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007f9ce4494ab3 in QMenu::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007f9ce430f05c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007f9ce4314c19 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007f9ce3a1c38b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x00007f9ce4313b32 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#29 0x00007f9ce436c91d in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#30 0x00007f9ce436eb7b in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#31 0x00007f9ce430f05c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#32 0x00007f9ce4314516 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#33 0x00007f9ce3a1c38b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x00007f9ce3d5e4e1 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#35 0x00007f9ce3d601a5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#36 0x00007f9ce3d43f08 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#37 0x00007f9cd76e1200 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#38 0x00007f9cdfc21197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#39 0x00007f9cdfc213f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#40 0x00007f9cdfc2149c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#41 0x00007f9ce3a727cf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#42 0x00007f9ce3a19b4a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#43 0x00007f9ce448ee40 in QMenu::exec(QPoint const&, QAction*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#44 0x00007f9ce44d12ae in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#45 0x00007f9ce3a4ad2a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#46 0x00007f9ce440bff7 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#47 0x00007f9ce440c151 in QAbstractButton::mousePressEvent(QMouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#48 0x00007f9ce44d209f in QToolButton::mousePressEvent(QMouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#49 0x00007f9ce435240f in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#50 0x00007f9ce44d2349 in QToolButton::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#51 0x00007f9ce430f05c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#52 0x00007f9ce4314c19 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#53 0x00007f9ce3a1c38b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#54 0x00007f9ce4313b32 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#55 0x00007f9ce436c5bb in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#56 0x00007f9ce436eb7b in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#57 0x00007f9ce430f05c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#58 0x00007f9ce4314516 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#59 0x00007f9ce3a1c38b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#60 0x00007f9ce3d5e4e1 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#61 0x00007f9ce3d601a5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#62 0x00007f9ce3d43f08 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#63 0x00007f9cd76e1200 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#64 0x00007f9cdfc21197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#65 0x00007f9cdfc213f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#66 0x00007f9cdfc2149c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#67 0x00007f9ce3a727cf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#68 0x00007f9ce3a19b4a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#69 0x00007f9ce3a21bec in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#70 0x000000000051fc5a in main ()

Thread 10 (Thread 0x7f9cade41700 (LWP 8880)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f9ce383ca5b in QWaitCondition::wait(QMutex*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00000000004a60ff in Displayer::scaleThread() ()
#3  0x00000000004ac4a5 in void std::_Mem_fn_base<void (Displayer::*)(), true>::operator()<, void>(Displayer*) const ()
#4  0x00000000004abf93 in void std::_Bind<std::_Mem_fn<void (Displayer::*)()> (Displayer*)>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) ()
#5  0x00000000004ab10d in void std::_Bind<std::_Mem_fn<void (Displayer::*)()> (Displayer*)>::operator()<, void>() ()
#6  0x00000000004a9986 in std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (Displayer::*)()> (Displayer*)> >::_M_invoke(std::_Any_data const&) ()
#7  0x00000000004a8344 in std::function<void ()>::operator()() const ()
#8  0x00000000004a7e88 in Displayer::ScaleThread::run() ()
#9  0x00007f9ce383b7be in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007f9ce2abd6ba in start_thread (arg=0x7f9cade41700) at pthread_create.c:333
#11 0x00007f9ce27f33dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 9 (Thread 0x7f9cc8f81700 (LWP 8869)):
#0  0x00007f9ce27e770d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f9c9716794a in ?? () from /usr/lib/x86_64-linux-gnu/libavahi-common.so.3
#2  0x00007f9c971674d3 in avahi_simple_poll_run () from /usr/lib/x86_64-linux-gnu/libavahi-common.so.3
#3  0x00007f9c971676a8 in avahi_simple_poll_iterate () from /usr/lib/x86_64-linux-gnu/libavahi-common.so.3
#4  0x00007f9c971678dd in avahi_simple_poll_loop () from /usr/lib/x86_64-linux-gnu/libavahi-common.so.3
#5  0x00007f9c971679a4 in ?? () from /usr/lib/x86_64-linux-gnu/libavahi-common.so.3
#6  0x00007f9ce2abd6ba in start_thread (arg=0x7f9cc8f81700) at pthread_create.c:333
#7  0x00007f9ce27f33dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 8 (Thread 0x7f9cad640700 (LWP 8863)):
#0  0x00007f9ce27e770d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f9cdfc2138c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f9cdfc2149c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f9ce3a727cf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007f9ce3a19b4a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f9ce3836834 in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007f9ce383b7be in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007f9ce2abd6ba in start_thread (arg=0x7f9cad640700) at pthread_create.c:333
#8  0x00007f9ce27f33dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 7 (Thread 0x7f9cb926c700 (LWP 8861)):
#0  0x00007f9ce27e770d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f9cb927c64c in ?? () from /lib/x86_64-linux-gnu/libusb-1.0.so.0
#2  0x00007f9ce2abd6ba in start_thread (arg=0x7f9cb926c700) at pthread_create.c:333
#3  0x00007f9ce27f33dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 6 (Thread 0x7f9cb9e98700 (LWP 8860)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f9ce383ca5b in QWaitCondition::wait(QMutex*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x000000000052591d in Utils::AsyncQueue<ScannerSane::Request>::dequeue() ()
#3  0x0000000000520232 in ScannerSane::run() ()
#4  0x000000000052c6ab in ScannerSane::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#5  0x00007f9ce3a4ad2a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007f9ce383b7a5 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007f9ce2abd6ba in start_thread (arg=0x7f9cb9e98700) at pthread_create.c:333
#8  0x00007f9ce27f33dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 5 (Thread 0x7f9cc9cbb700 (LWP 8851)):
#0  0x00007f9ce27e770d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f9cdfc2138c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f9cdfc2149c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f9ccb35028d in ?? () from /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
#4  0x00007f9cdfc47bb5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f9ce2abd6ba in start_thread (arg=0x7f9cc9cbb700) at pthread_create.c:333
#6  0x00007f9ce27f33dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 4 (Thread 0x7f9cca4bc700 (LWP 8850)):
#0  0x00007f9ce27e770d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f9cdfc2138c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f9cdfc21712 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f9cceda99d6 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007f9cdfc47bb5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f9ce2abd6ba in start_thread (arg=0x7f9cca4bc700) at pthread_create.c:333
#6  0x00007f9ce27f33dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 3 (Thread 0x7f9ccacbd700 (LWP 8849)):
#0  0x00007f9ce27e770d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f9cdfc2138c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f9cdfc2149c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f9cdfc214d9 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f9cdfc47bb5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f9ce2abd6ba in start_thread (arg=0x7f9ccacbd700) at pthread_create.c:333
#6  0x00007f9ce27f33dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7f9cd539d700 (LWP 8848)):
#0  0x00007f9ce27e770d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f9cdd105c62 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007f9cdd1078d7 in xcb_wait_for_event () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007f9cd76af889 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#4  0x00007f9ce383b7be in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f9ce2abd6ba in start_thread (arg=0x7f9cd539d700) at pthread_create.c:333
#6  0x00007f9ce27f33dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7f9cd8e5e940 (LWP 8847)):
#0  0x00007f9ce27e9593 in select () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f9ce3a6de5f in qt_safe_select(int, fd_set*, fd_set*, fd_set*, timespec const*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00007f9ce3a6df4a in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007f9ce39b15a2 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007f9ce394c2bf in QProcess::waitForFinished(int) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00000000004b3d8a in MainWindow::signalHandler(int) ()
#6  0x00000000004b4004 in terminateHandler() ()
#7  0x00007f9ce34a16b6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007f9ce34a1701 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007f9ce34a1716 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007f9ce34a1342 in __cxa_call_unexpected () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007f9ce34a1f31 in operator new[](unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#12 0x00007f9ce4f1c717 in PoDoFo::PdfFontTTFSubset::BuildFont(PoDoFo::PdfOutputDevice*) () from /usr/lib/libpodofo.so.0.9.3
#13 0x00007f9ce4f0f1d0 in PoDoFo::PdfFontCache::GetFontSubset(char const*, bool, bool, bool, PoDoFo::PdfEncoding const*, char const*) () from /usr/lib/libpodofo.so.0.9.3
#14 0x00000000005041ae in HOCRPdfExporter::run(QString&) ()
#15 0x0000000000517259 in OutputEditorHOCR::exportToPDF() ()
#16 0x000000000052c0aa in OutputEditorHOCR::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#17 0x00007f9ce3a4ad2a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007f9ce4305412 in QAction::triggered(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007f9ce4307898 in QAction::activate(QAction::ActionEvent) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007f9ce4489e52 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007f9ce44900ec in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007f9ce4494060 in QMenu::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007f9ce4351fc8 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007f9ce4494ab3 in QMenu::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007f9ce430f05c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007f9ce4314c19 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007f9ce3a1c38b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x00007f9ce4313b32 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#29 0x00007f9ce436c91d in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#30 0x00007f9ce436eb7b in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#31 0x00007f9ce430f05c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#32 0x00007f9ce4314516 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#33 0x00007f9ce3a1c38b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x00007f9ce3d5e4e1 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#35 0x00007f9ce3d601a5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#36 0x00007f9ce3d43f08 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#37 0x00007f9cd76e1200 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#38 0x00007f9cdfc21197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#39 0x00007f9cdfc213f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#40 0x00007f9cdfc2149c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#41 0x00007f9ce3a727cf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#42 0x00007f9ce3a19b4a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#43 0x00007f9ce448ee40 in QMenu::exec(QPoint const&, QAction*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#44 0x00007f9ce44d12ae in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#45 0x00007f9ce3a4ad2a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#46 0x00007f9ce440bff7 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#47 0x00007f9ce440c151 in QAbstractButton::mousePressEvent(QMouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#48 0x00007f9ce44d209f in QToolButton::mousePressEvent(QMouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#49 0x00007f9ce435240f in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#50 0x00007f9ce44d2349 in QToolButton::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#51 0x00007f9ce430f05c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#52 0x00007f9ce4314c19 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#53 0x00007f9ce3a1c38b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#54 0x00007f9ce4313b32 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#55 0x00007f9ce436c5bb in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#56 0x00007f9ce436eb7b in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#57 0x00007f9ce430f05c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#58 0x00007f9ce4314516 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#59 0x00007f9ce3a1c38b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#60 0x00007f9ce3d5e4e1 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#61 0x00007f9ce3d601a5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#62 0x00007f9ce3d43f08 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#63 0x00007f9cd76e1200 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#64 0x00007f9cdfc21197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#65 0x00007f9cdfc213f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#66 0x00007f9cdfc2149c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#67 0x00007f9ce3a727cf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#68 0x00007f9ce3a19b4a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#69 0x00007f9ce3a21bec in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#70 0x000000000051fc5a in main ()

**Comment by manisandro** [comment]
Can you do a print-screen of the pdf-export dialog with the settings that lead to this crash?

**Comment by manisandro** [comment]
Hi, can you still reproduce this? Can you provide the info requested in my previous comment?

**Comment by napasa** [comment]
Hi, It seems produce by my temporary code, not yours.
