### ISSUE TITLE
Equivalent of gImageReader in console?

### ISSUE THREAD

**Issue by h0gar** [manisandro/gImageReader#277]
I get much better results with gImageReader out of the box than vanilla tesseract command line. But I'd like to use the command line from automatic batch processing. So what I wonder what is the equivalent command line of gImageReader out-of-the-box?

For example with the image below I get "15 Jan 1805\n\n" in gImageReader and Jan\n\n1805\n\n" with "tesseract img.png result".

![_tmp](https://user-images.githubusercontent.com/439138/34358219-1313bd2c-ea4e-11e7-8c1c-9b1905732251.png)

**Comment by manisandro** [comment]
Hi
Perhaps it is that you didn't explicitly specify the language on the command line, so perhaps a generic traineddata was used.

If that is not the case, I'm afraid I can't give you a good answer, since I don't actually know what the tesseract executable does in detail. As far as gImageReader is concerned, it essentially does

    tesseract::TessBaseAPI tess;
    tess.Init(nullptr, language /* i.e. eng */);
    tess.SetPageSegMode(mode /* tesseract::PageSegMode */)
    tess.SetImage(rgba_data, width, height, 4 /* bytesPerPixel */, stride /*bytesPerRow*/);
    tess.SetSourceResolution(srcDpi); /* actually only to ensure that the detected HOCR font sizes are physically correct */
    tess.Recognize();

The image data as passed to tess.SetImage is what you see in the gImageReader canvas (i.e. no additional processing done before it is passed to tesseract).

**Comment by h0gar** [comment]
Thank you for your quick reply. Even though I'm don't know yet why it produces a different result at least it's not coming from some gImageReader pre processing. I'll continue investigating another path. Thanks again.

**Comment by danfelder2** [comment]
I have a similar issue. Here is the image, that I am working with.
![image](https://user-images.githubusercontent.com/63428301/78944371-bee5de80-7a8b-11ea-8d65-906a23cb7ce2.png)
When I run it through Tesseract, I get this output:

![image](https://user-images.githubusercontent.com/63428301/78945100-77f8e880-7a8d-11ea-9740-1917e24a52b6.png)

I also tried running it through Tesseract, after generating an trained dataset, based on this site, but the results did not improve.

https://pretius.com/how-to-prepare-training-files-for-tesseract-ocr-and-improve-characters-recognition/

Using gImageReader, it is almost perfect, but I want to run it from a command line, so it can be batched & automated by a script. 

![image](https://user-images.githubusercontent.com/63428301/78944844-df626880-7a8c-11ea-9dcf-63347344937a.png)

Is there a command line that I can use with gImageReader to accomplish this or could you let me know how I could setup Tesseract (I,e, where to put the details that you mentioned in the previous response.)
tesseract::TessBaseAPI tess;
tess.Init(nullptr, language /* i.e. eng */);
tess.SetPageSegMode(mode /* tesseract::PageSegMode */)
tess.SetImage(rgba_data, width, height, 4 /* bytesPerPixel */, stride /*bytesPerRow*/);
tess.SetSourceResolution(srcDpi); /* actually only to ensure that the detected HOCR font sizes are physically correct */
tess.Recognize();
Thank you for your time.

**Comment by manisandro** [comment]
gImageReader does not have a command line interface.

The "details" you quoted is how gImageReader internally invokes tesseract, so if you want to develop your own C or C++ application which invokes tesseract, you'd do something along those lines. But I still see no reason why tesseract command line should not behave the same, try going through the tesseract manual and explore which options you can set I'd suggest.
