### ISSUE TITLE
'Append to current text' insertion mode does not work as expected

### ISSUE THREAD

**Issue by jesrui** [manisandro/gImageReader#28]
I have observed the following bug in gimagereader 3.1:

1. Move the cursor somewhere to the middle of the output text
2. Select 'Append to current Text'
3. Drag two rectangles in the scanned image to select two different text
blocks.

The text of the first rectangle is appended to the end of output text
while the text of the second rectangle is inserted at the current cursor
position.

**Comment by manisandro** [comment]
Thanks for reporting.
