### ISSUE TITLE
Change focus to highlighted hOCR node after clicking in image.

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#280]
The purpose of this function is to use the keyboard to manipulate the hOCR nodes after selected.

**Comment by manisandro** [comment]
Done

**Comment by SantosSi** [comment]
Thanks for implementing so quickly.
Fine in Qt.
In GTK clicking in the image its corresponding hidden/
folded node does not unfold superordinate nodes. And: 
if the superordinated nodes are unfolded, the node is 
highlighted, but the focus is not changed to that node. 
Instead the focus stays on the last node selected in the 
hOCR list.

**Comment by manisandro** [comment]
Fixed
