### ISSUE TITLE
Newest GTK build crashes on clicking PDF export

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#281]
Console error:
(gimagereader-gtk:18710): Gtk-WARNING **: Allocating size to gtkmm__GtkBox 0x5652971438b0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(gimagereader-gtk:18710): Gtk-WARNING **: Allocating size to gtkmm__GtkViewport 0x565296f62f30 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(gimagereader-gtk:18710): GLib-GIO-ERROR **: Settings schema 'org.gnome.gimagereader' does not contain a key named 'pdfimagedithering'
Trace/Breakpoint ausgelöst

**Comment by manisandro** [comment]
You need to add to the `XDG_DATA_DIRS` environment variable the folder where the updated settings schema is located. Typically, if you build in `gimagereader/build`, you can run the application from the build folder as

    XDG_DATA_DIRS=$PWD:/usr/share ./gimagereader-gtk

The path you add to XDG_DATA_DIRS must contain the following children `glib-2.0/schemas/{gschemas.compiled,org.gnome.gimagereader.gschema.xml}`.
