### ISSUE TITLE
Add "Open after export" option for ODT and plain text export

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [manisandro/gImageReader#287]
Hello @manisandro 
Can you add please option for automatic opening output document for these formats?

**Comment by manisandro** [comment]
What about a centralized setting in the main setting dialog for all export options? It is a bit excessive to add dialogs to the text and odt export just for this one checkbox...

**Comment by ZaMaZaN4iK** [comment]
Yep, good idea.
P.S. Can we talk via Google Hangouts now?

**Comment by manisandro** [comment]
Done in 869a38b90b1a0142b263ed64849a1b568eebff52
