### ISSUE TITLE
Add build to About dialog

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#290]
Knowing the compiled build over the released version helps in identifying what was the latest compilation for development.

**Comment by manisandro** [comment]
Like adding the git revision?

**Comment by SantosSi** [comment]
Yes

**Comment by manisandro** [comment]
Done, but you need to manually ensure cmake is re-run to ensure you have the current git revision in the dialog (doing it build-time would always lead to recompilation of at least a portion of the program, which is undesirable for development).
