### ISSUE TITLE
provide pdf output using tesseract's pdfrenderer

### ISSUE THREAD

**Issue by Shreeshrii** [manisandro/gImageReader#292]
Tesseract can now output a pdf file with the ocred text layer.

This could be offered as an option since 'podofo' does not seem to support complex scripts - https://github.com/manisandro/gImageReader/issues/183#issuecomment-344081421

**Comment by manisandro** [comment]
As far as I can see it is not possible to pass external HOCR data to the tesseract PDF renderer - it is only possible to pass a TessBaseAPI object from which the renderer extracts the data internally, see `renderer.h`.

    /**
     * Adds the recognized text from the source image to the current document.
     * Invalid if BeginDocument not yet called.
     *
     * Note that this API is a bit weird but is designed to fit into the
     * current TessBaseAPI implementation where the api has lots of state
     * information that we might want to add in.
     */
    bool AddImage(TessBaseAPI* api);

So I believe this is not possible. But there is a work-in-progress PR to allow the user to choose Qts PDF renderer [1], which should help somewhat. The proper solution however is to better investigate what needs to be done for PoDoFo to render such fonts correctly.

[1] https://github.com/manisandro/gImageReader/pull/289

**Comment by Shreeshrii** [comment]
>As far as I can see it is not possible to pass external HOCR data to the tesseract PDF renderer 

How about adding a new option to create pdf using tesseract directly (without using hocr)?

In command line version, in just requires invoking of 'pdf' config file. I am not sure what is required in the api though.

**Comment by Shreeshrii** [comment]
Here is tesseract generated pdf for the test case in zip file in https://github.com/manisandro/gImageReader/issues/291

[skanda700test-Devanagari-fast.pdf](https://github.com/manisandro/gImageReader/files/1622460/skanda700test-Devanagari-fast.pdf)

**Comment by manisandro** [comment]
But in that case one could just use tesseract directly, there is little value in using gImageReader?

**Comment by Shreeshrii** [comment]
Many users use gImageReader as a user-friendly GUI for tesseract. So it will certainly be of value to them.

I am only requesting it as an additional option to the **hocr, pdf**.

**Comment by Shreeshrii** [comment]
> But there is a work-in-progress PR to allow the user to choose Qts PDF renderer [1]

I will wait to see whether that handles Devanagari script correctly.

**Comment by manisandro** [comment]
I can't see a straight forward way to integrate it into the GUI, since it would bypass the output editor completely. Personally I'd rather have PoDoFo work correctly.

**Comment by manisandro** [comment]
I'll close this in favor of #291
