### ISSUE TITLE
Win 64 bit Qt5: No spellcheck with newest master

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#297]
Former builds worked with the existing spellcheck files, lastest working version unknown. Redetect Languages useless. Removing and (re-)downloading german spellcheck files shows error downloading DE_LU.
Same build spellchecking fine on Linux.

**Comment by manisandro** [comment]
Looks like something changed in enchant, if you move the spelling dictionaries from `%ProgramFiles%\share\myspell\dicts` to `%ProgramFiles%\share\myspell\` it should work again.

**Comment by manisandro** [comment]
Fixed
