### ISSUE TITLE
Use gImageReader to convert scanned computer code into text file

### ISSUE THREAD

**Issue by financian** [manisandro/gImageReader#298]
Has anybody tried to convert scanned old computer code such as Matlab, R, or even LaTeX into text file with gImageReader? When I tried it, gImageReader won't be able to recognize code. I would hope the OCR simply recognize every letter and put them back in the same way as from the scan.

**Comment by manisandro** [comment]
It depends a lot on the traineddata - most are trained for recognizing text made of words in a particular language, not just single characters. You'll need to train tesseract (the OCR engine gImageReader uses) specifically for this use case, see https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract.
