### ISSUE TITLE
hOCR: Output preview for formats maintaining layout

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#300]
Currently the whole created PDF has to be openend side by side in a viewer to see the layout problems, with large documents creation takes time and requires review management. A preview for the editing phase (as opposed to the export phase) would resolve the issue. Either a page on demand preview or ideally an interactive WYSIWYG area for the current page with synchonized zoom and positioning next to the input image would make sense.
Think of the same for other output formats, especially those maintaining the layout, like ODT.

**Comment by manisandro** [comment]
A preview mode for the editing phase makes sense and should be fairly easy. A WYSIWYG editor is very complex (since you need to syncronize the changes with the HOCR document model), and actually I think is beyond the scope of the program. If you want to edit that way, it is much easier to just export to ODT and export to PDF from there.

**Comment by manisandro** [comment]
Preview implemented for Qt

**Comment by SantosSi** [comment]
Thank you. It is sometimes difficult to see differences as an overlay, can you also make it available side by side?

**Comment by manisandro** [comment]
I can look at it at a later stage, now I don't want to do any more feature work or else I'll never be able to prepare a release. I could just increase the opacity say to 75% if that helps though.

By the way, if you spot any issues with the current codebase, testing feedback is appreciated to allow for a polished release.

**Comment by SantosSi** [comment]
Thanks, understood.
I already did test all the resolved issues I reported and also some of the others.

**Comment by manisandro** [comment]
Done also for Gtk
