### ISSUE TITLE
Error exists in coordinate translation from HOCR BBox to font size

### ISSUE THREAD

**Issue by napasa** [manisandro/gImageReader#301]
[浅论公司自治与司法介入的平衡.pdf](https://github.com/manisandro/gImageReader/files/1672530/default.pdf)
Hi, OCR this file and preview result with keeping every export option not change, you will find word size is magnified.

**Comment by manisandro** [comment]
Don't know much about Chinese, but doesn't look obviously wrong to me. Processing the PDF at 300dpi results in a font size of 10pt.
And by the way, font size detection is done by tesseract itself, not gImageReader, so there is not much I can do about it on gImageReader side I fear.

**Comment by napasa** [comment]
Hi, It seems Tessract error,  The font size is more precise if I calculate it by bbox. The size of word of same line  is alway same under libtesseract version 3.05

**Comment by manisandro** [comment]
I'd take it to tesseract upstream.

**Comment by napasa** [comment]
Snippet from HOCR export:
<span title="bbox 231 1371 279 1430; x_font Arial_Unicode_MS; x_fsize 19; x_wconf 92" class="ocrx_word" id="word_1_13" lang="zh_CN">甲</span>
<span title="bbox 226 1749 276 1800; x_font Arial_Unicode_MS; x_fsize 30; x_wconf 93" class="ocrx_word" id="word_1_23" lang="zh_CN">乙</span>

height of bbox of 甲 is 1430-1371=61, height of bbox of 乙 is 1800-1749=51, but their x_fsize is difference of 11.

**Comment by napasa** [comment]
Snippet from HOCR export:
    `     <span class="ocrx_word" title="bbox 231 1371 279 1430; x_wconf 88; x_font Arial_Unicode_MS; x_fsize 19" lang="en_US" id="word_1_19">甲</span>` 
`     <span class="ocrx_word" title="bbox 226 1749 276 1800; x_wconf 89; x_font Arial_Unicode_MS; x_fsize 19" lang="en_US" id="word_1_29">乙</span>`



height of bbox of 甲 is 1430-1371=61, height of bbox of 乙 is 1800-1749=51, but their x_fsize is difference of 11. As I know point size should equivalent to 61/300*72= 14.

**Comment by napasa** [comment]
Snippet from HOCR export:
`<span class="ocrx_word" title="bbox 231 1371 279 1430; x_wconf 88; x_font Arial_Unicode_MS; x_fsize 19" lang="en_US" id="word_1_19">甲</span>`
`<span class="ocrx_word" title="bbox 226 1749 276 1800; x_wconf 89; x_font Arial_Unicode_MS; x_fsize 19" lang="en_US" id="word_1_29">乙</span>`

height of bbox of 甲 is 1430-1371=61, height of bbox of 乙 is 1800-1749=51, but their x_fsize is difference of 11. As I know point size difference should equivalent to 10/300*72= 2.4

**Comment by napasa** [comment]
Hi, [Tesseract4](https://copr.fedorainfracloud.org/coprs/smani/tesseract4/)^_^. It has better effect
