### ISSUE TITLE
Hi, Fail to install tesseract4 package.

### ISSUE THREAD

**Issue by napasa** [manisandro/gImageReader#302]
Hi, It seems [Tess](https://copr.fedorainfracloud.org/coprs/smani/tesseract4/) is maintenanced by you.
I fail to install tesseract4.0 and dnf report error lacking of libc.so.6 as though I installed libc.so.6 in /lib64. The below are command I used and error reported.  
[root@localhost sys-root]# dnf repository-packages smani-tesseract4 install tesseract
Last metadata expiration check: 2:25:38 ago on Thu 01 Feb 2018 12:34:16 PM CST.
Error: 
 Problem: conflicting requests
  - nothing provides libc.so.6(GLIBC_2.27)(64bit) needed by tesseract-4.00-0.1.gitbc668da.fc28.x86_64

**Comment by manisandro** [comment]
Yeah rawhide is fast-moving so things need to be rebuilt fairly often. Fired off a new rebuild now.

**Comment by napasa** [comment]
Thanks.~~~~
