### ISSUE TITLE
Windows 64 bit Qt5: No icons for Image controls (main), Show confidence values (hOCR)

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#307]

**Comment by manisandro** [comment]
Looks like something is broken with the Docker build... Local build works fine.

**Comment by napasa** [comment]
fedora has similar issue

**Comment by manisandro** [comment]
Meaning the mingw build created from Fedora?

**Comment by manisandro** [comment]
Most likely same issue as #355.
