### ISSUE TITLE
Windows 64 bit Qt5. Error downloading german tessdata

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#308]
Manage languages, selected german. Error message window:
![dlgermantessdatawin](https://user-images.githubusercontent.com/31543615/35875170-b9b23744-0b6e-11e8-8683-fdd10eef2289.png)

Manually installing files and clicking Redetect languages made the languages available to the software.

**Comment by manisandro** [comment]
If you are using system-wide paths (see gImageReader config dialog) and are running the application as unpriviliged user, this is normal.

**Comment by SantosSi** [comment]
Can you provide affected users with a message about the situation and how to amend it?

**Comment by manisandro** [comment]
Done
