### ISSUE TITLE
Windows 64 bit Qt5, both PDF engines. Preview and PDF at wrong position on last input document on (7th of 7).

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#309]
This problem did not appear before with the same files, incl. older versions hOCR HTML files.
294 pages from the first 6 PDF input files are OK, but the error appears starting with the last input PDF file. Every word is positioned twice the font height lower as the one before from the same textline, looking like steps. The textline also starts lower than defined.

**Comment by manisandro** [comment]
I suppose it is the actual content of that document which matters, not whether it is first or last? If yes, can you send that document? Possibly the baseline is incorrect.

**Comment by manisandro** [comment]
Fixed (the issues was that the baselines had a comma as decimal separator)
