### ISSUE TITLE
Selecting multiple languages

### ISSUE THREAD

**Issue by porculator** [manisandro/gImageReader#31]
Very annoying thing:

1) Select several languages for OCR
2) Then select just one language from the first drop-down menu
3) If I want again to do multilingual ocr with the languages from the 1. I have first to select some language in the multilingual list to activate multilingual setting and then deselect it because I don't need this additional language

Another annoying thing is when a single language has its own sub-menu with only one thing to choose from, this should be flattened.

**Comment by manisandro** [comment]
Yes I agree this is annoying, unfortunately this is a toolkit limitation (both Qt and Gtk). You apparently cannot have a menu item with a check or radio button which has a submenu and get it to behave correctly when triggered - it will merely open or close the submenu, not toggle the radio. So with the currenty menu-based structure, this is hard to fix. Unless we split out the items: one "Multilanguage enabled" radio item, and one "Multilanguage setup" item with the language selection submenu.

**Comment by porculator** [comment]
Why not create another pane/windows, a floating one maybe,  where you can check the language you want to use?

**Comment by manisandro** [comment]
I'd really prefer to avoid extra windows floating around if possible, but I'll look at reworking the menu structure.

**Comment by manisandro** [comment]
I've added some code to make clicking on the "multilingual" item actually toggle the radio. Also, the submenu where one can select the languages now stays open after selecting a language, so one can select multiple languages without having to re-open the menu each time.
As for flattening out the single language items with just one subitem - I believe it is more consistent this way: items without subitems have no spelling dictionary associated, the other ones do. So I'd rather keep it this way.

**Comment by Beruskyfan** [comment]
On Windows 7 64bit Arabic with additional languages (multilaanguage syriac, or english) crash to desktop at 70%

**Comment by manisandro** [comment]
Please don't post to unrelated issue, but open a separate issue, and provide more information. Thanks.
