### ISSUE TITLE
Handle text and image on top of each other

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#311]
If the image is after the text in the hOCR tree, it is drawn on top of the image on PDF. Sometimes this is wanted behaviour, to keep text for searchability, but the image is so complex that it covers the text behind. It is not obvious to the user how to achieve this.

**Comment by manisandro** [comment]
So you'd want to have images always drawn behind the text?

**Comment by SantosSi** [comment]
No, I found the behaviour by testing. I created the issue to make other users known in a defined way.

**Comment by manisandro** [comment]
Ok but is there anything to specifically address here?

**Comment by SantosSi** [comment]
Can you detect the overlapping, then make it identifiable and changeable by the user?

**Comment by manisandro** [comment]
Is there actually a scenario where you want the text behind the image?

**Comment by SantosSi** [comment]
Yes, I shared my document with you through Nextcloud for issue #309 . See page 290, the image in there is too complex to be defined with separate single lines. So there is a hidden text layer behind the niveau steps to make it searchable.

**Comment by manisandro** [comment]
Ok - so I'd rather handle this by allowing to re-order the items via drag-and-drop - the idea being that what comes before gets painted before.

**Comment by manisandro** [comment]
Tracking in #438
