### ISSUE TITLE
Qt5: Do only clear hOCR when loading new document

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#313]
Procedure:

1. Click Open hOCR file
2. In the Open file dialog click cancel

The previous hOCR document disappeared, which should only be the case if a new document was really selected to be loaded.

**Comment by manisandro** [comment]
Dunno, you can see it both ways:
1. Click Open hOCR file
2. Dialog pops up: save or discard?
3. Press discard
4. In the file Open dialog, click cancel
5. Old document remains? But didn't I just tell the program to discard the changes?

And what if the new file could not be read for some reason?

I believe that the current approach is the most consistent.

**Comment by SantosSi** [comment]
You are right if the previous file was unsaved.
But here the file was saved before clicking the open button. Now if the 
new file cannot be loaded/loading was cancelled you do not return to the 
status you had before: the hOCR area is empty, but it should not.

**Comment by manisandro** [comment]
The only other consistent option is to ask whether to save/discard (if necessary) after open, but that is in my view a worse option since you potentially have a save dialog popping up after the open dialog, which is confusing.

I don't really see a better option than the status quo.

**Comment by SantosSi** [comment]
In my opinion cancelling an action should restore the situation before. You do not need to ask for save/discard in my described case, where the contents are already saved. So I suggest you keep the current behavior for unsaved and to change it when saved.

**Comment by manisandro** [comment]
I would find it pretty confusing that whether the current document is cleared before or after the open operation depends on whether the document is saved or not.

**Comment by SantosSi** [comment]
The difference is that the user is asked for clearing or not. If the asked user cancels lodaing then it is cleared as decided. If the user saves the file before loading, then cancels loading he was not asked to clear and thus should stay with the data as before.

**Comment by manisandro** [comment]
I thought about it some more, and I still am relucant to change anything. I understand your point of view, but from a codebase point of view the current approach is just much simpler, and I still see this as a marginal issue most people will never notice.

If you look at the code [1], you will see that now there is one central clear function which takes care of all the cleanup of a previous session, asking whether to save or not if necessary. Implementing the changes for this issue would require to break up this code into multiple functions or adding redundant code. If you want to give it a shot, by all means feel free and I will certainly consider your work.

[1] https://github.com/manisandro/gImageReader/blob/master/qt/src/hocr/OutputEditorHOCR.cc#L770
