### ISSUE TITLE
Automatic page layout issues

### ISSUE THREAD

**Issue by Shreeshrii** [manisandro/gImageReader#314]
I find that certain sections are not being picked up when using automatic page layout. Please see attached image.

Is this an upstream issue for tesseract?

![page-layout](https://user-images.githubusercontent.com/5095331/36214661-12a75ef8-11d0-11e8-9e57-d3fda82a3294.png)

**Comment by manisandro** [comment]
Yep, gImageReader relies on tesseract for page layout analysis, the only thing it does is filtering out areas which are less than 10x10 pixels to clean up the result. See [1].

[1] https://github.com/manisandro/gImageReader/blob/master/qt/src/DisplayerToolSelect.cc#L155
