### ISSUE TITLE
gImageReader crashes without error/exception/log when performing ocr on png

### ISSUE THREAD

**Issue by dominikandreas** [manisandro/gImageReader#317]
**Description**
- gImageReader GUI crashes when performing ocr recognition on a single particular png file

**Affected Versions**
- 3.1.2, 3.2.3 were tested, both were affected. No other versions tested

**Remedy**
- Converting the png file to jpg solves the problem in this case

**Replication**
- Load this image in gImageReader, perform ocr with default settings: https://ibb.co/krsc0n

No logs are created or error messages shown, GUI just disappears.

**Comment by manisandro** [comment]
What platform are you using?

**Comment by dominikandreas** [comment]
Sorry, forgot to mention that. Windows 10 64 bit

**Comment by manisandro** [comment]
Can you try with the following fairly recent development build: https://smani.fedorapeople.org/tmp/gImageReader_3.2.3_qt5_x86_64.exe

**Comment by dominikandreas** [comment]
Same result, crashes without any error message

**Comment by manisandro** [comment]
Ok managed to reproduce in hOCR mode - looks like a tesseract bug it errors out with 

    start >= 0 && start + num <= length_:Error:Assert failed:in file ratngs.cpp, line 321

Unfortunately tesseract raises deliberate SIGSEGVs when it encounters an error, which make it very hard for the application to catch and show a friendly error message.

**Comment by dominikandreas** [comment]
Ok, thanks for the investigation. Maybe this issue should then be moved to the tesseract repository.
