### ISSUE TITLE
there's no Chinese(Simp) language dictionaries - zh_CN, can't OCR chinese words.

### ISSUE THREAD

**Issue by nide312** [manisandro/gImageReader#318]
here:
https://cgit.freedesktop.org/libreoffice/dictionaries/tree/

**Comment by nide312** [comment]
here:
https://cgit.freedesktop.org/libreoffice/dictionaries/tree/

**Comment by manisandro** [comment]
For OCRing the tesseract traineddata is relevant, not the spelling dictionary. Latter is only relevant for spell-checking the OCR result.
In any event, this is not a gImageReader issue.
