### ISSUE TITLE
"Strip line breaks" suggestions...

### ISSUE THREAD

**Issue by ferdnyc** [manisandro/gImageReader#32]
An _exceedingly_ minor suggestion regarding option labeling.

The "strip line breaks..." options menu currently looks like this, in the top section:
Strip line breaks in selected text
--------------------------
Keep line breaks if...
- [ ] Preceded by dot
- [ ] Preceded or succeeded by quote

I would suggest changing the label on the first to "Preceded by period", which is a better description of its function. Especially with whitespace characters being drawn as _actual_ gray **dots**, when "Draw whitespace" is enabled, "dot" is a confusing way to refer to a period character.

----

Actually, as a separate enhancement suggestion, it might be better to change the label to "Preceded by end of sentence", and add other sentence-terminating punctuation like ? and ! to the list. Currently, a sentence ending in a period will cause the line break to be preserved, but non-period-terminated sentences at the end of lines will be combined. It seems like we'd want to leave line breaks alone equally, whether the line ends with any of `.?!`

...In that same vein, whitespace characters following the period at the end of a line will trip up the combining logic, so a line that ends with ...`some words.<space><space>` will be combined with the next, even if "Keep line breaks if preceded by dot" is enabled. I wonder if the line-ending-character determination shouldn't trim off whitespace first, and consider only the last _non_-whitespace character?

**Comment by manisandro** [comment]
Thanks for suggestions, I'll look into these.

**Comment by manisandro** [comment]
Ok this should be done.
