### ISSUE TITLE
Spanish translation not applied to the interface

### ISSUE THREAD

**Issue by micrococo** [manisandro/gImageReader#321]
Hi.

gImageReader is in English despite the Spanish (es_ES) translation is available. If I copy `/usr/local/share/locale/es_ES/LC_MESSAGES/gimagereader.mo` to `/usr/local/share/locale/es/LC_MESSAGES/gimagereader.mo`, then it is used.

```
$ locale
LANG=es_ES.UTF-8
LC_CTYPE="es_ES.UTF-8"
LC_NUMERIC="es_ES.UTF-8"
LC_TIME="es_ES.UTF-8"
LC_COLLATE="es_ES.UTF-8"
LC_MONETARY="es_ES.UTF-8"
LC_MESSAGES="es_ES.UTF-8"
LC_PAPER="es_ES.UTF-8"
LC_NAME="es_ES.UTF-8"
LC_ADDRESS="es_ES.UTF-8"
LC_TELEPHONE="es_ES.UTF-8"
LC_MEASUREMENT="es_ES.UTF-8"
LC_IDENTIFICATION="es_ES.UTF-8"
LC_ALL=
```
I didn't report this before because I thought that it could be caused due an incomplete translation.

Greetings.

**Comment by manisandro** [comment]
What distro are you on? On Fedora, I need to install `glibc-langpack-es`, then it works.

**Comment by micrococo** [comment]
Sorry, there must be something wrong here (openSUSE Tumbleweed btw). I have just built gImageReader in a Tumbleweed virtual machine and it works as expected. I'll compare the package list in both installations to see what's missing. There is no `glibc-langpack-es` but there are `glibc-locale` and `glibc-i18ndata`. The latest wasn't installed but installing it makes no difference.

I don't know if this is an issue, but when gImageReader is installed in `/usr/local`, it outputs: 
```
Failed to open /usr/local/share/xml/iso-codes/iso_639.xml for reading
Failed to open /usr/local/share/xml/iso-codes/iso_3166.xml for reading
```
but those files exists in `/usr/share/xml/iso-codes`. Shouldn't gImageReader be able to find them in the system path? Permissions look right.

**Comment by micrococo** [comment]
I've found the problem was the `$LANGUAGE` environment variable. Its value and the value of `$LANG` doesn't match:
```
$ echo $LANG
es_ES.UTF-8
$ echo $LANGUAGE
es:en_GB:en_US
```
`unset $LANGUAGE` fixes the issue. It may be set by Plasma desktop. Sorry for the noise.

**Comment by manisandro** [comment]
Concerning the iso-codes, it depends how qtspell was compiled, see [1].

Anyway good that you found the problem!

[1] https://github.com/manisandro/qtspell/blob/master/CMakeLists.txt#L18
