### ISSUE TITLE
error installing from ppa on trusty

### ISSUE THREAD

**Issue by Shreeshrii** [manisandro/gImageReader#322]
```
sanskrit@sanskrit:~$ sudo apt-get install gimagereader-gtk
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  gimagereader-common liblept4 libtesseract3
The following NEW packages will be installed:
  gimagereader-common gimagereader-gtk liblept4 libtesseract3
0 upgraded, 4 newly installed, 0 to remove and 228 not upgraded.
Need to get 0 B/2,251 kB of archives.
After this operation, 6,975 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Selecting previously unselected package gimagereader-common.
(Reading database ... 1441327 files and directories currently installed.)
Preparing to unpack .../gimagereader-common_3.2.3-1~trustyppa1_all.deb ...
Unpacking gimagereader-common (3.2.3-1~trustyppa1) ...
Selecting previously unselected package liblept4.
Preparing to unpack .../liblept4_1.70.1-1_amd64.deb ...
Unpacking liblept4 (1.70.1-1) ...
Selecting previously unselected package libtesseract3.
Preparing to unpack .../libtesseract3_3.03.02-3_amd64.deb ...
Unpacking libtesseract3 (3.03.02-3) ...
Selecting previously unselected package gimagereader-gtk.
Preparing to unpack .../gimagereader-gtk_3.2.3-1~trustyppa1_amd64.deb ...
Unpacking gimagereader-gtk (3.2.3-1~trustyppa1) ...
Processing triggers for hicolor-icon-theme (0.13-1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu1.1) ...
Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
Processing triggers for bamfdaemon (0.5.1+14.04.20140409-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.54ubuntu1.1) ...
Processing triggers for libglib2.0-0:amd64 (2.40.2-0ubuntu1) ...
Setting up gimagereader-common (3.2.3-1~trustyppa1) ...
Setting up liblept4 (1.70.1-1) ...
Setting up libtesseract3 (3.03.02-3) ...
Setting up gimagereader-gtk (3.2.3-1~trustyppa1) ...
Processing triggers for libc-bin (2.19-0ubuntu6.13) ...
sanskrit@sanskrit:~$ sudo apt-get install gimagereader
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gimagereader : Depends: gimagereader-gtk but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
sanskrit@sanskrit:~$

```

**Comment by Shreeshrii** [comment]
gimagereader-gtk  installs ok, but gimagereader complains of unmet dependencies.

FYI, I have newer versions of tesseract and leptonica installed from
https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr

**Comment by manisandro** [comment]
Uhm not following. `gimagerader` is typically the stock ubuntu package [1], though only available for xenial onwards, whereas `gimagereader-gtk` is most likely the package from my PPA.

And also, you can't generally expect to be able to install different version of dependencies and have depending programs just work. If these dependencies carry changes in the binary interface, the depending program needs to be rebuilt (on a package level, you will get dependency errors due to changes in the soname of dependent libraries).

[1] https://packages.ubuntu.com/search?keywords=gimagereader

**Comment by Shreeshrii** [comment]
Yesterday I saw as  part of the latest release comment ...

'Binary packages for Linux are available for Ubuntu in the gImageReader-devel PPA and for Fedora in this COPR repository.'

Hence I added your ppa and then tried to install gimagereader. It gave error regarding gimagereader-gtk. So I tried to install gimagereader-gtk. That installed ok. However, trying to install gimagereader again gave same error. I tried a couple of times, by doing apt-get remove, apt-get purge, autoremove etc

The second comment was only FYI, that I have tesseract 4.0.0-beta.1 installed using Alex's PPA.

**Comment by manisandro** [comment]
Ok, but my PPA only ships `gimagereader-gtk` resp. `gimagereader-qt`. The `gimagereader` package comes from another source.

And the tesseract from the PPA may well be what is causing the conflicts.

**Comment by Shreeshrii** [comment]
Ok, so that must be the problem. I did not check the package name in your PPA and tried to install gimagereader.

Thanks, will try again and report.

**Comment by Shreeshrii** [comment]
I checked just now, https://launchpad.net/~sandromani/+archive/ubuntu/gimagereader-devel shows the package as gimagereader only.

Is that the wrong repo?

**Comment by manisandro** [comment]
The source package is called `gimagereader`, the binary packages built from that source are `gimagereader-gtk` and `gimagereader-qt`, see [1] and expand an entry to see "Built packages".

[1] https://launchpad.net/~sandromani/+archive/ubuntu/gimagereader-devel/+packages

**Comment by Shreeshrii** [comment]
Thanks for your patience in explaining. I see it now:

Built packages
gimagereader-common Common files for gimagereader
gimagereader-dbg Debugging symbols for gimagereader
gimagereader-gtk A graphical frontend to tesseract-ocr
gimagereader-qt A graphical frontend to tesseract-ocr

But I don't see the ppa for trusty any more.

Source | Published | Status | Series | Section | Build Status
-- | -- | -- | -- | -- | --
gimagereader - 3.2.99-2~xenialppa1 | (changes file) | 2018-02-25 | Published | Xenial | Graphics | amd64 i386
gimagereader - 3.2.99-1~bionicppa1 | (changes file) | 2018-02-24 | Published | Bionic | Graphics |  
gimagereader - 3.2.99-1~artfulppa1 | (changes file) | 2018-02-24 | Published | Artful | Graphics |  
gtkspell3 - 3.0.9-1~xenialppa1

**Comment by manisandro** [comment]
Yes, I didn't build 3.2.99 for trusty, since some dependencies shipped by that release are just too old.

**Comment by Shreeshrii** [comment]
Thanks! Closing the issue.
