### ISSUE TITLE
Some texts not showing translated text.

### ISSUE THREAD

**Issue by Pablohn26** [manisandro/gImageReader#324]
It seems "Manage languages" text tools options is not showing [translated text](https://hosted.weblate.org/translate/gimagereader/translations/es/?checksum=2ea12d4ea940beef) when default GUI language is Spanish (I have not tested it with other languages).

![consejo emergente_00427](https://user-images.githubusercontent.com/1228418/37570702-61472d7c-2af3-11e8-8f10-47841b57536c.png)

**Comment by manisandro** [comment]
Is this with a fresh git master build?

**Comment by manisandro** [comment]
The spanish translation was updated post 3.2.99, so this is expected. You can either manually compile the latest git master, or wait for 3.3.0.

**Comment by Pablohn26** [comment]
Ok, I will wait for 3.3.0 version. 
I left here another non translated strings to double check in the future. 
![seleccion_00438](https://user-images.githubusercontent.com/1228418/37571966-67d5965e-2b04-11e8-98f8-cef4aeb89728.png)

I also have finished Spanish translation, so I hope this issue will never happen again.

**Comment by manisandro** [comment]
Well translation is a continuous catch up game, as new features get added to the program, new translatable strings will get added, and someone needs to translate these. So it will most definitely happen again. But the point of 3.2.99 (which is marked as pre-release) is exactely to give users the chance to complete the translations before a new stable release.
