### ISSUE TITLE
Adding french language

### ISSUE THREAD

**Issue by yanis60** [manisandro/gImageReader#327]
Hi,

I see your project and it's a very good application, i love it.
I want to embed it to my ERP software but it doesn't have french gui language, so can i add this language to your project?

Regards

**Comment by manisandro** [comment]
Hi
There already is a french translation which is currently ca 80% complete, you can finish it at [1].

[1] https://hosted.weblate.org/languages/fr/gimagereader/

**Comment by yanis60** [comment]
ok thank you i didn't see it.
