### ISSUE TITLE
gimagereader-qt5.exe - Ordinal Not Found

### ISSUE THREAD

**Issue by mawekuwe** [manisandro/gImageReader#33]
Hi, thanks for the software. 
I installed `gImageReader_3.1.2_qt5_x86_64.exe` and getting the following error at launch:

```
---------------------------
gimagereader-qt5.exe - Ordinal Not Found
---------------------------
The ordinal 3873 not found in dynamic link library libeay32.dll.
---------------------------
OK
---------------------------
```

**Comment by manisandro** [comment]
Hi,
This is a library conflict - there is a library probably below `C:\Windows` which is taking precedence one of the bundled libraries in `%ProgramFiles%\gImageReader\bin`. Please download dependency walker at `http://www.dependencywalker.com/`, open the `gImageReader-qt5.exe` executable, and it should report you which dll is causing the error. Non-system-wide libraries should not be installed be installed below the Windows directory, so this is a bug with the application that did so.

**Comment by mawekuwe** [comment]
Thanks for the quick answer.

here the errors with DW:

```
Error: At least one module has an unresolved import due to a missing export function in an implicitly dependent module.
Error: Modules with different CPU types were found.
Warning: At least one delay-load dependency module was not found.
Warning: At least one module has an unresolved import due to a missing export function in a delay-load dependent module.
```
This is no longer relevant at the moment because I thought gImageReader had the opportunity to convert a PDF file from scanned images in PDF selectable text format. Sorry for the inconvenience and thank you.
