### ISSUE TITLE
the GTK and Qt packages are indistinguishable in KDE Discover Software Center

### ISSUE THREAD

**Issue by skierpage** [manisandro/gImageReader#332]
When I searched for OCR in the Discover "app store" in Fedora 28 beta KDE spin, the first two results were both gImageReader. Same description (A graphical frontend to tesseract-ocr), also same category, version (3.2.99-1.fc28), source (Fedora), license, and homepage. But different sizes, different screenshot, one has 6 reviews and the other none.

I instead used the command-line `dnf search gimagereader` which reported
> gimagereader-qt.x86_64 : A Qt front-end to tesseract-ocr
> gimagereader-gtk.x86_64 : A Gtk+ front-end to tesseract-ocr

I want the Qt version but it's impossible for a non-UI-expert to tell which is which from the screenshot.

The file packaging/gimagereader.spec.in distinguishes the two toolkit versions, but I think app stores use an appdata file. The file data/gimagereader.appdata.xml.in references a toolkit-dependent `gimagereader-@INTERFACE_TYPE@.jpg`, so maybe the summary and description could branch or do something like
```xml
<description>
<p>gImageReader is a simple optical character recognition (OCR) application 
  using the @INTERFACE_TYPE@ toolkit which acts as a front-end ...
```

(The program works well, thanks!)

**Comment by manisandro** [comment]
Good point, fixed.
