### ISSUE TITLE
Error cross-compiling for Windows through Docker

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#333]
On Debian Testing:
$ docker build -t gimagereader_buildenv packaging/win32
$ docker run -v $PWD:/workspace gimagereader_buildenv packaging/win32/makeinstaller.sh x86_64 qt5
-- GSettings schemas will be installed locally.
-- GSettings shemas will be compiled.
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!

[CMakeOutput.log](https://github.com/manisandro/gImageReader/files/1891510/CMakeOutput.log)

On Ubuntu 17.10, the process complains about missing intltool.

**Comment by manisandro** [comment]
Ah yes indeed, the dependeny was added in d57aabf6efbee1e6ff531a1ef9de2dd15c22de but the Dockerfile was not updated. Fixed.

**Comment by SantosSi** [comment]
The Docker image is successfully updated, but the error above persists on Debian while cross compiling.

**Comment by manisandro** [comment]
Should be addressed by 93470539d3a5417593b69494041bac9be9c14584

**Comment by SantosSi** [comment]
Strange: The problem disappeared on my Debian system with a completely 
new Docker image, but it persists on Ubuntu. On Ubuntu I updated the 
Fedora image before retrying. This is the end of the Docker image 
creation output before it stops:
================================================================================
  Package                       Arch        Version           Repository  
   Size
================================================================================
Installing:
  dnf-plugins-core              noarch      2.1.5-4.fc28      rawhide     
   51 k
Installing dependencies:
  python3-dnf-plugins-core      noarch      2.1.5-4.fc28      rawhide     
  141 k

Transaction Summary
================================================================================
Install  2 Packages

Total download size: 192 k
Installed size: 387 k
Downloading Packages:
(1/2): dnf-plugins-core-2.1.5-4.fc28.noarch.rpm 276 kB/s |  51 kB     
00:00
(2/2): python3-dnf-plugins-core-2.1.5-4.fc28.no 587 kB/s | 141 kB     
00:00
--------------------------------------------------------------------------------
Total                                           482 kB/s | 192 kB     
00:00
warning: 
/var/cache/dnf/rawhide-2d95c80a1fa0a67d/packages/dnf-plugins-core-2.1.5-4.fc28.noarch.rpm: 
Header V3 RSA/SHA256 Signature, key ID 429476b4: NOKEY
Importing GPG key 0x9DB62FB1:
  Userid     : "Fedora 28 (28) <fedora-28@fedoraproject.org>"
  Fingerprint: 128C F232 A937 1991 C8A6 5695 E08E 7E62 9DB6 2FB1
  From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-28-x86_64
Key imported successfully
Import of key(s) didn't help, wrong key(s)?
Public key for dnf-plugins-core-2.1.5-4.fc28.noarch.rpm is not 
installed. Failing package is: dnf-plugins-core-2.1.5-4.fc28.noarch
  GPG Keys are configured as: 
file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-28-x86_64
Public key for python3-dnf-plugins-core-2.1.5-4.fc28.noarch.rpm is not 
installed. Failing package is: 
python3-dnf-plugins-core-2.1.5-4.fc28.noarch
  GPG Keys are configured as: 
file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-28-x86_64
The downloaded packages were saved in cache until the next successful 
transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED
The command '/bin/sh -c echo all > /etc/rpm/macros.image-language-conf 
&& dnf install -y 'dnf-command(config-manager)' && dnf config-manager 
--add-repo 
https://copr.fedorainfracloud.org/coprs/smani/mingw-extras/repo/fedora-rawhide/smani-mingw-extras-fedora-rawhide.repo 
&& dnf install -y   cmake   make   iso-codes   findutils   gettext   
intltool   hunspell-en   tesseract   mingw32-nsis     mingw32-gdb   
mingw32-gcc-c++   mingw32-dlfcn   mingw32-djvulibre   mingw32-libgomp   
mingw32-libjpeg-turbo   mingw32-podofo   mingw32-poppler-qt5   
mingw32-qt5-qtbase   mingw32-qt5-qtimageformats   mingw32-qt5-qttools   
mingw32-qt5-qttranslations   mingw32-qtspell-qt5   mingw32-tesseract   
mingw32-twaindsm   mingw32-quazip-qt5     mingw64-gdb   mingw64-gcc-c++  
  mingw64-dlfcn   mingw64-djvulibre   mingw64-libgomp   
mingw64-libjpeg-turbo   mingw64-podofo   mingw64-poppler-qt5   
mingw64-qt5-qtbase   mingw64-qt5-qtimageformats   mingw64-qt5-qttools   
mingw64-qt5-qttranslations   mingw64-qtspell-qt5   mingw64-tesseract   
mingw64-twaindsm   mingw64-quazip-qt5' returned a non-zero code: 1

**Comment by SantosSi** [comment]
Got it: removing the exisiting Fedora and also the gimagereader_buildenv 
container did the trick. This could also happen to other users, so maybe 
you know a solution?

**Comment by manisandro** [comment]
Not really, when I encounter trouble I also just ensure all previous containers / images are cleared and start over...
