### ISSUE TITLE
Add tab support for text in columns

### ISSUE THREAD

**Issue by skierpage** [manisandro/gImageReader#334]
I've scanned the pages of a tabular report like a credit card or bank statement, where most of each page is text in well-defined columns. gImageReader does a good job of recognizing the text, but in plain text OCR mode it loses the position information. Widely separated text like
```
column A                     col B
```
is output as  `column A col B` with a single space.

It would be nice to have a "plain text with tabs" mode where any wide gap becomes a tab. You could even drag tab lines into layout region, such that whenever a line of text crosses the tab line, a tab appears in the output file.

A workaround is to manually draw each column as a separate layout region, scan as text, then use a utility like paste(1) to join their contents line-by-line with tabs. But gImageReader seems prone to add or lose line breaks, so the lines of text in regions would get misaligned. There could be an option in gImageReader to save numbered regions as an .ods spreadsheet, in which the text in layout region _N_ appears in column _N_.

(I tried the hOCR mode saved as an .odt file and each line of text becomes a frame, which doesn't really help.)

See also issue #221 , that could also work well for tabular reports.

**Comment by manisandro** [comment]
Doesn't page layout detection recognize the columns as separate text blocks?

In any event this needs to be handled on the tesseract side, gImageReader doesn't implement any OCR logic itself, it is all handled by tesseract.
