### ISSUE TITLE
Feature Request: macOS or MacPorts version

### ISSUE THREAD

**Issue by f1yankees** [manisandro/gImageReader#336]
First, thanks for a really great program.  This is exactly what I was looking for to make tesseract-ocr easier to use and it is well done!  

Is there any chance you could do a mac release?  Or at least setup the source in [MacPorts](https://www.macports.org)?  I had to run it on a Debian VM to use it - would be to great skip that step going forward.  I'm not a programmer but let me know if I could help.

Thanks!

**Comment by manisandro** [comment]
I don't own a mac, and you can't even run a virtualized macOS, so I have to way to work on it. Unless someone on macOS steps up, I fear that there will be no macOS release.

**Comment by bmwmy** [comment]
I have a virtual mac os running on vmware pro or player which is free.
You have to patch binaries of vmware with unlocker (patch to support mac os) 
Helpful link: http://www.tactig.com/install-macos-sierra-on-vmware/

**Comment by manisandro** [comment]
I don't really have time to pursue this, if you want to give it a shot I'm happy to answer questions about issues with the code/required dependencies/etc.

**Comment by DragonSerW** [comment]
+1 here! Your application is simply great, but Apple users use to pay money for A??YY's shareware product! ((
