### ISSUE TITLE
Feature Request: Allow multiple images to be recognized as separate files

### ISSUE THREAD

**Issue by Shreeshrii** [manisandro/gImageReader#337]
>If multiple images are selected, the program will treat the set of images as multipage document.

While the above works well for recognizing multiple images representing pages in a document or book, there is another case when a user may want to recognize a batch of unrelated images to separate text files.

Request an option to allow selection of multiple images to be recognized individually to separate files.

Thanks.

**Comment by manisandro** [comment]
So you basically want, for each selected file, to run OCR and produce a separate output file (txt or hocr/pdf)? Entirely skipping the post-processing possibility for the individual outputs? Sounds like a duplicate of #103?

**Comment by Shreeshrii** [comment]
Thanks. Yes, looks like this is a duplicate of an earlier issue. Closing this.

You did mention elsewhere that the OCRed output can be loaded after the fact for editing, right?

**Comment by manisandro** [comment]
Sure, in both the plain text and hocr output panes you can load existing files.
