### ISSUE TITLE
multilanguage (arabic+additional languages) crash to desktop at 70%

### ISSUE THREAD

**Issue by Beruskyfan** [manisandro/gImageReader#340]
On Windows 7 64bit Arabic with additional languages (multilaanguage syriac, or english) crash to desktop at 70% on version 3.2.2-3.2.99 (I didn't check other versions) - on single page.jpg

**Comment by manisandro** [comment]
Does the crash handler show up? Can you post the stacktrace shown in the crash handler dialog?

If it happens while recognizing: might be that you are using incompatible traineddata files.

**Comment by Beruskyfan** [comment]
yes crash handler show up at 70%. Massage in polish: The gimagereader-qt5.exe program has stopped working. The program has stopped working correctly due to the occurrence problem. Windows will close the program and notify you if there is an available solution.

a single language recognizes in version 3.2.2 - downloaded via program "manage language"

**Comment by manisandro** [comment]
Does re-downloading the traineddata files via the integrated tessdata manager help? Are you using the tesseract4 version?

**Comment by Beruskyfan** [comment]
I use gImageReader_3.2.99_qt5_x86_64.exe - sorry for previous massage: crash handler doesn't showup - only show up massage in polish "The gimagereader-qt5.exe program has stopped working..." - re-downloading via manager didn't help -  program stops working at 70%. [arabic file traineddata is incorrect for multilang but other languages with modificated arabic script work fine in multilanguage]

**Comment by manisandro** [comment]
Please try again with 3.3.0 and re-open if the issue persists.

**Comment by Beruskyfan** [comment]
Thank you so much. The new version works perfectly. Syriac text (multilanguage) recognizes better than Arabic - and with vowels - I am very happy. Great job - thanks, thanks, thanks
