### ISSUE TITLE
non-Western-character poppler font issue

### ISSUE THREAD

**Issue by napasa** [manisandro/gImageReader#343]
after read up makeinstaller.sh I found that you don`t add popper-data to win distribution, As result I tested, poppler::page::renderToImage will render non-Western-character into  blank blocks. so as code the poppler wrote, we should add popper-data to share dir. But here seems have some License issue?
https://cgit.freedesktop.org/poppler/poppler/tree/poppler/GlobalParams.cc

**Comment by manisandro** [comment]
Good point, I'll look into it!

**Comment by manisandro** [comment]
Addressed in #347
