### ISSUE TITLE
Windows  gImageReader Version is three times slower  than that of linux

### ISSUE THREAD

**Issue by napasa** [manisandro/gImageReader#345]
Thank you for your dedication. I learned a lot about cross platform knowledge. I ran into a strange problem. I compiled the Windows version of Tesseract with mingw32-cmake, compiled the Linux version with cmake, and the code was the latest code from clone on GitHub. But the speed of gImageReader under Windows is three times slower than that of Linux, and I don't know why. I spent two days trying to solve it, but I still don't know why.

**Comment by manisandro** [comment]
I never really specifically tuned the flags when compiling tesseract for windows. There were some other reports in the other ticket (https://github.com/manisandro/gImageReader/issues/285) of slowdowns, if none of the workarounds there help, I'd ask upstream for ideas.
