### ISSUE TITLE
Hi, Some type non-Western-character do not need keep space between words

### ISSUE THREAD

**Issue by napasa** [manisandro/gImageReader#346]
Hi, Some type non-Western-character do not need keep space between words.  for consider circumstance like this,we should add a mechanism to check whether we should puls word x coor calculated out  with a extra spacing  width . 
for eaxmple. 
English: Hello world!
Chinese:你好世界！

x += painter.getTextWidth(text + " ") / px2pu;
code snippet quote from src/hocr/HOCRPdfExporter.cc, line 717

**Comment by manisandro** [comment]
Any ideas how such a mechanism could look like?

**Comment by napasa** [comment]
I try it. ^_^.

**Comment by napasa** [comment]
https://src.chromium.org/viewvc/chrome/trunk/src/third_party/cld/languages/internal/
How about this, the CLD (Compact Language Detection) library.

**Comment by manisandro** [comment]
Well detecting the language is not that much of a problem per se, typically recognition language chosen by the user will match the actual text language. What needs to be defined are the rules when to add spaces and when not.

**Comment by napasa** [comment]
We need a blackboard to call on people to write that whether their language need to add spaces. 

Sometimes，Especially in non western countries, we often encounter Western characters in our paper  , so I suggest that when we draw each word, we can let users open the language detection plug-in.

**Comment by manisandro** [comment]
If you do a multilingual recognition, tesseract will detect the language and will write i in the lang attribute of the corresponding element of the hOCR document.

**Comment by napasa** [comment]
It seems not tell what language is when I use choose single Chinese recognition.
<span title="bbox 1434 2311 1566 2344; x_fsize 10; x_wconf 56" class="ocrx_word" id="word_1_117" lang="zh_CN">AAAN</span>

**Comment by manisandro** [comment]
Following up in the pull request #351

**Comment by napasa** [comment]
I reset my commit. so pls change pull request of following up to [#353](https://github.com/manisandro/gImageReader/pull/353)
