### ISSUE TITLE
Add ability to recognize text on multiple files

### ISSUE THREAD

**Issue by stewx** [manisandro/gImageReader#35]
It would be great if you could select multiple files in the "Sources" pane and recognize text from all of them with one click. I have a bunch of files right now and the only way to do it (as far as I know) is to go through one by one.

**Comment by manisandro** [comment]
Yes this is a good point. I've already thought a bit about this. I envision to allow the user to group images in the sources list, and then the user can operate on an entire group similarly to how one currently operates on a multipage PDF.

**Comment by manisandro** [comment]
Implemented this by just allowing the user to select multiple sources at once in the sources pane. Then one can recognize them at once as one already could with multiple-page PDFs.

**Comment by stewx** [comment]
Thank you! This will save me lots of time.

**Comment by manisandro** [comment]
Oh, would be nice if you could do some testing. Are you comfortable compiling? Otherwise, what platform are you on?

**Comment by stewx** [comment]
I'm on Windows. What is the make command?

**Comment by manisandro** [comment]
I currently cross-compile the Windows binaries from Linux, setting up a Windows build environment is quite some work... I'll fire up some builds an then post them.

**Comment by stewx** [comment]
I can compile on Linux too if you want

**Comment by manisandro** [comment]
As you prefer, for me building for Windows is just running a shell script.

**Comment by manisandro** [comment]
Windows build is here:
http://smani.fedorapeople.org/tmp/gImageReader_3.2.0_qt5_x86_64.exe

**Comment by stewx** [comment]
Works great. Thanks!

**Comment by stewx** [comment]
As a bit of feedback, it might be better, when a user has multiple pages selected and clicks "Recognize all", to simply display a dialog box that says "Do you want to recognize text on all 63 pages?" with "Yes" and "No" buttons. I found the prompt a little confusing.

**Comment by manisandro** [comment]
Thanks for testing! Do you mean the menu that appears which allows to choose between "Current Page" and "Multiple Pages"? That distinction is kinda necessary when you have a multipage PDF where you cannot select one single page. In the case of multiple selected images, this may be somewhat redundant, but on the other hand it keeps the behavior consistent. But what I could do is add an "All Pages" option, and possibly rename "Multiple pages..." to something like "Choose pages...".
