### ISSUE TITLE
Updating the Ubuntu PPA

### ISSUE THREAD

**Issue by Yuri-M-Dias** [manisandro/gImageReader#359]
Hello and thanks for the awesome software!
I've used it before, but the ubuntu ppa hasn't been updated in some time, and I can't install it via pap on the latest ubuntu 18.04 Bionic Beaver.
Could someone look into this? I'd be willing to help if necessary too.

**Comment by manisandro** [comment]
I was meaning to follow up pretty quickly with a 3.3.0 release after 3.3.0-beta, but then tesseract 4.0.0-beta came along which required some non trivial changes to the tessdata handling, hence things stalled a bit. (Actually I think things should be in a pretty good state now, so in theory I could head for a release pretty soon, but at the moment I don't have the time to do any thorough testing.).

In any event, the 3.3.0-beta release is built in the -devel ppa:
https://launchpad.net/~sandromani/+archive/ubuntu/gimagereader-devel

I hope that I'll manage to finally push out the 3.3.0 release in the coming weeks, and then it will also get built in the regular PPA.

**Comment by manisandro** [comment]
PPA is updated with 3.3.0 release
