### ISSUE TITLE
Spellcheck intelligently around unspaced em dashes

### ISSUE THREAD

**Issue by foghawk** [manisandro/gImageReader#362]
Many documents use the "word—word" convention for typesetting em dashes. Currently, gImageReader (at least in the Qt interface) interprets this as a single word, tries to spellcheck it as such, and inevitably fails, resulting in false-positive flags even when both words are correct.

I haven't tried to implement this yet because I'm uncertain about the details. Just suppressing the false positives would be simple enough, but how to handle suggestions? What to display if one word is valid and one is not? (Just splitting them would work in plain text mode, but doesn't seem realistic for hOCR.)

**Comment by manisandro** [comment]
If it is about one single word node containing em dashes which should remain one single word node, I believe this should be handled at spell-checker level. The components involved are

gImageReader (application) -> QtSpell (Qt wrapper for enchant) -> Enchant (abstraction library for various spelling providers) -> Hunspell/MySpell (typically used spelling provider)

I suppose ideally this should be done at the spelling provider level, but it could also be done at QtSpell level, by splitting the text at em dashes, checking the individual words, and then re-assembling the respective suggestions if necessary.

**Comment by manisandro** [comment]
Closing since out of scope for gImageReader (but rather something to do at spell checker level).

**Comment by foghawk** [comment]
The Enchant API only exposes checking for individual words; applications have to do their tokenization at a higher level, possibly through a wrapper such as pyenchant. (Some of the providers have their own tokenizers, but through Enchant it seems a moot point, and although they differ on treating things like hyphens in supplied words, I don't think any do or should dismantle dashes.)

I was going to suggest that QtSpell handle it, since it doesn't tokenize words around em dashes correctly in text fields anyway, but having actually looked at it that's quite unfair: `QTTextEngine`'s own `atWordSeparator` doesn't recognize the em dash, and it should. I'll file a bug with them.

That said, that still leaves `HOCRItem` word-splitting in the hands of either gImageReader or QtSpell. gIR already does some such trimming, whereas QtSpell is fairly transparent to Enchant; reassembling suggestions could get awkward either way. (More awkward than actually splitting the word nodes and fiddling with the spacing for plaintext/ODT exports? Probably not; the PDF positioning would get iffy.)

Thoughts on that, or maybe something I've missed? Sorry, I should have gotten back to you on this more promptly.

**Comment by manisandro** [comment]
Having it in QtSpell would catch all uses in one central place, instead of having to implement it separately in text and hOCR mode in gImageReader. Reassembling suggestions should more or less work, since they are two distinct words in any case? Or am I missing something?

**Comment by foghawk** [comment]
If Qt adds dashes to its word separator list, that will fix QtSpell's (and hence gIR's) text mode without any action on your part; it should happen anyway since it also affects the vanilla QTextEdit, e.g. for double-click select and ctrl+arrow navigation.

Only hOCR mode would then need to be fixed (since it preserves tesseract's word boundaries rather than working with Qt's), so only one implementation is necessary.

Reassembling suggestions will work, it's just a bit gross. I guess there's no way around it, though.

**Comment by foghawk** [comment]
hOCR implementation in #379 (Qt bug report over at [their tracker](https://bugreports.qt.io/browse/QTBUG-70834)).
