### ISSUE TITLE
[Feature request] Allow hiding of words by confidence score

### ISSUE THREAD

**Issue by talentoscope** [manisandro/gImageReader#363]
Slightly different to issue #175 so have created another issue.

Rather than sorting confidences which would be a nightmare with a tree structure, can a feature be added to F3 through words that are below a certain user-defined threshold? This will help greatly with proofing.

This option could be added to the selection dropdown as in the image below

![image](https://user-images.githubusercontent.com/22162766/44948023-35315200-ae0e-11e8-90ac-0b91efee15aa.png)

Keep up the great work!

**Comment by talentoscope** [comment]
Updated the title to be more representative of the feature requested.
If I could code in C++, I'd add this in. To my mind it's a relatively simple addition to add the x_wconf < VALUE as another F3 function. Would be great if anyone out there could add this as it would be very helpful for hOCR - and in general - to correct the output pretty quickly.

**Comment by manisandro** [comment]
Sorry for the late reply. I'm pretty busy at the moment, but I'll perhaps I'll manage to give it a shot soonish.

**Comment by manisandro** [comment]
@ZaMaZaN4iK Just severe lack of time to properly test my tesseract-4.x changes

**Comment by manisandro** [comment]
Tracking in #438
