### ISSUE TITLE
[Qt] hOCR PoDoFo export to overlay PDF with JPEG compression crashes

### ISSUE THREAD

**Issue by foghawk** [manisandro/gImageReader#369]
Backtrace [attached](https://github.com/manisandro/gImageReader/files/2377048/bt.txt) (though not very illustrative).

I've narrowed this down to the `PdfObject::GetDictionary()` call in [line 268 of HOCRPdfExporter](https://github.com/manisandro/gImageReader/blob/master/qt/src/hocr/HOCRPdfExporter.cc#L268), which fails even though the PdfObject pointer is _not_ null.

Based on the PoDoFo headers, that makes it seem like either a recursive delayed load or a non-dictionary data type on the object, but I would need to do a lot more digging in the gIR/PoDoFo relationship to figure out which one and why.

CCITT4 seems likely to be vulnerable to the same bug, but I haven't tested it (not sure what controls whether it's enabled).

**Comment by manisandro** [comment]
CCITT4 is available if you choose monochrome as image format.

What version of PoDoFo did you compile against?

**Comment by foghawk** [comment]
Good question. I can no longer replicate this and I suspect the 0.9.6-2 upgrade is the culprit, or rather uncuplrit. (Arch was a little late on the package update and I was a few days later.)

I'll downgrade to 0.9.5-2 and see if I can bring it back sometime in the next few days—something I've done might have scared it off and I want to clean up my commits before before checking against master again. But the timing on the upgrade is right.

**Comment by manisandro** [comment]
Actually, I hit this one myself last year, see [1] and in particular [2] for details. Has since been resolved with PoDoFo-0.9.6.

[1] https://sourceforge.net/p/podofo/mailman/podofo-users/thread/450273be-69b7-74d6-864d-e2e95727faf1%40gmail.com/#msg35658951
[2] https://sourceforge.net/p/podofo/mailman/message/35659963/

**Comment by foghawk** [comment]
Nice work. Interesting bug!
