### ISSUE TITLE
Feature request: enhancement: save as project file unfinished work-in-progress

### ISSUE THREAD

**Issue by caganer** [manisandro/gImageReader#372]
I checked but may have missed an existing means whereby this is accomplished, however assuming it is not present: 
Feature request: enhancement: add a means of saving the current state of a *project* e.g. where the item is too long to input, recognize and/or check/correct in one session.  Currently recognised and corrected text may be output in one or other formats but that presupposes all the necessary work can be accomplished in one session, whereas depending on the nature and length of the input file it may take several spread over a longer period of time.

**Comment by manisandro** [comment]
Isn't this covered by just saving the output to text (in plain text mode) resp. hOCR html (in hOCR mode), and then re-opening the document to continue working where you left off?

**Comment by manisandro** [comment]
Closing since no reply, feel free to reopen if you feel the current functionality does not cover what you are looking for.

**Comment by Carmina16** [comment]
No. A project should save the image list, the transformations applied to those images, the text area locations, and the OCR results. Without a project feature, recognizing more than 1-2 pages is inefficient.

**Comment by manisandro** [comment]
The hOCR document saves all of that except for the brightness/contrast adjustments.
