### ISSUE TITLE
gimage Reader will be crash by Chinese OCR

### ISSUE THREAD

**Issue by Leroy-X** [manisandro/gImageReader#38]
I download gimage Reader in http://sourceforge.net/projects/gimagereader/
and the language data in https://github.com/tesseract-ocr/tessdata/blob/master/chi_sim.traineddata

and copy the language data file in the gimage reader, all like right, but it's crash by use Chinese language ocr , I don't know where wrong, the gimage reader just closed and not any error tip, same problem in free OCR,  sorry my poor English, thanks!

**Comment by manisandro** [comment]
I suspect the reason for the crash is that the traineddata might be too new for the version of tesseract the current version of gimagereader uses. If you use the older traineddata files from [1], do you still get the crash?

[1] https://code.google.com/p/tesseract-ocr/downloads/list

**Comment by Leroy-X** [comment]
you are right, the version of 3.02 is ok, it's work, but the new version is 3.04, hope the giamge will support that, thanks : )

**Comment by manisandro** [comment]
On Linux, gImageReader uses whichever version of tesseract which is currently available in the distribution - some already have version 3.04 (i.e. Fedora). On Windows, I need to bundle tesseract with the application, so it uses whichever version was the newest one when doing a release. So yes, the Windows build of the next version will use 3.04 (or a newer version if one will be released by then).

**Comment by manisandro** [comment]
FWIW, I've added some Windows installers for gImageReader built against tesseract-3.04.00 in the releases page until I manage to get a new release out.
