### ISSUE TITLE
Build fails when cmake was called twice

### ISSUE THREAD

**Issue by stweil** [manisandro/gImageReader#382]
My build on Debian uses `libxml++2.6-dev`.

After running `cmake ...`, the compiler option `-DHAVE_LIBXMLPP_2` is correctly set.

When I run `cmake ...` a second time, the option is changed to `-DHAVE_LIBXMLPP_3` which is wrong, so the build now fails.

Maybe this is caused because both versions of libxml set `LIBXMLPP_FOUND` and the package checks are not repeated when calling cmake a 2nd time. So a possible solution might be to use different macros `LIBXMLPP2_FOUND` and `LIBXMLPP3_FOUND` for the two cases.

I think there are more similar cases in `CMakeLists.txt` which are handled wrong.

**Comment by manisandro** [comment]
Should be fixed by d513c63

**Comment by stweil** [comment]
Thank you.
