### ISSUE TITLE
Feature Request: implement kraken as second backend

### ISSUE THREAD

**Issue by sixtyfive** [manisandro/gImageReader#385]
Would it (in principle) be possible to implement [kraken](https://github.com/mittagessen/kraken) as another backend for gImageReader? It's a fork of OCRopus that has different strengths than tesseract and is especially useful for Arabic text, with even work in manuscript recognition being done on it.

I realize that gImageReader was not originally intended for multiple backends, still, I hope y'all don't mind the question :-)

**Comment by manisandro** [comment]
In principle everything is possible, but as you noticed, gImageReader is closely tied to tesseract and not trivially adaptable to use other OCR engines. If someone wants to give it a go, feel free, but it is not something that I plan working on.

**Comment by ZaMaZaN4iK** [comment]
@sixtyfive Can you provide a detailed comparison with Tesseract? Because for now I don't see any reason to use Kraken instead of Tesseract in gImageReader

**Comment by sixtyfive** [comment]
@ZaMaZaN4iK I didn't mean "instead" at all. Tesseract is (and likely will always be) better in a lot of things, for example amount of languages / scripts supported. Kraken is good at things like handling inline bi-directional text, مثلا نص عربي بالوسط الإنكليزي, like so. IMHO it's not about "better" and "worse", it's more about "different". I'd like to be able to put the same document through different OCR engines using the same GUI. If there was a _second_ backend to gImageReader, then it wouldn't be so far to a third, etc., backend from there.

@manisandro Thank you for the the reply! How about just getting bounding boxes to work for starters? I.e. instructing Kraken to process a document and then displaying the bounding boxes it found and letting the user re-adjust them in case they're off. 

Here's an example document of mine where (a) Kraken's bounding boxes would be more helpful but (b) I'd still like to adjust them to produce training data.

![image](https://user-images.githubusercontent.com/192860/47314213-5578d280-d641-11e8-9e5b-f9b89354d472.png)

**Comment by manisandro** [comment]
That also already requires a non trivial amount of work, think of aspects building an abstraction layer for other OCR engines (because I definitely don't want a hard dependency on kraken, which is not widely packaged and hence unavailable on many systems), adding a plugin-mechanism of optional OCR engines, then also stuff like mapping tesseract tessdata languages to whatever notion kraken uses. Again, no something I'm planning to work on.

**Comment by sixtyfive** [comment]
All understandable! Thanks for taking the time to comment :-)
