### ISSUE TITLE
Prevent tesseract from generating ligatures

### ISSUE THREAD

**Issue by stefansoyka** [manisandro/gImageReader#392]
Ligatures are glyphs for character sequences like "fi" or "fl" which are considered to look better than the characters when they are rendered and kerned separately. For processing and spell-checking it is often preferable to have text without ligatures, which tesseract by default generates, but with a separate glyph per character. Purists have also strict opinions about where ligatures can be used and where not, for instance a ligature must never span word boundaries in composita.
Therefore a checkbox for "no ligatures" in gimagereader or in a tesseract settings dialog within gimagereader would be very helpful.
To make things more complicated, one might find ligatures desirable in a particular language (e.g. arabic languages) but not in another (with latin alphabets), therefore one might even want to have this checkbox to be language dependant.

**Comment by manisandro** [comment]
So is there actually an option in tesseract to disable the ligatures? Or does it depend on the traineddata?

**Comment by stefansoyka** [comment]
Either option would probably work, in native tesseract you might set up a blacklist file with the glyphs you don't want tesseract to use. Or you also like remix the traineddata file, but I can't find it in gimagereader.

**Comment by manisandro** [comment]
Looks like the whitelist/blacklist does not work anymore with 4.0.0+LTSM [1]. What do you mean by traineddata remix?

[1] https://github.com/tesseract-ocr/tesseract/issues/751

**Comment by stefansoyka** [comment]
Haven't done that myself, I only saw in some newsgroup, sorry. I will try to find out a come back here

**Comment by manisandro** [comment]
Blacklist/whitelist can now be specified (https://github.com/manisandro/gImageReader/commit/88c3491df15ba548f42dc51813867bdbbebc16ba)
