### ISSUE TITLE
option to produce ASCII instead of UTF-8 glyphs.

### ISSUE THREAD

**Issue by skierpage** [manisandro/gImageReader#394]
gImageReader 3.3.0 on Fedora 29 produces UTF-8 smart quotes ‘ ’, “ ” and dashes —  as well as plain ',",-. It would save post-processing in several circumstances if there was a way to disable the former; for example, scanning lyrics for Genius which wants typewriter quotation marks and dashes, not typographer's marks. This sounds like issue #392.

I don't know if it makes sense or is even possible to disable _all_ non-ASCII glyphs. E.g. if it thinks it's recognized © or é, do you want to get (c) and e? I guess there's "I don't want gImageReader to _recognize_ anything but ASCII shapes," a claim about what's in the input that could enhance scanning accuracy; and separately "I don't want gImageReader to _produce_ anything but ASCII code points," which is a preferred output format; but that's a complicated UI. There's a preference for Text file encoding, but 7-bit ASCII isn't one of the choices.

(To show all non-ASCII characters in output using ripgrep, in a terminal enter `LC_ALL=C rg '[^\x00-\x7f]' outputfile.txt`)

**Comment by manisandro** [comment]
It is actually tesseract who produces the text, so one would need to check whether one can configure the tesseract engine accordingly or whether one needs to train a specialized traineddata to have the output only contain the desired glyphs.

**Comment by manisandro** [comment]
Character whitelist and blacklist can now be specified (https://github.com/manisandro/gImageReader/commit/88c3491df15ba548f42dc51813867bdbbebc16ba)
