### ISSUE TITLE
[Qt] Rapidly changing sources from hOCR output pane hangs on Qt 5.12

### ISSUE THREAD

**Issue by foghawk** [manisandro/gImageReader#399]
Opening an hOCR file (recognized from one image per page) and holding 'down' in the collapsed output pane reliably triggers this after 7–8 pages. gIR will rapidly spin to 100% CPU and remain unresponsive until manually signaled. Example backtrace is [here](https://github.com/manisandro/gImageReader/files/2798563/bt.txt).

Also, starting the application prints
`QNetworkReplyHttpImplPrivate::_q_startOperation was called more than once QUrl("https://raw.githubusercontent.com/manisandro/gImageReader/master/LATEST")`. (LATEST still reports "3.2.99", btw.)

I have built and run against a snapshot of the last 5.11 release and confirmed that neither of these symptoms appear. Between the multiple start operation message, the backtrace showing two different threads polling `processEvents`, and the nondeterminism in the timing, this looks like a race-condition deadlock, but I don't know what changed in 5.12 to cause it or whether there might be other ways to trigger it.

**Comment by manisandro** [comment]
Is this 5.12.0 or 5.12.1?

Thanks also for the LATEST heads-up, fixed.

**Comment by foghawk** [comment]
5.12.0; I haven't tested against 5.12.1 yet.

**Comment by foghawk** [comment]
5.12.1 has the same symptoms.

**Comment by manisandro** [comment]
If you run gimagereader in gdb and interrupt execution, what does the call stack look like? Does it always look the same if you interrupt resume and re-interrupt?

**Comment by manisandro** [comment]
Cannot reproduce this with 5.12.4, please feel free to reopen if it still applies.
