### ISSUE TITLE
Spellchecker uses incorrect codepage

### ISSUE THREAD

**Issue by xarx00** [manisandro/gImageReader#40]
I'm using the cs_CZ dictionaries, gImageReader 3.0.2 on Win7 x64.

In the Output window, if a word gets marked as incorrect, the spellchecker rarely offers (on right-click) an alternative word that contains accented characters (unaccented words seem to be preferred). But if it does, the word is presented in an incorrect codepage, and if the word is clicked, the same incorrect characters are inserted into the output text.

Details:
The words in the dictionary are encoded in UTF8 (e.g. "psychickým"). But the spellchecker presents and inserts the words in a byte encoding ("psychickĂ˝m")

**Comment by manisandro** [comment]
Oh bummer, this is caused by an incorrect conversion from std::string to QString in QtSpell.

**Comment by manisandro** [comment]
I've released a new version of qtspell which fixes this. Windows users will only get it with with the next version of gImageReader however. In the meantime, you should be able to just replace the qtspell-qt5-0.dll in the gImageReader/bin folder with the one here: http://smani.fedorapeople.org/tmp/qtspell.zip
(Back up the old one just in case)

**Comment by xarx00** [comment]
That was fast! But the fix does not work. Now:
1. all correctly spelled Czech words are marked as incorrect
2. In the list of alternatives, the words are still displayed with an incorrect codepage

**Comment by manisandro** [comment]
Uhm, this is very odd since the only thing I've changed is how the strings returned by the enchant speller are converted to QString, so  it should have no effect whatsoever on whether a word is detected as correctly or incorrectly spelled. Admittedly, I've only tested it on Linux, will quickly check on Windows too.

**Comment by manisandro** [comment]
Working on Windows also as far as I can see...

![screen](https://cloud.githubusercontent.com/assets/1298852/11182494/8f9d75ce-8c6b-11e5-9e70-a526fb55af8d.jpg)

**Comment by xarx00** [comment]
This is the original dll before fix:
![orig](https://cloud.githubusercontent.com/assets/15482887/11188337/969e49a6-8c8a-11e5-86a4-956203ef705e.jpg)

Here is the same document with fixed dll you pointed me to. Note that almost everything is marked as incorrectly spelled:
![fixed](https://cloud.githubusercontent.com/assets/15482887/11188393/e470e31e-8c8a-11e5-80ba-0842267ba762.jpg)

And here is how a spell checker menu looks like on this text:
![fixed_menu](https://cloud.githubusercontent.com/assets/15482887/11188415/02d6cef4-8c8b-11e5-9379-9187b8789bfa.jpg)

**Comment by manisandro** [comment]
I'll need to find a Windows 7 machine to test this on, in the meantime could you please specify whether you are using the spelling dictionary from [1] or from somewhere else, and just in case also attach the image you are working with.

[1] http://cgit.freedesktop.org/libreoffice/dictionaries/tree/cs_CZ

**Comment by xarx00** [comment]
You're right. I used a year-old dictionary, and it contained a bug. In cs_CZ.aff, there was specified the charset ISO-8859-2, while the dictionary was in fact in UTF-8. The dictionary from your link works fine, and after fixing the charset specification in my dictionary, it works fine too. I've been using my dictionary with an office suite (not OO), and never had a problem with it. The suite perhaps ignores the charset specification header. Thank you, please close the bug now.

**Comment by manisandro** [comment]
Ah cool, that explains it. Thanks for reporting the issue!
