### ISSUE TITLE
Keep text styles in plain text mode

### ISSUE THREAD

**Issue by link2xt** [manisandro/gImageReader#402]
Currently italics and bold are only preserved in hOCR mode, but hOCR is very hard to edit so it is not suitable for scanning big amounts of texts.

Is it possible to add some lightweight text styles to plaintext mode, for example in the form of inline tags?

**Comment by manisandro** [comment]
The output comes directly from tesseract, and in the case of plain text recognition, any formatting information is discarded by the engine. But in your case you could export the hOCR document to ODT to edit in more comfortably in a word processor.

**Comment by link2xt** [comment]
> The output comes directly from tesseract

Maybe request `.hocr` from tesseract and extract plain text from there? No need to ever request `.txt` from tesseract if it simply contains less informaiton.

>  But in your case you could export the hOCR document to ODT to edit in more comfortably in a word processor.

I can't proofread the text in a word processor. There is no scan to compare side-by-side and confidence values are lost.

What I want is a FineReader-like workflow for scanning large texts (e.g. books), where it produces draft "rich text" with styles and special markup for low-confidence text and proofread the text against the images before saving it. If such mode is available, I don't see the reason to have pure plain text mode.

Current hOCR mode is more suitable for adding OCR layer to PDFs than converting texts to reflowable formats.

**Comment by manisandro** [comment]
I suppose one could add a Rich-Text mode which places the hocr HTML directly into a QTextEdit for editing. At latest when you start editing though, you'd start destroying the hOCR layout information (i.e. item bboxes, etc), so creating a layout-preserving PDF/ODT from the edited text would be impossible.

**Comment by manisandro** [comment]
Tracking in #438
