### ISSUE TITLE
improve current page selector

### ISSUE THREAD

**Issue by riclas** [manisandro/gImageReader#403]
Just used the software for the first time and took me too long to figure out there was a spinbox to change the current page.
Like in a regular pdf reader, it would be nice if the page number was highlighted somehow, for example on a new taskbar line or better spacing/reorganization of existing buttons.
A quick improvement would be to add a text on hover of the spinner saying "current page". For some reason seems to be the only taskbar image without a hover text.

cheers

**Comment by manisandro** [comment]
Thanks for the feedback, I've added a tooltip.
