### ISSUE TITLE
Document how to install build-time dependencies in Ubuntu 14.04, 16.04

### ISSUE THREAD

**Issue by probonopd** [manisandro/gImageReader#404]
https://github.com/manisandro/gImageReader/wiki/Compiling-gImageReader is somewhat vague regarding the exact packages that need to be installed on Ubuntu in order to compile the application. It would be great if the exact apt-get command could be mentioned, along with the correct package names.

Something vaguely along the lines of `sudo apt-get -y install qt59base tesseract-ocr-dev libsane-dev libpodofo-dev libjpeg-dev libdjvulibre-dev intltool-debian libzip-dev uuid-dev libxml++2.6-dev libpoppler-qt5-dev libquazip5-1`.

**Comment by probonopd** [comment]
Especially, where do I find `qtspell-qt5` in trusty or xenial?

**Comment by probonopd** [comment]
Work in progress toward an [AppImage](http://appimage.org/):
https://github.com/probonopd/gImageReader/blob/patch-1/.travis.yml

**Comment by probonopd** [comment]
Getting

```
-- Checking for module 'tesseract'
--   Package 'lept', required by 'tesseract', not found
-- Checking for module 'ddjvuapi'
--   Found ddjvuapi, version 3.5.27
CMake Warning at CMakeLists.txt:58 (MESSAGE):
  Using hardcoded cflags and ldflags for tesseract
-- Checking for module 'sane-backends'
--   Found sane-backends, version 1.0.25git
CMake Error at CMakeLists.txt:67 (MESSAGE):
  Couldn't find intltool-merge, please install intltool
-- Configuring incomplete, errors occurred!
```

so possibly the list in the Wiki is incomplete?

**Comment by manisandro** [comment]
Ubuntu 14.04 is most definitely too old, but generally you can look at the dependencies specified in the debian package sources at https://github.com/manisandro/gImageReader/blob/master/packaging/debian/control.

**Comment by probonopd** [comment]
Looks like `libqtspell-qt5-dev` was added to Ubuntu only very recently and is not available for the oldest still supported LTS releases:

https://packages.ubuntu.com/search?keywords=libqtspell-qt5-dev

Can this be made an optional dependency?

**Comment by manisandro** [comment]
You could just compile it manually from https://github.com/manisandro/qtspell.

**Comment by probonopd** [comment]
Thanks. Getting a bit further now, but tripping over some Poppler errors:

```
[ 85%] Building CXX object CMakeFiles/gimagereader.dir/qt/src/SourceManager.cc.o
[ 86%] Building CXX object CMakeFiles/gimagereader.dir/qt/src/SubstitutionsManager.cc.o
/home/travis/build/probonopd/gImageReader/qt/src/SourceManager.cc: In member function ‘bool SourceManager::checkPdfSource(Source*, QStringList&) const’:
/home/travis/build/probonopd/gImageReader/qt/src/SourceManager.cc:166:29: error: ‘class Poppler::Document’ has no member named ‘author’
  source->author = document->author();
                             ^
/home/travis/build/probonopd/gImageReader/qt/src/SourceManager.cc:167:30: error: ‘class Poppler::Document’ has no member named ‘creator’
  source->creator = document->creator();
                              ^
/home/travis/build/probonopd/gImageReader/qt/src/SourceManager.cc:168:31: error: ‘class Poppler::Document’ has no member named ‘keywords’
  source->keywords = document->keywords();
                               ^
/home/travis/build/probonopd/gImageReader/qt/src/SourceManager.cc:169:31: error: ‘class Poppler::Document’ has no member named ‘producer’
  source->producer = document->producer();
                               ^
/home/travis/build/probonopd/gImageReader/qt/src/SourceManager.cc:170:28: error: ‘class Poppler::Document’ has no member named ‘title’
  source->title = document->title();
                            ^
/home/travis/build/probonopd/gImageReader/qt/src/SourceManager.cc:171:30: error: ‘class Poppler::Document’ has no member named ‘subject’
  source->subject = document->subject();
                              ^
CMakeFiles/gimagereader.dir/build.make:364: recipe for target 'CMakeFiles/gimagereader.dir/qt/src/SourceManager.cc.o' failed
make[2]: *** [CMakeFiles/gimagereader.dir/qt/src/SourceManager.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/gimagereader.dir/all' failed
make[1]: *** [CMakeFiles/gimagereader.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
The command "make -j$(nproc)" exited with 2.
```

Could the version of Poppler that is required to build the project be downgraded, so that one can build with the Poppler that comes with trusty or xenial?

**Comment by manisandro** [comment]
May I ask why you want to build gImageReader for such an old distro?

**Comment by ZaMaZaN4iK** [comment]
@probonopd If you want to use program on such old distro - please use Snap or Flatpak. Developers chose minimal deps version because they need some functionality which are not available in older versions. So that's not a developer problem - it's your problem as a user of such old distro?

What should you do in such situations? Just dont use libraries from distro and use distro-independent way to install an application: Snap, Flatpak (I recommend it), possibly AppImage (I don't recommend it). If gImageReader isn't available in Flatpak - just build flatpak for gImageReader (it should be easier than fighting with old libraries in repo) and use it!

@manisandro I think it should be closed. The maximum what can we do here - prepare Snap\Flatpak for gImageReader.

**Comment by manisandro** [comment]
Not sure if you can even run flatpak or snap on such old distros to be honest, but fwiw @scx has worked on such packages, see #396.

**Comment by ZaMaZaN4iK** [comment]
@manisandro just found that snapd is available on Ubuntu 14.04: https://www.howtoforge.com/tutorial/how-to-install-snap-applications-on-ubuntu-14-04-lts/

**Comment by probonopd** [comment]
> May I ask why you want to build gImageReader for such an old distro?

(Not meant as a lecture to anyone, but answering since you asked.)

Many users like to use long-term-support (LTS) versions of the operating system, but still use the latest applications. The situation is similar as e.g., in the Windows world, where many users are still running Windows 7 but expect the latest applications to run.

For application developers this means that one should generally try to target the oldest still-supported, not the latest and greatest, operating system releases. It's developing with "backward compatibility" in mind.

In my opinion, solutions like Flatpak and Snappy merely work around this - namely, by ignoring entirely the libraries that are part of the operating system and replacing everything with private copies. This may be considered "bloated" by some. (It is like coding your application for Windows 10 and then ship those parts of Windows 10 along with your application that have changed since Windows 7 came out.)

> Developers chose minimal deps version because they need some functionality which are not available in older versions. So that's not a developer problem - it's your problem as a user of such old distro?

I beg do disagree. Any Android application developer will check which versions of Android are popular among users, and develop against those versions. Almost no one writes Android applications for Android 9 because its market share, and hence potential user base, is currently under 10% of all Android users. This kind of thinking (which is second nature to Android developers) needs to happen in the Linux world as well in my opinion (where it frequently seems not to exist).

> What should you do in such situations? Just dont use libraries from distro and use distro-independent way to install an application: Snap, Flatpak (I recommend it), possibly AppImage (I don't recommend it).

As the inventor and main developer of AppImage, currently trying to package gImageReader as an AppImage, I am genuinely interested in understanding why you don't recommend it. By the way, it would entirely be possible to make an AppImage that contains the application and _all_ libraries, hence using _nothing_ from the system - but again, some users may consider this bloated and bad practice.

In any case, my point is not to persuade anyone of anything - if this project deems that it is sufficient to support only the latest and greatest distributions, well, it's the project's choice.

**Comment by manisandro** [comment]
I'm certainly aware of LTS distros, but there is always a trade off between moving the software forward and keeping support with old userspaces. 14.04 is EOL as of this month, so it really shouldn't be used anymore anyway. I'd expect the current version to compile on any distro released in the past two to three years, and judging from the overall feedback, that seems to suffice. I'm not per se opposed to ensuring compatibility with older versions, but at some point I draw a line with what I'm willing to carry upstream (and 14.04 is definitely too old).

As for AppImage etc, personally I have no strong opinions for or against any of them, I'll let @ZaMaZaN4iK  reply to that.

**Comment by probonopd** [comment]
> 14.04 is EOL as of this month, so it really shouldn't be used anymore anyway. 

Agree, let's say 16.04 :-)

**Comment by scx** [comment]
Flatpak package should works on Ubuntu 16.04 LTS as well as on RHEL 7.
https://github.com/scx/gimagereader-flatpak/tree/qt5
https://github.com/scx/gimagereader-flatpak/tree/gtk3

**Comment by probonopd** [comment]
Thanks for the pointer but Flatpak does not work for me, it is not installed and working out-of-the-box on Ubuntu Live ISOs which I am using most of the time.

**Comment by probonopd** [comment]
Anyway, manually compiling Poppler works for me on xenial. Hence, closing here. Thank you.
