### ISSUE TITLE
Make relocatable in filesystem

### ISSUE THREAD

**Issue by probonopd** [manisandro/gImageReader#405]
Unless I am doing wrong, it seems like  `gImageReader-qt` does not honor the environment variable `TESSDATA_PREFIX`. It always wants to load from `/usr/share/tesseract-ocr` despite `TESSDATA_PREFIX` points somewhere else, and as a result I get

> No tesseract languages are available for use. Recognition will not work.

Can you confirm?

```
me@host:~/foo$ sudo strace -f /home/me/Downloads/gImageReader-6215cdc-x86_64.AppImage 2>&1 | grep -i TESSDATA
[pid 10937] <... read resumed> "export TESSDATA_PREFIX=${HERE}/u"..., 155) = 101
[pid 10937] openat(AT_FDCWD, "/usr/share/tesseract-ocr/tessdata/eng.traineddata", O_RDONLY <unfinished ...>
[pid 10937] write(2, "Error opening data file /usr/sha"..., 74Error opening data file /usr/share/tesseract-ocr/tessdata/eng.traineddata
[pid 10937] write(2, "Please make sure the TESSDATA_PR"..., 119Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
[pid 10937] openat(AT_FDCWD, "/usr/share/tesseract-ocr/tessdata/eng.traineddata", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 10937] write(2, "Please make sure the TESSDATA_PR"..., 119) = 119
[pid 10937] openat(AT_FDCWD, "/usr/share/tesseract-ocr/tessdata/", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)
```

Here is the file in question:
https://github.com/probonopd/gImageReader/releases

You can inspect its contents by running it with the `--appimage-extract` option.

**Comment by manisandro** [comment]
Yes this is the case, see [1]. This was done mainly because of the packagekit integration for downloading traineddatas. If the TESSDATA_PREFIX points to somewhere else than the system location, tessdata management with packagekit would break (since tesseract would report different available languages that the package manager).

[1] https://github.com/manisandro/gImageReader/blob/master/qt/src/Config.cc#L201

**Comment by probonopd** [comment]
Would it be acceptable to set `TESSDATA_PREFIX` on Linux to a path relative to the main executable's directory, similarly to what is done for Windows? This way, the application would become relocatable in the filesystem and not married to a static build-time `$PREFIX`.

**Comment by manisandro** [comment]
This is actually more of a problem about relocating tesseract itself, not just gImageReader. Since the tessdata directory tends to vary quite a bit between distros, the only solution I can think of is checking whether `tess.GetDatapath()` returns a canonical absolute path, and if yes, rewrite it as the path to the bin dir plus the relative path to the tessdata folder. I.e.

    "/usr/share/tessdata" -> QApplication::applicationDirPath() + "/../share/tessdata"

**Comment by probonopd** [comment]
Would be great if you could have a look at the AppImage at https://github.com/probonopd/gImageReader/releases. You can extract it for inspection using `--appimage-extract`.

**Comment by probonopd** [comment]
Yes, using `QApplication::applicationDirPath() + "/../share/tessdata"`seems like the way to go. I don't understand what you mean by "checking whether tess.GetDatapath() returns a canonical absolute path". What else should it return and why do you want to check this first?

**Comment by manisandro** [comment]
In theory `GetDatapath` can return anything, depending on how tesseract was compiled. But essentially what I meant is you need to take whatever GetDatapath returns, ensure it is a canonical absolute path, and the rewrite that path expressed as relative to QApplication::applicationDirPath(). Note that `/usr/share/tessdata` varies between distros (some have `/usr/share/tesseract-ocr/tessdata`, others `/usr/share/tesseract/`, others again `/usr/share/tessdata/` etc etc.)

**Comment by probonopd** [comment]
For the purpose of making the AppImage, it would be sufficient that in case the hardcoded absolute paths don't exist, `../share/tesseract-ocr/tessdata` relative to `QApplication::applicationDirPath()` is checked as a _fall back_. Would that work?

**Comment by probonopd** [comment]
It seems like the spelling dictionaries also need special treatment in order to become relocatable?

**Comment by probonopd** [comment]
This is what I mean:

![](https://github.com/AppImage/appimage.github.io/blob/6265fbd62f12e4dd72e8755ae5d4ccaa234124fb/database/gImageReader/screenshot.png?raw=true)

If you want to test: https://github.com/probonopd/gImageReader/releases/continuous

**Comment by manisandro** [comment]
Sorry forgot to follow up. There are two possibilities:

- Either enchant needs to be build with `-DENABLE_COSTLY_RELOCATABLE`
- Or the application must manually call `enchant_set_prefix_dir`.

**Comment by probonopd** [comment]
I am using `./configure --prefix=/usr --disable-static --enable-relocatable` for enchant, apparently this is not sufficient? In the [build log](https://api.travis-ci.com/v3/job/198629866/log.txt), I see `checking whether to activate relocatable installation... yes` but that seems to be all it does... as I still see

```
$ strings ./usr/lib/libenchant-2.so.2 | grep "/enchant"
/usr/share/enchant
/usr/lib/enchant-2
```

**Comment by probonopd** [comment]
Is there a way to get the application to load `../share/doc/gimagereader/manual-en.html` from a location relative to the main application?

**Comment by probonopd** [comment]
> Either enchant needs to be build with -DENABLE_COSTLY_RELOCATABLE

Thanks for the pointer, it is now looking at relative paths but it is still not picking up `../share/hunspell/en_US.aff` and `../share/hunspell/en_US.dic`. I am a bit puzzled...

**Comment by manisandro** [comment]
> Is there a way to get the application to load `../share/doc/gimagereader/manual-en.html` from a location relative to the main application?

This is currently only done for Windows, see https://github.com/manisandro/gImageReader/blob/master/qt/src/MainWindow.cc#L292, on other platforms the `MANUAL_DIR` compile-time definition is used, given that some distros have differing conventions where to install manuals. But perhaps this could be changed that if MANUAL_DIR is set empty, it defaults to the relative path as in the Windows case.

As for the dictionaries, that's odd as the same logic is used in the Windows build and works there. Perhaps inspect with `strace` to see where it is actually looking for the dictionaries.

**Comment by probonopd** [comment]
> Perhaps inspect with strace to see where it is actually looking for the dictionaries.

That's what I tried but I was unable to figure something useful out so far.

**Comment by probonopd** [comment]
I still see 

![](https://user-images.githubusercontent.com/2480569/57403181-9513a000-71c8-11e9-92ef-858ba4bc5385.png)

The "spelling dictionaries path" is wrong.

**Comment by manisandro** [comment]
Can you check whether b56586d87d844efa61ee3c10fb29e7d9decbb522 helps for the spelling path? I've also pushed eef6096842f4b5212e4f06cc3fec23930f945cab for the manual dir issue.

**Comment by probonopd** [comment]
Thanks, new build at https://github.com/probonopd/gImageReader/releases/tag/continuous. Still need to find out why the spelling dictionary is not being found. This is how I build: https://github.com/probonopd/gImageReader/blob/patch-1/.travis.yml

**Comment by manisandro** [comment]
Can you post the strace output?

**Comment by probonopd** [comment]
Please find it attached: [strace.log.zip](https://github.com/manisandro/gImageReader/files/3167458/strace.log.zip)

**Comment by Symbian9** [comment]
Any news on solving this issue?

**Comment by manisandro** [comment]
Ah right. So the strace does not actually show any trace of the spelling dictionary. One would need to have a enchant build with debug symbols, and then check here [1] which directories it is actually scanning.

https://github.com/AbiWord/enchant/blob/master/providers/enchant_hunspell.cpp#L414

**Comment by probonopd** [comment]
Can you invest some time in doing this @Symbian9?

**Comment by Symbian9** [comment]
> Can you invest some time in doing this

I'm user of gImageReader and can't help with code; I just need AppImage binary for work with docs.

**Comment by probonopd** [comment]
Someone needs to invest debugging time into the payload here, time which I don't have atm :(

**Comment by manisandro** [comment]
This looks abandoned, please reopen if still relevant.
