### ISSUE TITLE
Add to dictionary not working on Windows 10

### ISSUE THREAD

**Issue by sashimipenguin** [manisandro/gImageReader#408]
I'm using Windows 10, version 3.3.0 (tesseract 4.0.0-beta.3)

After recognizing text if I right click on a misspelled word and click 'Add "xxx" to dictionary' nothing happens.  The word stays underlined.  Ignore also does nothing.

Under preferences I have Language data locations to be under User paths, and I have verified that I have full permissions to these directories.

Two files, 'en_US.dic' and 'en_US.exc' get created if there is nothing initially in the spelling folder, but no words get added.  If I manually add words to the .dic file and redetect language, these words seem to get used for spell checking.

**Comment by manisandro** [comment]
This was a qtspell bug, fixed in qtspell-0.9.0.
