### ISSUE TITLE
The quality of normal text OCR and hOCR differ

### ISSUE THREAD

**Issue by omega3** [manisandro/gImageReader#409]
The great thing about scanning as normal text is that I can you spell check and correct mistakes. 

When I do hOCR it seems impossible. It is like one or the other choice. 

I would like to be able to correct text and export to pdf with text on top of picture (something that is available in PDF-XChange Editor). And have pdf with searchable OCR-ed text. 

When I now export to pdf after hOCR the result is not very good, definitely worse then text-OCR. When I use preview after hOCR it looks so bad that it is sometimes hard to recognize anything:
https://imgur.com/8cVBij7

https://imgur.com/AwQYBWg

Would it be possible to develop better preview, so that it would show OCR-ed text in another color to make it well visible for example red on top of the area from where it comes from, or just below? Or maybe small, separate panel below image preview with line of text. Or third small area on the right panel, that would show text that is marked in currently chosen option: text blok, paragraph, line. I mean when I check paragraph I would see a full sentence from this parahraph. So that user could compare how good it was hOCR-ed. Just looking at the table in the right side panel where word are listed one below the other in a tree-like structure to see how good OCR result is, is difficult task. 

Maybe it would be possible first to do text-OCR to get good quality text and check it with language tool, and then somehow match it to hOCR (I mean to put in the right place).

Now hOCR lacks the goodies of normal OCR.

**Comment by manisandro** [comment]
The issue that the text in the preview is garbled is fixed in https://github.com/manisandro/gImageReader/commit/6d41bed2b9d5e6385d2b70799547d25de4eea79f

**Comment by manisandro** [comment]
Refering to your points above: the quality is actually the same, there was just an issue with the detected font family being empty with tesseract 4.x LTSM, resulting in the preview drawn with garbled glyphs.

**Comment by omega3** [comment]
Ok. Thank you. But further hOCR function would be welcomed.

**Comment by manisandro** [comment]
Sure there are still a number of ways the workflow can be improved. Just a matter of me or someone else having the time to work on it.

**Comment by manisandro** [comment]
Tracking in #438
