### ISSUE TITLE
Language packages path has changed

### ISSUE THREAD

**Issue by meaz** [manisandro/gImageReader#410]
I'm on Debian Stretch. I use gImageReader 3.2.0
I have Tesseract 4.0.0-2~bpo9+1 installed.
Since this 4.0.0-2 was installed, gImageReader can't not find any language. Indeed, in the settings, it is searching in `/usr/share/tesseract-ocr/tessdata/` for the language. But Tessaract language packages are now installed in `/usr/share/tesseract-ocr/4.00/tessdata/`.

However, I can't change this path in the settings

**Comment by manisandro** [comment]
Unless overridden by the TESSDATA_PREFIX env-var, the path on Linux is queried from tesseract itself, see [1], so it looks like tesseract is misconfigured?

[1] https://github.com/manisandro/gImageReader/blob/master/qt/src/Config.cc#L232

**Comment by meaz** [comment]
I've just did `apt install -t stretch-backports tesseract-ocr` ... So, should I start an issue ticket on tesseract repo?

**Comment by manisandro** [comment]
I see now that you are using gimagereader-3.2.0, which still had hard-coded paths. Please upgrade to 3.3.0, which correctly detects the paths from tesseract.

**Comment by meaz** [comment]
I've updated to Buster, so to gimagereader-3.3.0. It is working fine. Thanks.

**Comment by sebma** [comment]
@manisandro Hi, as there is no v3.3 build for Ubuntu Trusty at [your Launchpad's gImageReader PPA](https://launchpad.net/~sandromani/+archive/ubuntu/gimagereader/+packages?field.name_filter=gimagereader&field.status_filter=published&field.series_filter=trusty), I've decide to create a symbolic link for `/usr/share/tesseract-ocr/tessdata` to follow the new path (`/usr/share/tesseract-ocr/4.00/tessdata/`).

But then `gimagereader` crashed, is the v3.2 compatible with Tesseract4 ?

If not, can you please update the dependencies from `libtesseract3` to `libtesseract3 | libtesseract4` and rebuild `gimagereader-gtk` for Ubuntu Trusty ?

**Comment by manisandro** [comment]
Sorry but trusty is EOL and no new builds can be submitted (you should really look at upgrading btw.).

**Comment by manisandro** [comment]
Sorry but trusty is EOL and no new builds can be submitted (you should really look at upgrading btw.).
