### ISSUE TITLE
How do I improve recognition?

### ISSUE THREAD

**Issue by orangebutblue** [manisandro/gImageReader#411]
When I process a document, then the result is generally good. However there are always a few errors on every page. Often times there are same/similar errors in all pages.

Is it not possible to manually correct an error and thus 'teach' the recognition engine?
I'm trying to correct a few errors by hand, to be able to re-run the process, to improve recognition.

Since i'm dealing with documents that have hundreds of pages, I can't just manually look through all of them and fix the same small errors by hand every time.

**Comment by manisandro** [comment]
You'll need to do this at the OCR engine (i.e. tesseract) level, see https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00. gImageReader is just a frontend.
