### ISSUE TITLE
Feature Request: Recursive directory traversal

### ISSUE THREAD

**Issue by JoshuaKyleLambert** [manisandro/gImageReader#414]
The ability to add images in an entire directory structure would be very useful.

**Comment by manisandro** [comment]
You can pass filenames as arguments to gImageReader if you launch it from the command line. So you could do something like

    gimagereader-<qt5/gtk> $(find -type f -name '*.jpg')

Is that sufficient for your needs?

**Comment by JoshuaKyleLambert** [comment]
unfortunately I have 800+ images in wide directory structure but only about
3 levels deep. I wanted to pair these images with their text.

**Comment by manisandro** [comment]
Not sure I follow, so it's more than just adding all the images from a directory structure, but to also process them automatically one at a time?

**Comment by JoshuaKyleLambert** [comment]
that was the goal yes. OCR an image and leave behind a text file with the
recognized text with the same name next to it.

However I've jumped the gun a bit here.

I've tried processing these images and the text is not being recognized
accurately. I've tried pre-processing them "binarizing" .   Still no good
recognition. i realize this is a limitation of the tesseract library (more
likely my inexperience) and not gImageReader. The images are screen
captures with text on a black background. seems perfect for accurate OCR
but this just not the case.  Do you have any experience with images like
these?

**Comment by manisandro** [comment]
To mass recognize the images, you are probably better off writing a quick shell script which invokes the tesseract executable directly. As far as the image is concerned, I suppose it should work, you could try upscaling the images, or perhaps even inverting them, though I'm not familiar enough with the tesseract internals to be able to state that it actually should make a difference.

**Comment by JoshuaKyleLambert** [comment]
thanks, for the help. Inverting the images made all the difference.  I
think I'll go with the shell script idea .

Thanks again,

-j

**Comment by manisandro** [comment]
Cool, so this confirms that the invert image setting in gImageReader actually can be useful ;)
