### ISSUE TITLE
Going back with results from gImageReader to command line

### ISSUE THREAD

**Issue by guysoft** [manisandro/gImageReader#415]
Hey, 
I am getting good results using gImageReader, but when I try to replicate the command in the commandline I am getting bad results.
Is there a way to extract what settings gImageReader is using so I can move the result back to the commandline or library?

Thanks!

**Comment by manisandro** [comment]
Not really - gImageReader invokes the tesseract API directly, it does not invoke tesseract via command line. You can have a look a the `recognize` function [1] to see how gImageReader configures tesseract, but there is no magic there really.

[1] https://github.com/manisandro/gImageReader/blob/master/qt/src/Recognizer.cc#L431
