### ISSUE TITLE
404 errors on source strings

### ISSUE THREAD

**Issue by leela52452** [manisandro/gImageReader#418]
source strings on weblate are giving 404 errors.
[weblate](https://hosted.weblate.org/projects/gimagereader/translations/source/review/?type=check%3Aellipsis)
[example 1](https://github.com/manisandro/gImageReader/tree/qt/src/Recognizer.cc#L79)
[example 2](https://github.com/manisandro/gImageReader/tree/gtk/data/MainWindow.ui.h#L58)

**Comment by manisandro** [comment]
It's resolving the `../` in the file paths beyond the the root of the repo, so that i.e. concatenating 

    https://github.com/manisandro/gImageReader/tree/master

with 

    ../qt/src/Recognizer.cc#L79

results in 

    https://github.com/manisandro/gImageReader/tree/qt/src/Recognizer.cc#L79

rather than

    https://github.com/manisandro/gImageReader/tree/master/qt/src/Recognizer.cc#L79

Not much I can do here I'm afraid, I'll report the issue to weblate.

**Comment by leela52452** [comment]
thanks a lot
