### ISSUE TITLE
Add word/line/paragraph don't work

### ISSUE THREAD

**Issue by b1fer** [manisandro/gImageReader#419]
In gimagereader 3.31 (on win 10) after i scan an image in hocr and some words are not recognized, i try to "add word" in a text line, but nothing happens.
Same thing if i try to "add a textline" or "add paragraph" or "add text block".
Is this a bug or how can i add a word if it is not recognized by gimagereader?

**Comment by manisandro** [comment]
After activating the function, drag a box in the image to define where the corresponding element (word/line/paragraph/...) should be added.
