### ISSUE TITLE
Exclude graphic region in hOCR

### ISSUE THREAD

**Issue by b1fer** [manisandro/gImageReader#420]
When I apply the hocr to the images of a book in which there is only text, is there the possibility of excluding the graphic regions in the recognition (because I am sure that there are no graphic regions)?

If there is no possibility to exclude graphic regions in hocr recognition, is it possible to add the option in future versions of gimagereader?

**Comment by manisandro** [comment]
It's tesseract, the OCR engine, which does the recognizing, and I don't believe it allows restricting the types of elements to recognize. Filtering graphic regions from the OCR result could be done though.

**Comment by manisandro** [comment]
Tracking in #438
