### ISSUE TITLE
gimagereader crashes when $LANG not set

### ISSUE THREAD

**Issue by innir** [manisandro/gImageReader#421]
Hi,

I got the following bug report in Debian [https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=930642]:

> When LANG is not set in the environment, gimagereader
> crashes and it is not obvious, that the fix is to set LANG
> in your environment.
> 
> ```
> (gimagereader-gtk:2877): glibmm-ERROR **: 13:43:01.058:
> unhandled exception (type std::exception) in signal handler:
> what: basic_string::_M_construct null not valid
> ```

Uh, yes - seems to be:

https://github.com/manisandro/gImageReader/blob/master/gtk/src/MainWindow.cc#L319

and for the Qt version:

https://github.com/manisandro/gImageReader/blob/master/qt/src/MainWindow.cc#L310

I guess gImageReader also behaves strange for $LANG set to variants of "C"

Best,
Philip

**Comment by manisandro** [comment]
Indeed, this is not very robust. I'll look into it, thanks!

**Comment by manisandro** [comment]
Turns out Glib::getenv is safe, but g_getenv used elsewhere returned a null pointer. Fixed.
