### ISSUE TITLE
automatically rotate

### ISSUE THREAD

**Issue by rafael844** [manisandro/gImageReader#423]
Is there a way to identify the page orientation automatically? Sometimes a page comes upside down or landscape. When a page is text rotate 90º it can be identified, but 180 and 270 no, as in the example. Is there somewhere to set it??

Thanks.

[rot.pdf](https://github.com/manisandro/gImageReader/files/3647163/rot.pdf)

**Comment by ZaMaZaN4iK** [comment]
In Leptonica library there is an algorithm for auto rotating pages.

**Comment by manisandro** [comment]
I believe it ist just about deskewing the image (which tesseract already does internally). But if the orientation itself is already wrong, it won't work.

**Comment by ZaMaZaN4iK** [comment]
No, it's not deskew. It's really auto-rotating.
https://github.com/DanBloomberg/leptonica/blob/master/src/flipdetect.c

**Comment by manisandro** [comment]
Indeed, that would be `pixOrientDetec`.

**Comment by ZaMaZaN4iK** [comment]
Btw here you can see my implementation in PRLib: https://github.com/ZaMaZaN4iK/PRLib/blob/master/src/deskew/deskew.cpp

**Comment by manisandro** [comment]
Thanks - would be cool to do without the opencv dependency though.
