### ISSUE TITLE
Compiling on MSVC 2017

### ISSUE THREAD

**Issue by WRFan** [manisandro/gImageReader#428]
Compiling on MSVC 2017

I'm trying to compile gImageReader on MSVC 2017 (I want to link gImageReader against Tesseract 5 Alpha), but the compiler is throwing all over. I fixed most of the errors, but I'm stuck on several errors I can't fix:

I) Unresolved external symbol

`outputeditortext.obj : error LNK2001: Nicht aufgelöstes externes Symbol ""public: class QList<class Source *> __thiscall SourceManager::getSelectedSources(void)const " (?getSelectedSources@SourceManager@@QBE?AV?$QList@PAVSource@@@@XZ)"`

The line in question is (outputeditortext.cc):

	QList<Source*> sources = MAIN->getSourceManager()->getSelectedSources();

I also get this error for hocrodtexporter.cc, hocrpdfexporter.cc, outputeditorhocr.cc, mainwindow.cc

https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk2001

I checked the available symbols using dumpbin.exe, there's a "**struct** Source" in sourcemanager.hh, but not a "**class** Source". I added the following code to the "private" block in mainwindow.hh:

	QList<Source*> m_sources;

and the error disappeared, but I don't know if that's a proper thing to do, since I am new to this stuff, so I don't know what I'm doing most of the time.

II) acquirer.cc + scannertwain.cc fail to compile. The compiler was expecting an include called twain.h , which isn't included in the source code. So I downloaded twain v.2.4, but now I'm getting errors:

scannertwain.hh , line:

	static PASCAL TW_UINT16 callback(TW_IDENTITY* origin, TW_IDENTITY* dest, TW_UINT32 DG, TW_UINT16 DAT, TW_UINT16 MSG, TW_MEMREF data);

Errors:

	error C3646: "callback": Unbekannter Überschreibungsspezifizierer

	error C2065: "origin": nichtdeklarierter Bezeichner

	error C2275: "TW_IDENTITY": Ungültige Verwendung dieses Typs als Ausdruck

	error C2065: "dest": nichtdeklarierter Bezeichner

	error C2275: "TW_UINT32": Ungültige Verwendung dieses Typs als Ausdruck

	error C2146: Syntaxfehler: Fehlendes ")" vor Bezeichner "DG"

	error C2238: Unerwartete(s) Token vor ";"

scannertwain.cc , line:

	sources.append({sourceID.ProductName, sourceID.ProductName});

Errors:

	error C2668: "QList<Scanner::Device>::append": Mehrdeutiger Aufruf einer überladenen Funktion

	qlist.h: kann "void QList<Scanner::Device>::append(const QList<Scanner::Device> &)" sein... oder "void QList<Scanner::Device>::append(const T&)"

	with [T=Scanner::Device] bei Anpassung der Argumentliste "(initializer list)"

This is pointing to the following code in qlist.h (QT5):

	void append(const T &t);
	void append(const QList<T> &t);

scannertwain.cc , line:

	cb.CallBackProc = reinterpret_cast<TW_MEMREF>(callback);

Errors:

	error C2065: "callback": nichtdeklarierter Bezeichner

scannertwain.cc , line:

	TW_UINT16 ScannerTwain::callback(TW_IDENTITY* origin, TW_IDENTITY* /*dest*/, TW_UINT32 /*DG*/, TW_UINT16 /*DAT*/, TW_UINT16 MSG, TW_MEMREF /*data*/)

Errors:

	error C2039: "callback": Ist kein Element von "ScannerTwain"

scannertwain.cc , line:

	if(origin == nullptr || origin->Id != s_instance->m_srcID.Id)

Error:

	error C2065: "s_instance": nichtdeklarierter Bezeichner

scannertwain.cc , line:

	s_instance->m_dsMsg = MSG;

Error:

	error C2065: "s_instance": nichtdeklarierter Bezeichner

III) Can't compile enchant-2.2.7 on MSVC. Seems the code is strictly for Linux, I'm getting tons of errors, in particular with the line in lib.c:

	*strchrnul(new_tag, '@') = '\0';

Now how exactly is Windows supposed to know about Linux functions?! And there is no Windows Enchant code on the internet, at least I didn't find any. I compiled Enchant-1.6.0, but this one behaves weirdly. If I compile the code into a static library, then link the gImageReader against it:

	add_executable(gimagereader ...)

	target_link_libraries(gimagereader "c:/copy/packs/enchant/build_my/release/enchant.lib")

I am getting errors all over:

	warning LNK4098: Standardbibliothek "MSVCRT" steht in Konflikt mit anderen Bibliotheken; /NODEFAULTLIB:Bibliothek verwenden.

	warning LNK4217: Lokal definiertes Symbol "__wfopen" wurde in _enchant_fopen-Funktion importiert.

	warning LNK4217: Lokal definiertes Symbol "_fclose" wurde in _enchant_load_ordering_from_file-Funktion importiert.

and so on. But if I pass the enchant code DIRECTLY into gImageReader:

	add_executable(gimagereader
		...
		c:/copy/packs/enchant/src/enchant.c
		c:/copy/packs/enchant/src/pwl.c
	)

no warning occurs. I don't see the difference between both approaches, no idea why the compiler is complaining

**Comment by manisandro** [comment]
General note: I've never compiled gImageReader with MSVC (the Windows builds are cross-compiled with gcc/mingw), so it might involve quite some work to get it compiling. There may indeed be various dependencies which do not natively compile with MSVC, so you'd need to work yourself through those as well, as you have noticed. I don't have a MSVC install so not really able to help much I'm afraid.
Depending on your specific needs, cross-compiling with the provided docker image might be quicker (see the compilation howto in the wiki). Or if you want to avoid docker, you can try installing MINGW on your Windows system and build gImageReader with gcc that way.
