### ISSUE TITLE
Unable to compile on gentoo

### ISSUE THREAD

**Issue by enimog** [manisandro/gImageReader#432]
I tried to build the latest commit on my gentoo machine, and it fails with the following errors:

qt/src/hocr/HOCROdtExporter.cc: In member function ‘bool HOCROdtExporter::run(const HOCRDocument*, QString&)’:
qt/src/hocr/HOCROdtExporter.cc:261:35: error: incomplete type ‘QUrl’ used in nested name specifier
  261 |   QDesktopServices::openUrl(QUrl::fromLocalFile(outname));
      |                                   ^~~~~~~~~~~~~

qt/src/hocr/HOCRTextExporter.cc: In member function ‘bool HOCRTextExporter::run(const HOCRDocument*, QString&)’:
qt/src/hocr/HOCRTextExporter.cc:64:35: error: incomplete type ‘QUrl’ used in nested name specifier
   64 |   QDesktopServices::openUrl(QUrl::fromLocalFile(outname));
      |                                   ^~~~~~~~~~~~~

I guess this is a Qt5 version error. I am using version 5.14.1.

**Comment by manisandro** [comment]
Sorry for the late reply and thanks for reporting, should be fixed by 6209e25dab20b233e399ff36fabe4252db0f9e44
