### ISSUE TITLE
Add manual layout for hOCR

### ISSUE THREAD

**Issue by gjvnq** [manisandro/gImageReader#433]
Hi, I am having trouble with more complicated text layouts, especially multiple columns. I think it would be great to be able to select regions of the image and apply the current hOCR recognition individually in each of the selected areas.

**Comment by manisandro** [comment]
It's a bit a question of workflow, I suppose you could start by assuming a blank page the same size as the source image and then recognize the regions manually, and insert the recognized documents in to the blank page by offsetting the bounding box as neccessary. Needless to say it would then be up to the user to make sure that he does not recognize the same area twice etc.

**Comment by zohozer** [comment]
Yes, will be good to be able to define which portions of the image are text or pictures or tables. I do miss this feature a lot.

**Comment by manisandro** [comment]
Tracking in #438
