### ISSUE TITLE
[enhancement] Add hand tool to move image

### ISSUE THREAD

**Issue by omega3** [manisandro/gImageReader#434]
Can you add hand tool that moves image in all directions?
https://i.imgur.com/iijEXiG.png

I use this program to OCR single sentences as examples for language learning. I noticed that it sometimes works better with big zoom like 300% or more so in this type of usage it would be more handy than scrolling. And I am used to it from pdf viewers.

**Comment by manisandro** [comment]
This is already implemented, just use the middle mouse button.

**Comment by omega3** [comment]
I use normal mouse - two buttons and wheel, like this one:
https://image.ceneostatic.pl/data/products/2456560/eada30db-d3c8-4886-93ae-78353325227e_i-logitech-b110-910-001246.jpg?=364b5

Do you use some kind of gaming mouse?

Wouldn't it make sense to create icon that activates this?

**Comment by manisandro** [comment]
Don't you get the middle button by pressing the wheel? I haven't seen a mouse which does not have a middle button of some sort for over a decade to be honest :\

**Comment by omega3** [comment]
Ok. It was in settings to activate middle button.

**Comment by ZaMaZaN4iK** [comment]
@manisandro Possibly that's a good point for adding settings about user customization for hotkeys

**Comment by manisandro** [comment]
@ZaMaZaN4iK What do you mean?

**Comment by ZaMaZaN4iK** [comment]
I mean we can provide a GUI for hotkeys. User will get a possibility to choose own hotkeys for any operation in the program.
