### ISSUE TITLE
[enhancement] Allow keep custom pane layout

### ISSUE THREAD

**Issue by omega3** [manisandro/gImageReader#435]
Please, allow keep custom pane layout. For example, I like working when I have sources and translation pane on the bottom. This is because I have old narrow (1280x1024) screen. And after each program start it gets back to default pane layout. Besides sources pane cannot be closed which is not convenient. When working with only one file it is not necessary to have sources pane displayed all the time.

**Comment by manisandro** [comment]
Are you using the gtk or qt interface? The qt interface remembers the pane positions. As for closing the source pane, in both the gtk and qt interface you can close it by toggling the first button left in the toolbar.

**Comment by omega3** [comment]
I use qt interface on Manjaro Linux
https://i.imgur.com/ljNKBq9.png
Indeed sources pane can be closed. But when I move OCR  pane to the bottom and close program and start again it has default layout. 

Operating System: Manjaro Linux 
KDE Plasma Version: 5.18.3
KDE Frameworks Version: 5.67.0
Qt Version: 5.14.1
Kernel Version: 5.4.24-1-MANJARO
OS Type: 64-bit

**Comment by manisandro** [comment]
Works here on Fedora. Settings are stored in `$HOME/.config/gImageReader/gImageReader.conf`, specifically `winstate`. In you should see the value change if you change a pane position.

**Comment by omega3** [comment]
I copied the values before moving OCR pane to the bottom and after moving OCR pane to the bottom. And Kate is showing me that they are exactly the same.
https://i.imgur.com/xUAS90m.png

**Comment by manisandro** [comment]
Are the values after moving the pane copied before or after closing the program?

**Comment by omega3** [comment]
Before closing the program.

**Comment by manisandro** [comment]
The state is only serialized when the program is closed.

**Comment by omega3** [comment]
But when I closed the program they are the same. And when I reopen the program it has default layout. If values were changed it should show saved layout. Maybe it is and issue with qt. 

Ok. It is not very important. I can live with that. Maybe someone else will confirm.

**Comment by manisandro** [comment]
Did you by any chance have the window maximized when closing? If yes, this https://github.com/manisandro/gImageReader/commit/79e84fd614da8bed236b1738905082ac3111ac75 should fix the issue.

**Comment by omega3** [comment]
Yes, I have small screen and I always work with maximized windows. By the way gtk version works ok.

**Comment by manisandro** [comment]
The maximized window explains the behaviour you saw. Should be fixed by 79e84fd.
