### ISSUE TITLE
Word synchronisation between correction text field and image?

### ISSUE THREAD

**Issue by zohozer** [manisandro/gImageReader#436]
Hi. It os possible to add a word to image synchronisation in gImageReder?

Please check [this video](https://youtu.be/pKmtT7uD_xk?t=297) about how to use FineReader. At min. 4:57it is showing that clicking on the text window from the right will highlight the corresponding character on the image, both on the left page image and also on the bottom zoomed section of the image.

As I do need to correct the OCR-ed text, this feature will help tremendously as I will have a reference of where it is located the corrected text into the original image.

**Comment by manisandro** [comment]
This is already the case in the hOCR editor, unless I misunderstood your question?

![image](https://user-images.githubusercontent.com/1298852/77233157-d7a65700-6ba5-11ea-9416-c30753c17ca9.png)

**Comment by zohozer** [comment]
Unfortunately this feature it is missing in OCR mode: Plain text.

**Comment by manisandro** [comment]
There is now way to implement it there since in plain text mode all text layout information is discarded.

**Comment by zohozer** [comment]
It is possible to have a more compact version of the "Output" tree? The right panel from the picture on top of this tread? It is very difficult to navigate and check all the tree. I am very used to do OCR in ABBYY Fine Reader, and there it is so easy to correct the OCR text.

**Comment by manisandro** [comment]
Would the approach outlined in https://github.com/manisandro/gImageReader/issues/438#issuecomment-602771732 help?
