### ISSUE TITLE
gImageReader build for MacOS?

### ISSUE THREAD

**Issue by zohozer** [manisandro/gImageReader#437]
As a Mac user will be very helpful to have a native build of gImageReader for MacOS. Right now I am trying to use-it through Vine, but without great results as the dialog boxes don't want to close once I open them, I need to close the whole app. A native MacOS build will be welcomed. Thank you.

**Comment by manisandro** [comment]
Sorry, but someone who actually owns a Mac will need to do this. Apple makes it very hard to develop anything for their platform without buying the corresponding hardware.
