### ISSUE TITLE
How to improve ocr reader?

### ISSUE THREAD

**Issue by TeoColuccio** [manisandro/gImageReader#439]
The quality is already very good, but is lower than abby finereader. This is a comparison between abby and gimagereader ocr:
![Schermata da 2020-03-24 02-59-00](https://user-images.githubusercontent.com/16000669/77488741-5adddc00-6e36-11ea-9060-04493a6e3a4e.png)
How we can improve it?

**Comment by manisandro** [comment]
gImageReader is only a frontend, the recognition is done by tesseract, so you'll want to pursue there issue there. You can start by going through https://tesseract-ocr.github.io/tessdoc/, you many also want to read the section about training. If there is a particular tesseract option which helps your case that you feel should be exposed in gImageReader, please feel free to file an issue here.

**Comment by TeoColuccio** [comment]
I discovered that the problem is not with reading, but with exporting to pdf. As I have tried to save both readings as txt files and they are almost the same. So how can I make the export more like abby's? With the text precisely on the document, all aligned I mean ..

**Comment by manisandro** [comment]
That again is tesseract behaviour, as tesseract generates the hOCR file which contains all the text layout information.

**Comment by TeoColuccio** [comment]
Ok, thanks for the help

**Comment by TeoColuccio** [comment]
I'm not sure that is tesseract's fault. This because I used it trough terminal with
`tesseract tphoto.png photo-eng -l eng hocr`
and the obtained coordinates seem correct. I'll upload it in attachment.
[pho-eng.txt](https://github.com/manisandro/gImageReader/files/4389900/pho-eng.txt)

**Comment by manisandro** [comment]
That attachment contains just text - but gImageReader does not recompute any coordinates unless you change them manually.
