### ISSUE TITLE
multi pages for PDF?

### ISSUE THREAD

**Issue by manuelsongokuh** [manisandro/gImageReader#44]
hello

i did add source file PDF (multi-pages) and first page is 1 but where i go to page 2,3,4,5,etc?

**Comment by manisandro** [comment]
Hi, there is a spinbox which appears in the toolbar next to the rotation spinbox where you can select the page to display.

**Comment by manuelsongokuh** [comment]
ok, sorry, that is not clear visual design.. cloud be write word: "page" because that icon is not clear..
rotation near page is too... so that is not clear..

proposal:
A-
add word "page" (page+icon)
far between rotation, page, not near.. 

do you think about this?

**Comment by manisandro** [comment]
Dunno, for consistency I'd then need to add labels everywhere, which would greatly increase the width occupied by the toolbar. I'd rather leave things like they are now.
