### ISSUE TITLE
Reset my preferences

### ISSUE THREAD

**Issue by TeoColuccio** [manisandro/gImageReader#443]
I've done many changes and i'd like return to default settings. I tried "apt purge", but nothing, my changes remained.

**Comment by manisandro** [comment]
Use profile settings are never removed by a package manager. You'll need to remove these manually. You should be able to remove the settings using `dconf-editor`.

**Comment by TeoColuccio** [comment]
Ok thanks

**Comment by TeoColuccio** [comment]
I can reset with "dconf reset -f / org / gnome / gimagereader" but it might be useful to add a button with "Reset all my changes", so as to use the function regardless of the operating system
