### ISSUE TITLE
UI Language

### ISSUE THREAD

**Issue by bini2215** [manisandro/gImageReader#444]
Hi, we are translating gImageReader UI on new language, but i am unable to find where to change it from English.

**Comment by manisandro** [comment]
There is currently no GUI option to select the language, but you can launch the application from the command line while setting the LANG environment variable, under linux i.e.:

    LANG=de_CH.utf8 gimagereader-qt5

or under Windows

    set LANG=de
    gimagereader-qt5.exe

**Comment by bini2215** [comment]
i tired under windows and it works, but is there any way to make it default ?
Thanks

**Comment by manisandro** [comment]
Currently no, unless you set the environment variable system wide, which you probably don't want to do. Otherwise you can just create a `bat` file which contains the commands and start the application through the that.

**Comment by bini2215** [comment]
I have the following error when i try to compile with the following command:
docker run -v $PWD:/workspace gimagereader_buildenv packaging/win32/makeinstaller.sh i686 qt5

...............
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: CMakeFiles/gimagereader.dir/objects.a(ScannerTwain.cc.obj): in function `ScannerTwain::doStop()':
/workspace/qt/src/scanner/ScannerTwain.cc:344: undefined reference to `Scanner::scanStateChanged(Scanner::State)'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: CMakeFiles/gimagereader.dir/objects.a(ScannerTwain.cc.obj): in function `ScannerTwain::init()':
/workspace/qt/src/scanner/ScannerTwain.cc:108: undefined reference to `Scanner::initFailed()'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: /workspace/qt/src/scanner/ScannerTwain.cc:150: undefined reference to `Scanner::initFailed()'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: /workspace/qt/src/scanner/ScannerTwain.cc:86: undefined reference to `Scanner::initFailed()'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: CMakeFiles/gimagereader.dir/objects.a(ScannerTwain.cc.obj): in function `ScannerTwain::redetect()':
/workspace/qt/src/scanner/ScannerTwain.cc:173: undefined reference to `Scanner::devicesDetected(QList<Scanner::Device>)'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: CMakeFiles/gimagereader.dir/objects.a(ScannerTwain.cc.obj): in function `ScannerTwain::scan(Scanner::Params const&)':
/workspace/qt/src/scanner/ScannerTwain.cc:182: undefined reference to `Scanner::scanStateChanged(Scanner::State)'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: /workspace/qt/src/scanner/ScannerTwain.cc:202: undefined reference to `Scanner::scanStateChanged(Scanner::State)'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: /workspace/qt/src/scanner/ScannerTwain.cc:244: undefined reference to `Scanner::scanStateChanged(Scanner::State)'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: /workspace/qt/src/scanner/ScannerTwain.cc:295: undefined reference to `Scanner::scanStateChanged(Scanner::State)'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: /workspace/qt/src/scanner/ScannerTwain.cc:320: undefined reference to `Scanner::pageAvailable(QString const&)'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: CMakeFiles/gimagereader.dir/objects.a(ScannerTwain.cc.obj): in function `ScannerTwain::failScan(QString const&)':
/workspace/qt/src/scanner/ScannerTwain.cc:349: undefined reference to `Scanner::scanFailed(QString const&)'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: /workspace/qt/src/scanner/ScannerTwain.cc:349: undefined reference to `Scanner::scanFailed(QString const&)'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: /workspace/qt/src/scanner/ScannerTwain.cc:349: undefined reference to `Scanner::scanFailed(QString const&)'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: /workspace/qt/src/scanner/ScannerTwain.cc:349: undefined reference to `Scanner::scanFailed(QString const&)'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: /workspace/qt/src/scanner/ScannerTwain.cc:349: undefined reference to `Scanner::scanFailed(QString const&)'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: CMakeFiles/gimagereader.dir/objects.a(ScannerTwain.cc.obj):/workspace/qt/src/scanner/ScannerTwain.cc:349: more undefined references to `Scanner::scanFailed(QString const&)' follow
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/gimagereader.dir/build.make:689: gimagereader-qt5.exe] Error 1
make[2]: Leaving directory '/workspace/build/mingw64-qt5'
make[1]: *** [CMakeFiles/Makefile2:181: CMakeFiles/gimagereader.dir/all] Error 2
make[1]: Leaving directory '/workspace/build/mingw64-qt5'
make: *** [Makefile:147: all] Error 2

**Comment by manisandro** [comment]
Uhm, that's odd, not sure what happened there. There is a CI build which is using the same docker container which regularly runs through. Perhaps try recreating the container?

**Comment by bini2215** [comment]
Its a clean install of Ubuntu 19 (VM) and docker.io, nothing else. Maybe there is something else i need to configure/install?

**Comment by manisandro** [comment]
Uhm not really no, but what is strange is that you are running

    packaging/win32/makeinstaller.sh i686 qt5

whereas it clearly gets built for x86_64.

Can you attach the full output?

**Comment by bini2215** [comment]
Sorry my mistake about messing x64 and x86, i tried both thats why i messed them up.
Here i am attaching a .txt file with full output.
[gimagereaderError.txt](https://github.com/manisandro/gImageReader/files/4458013/gimagereaderError.txt)

**Comment by manisandro** [comment]
The reason is this:

     Policy CMP0100 is not set: Let AUTOMOC and AUTOUIC process .hh files.  Run
      "cmake --help-policy CMP0100" for policy details.  Use the cmake_policy
      command to set the policy and suppress this warning.
    
      For compatibility, CMake is excluding the header file(s):

Either use a current git checkout of gImageReader, or backport at least https://github.com/manisandro/gImageReader/commit/197cf34eacb04fdb91845a50fe82326a16ccc9d2#diff-af3b638bc2a3e6c650974192a53c7291

**Comment by bini2215** [comment]
Thank you. Works now.
