### ISSUE TITLE
incorrect res (resolution) of 50 assumed in hOCR files without res set

### ISSUE THREAD

**Issue by ospalh** [manisandro/gImageReader#447]
gImageReader seems to assume a res (resolution) of 50 for hOCR files it reads when none is set.
tesseract does not set the res in its hOCR output but uses a value of 100.
This means that text boxes from hOCR files produces via command line tesseracrt apear twice as far to the right and down as they should.

Example files in the zip:
[bad-res-demo.zip](https://github.com/manisandro/gImageReader/files/4461369/bad-res-demo.zip)

* `colophon.tif`: Colophon of a book as an example page
* `colophon_gImageReader.html`: The hOCR file produced with gImageReader
* `colophon_tesseract_as_is.html`: The hOCR file as produced with a command line call to tesseract
* `colophon_tesseract_with_explicit_res.html`: The same with “res 100” added to the “title” of the ocr_page div tag.

Loading colophon_gImageReader.html in the output pane and clicking on elements in the tree view neatly highlights the corresponding elements in the image pane.
With colophon_tesseract_as_is.html, clicking on elements highlights boxes twice the correct size, shifted down and right to twice the correct distance.
With colophon_tesseract_with_explicit_res.html everything is fine again.

Versions:
gImageReader Qt 3.3.1, the version on my system
tesseract 4.1.0

**Comment by manisandro** [comment]
Thanks for the report!

Actually it would have set resolution to 0 except that 50 is the minimum of the spinbox. I've now made it default to 100 if `"res"` is missing. Fixed in https://github.com/manisandro/gImageReader/commit/7d71d0e0df08fb2a1ca7280d524c8e69258255c1.

**Comment by ospalh** [comment]
Thanks for the quick fix.
