### ISSUE TITLE
is it possible: middle-mouse like as pan the view?

### ISSUE THREAD

**Issue by manuelsongokuh** [manisandro/gImageReader#45]
hi
i wish improvement to gimagereader:
i will do hold down the middle mouse button and move the mouse pointer to pan the view.

is it possible?

**Comment by manisandro** [comment]
Yes this is a valid point.

**Comment by manuelsongokuh** [comment]
well, when will be release..? date schedule ?

**Comment by manisandro** [comment]
Well, when I have time. Sorry but I've got many other things on my todo list also.

**Comment by manisandro** [comment]
Implemented in 4a79515.

**Comment by manuelsongokuh** [comment]
THANKYOU!!!!!!!!!!!!
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:
