### ISSUE TITLE
BUG: When I add multiple images, gImageReader shows overlapping preview of all pages! 

### ISSUE THREAD

**Issue by raindropsfromsky** [manisandro/gImageReader#450]
I added two images, as shown below.

**Image#1**
![image](https://user-images.githubusercontent.com/9047168/79179162-a297c800-7e24-11ea-9398-ab022c6a16e3.png)

**Image#2**
![image](https://user-images.githubusercontent.com/9047168/79179183-acb9c680-7e24-11ea-9155-97f504638e2f.png)

And then ran OCR on them. At first, the preview of the current image looks fine. 

But if I switch between the images, I get this display:
![image](https://user-images.githubusercontent.com/9047168/79179316-fdc9ba80-7e24-11ea-9390-0ca6eb06facf.png)

(Instead of showing preview of one image at a time, gImageReader shows previews of both!)

Note that I did NOT select both images simultaneously (the thumbnail shows only one image at any given point of time).

Further observation: The overlapped preview occurs only when I select the first image that I pasted. 

When I repeated the experiment with 3 images, the last image was selected when I did the OCR. So now its preview is superimposed on the other two images. But if I click on the images, they show their own preview also.

**Comment by manisandro** [comment]
It is just that the preview refers to the current page selected in the hOCR tree, it should be a bit smarter and either deactivate if the selected image does not exist in the hOCR tree, or automatically switch to the corresponding page if it does.

**Comment by manisandro** [comment]
Done (for Qt interface, Gtk will get it when I get it on par again)
