### ISSUE TITLE
Bug: The "Take screenshot" function does not minimize the gImageReader GUI itself

### ISSUE THREAD

**Issue by raindropsfromsky** [manisandro/gImageReader#451]
IINW the purpose of the "take screenshot" function is to OCR the screen in the background. In many cases, the user may want to OCR only a particular frame of the screen, and not the whole screen.

Anyhow, the purpose is defeated because the gImageReader's own GUI is always in the screenshot!

**Desired:** Please minimize the gImageReader GUI and then take the screenshot.

**Comment by manisandro** [comment]
Done (for Qt inferace, Gtk will get it when I get it on par again)
