### ISSUE TITLE
UI Language

### ISSUE THREAD

**Issue by bini2215** [manisandro/gImageReader#453]
Hi
i need to add 3 languages in UI (pic attached).
<img width="146" alt="ocrlang" src="https://user-images.githubusercontent.com/11375174/79224666-cd514300-7e5b-11ea-8468-de8af5a0c299.png">

i have created 3 .vbs scripts and 3 .bat:
en.vbs; en.bat
mk.vbs; mk.bat
sq.vbs; sq.bat

When 'Makedonski' is clicked from menu; i want to run mk.vbs which will create a shortcut on desktop of mk.bat
mk.bat contains 'set LANG:mk' which will launch the app in Macedonian language.
and a popup saying please restart application.

same procedure for other 2 languages.
the vbs script will replace the shortcut on desktop.

Currently im stuck at calling .vbs scripts from the app.
i have just created the languages from menu as can be seen from picture attached.
I would be thankful if someone helps me.

**Comment by manisandro** [comment]
Rather than a hacky approach like that it would be better to just add a language selection combo in the settings dialog.

**Comment by bini2215** [comment]
Firs time on C++, im doing it with Notepad++.
What IDE do you prefer for C++
