### ISSUE TITLE
Compile error on Debian Bullseye: variable ‘QVector<QStringRef> words’ has initializer but incomplete type

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#455]
`cmake -DINTERFACE_TYPE=qt5 .. && make`
[...]
`[ 86%] Building CXX object CMakeFiles/gimagereader.dir/qt/src/hocr/HOCRSpellChecker.cc.o
.../gImageReader/qt/src/hocr/HOCRSpellChecker.cc: In member function ‘bool HOCRSpellChecker::checkSpelling(const QString&, QStringList*, int) const’:
.../gImageReader/qt/src/hocr/HOCRSpellChecker.cc:26:22: error: variable ‘QVector<QStringRef> words’ has initializer but incomplete type
   26 |  QVector<QStringRef> words = word.splitRef(QRegExp("[\\x2013\\x2014]+"));
      |                      ^~~~~
.../gImageReader/qt/src/hocr/HOCRSpellChecker.cc:26:72: error: invalid use of incomplete type ‘class QVector<QStringRef>’
   26 |  QVector<QStringRef> words = word.splitRef(QRegExp("[\\x2013\\x2014]+"));
      |                                                                        ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:1204,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qnamespace.h:43,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:48,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:46,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QObject:1,
                 from /usr/local/include/QtSpell-qt5/QtSpell.hpp:28,
                 from .../gImageReader/qt/src/hocr/HOCRSpellChecker.hh:23,
                 from .../gImageReader/qt/src/hocr/HOCRSpellChecker.cc:22:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qtypeinfo.h:193:1: note: declaration of ‘class QVector<QStringRef>’
  193 | Q_DECLARE_MOVABLE_CONTAINER(QVector);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/gimagereader.dir/build.make:548: CMakeFiles/gimagereader.dir/qt/src/hocr/HOCRSpellChecker.cc.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:164: CMakeFiles/gimagereader.dir/all] Fehler 2
make: *** [Makefile:130: all] Fehler 2
`

**Comment by manisandro** [comment]
Does 77780ee259d68eee7d3a6fed8bf70657c3f87dd4 help?

**Comment by SantosSi** [comment]
Yes, that worked. You're the best.
