### ISSUE TITLE
Missing translated words

### ISSUE THREAD

**Issue by bini2215** [manisandro/gImageReader#456]
We have Translated 100% but there are still words in English (Files; Acquire; Devices; Output; Mode; Resolution) as can be seen in screenshot.
<img width="414" alt="translation issue" src="https://user-images.githubusercontent.com/11375174/80307708-16de4e00-87cb-11ea-828b-e4b1555a8a47.png">

**Comment by manisandro** [comment]
Looks like the UI file isn't being translated, I'll look into it.

**Comment by manisandro** [comment]
Fixed, thanks for reporting!
