### ISSUE TITLE
Missing extended characters in output for Polish

### ISSUE THREAD

**Issue by KFoster2** [manisandro/gImageReader#457]
In HOCR mode, when I export as Plain text, the extended characters are missing in the txt output for Polish.

As a example, the word "złożyć" is recognized correctly but it is exported as "zlozyc" in the txt.

I have tried to save the TXT as ANSI or UTF-8 but it does not work either.

Any ideas?

**Comment by manisandro** [comment]
Can you attach the hOCR file? What OS are you on?

**Comment by KFoster2** [comment]
Here you go.
I have attached the txt export as well as HOCR output along with the original tiff.
It works in the hocr html export but not as plain text.
I am using Windows 10.
[sample.zip](https://github.com/manisandro/gImageReader/files/4547115/sample.zip)

**Comment by manisandro** [comment]
Works if I choose UTF-8 as text file encoding in the settings:

![image](https://user-images.githubusercontent.com/1298852/80512409-b9d6c980-897d-11ea-9237-f3edc0596a91.png)

Possibly UTF-8 should just be made default.

**Comment by KFoster2** [comment]
It works now :) Thanks a million for your quick support!

**Comment by manisandro** [comment]
Welcome
