### ISSUE TITLE
Connecting/merging words from different TextLines

### ISSUE THREAD

**Issue by KFoster2** [manisandro/gImageReader#458]
In hOCR mode, I can see that text blocks are split into Paragraphs and Textlines. In some cases, the last word of a line falls into the next Textline section. 

Is it possible to connect or merge a word from a Textline into the next one? Otherwise, the output will show some words separated by hard returns but they should be in the same line. 

Hope this explains and sorry if this was answered in another thread.

**Comment by manisandro** [comment]
Probably easiest to understand if you attached a picture.

**Comment by KFoster2** [comment]
Hope this explains better.
<img width="179" alt="image" src="https://user-images.githubusercontent.com/62470748/80520206-67030f00-8989-11ea-8286-961ca1d895bb.png">

**Comment by manisandro** [comment]
Currently not easily doable, would be doable if I got around to implement drag and drop in the tree. At the moment best you can do is delete "haunted" and add readd it as a new word to the desired text line.

**Comment by KFoster2** [comment]
Got you. It would be awesome if you can add drag&drop feature in the next release.

Again, thanks for your help!

**Comment by manisandro** [comment]
Tried it once and got stuck, but I still have the work in progress lying around. Anyway, tracking this in #438.
