### ISSUE TITLE
The proofreading widget allows change of font size in widget text itself; not in OCRed text!

### ISSUE THREAD

**Issue by raindropsfromsky** [manisandro/gImageReader#459]
I am using the latest CI master (downloaded on 1st May, at 1:30 pm in India (IST = UTC+5.5).
My Windows is Win 10 Home, 64 bits.

I expected the proofreading widget to have controls that change the font size of the OCRed text.
Instead, the CTRL++ and CTRL+- change the font size in the widget itself!

Please see the screenshot of GitHub page:
![image](https://user-images.githubusercontent.com/9047168/80793062-b462c480-8bb3-11ea-8613-549ff1b13fc6.png)

Here, there is a large overlap between the words "Manisan**dro** **com**mitted"
So I wanted to reduce the font size of the OCRed text (outlined in the blue rectangle). 

But when I press the keyboard shortcuts, GImageReader changes the font size of the widget text itself! (outlined in red rectangle)

Now I am not against having such an adjustable widget, but our main focus should be on making the OCRed text readable, by adjusting its font size and kerning. This is still not achieved.

**Desired:**
Provide four additional shortcuts:
1. Two controls to increase and decrease the font size.
2. Two controls to increase and decrease kerning between the letters.

**Comment by manisandro** [comment]
You are welcome to post pull requests for the behaviour you desire.

**Comment by raindropsfromsky** [comment]
IINW a pull request can be raised by coders. But I am not a coder.
