### ISSUE TITLE
not work device scanner: hp network..?

### ISSUE THREAD

**Issue by manuelsongokuh** [manisandro/gImageReader#46]
hi

my scanner is hp, connect to wifi router switch, LAN home.

gimagereader not show list device.. buy my icon tray of HP there is device..
hp photosmart 5520 seires

Bonjour, ip, 

skanlite worked and xsane worked 
gimagereader not worked...
this is bug or something error config?

**Comment by manisandro** [comment]
Uhm, I'm calling `sane_get_devices(&device_list, false)`, the declaration being

    SANE_Status sane_get_devices (const SANE_Device *** device_list, SANE_Bool local_only)

so not sure what is the issue, but gImageReader definitely looks for remote scanners also (and I have seen it work with a scanner shared over LAN).

**Comment by manuelsongokuh** [comment]
i find resolve:
go to /etc/sane.d/dll.conf  (open with sudo gedit)
change from #hpaio to hpaio
save
and open gimagereader is worked!

**Comment by manisandro** [comment]
Okay, cool.
