### ISSUE TITLE
Bug: In a table, the vertical cell boundary is detected as a character (only in some cells)

### ISSUE THREAD

**Issue by raindropsfromsky** [manisandro/gImageReader#461]
If the image is a table, gImageReader detects the vertical cell boundary of many (-but NOT all-) cells, and interprets it as different characters. These are mostly converted into **]**, **}** and **)**.

See the sample image below:
![image](https://user-images.githubusercontent.com/9047168/81460056-86d3d780-91c0-11ea-8a88-2ff5e217f03c.png)

It is very tedious to remove these spurious characters.

**Desired:** 
1. If possible, please avoid this detection.
2. Otherwise, in the _proofreading_ stage, please provide a **find-and-replace** tool.

**Comment by manisandro** [comment]
There is already a find and replace tool in both hocr and text mode. Everything else is up to tesseract.
