### ISSUE TITLE
[Windows 7] No OCR without admin

### ISSUE THREAD

**Issue by galdring** [manisandro/gImageReader#464]
I'm trying to get gImage Reader to work for a colleague in our university. It's installed and I can choose the images I want to OCR, but when I click on the "Recognize all"-button, nothing happens.
If I start it as admin (default users on our university's PCs don't have admin priviliges), gImage Reader runs without any issues.
I'm guessing the software needs some rights it doesn't get if it's not admin, but what can I do to get it working?
I've tried installing it for all users (in program files/gImage Reader) and (after uninstalling) installing it for one user only in their userhome (user/Appdata/Local/gImage Reader), same result.

I couldn't find any issues on this, did anybody encounter the same problem and fix it somehow?

**Comment by manisandro** [comment]
I have never received any similar reports and there is nothing inside gImageReader which requires admin privileges. I suspect some policy on these machines, but it's impossible to tell without further debugging. I'd try with [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) and see if there are any obvious failures to open a file or such.
