### ISSUE TITLE
Can not export PDF: ePdfError_UnSupportedFontFormat

### ISSUE THREAD

**Issue by suokunlong** [manisandro/gImageReader#465]
Steps to Reproduce:
1. Open any PDF document with gImageReader. For instance, a simple pdf document created with LibreOffice Writer with plain text.
2. Do OCR recognition.
3. Try to export as PDF.

Shows error message in step 3: Can not export PDF: ePdfError_UnSupportedFontFormat

gImageReader 3.3.1, installed from Fedora official repo.
Fedora 32
tesseract 4.1.1.
LANG=zh_CN.UTF-8

**Comment by manisandro** [comment]
Might be related to the Chinese script. Does the same happen with the QPainter backend?

**Comment by suokunlong** [comment]
> Might be related to the Chinese script. Does the same happen with the QPainter backend?

How can I use the QPainter backend?

**Comment by manisandro** [comment]
Oh, are you using the gtk or qt front-end? In the qt front-end you can choose.

**Comment by suokunlong** [comment]
I am in Fedora 32 default config, so I guess it should be GTK.

**Comment by manisandro** [comment]
Both variants are available on Fedora.

**Comment by lnicola** [comment]
I got the same error in the Qt frontend with PoDoFo. The PDF is in English and the export only fails at the end. I used the invisible text layer option.

**Comment by manisandro** [comment]
@lnicola How did you install gImageReader? Self-compiled / windows package / distro package (which?)? Can you share the hOCR file + sources which trigger the error?

**Comment by lnicola** [comment]
@manisandro Arch Linux package. I'm not sure I can share the PDF unfortunately, but the export works if I disable the font size override and change the font override from Cantarell to DejaVu Sans. Maybe PoDoFo doesn't like my Cantarell font (OpenType).

**Comment by manisandro** [comment]
Thanks for the info, I'll check it out. It's unlikely related to the specific PDF in this case, but rather indeed with the font. Probably not much I can do about that in gImageReader, except possibly improving the error handling/display.

**Comment by lnicola** [comment]
I also tried with the GTK front-end, it's about the same, but it outputs a 2 GB PDF on export (the hOCR is 13 MB).

**Comment by mattia-b89** [comment]
I cannot reproduce the issue.
Is it still here?

**Comment by manisandro** [comment]
I also cannot reproduce it anymore. Please reopen if it still applies.

**Comment by HunterZ** [comment]
How does one reopen a bug? I'm seeing this in Debian with gImageReader 3.3.1 with a PDF that I'm tweaking the OCR text for, including via the use of some OTF fonts manipulated in FontForge.

**Comment by edward-dauvergne** [comment]
Only a member of the project can reopen it.  This bug still occurs in the master branch a0db3dc13430afdc20f4fa42f338bf4737f8b001.  I see it for all of the `Noto Sans` fonts using the PoDoFo backend.  The QPainter backend does not have this issue.
