### ISSUE TITLE
Enable low-confidence checking filter

### ISSUE THREAD

**Issue by talentoscope** [manisandro/gImageReader#467]
![image](https://user-images.githubusercontent.com/22162766/89069982-1b874500-d36c-11ea-8655-876dcffbe98d.png)

This addition is great, but it would be nice if we could also quickly sift through the low-confidence boxes too. 

Would definitely help verify text in cases where it is okay in the dictionary, but not necessarily correct (quotes, commas, etc.)

**Comment by manisandro** [comment]
I've added low confidence words (i.e. w_conf < 90) as an option in the hOCR tree quick navigation bar:

![image](https://user-images.githubusercontent.com/1298852/150873981-48b0093e-bddb-443b-8134-5413bae4b919.png)

**Comment by talentoscope** [comment]
omg this is absolutely phenomenal, thank you so so much!!!!
