### ISSUE TITLE
gImageReader as command line tool only

### ISSUE THREAD

**Issue by Skywalker13** [manisandro/gImageReader#468]
Hi,

You app is great, and I'm sure that it will be very useful if we can use it by command line in order to OCR and export for example to PDF with transparent texts.

I tested pdfsandwich but it doesn't work fine (for me) like gImageReader.

Regards

**Comment by manisandro** [comment]
You can use the tesseract command line executable which should give you a very similar result as gImageReader is just a frontend to tesseract in the end.

**Comment by Skywalker13** [comment]
It's possible to see somewhere the commands sent by gImageReader to tesseract?

**Comment by manisandro** [comment]
Not the commands as you'd enter them when invoking tesseract on the command line, as gImageReader uses the C++ API of tesseract, not the command line tool directly.

**Comment by Skywalker13** [comment]
It looks like that the whole PDF stuff is fully handled by gImageReader, https://github.com/manisandro/gImageReader/blob/884db2252e9eb9ffd6990a36d54d4b63289447ab/gtk/src/hocr/HOCRPdfExporter.cc#L529

It's not just a tesseract frontend. I see no way to produce a PDF with text overlay with tesseract without gImageReader. I'm sure that this issue is still relevant.

**Comment by manisandro** [comment]
Tesseract produces a pdf if you append `pdf` to the command line arguments, say

    tesseract <inputfile> <outputname> pdf

gImageReader contains a hOCR editor to manipulate the document tree post recognition and then allows you to produce a pdf from the that tree, hence the reimplemented PDF exporting functionality.

**Comment by Skywalker13** [comment]
Okay, thank you...  But it seems that tesseract can't use a PDF as inputfile then I miss something in the process...

**Comment by manisandro** [comment]
There are various tools to convert between image formats in case, i.e. ImageMagick
