### ISSUE TITLE
New (bugfix) release

### ISSUE THREAD

**Issue by vitlav** [manisandro/gImageReader#471]
Please make a new release (set tag and release tarball).

**Comment by manisandro** [comment]
I'll do so when I've finished getting the Gtk version on par with the Qt version.

**Comment by vitlav** [comment]
I believe it is a good idea to make release to fix build with new gcc, Qt and so on.
For example, https://github.com/manisandro/gImageReader/commit/6209e25dab20b233e399ff36fabe4252db0f9e44
