### ISSUE TITLE
Correlate the recognized character under cursor in the output to its origin on the image by highlighting

### ISSUE THREAD

**Issue by AvtechScientific** [manisandro/gImageReader#472]
First of all - thank you for the great application you have coded. It is by far the most elegant GUI for tesseract I was able to find.

It would make the manual process of proof-reading/editing the recognized text much easier if there were some sort of visual correlation between the character under cursor inside the output panel (especially in the "Plain text" mode) and that same original character on the image. Maybe some sort of blue, semi-transparent rectangle that highlights the original character on the image and moves there according to the cursor movement in the output panel.

As an extra helpful assistance - it would be nice to have an optional highlighting of low confidence characters on the image (by let's say red, semi-transparent rectangles) so that proof-reader/editor can prioritize them.

**Comment by manisandro** [comment]
So, the plain text mode is just that - plain text. There is no information about the document structure, hence there is now way to add visual correlation. This is only possible in hOCR mode.

**Comment by AvtechScientific** [comment]
Hmm... technically it is definitely possible. ABBYY FineReader does it. Maybe it utilizes the information about the document structure from the hOCR mode while creating some sort of overlapped Plain Text view. That way it is much more easier/natural to proof-read then in hOCR mode. Also highlighting in hOCR right now works per word and not per character (i.e. less fine-tuned)...

**Comment by manisandro** [comment]
Technically it surely is possible, it basically means creating a text view using the hOCR document as a model and then figuring out what to do with the hOCR model as the user starts freely altering the text. Pull requests welcome if someone wants to work on it. But I'd just suggest using the hOCR mode with the proof-read widget.

**Comment by AvtechScientific** [comment]
Sounds interesting... (I mainly use Gnome/gtk though). Thanks!

**Comment by manisandro** [comment]
I'll eventually port it also to Gtk and then release a new version.
