### ISSUE TITLE
Utilize GtkSourceView in the Output (in Plain Text mode)

### ISSUE THREAD

**Issue by AvtechScientific** [manisandro/gImageReader#473]
It would be nice to have [GtkSourceView](https://wiki.gnome.org/Projects/GtkSourceView) widget in the output instead of the standard GtkTextView. The widget substitution shouldn't be too problematic.

Advantages:
- source code syntax will be highlighted automatically. 
- documents editing in Markdown or other leighweight markup languages will be assisted by syntax highlighting.

**Comment by manisandro** [comment]
Actually, it is already a GtkSourceView: https://github.com/manisandro/gImageReader/blob/master/gtk/data/OutputEditorText.ui#L384

I think you need to explicitly select the syntax highlighting language, it's not done automatically?

**Comment by AvtechScientific** [comment]
> Actually, it is already a GtkSourceView: https://github.com/manisandro/gImageReader/blob/master/gtk/data/OutputEditorText.ui#L384

Hey, that's great!

> I think you need to explicitly select the syntax highlighting language, it's not done automatically?

True. [Gedit](https://wiki.gnome.org/Apps/Gedit) has a small drop-down menu on the bottom to select target language. Is it possible to add something like this?

![Select_Dar](https://user-images.githubusercontent.com/12374315/93525281-74bc2f80-f93e-11ea-9cff-0a87b6e44ea1.png)

**Comment by manisandro** [comment]
Probably not any time soon, but I'm happy to accept pull requests.

**Comment by AvtechScientific** [comment]
Hi,

there is somebody who wants to implement this functionality. She codes on Windows though. I looked into [info on compilation](https://github.com/manisandro/gImageReader/wiki/Compiling-gImageReader) but in its Windows section I only see the way to compile Qt GUI. Looks like the [Dockerfile](https://github.com/manisandro/gImageReader/blob/master/packaging/win32/Dockerfile) doesn't provide Gtk dependencies either. On the other hand [makeinstaller.sh](https://github.com/manisandro/gImageReader/blob/master/packaging/win32/makeinstaller.sh) mentions Gtk.

Could you, please, provide additional instructions/example on the above mentioned wiki page - how to compile Gtk GUI on Windows. Thank you!

**Comment by manisandro** [comment]
Hi
I honestly have no idea whether the Gtk port works on Windows, I gave up on it at the time and switched to Qt for Windows. makeinstaller.sh still has the logic used at the time to produce the windows Gtk builds.

I'd recommend running Fedora in a virtual machine, where you can just run

    dnf builddep gimagereader

to get all dependencies.

**Comment by AvtechScientific** [comment]
1. You now implement everything twice (for Gtk and for Qt) just because you didn't manage to compile pure Gtk on Windows?...
2. Using Fedora will not help us, even if we manage to compile the source, because we do need the GtkSourceView widget to run on Windows...

What do you suggest? Put effort into compiling the Gtk GUI for Windows?... Let's assume that this will succeed at some point:
3. Do you think there will be a need to polish/debug the Gtk GUI, since it was never tested on Windows?
4. What will this mean for the Qt? Will you abandon it?...

**Comment by AvtechScientific** [comment]
Look, what I've just found:

https://github.com/NoraCodes/rust-mingw64-gtk-docker

It uses your approach.

**Comment by AvtechScientific** [comment]
Could you, please, elaborate on the above questions 1, 3 and 4... so I can decide whether or not should I invest efforts into trying to compile the Gtk interface for Windows...

**Comment by manisandro** [comment]
1. There was a general interest in Qt, and instabilities running Gtk on Windows was added to the motivation to port the codebase to Qt
2. You can cross-compile from Fedora to Windows, so you can develop on Linux and then run the end-product on Windows
3. Really depends what are the reasons for specifically wanting to use the Gtk interface on Windows. Gtk was initially used on Windows, so isn't fundamentally impossible to get working, but I haven't even compiled it for Windows in many years.
4. Qt is usually the variant where I do the development, and I just try to keep Gtk on par. If at one point I'll deem it too much effort, it will probably be the Gtk interface I'll drop, even though I have an interest in keeping both alive, even just to keep up-to-date with both toolkits.

**Comment by AvtechScientific** [comment]
Thank you. So we will start with implementing it on/for Linux.
Do you have instructions on how to compile gImageReader (the Gtk part of it) in Debian10/Ubuntu?

**Comment by manisandro** [comment]
The instructions here should get you started on Debian/Ubuntu:

https://github.com/manisandro/gImageReader/wiki/Compiling-gImageReader

**Comment by AvtechScientific** [comment]
@manisandro - I'm currently working on implementing this issue and need a bit of your assistance... I've checked the way Language Highlighting selection works in Gedit and came to the conclusion that such a drop-down widget might overload the gImageReader UI unnecessarily. So I'm wondering whether there gImageReader has some sort of config file, like `/etc/gimagereader.conf` or `~/.gimagereader.conf` where we can add an additional parameter, like `highlight_language=c++`?

Thank you!

**Comment by AvtechScientific** [comment]
I've managed to make significant progress here. I'm in the final stage now. I'm implementing this method that will activate syntax highlight mode that was specified in Preferences upon pressing on the OK button:

```
void Config::activateHighlightMode() {
	Glib::RefPtr<Gsv::LanguageManager> language_manager = Gsv::LanguageManager::get_default();
	Glib::RefPtr<Gsv::Language> language = language_manager->get_language(MAIN->getConfig()->highlightMode());
	MAIN->getOutputEditor()->getTextBuffer()->set_language(language);
}
```

My issue is with the `MAIN->getOutputEditor()->getTextBuffer()` ... I try to obtain the pointer on the `Glib::RefPtr<OutputBuffer> m_textBuffer;` that is inside `OutputEditorText` class. What is the best way to get? I assume there is a way to do it already so I don't need to implement `getTextBuffer()` myself. If yes - what is this way? If not - how do I implement `getTextBuffer()` the best way?

Thank you!

**Comment by manisandro** [comment]
You can handle the settings directly inside the respective class (not in the Config class), so you don't need to add a getter for the text buffer. See the OutputEditorText constructor for example.

**Comment by AvtechScientific** [comment]
I added additional text entry to the Preferences (i.e. Config class) that holds which markup language to use for highlighting. And the constructor of OutputBuffer indeed uses this setting on the program start (see the picture bellow).  But I also want to create a callback function and `CONNECT (...)` it to the OK button of the `ConfigDialog.ui` (aka Preferences) in order to be able to change the markup languages "live" while the program runs already (without restart). I mean this blue OK button:

![Screenshot from 2021-05-22 21-26-33](https://user-images.githubusercontent.com/12374315/119238812-987ae980-bb4d-11eb-9f49-f6035badc9df.png)

As far as I understand this `CONNECT (...)` can only occur inside of the `Config` class. That's why I need a way to get access to the textBuffer from within `Config`. Alternatively - is there a way to referrence the buttonOK of the ConfigDialog inside `OutputEditorText`? (this seems less intuitive but probably should work either) Thank you.

**Comment by manisandro** [comment]
No, `CONNECT` is not limited in any way to the  `Config` class - look at the `customoutputfont` setting, it is the same situation: UI in the config dialog, used in the `OutputEditorText` class.

**Comment by AvtechScientific** [comment]
Thank you for your comment. It indeed helped and I've finished the task. Pushed to my fork.

I don't want to create a PR for now as I also want to add an Open button (close to the currently existing "Save as" button) that will open previously saved output.

Once I started to work on this I've noticed some pieces of code that imply that such functionality exists... E.g.: `void MainWindow::openOutput(const std::string& filename)` or `bool OutputEditorText::open(const std::string& file)`... but I couldn't really find a button that really opens a FileDialog and opens a file... Do I miss something? Thank you!

**Comment by manisandro** [comment]
Currently it's only used from the source manager if a document with the same basename as an input source with txt extension exists in the same folder.

Btw, I'd recomment using an IDE such as Qt-Creator, which allows you to check where a function is used throughout the codebase.

**Comment by AvtechScientific** [comment]
Done. Please review/merge my PR once you have time. It also closes another bug.
Is there any chance for a new release in the near future? (It's been almost 2 years since the previous one).
