### ISSUE TITLE
multiple link errors

### ISSUE THREAD

**Issue by salfter** [manisandro/gImageReader#475]
I maintain a Gentoo ebuild for gImageReader. I'd swear I had it working before, but with the current set of dependencies, linking causes lots of "undefined reference to" errors.  A build log is attached below.

[build.log](https://github.com/manisandro/gImageReader/files/5540110/build.log)

I'm trying to build for Qt 5 and using cmake 3.17.4. and gcc 9.3.0.

**Comment by manisandro** [comment]
You'll want to backport this [1] (and possibly [2]).

[1] https://github.com/manisandro/gImageReader/commit/197cf34eacb04fdb91845a50fe82326a16ccc9d2
[2] https://github.com/manisandro/gImageReader/commit/e023778d9cd25d2d4065d51dbccc039d9aff44d1

**Comment by salfter** [comment]
The patches (which look to be the same) didn't apply against v3.3.1 since the minimum declared cmake version was 2.8.11, but that was easy to fix.  Also, there are undeclared dependencies on enchant and qtspell (the latter possibly only when building for Qt).  Once those issues were resolved, I got at least the Qt build working (don't care so much about Gtk).  Thanks!
