### ISSUE TITLE
Clicking outside layout clears all autodetected areas

### ISSUE THREAD

**Issue by luggw1** [manisandro/gImageReader#477]
I'm using gImageReader 3.3.1 on Linux Mint 20 XFCE.  I've found that the Autodetect Layout function works fairly well in detecting text on the scanned page, but it places the boundaries right against the edge of the text so that the OCR process makes some mistakes on characters lying on the edges.  If I move the boundaries away from the text a bit I get much better results.

However, if I accidentally click outside the boundaries - in the white space of the page - it clears all the detected layouts and any adjustments I've made.  It would be helpful if either nothing happened when the user clicks in the white space, or if a message box popped up asking if the user really wanted to clear the layout.

Thanks for listening...
Bill Lugg

**Comment by manisandro** [comment]
I've implemented that if you click in a selection, you move it rather than clear all selections. I'd rather keep that selections are cleared when clicking in an unselected area.
