### ISSUE TITLE
[solved] pdf export doesn't work correctly

### ISSUE THREAD

**Issue by DoctorSubtilis** [manisandro/gImageReader#478]
I can do a good ocr and save the result as html (almost perfect), but when I try to export as PDF I get a pdf unreadable (with lots of small squares: no readable text, as you can see in the attached file).  

[Menozzi.example.pdf](https://github.com/manisandro/gImageReader/files/5730714/Menozzi.example.pdf)

OCR language: italian.  
SO: KDE Linux with the last release of gImageReader.  
Can you help me?

**Comment by DoctorSubtilis** [comment]
This is the error message I get when click on manage languages:  

    A session connection to the PackageKit backend is required for managing system-wide tesseract lanquage packs,  
    but it was not found. This service is usually provided by a software-management application such as Gnome Software.  
    Please install software which provides the necessary PackageKit interface, use other system package management software          
    to manage the tesseract language packs directly, or switch to using the user tessdata path in the configuration dialog.

**Comment by manisandro** [comment]
As for the original issue description, this is pretty much certainly related to the font used for exporting. Try selecting another font, perhaps a common one like dejavu-sans etc.

As for the second comment, the message says it all, you either need a packagekit daemon running if you want to have gImageReader interact with the system package manager, or switch to per-user tessdata path.

**Comment by DoctorSubtilis** [comment]
OK, I tried to change the font, but every time (at least 5 times) I try it, the program (and _the whole_ pc system) freezes for 2/3 minutes, without any possibility to choice a font ("sans" is the only, already given).  
Uninstalled and reinstalled gImageReader: nothing to do.

**Comment by DoctorSubtilis** [comment]
There is a minor problem, though: nor bold neither italic are recognized ...

**Comment by manisandro** [comment]
The tesseract 4 LTSM engine does not support bold and italic detection, I'm not sure whether this has since been implemented in the upcoming tesseract 5.

**Comment by DoctorSubtilis** [comment]
I see. Thanks!
