### ISSUE TITLE
Errors when a pdf file is hOCRed and saved. 

### ISSUE THREAD

**Issue by raindropsfromsky** [manisandro/gImageReader#481]
Reporting for gImageReader 3.3.1 running on Windows 10 64 bit.

I hOCRed [this 13-page pdf file](https://mha.gov.in/sites/default/files/PR_15042020RevisedConsolidatedGuidelines.pdf). 
(Note that the file has a single-colum text, and it does not have any images at all.)

Then I saved the file as text, odt and pdf formats.

I am facing the following problems:

1. The odt file contains images of the original file. Some images are full-page with original text, while others are just gray strips at top, bottom or side of the page.
2. The original page contains paragraph numbers on all pages. <br>These numbers appear in the hOCR output panel. <br> But when saved as odt, most of the paragraphs lose the numbers. <br> I do not think that they get cut off because of the left margin, because some of the numbers are indented inside the paragraphs.

I am attaching the odt file as example. 
1. Notice how the left margin is corrupted on p1 itself. 
2. From p2 onward, all the paragraph numbers are missing.  
3. On p3, the original image of the page appears. The OCRed text appears on top of it. <br> At least I can select the image and delete it.
4. On several pages, some large letters appear at the bottom. (e.g. p 4-7, 11)
5. On p2, 8, 12 and 13, a strip appears at the top of the page. (part of image of the original document)
6. On p9, there is a black line at the right side edge of the paper. (part of original image)

When I save the output as pdf, it has the same issues.

*****************
I tried out the **CI build** (a84a298), which shows the same revision number (3.3.1) in the Help>About dialog.
It has the same problems.

**Comment by raindropsfromsky** [comment]
[PR_15042020RevisedConsolidatedGuidelines2.zip](https://github.com/manisandro/gImageReader/files/5766300/PR_15042020RevisedConsolidatedGuidelines2.zip)

**Comment by manisandro** [comment]
Can you also attach the source hOCR file?

**Comment by raindropsfromsky** [comment]
[PR_15042020RevisedConsolidatedGuidelines.zip](https://github.com/manisandro/gImageReader/files/5949161/PR_15042020RevisedConsolidatedGuidelines.zip)

**Comment by raindropsfromsky** [comment]
I have attached the hOCR file (see above).
Please let me know if any other information is needed. 

BTW this is the first time I have saved the hOCR file.
Usually I have no use for the hOCR format: I need either odt or pdf.
There may be a difference between hOCR and odt/pdf (the hOCR file may be free of defects).
If that's the case, please let me know. I will attach the pdf file (which definitely has the issues I listed.)

**Comment by manisandro** [comment]
As far as I can see, the ODT export is working correctly, in the sense that it reflects the contents of the hOCR file. Missing paragraph numbers are also missing in the hOCR document, and the images appearing in the output are also present as graphics in the hOCR tree. The quality of the hOCR document really depends on tesseract training, nothing gImageReader can do about that.
