### ISSUE TITLE
[UI] options button being far off eyes' sight/easy to miss

### ISSUE THREAD

**Issue by MagicalDrizzle** [manisandro/gImageReader#482]
the options button seems to lie really far off to the right, off the eyesight, maybe it'd be better to move it next to the other buttons on the left side?
![buttonfaroff](https://user-images.githubusercontent.com/49761211/103606317-fcd63d00-4f0d-11eb-8985-846f0cd8d996.PNG)

**Comment by manisandro** [comment]
I suppose this is a matter of taste, resp many applications nowadays place their application menu on the far right side. Personally I'd keep it this way (since it's been like that in gImageReader basically since the beginning).
