### ISSUE TITLE
Failed to fetch list of available languages: Proxy connection refused

### ISSUE THREAD

**Issue by MagicalDrizzle** [manisandro/gImageReader#483]
I have created a rule for the program in my firewall, resetting my internet settings and run it without firewall, but it failed to check every single time.

**Comment by manisandro** [comment]
This is not so much about a firewall, but about a proxy server in your network. gimagereader-qt5 on Windows will attempt to use the system proxy if possible [1], on other platforms you'll probably need to set the `HTTP_PROXY` environment variable.

[1] https://github.com/manisandro/gImageReader/blob/master/qt/src/MainWindow.cc#L126
