### ISSUE TITLE
[UI Enhancement] Options to manipulate the output (make the font bigger/smaller, changing display font etc)

### ISSUE THREAD

**Issue by MagicalDrizzle** [manisandro/gImageReader#485]
It seems the non-latin writing systems (Japanese and Chinese espicallly) are very difficult to read in the output pane. There should be options to increase/decrease the output's font size/changing the font/etc...
![smallfont](https://user-images.githubusercontent.com/49761211/103783498-b62d3380-5030-11eb-9525-9ec44750b369.PNG)

**Comment by tukusejssirs** [comment]
This would useful in Latin writing system too (at least I find the font size a bit small).

**Comment by manisandro** [comment]
You can adjust the output pane font size in the preferences dialog:

![image](https://user-images.githubusercontent.com/1298852/107270719-96cc6080-6a4b-11eb-9ae9-f2c89cc19f60.png)
