### ISSUE TITLE
** (gimagereader-gtk:5075): CRITICAL **: 16:10:53.894: check_range: assertion 'spell->priv->speller != NULL' failed (Ubuntu 20.10)

### ISSUE THREAD

**Issue by sealse-solbegsoft** [manisandro/gImageReader#487]
sudo add-apt-repository ppa:sandromani/gimagereader
  sudo apt update; sudo apt install gimagereader 
  sudo apt-get install tesseract-ocr-ru
  sudo apt-get install tesseract-ocr-eng
  sudo apt-get install hunspell-ru 
  sudo apt-get install hunspell-en-us 
  gimagereader-gtk 
  
** (gimagereader-gtk:6644): CRITICAL **: 16:14:26.842: check_range: assertion 'spell->priv->speller != NULL' failed

  Ubuntu 20.10

**Comment by manisandro** [comment]
Can you provide some more detailed steps to reproduce?

**Comment by manisandro** [comment]
Should be fixed with https://github.com/manisandro/gImageReader/commit/15fc05c5b211298ab84dfbaad85b46fa6f3a4437
