### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by achimwagenknecht** [manisandro/gImageReader#49]
Windows 10, scanned image, start recognition, crash. Backtrace:
gImageReader 3.1.2 (b1c60a3530d0a6b367145faaca64b94216761b76)

#0  0x77c0ac21 in ntdll!DbgBreakPoint () from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x77c40f89 in ntdll!DbgUiRemoteBreakin () from C:\WINDOWS\SYSTEM32\ntdll.dll
#2  0xdbb67440 in ?? ()
#3  0x77c40f50 in ntdll!DbgUiIssueRemoteBreakin () from C:\WINDOWS\SYSTEM32\ntdll.dll
#4  0x76363744 in KERNEL32!BaseThreadInitThunk () from C:\WINDOWS\SYSTEM32\kernel32.dll
#5  0x77bf9e54 in ntdll!RtlSetCurrentTransaction () from C:\WINDOWS\SYSTEM32\ntdll.dll
#6  0x77bf9e1f in ntdll!RtlSetCurrentTransaction () from C:\WINDOWS\SYSTEM32\ntdll.dll
#7  0x00000000 in ?? ()

Thread 12 (Thread 7972.0x1760):
#0  0x77c0ac21 in ntdll!DbgBreakPoint () from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x77c40f89 in ntdll!DbgUiRemoteBreakin () from C:\WINDOWS\SYSTEM32\ntdll.dll
#2  0xdbb67440 in ?? ()
#3  0x77c40f50 in ntdll!DbgUiIssueRemoteBreakin () from C:\WINDOWS\SYSTEM32\ntdll.dll
#4  0x76363744 in KERNEL32!BaseThreadInitThunk () from C:\WINDOWS\SYSTEM32\kernel32.dll
#5  0x77bf9e54 in ntdll!RtlSetCurrentTransaction () from C:\WINDOWS\SYSTEM32\ntdll.dll
#6  0x77bf9e1f in ntdll!RtlSetCurrentTransaction () from C:\WINDOWS\SYSTEM32\ntdll.dll
#7  0x00000000 in ?? ()

Thread 11 (Thread 7972.0x288):
#0  0x77c08b7c in ntdll!ZwRemoveIoCompletion () from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x76883574 in KERNELBASE!GetQueuedCompletionStatus () from C:\WINDOWS\SYSTEM32\KernelBase.dll
#2  0x66b9bcc4 in ?? () from C:\Program Files (x86)\gImageReader\bin\Qt5Core.dll
#3  0x00b0ff00 in ?? ()

Thread 10 (Thread 7972.0x674):
#0  0x77c08b2c in ntdll!ZwWaitForSingleObject () from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x76878e99 in WaitForSingleObjectEx () from C:\WINDOWS\SYSTEM32\KernelBase.dll
#2  0x76878df2 in WaitForSingleObject () from C:\WINDOWS\SYSTEM32\KernelBase.dll
#3  0x66961402 in ?? () from C:\Program Files (x86)\gImageReader\bin\Qt5Core.dll

Thread 9 (Thread 7972.0x85c):
#0  0x77c090bc in ntdll!ZwWaitForMultipleObjects () from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x76881426 in WaitForMultipleObjectsEx () from C:\WINDOWS\SYSTEM32\KernelBase.dll
#2  0x768812d8 in WaitForMultipleObjects () from C:\WINDOWS\SYSTEM32\KernelBase.dll
#3  0x66a895eb in ?? () from C:\Program Files (x86)\gImageReader\bin\Qt5Core.dll
#4  0x6695fe1e in ?? () from C:\Program Files (x86)\gImageReader\bin\Qt5Core.dll
#5  0x76af7196 in msvcrt!_beginthreadex () from C:\WINDOWS\SYSTEM32\msvcrt.dll
#6  0x76af7261 in msvcrt!_endthreadex () from C:\WINDOWS\SYSTEM32\msvcrt.dll
#7  0x76363744 in KERNEL32!BaseThreadInitThunk () from C:\WINDOWS\SYSTEM32\kernel32.dll
#8  0x77bf9e54 in ntdll!RtlSetCurrentTransaction () from C:\WINDOWS\SYSTEM32\ntdll.dll
#9  0x77bf9e1f in ntdll!RtlSetCurrentTransaction () from C:\WINDOWS\SYSTEM32\ntdll.dll
#10 0x00000000 in ?? ()

Thread 8 (Thread 7972.0x2518):
#0  0x77c090bc in ntdll!ZwWaitForMultipleObjects () from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x73e03456 in WINMM!PlaySoundW () from C:\WINDOWS\SYSTEM32\winmm.dll
#2  0x76363744 in KERNEL32!BaseThreadInitThunk () from C:\WINDOWS\SYSTEM32\kernel32.dll
#3  0x77bf9e54 in ntdll!RtlSetCurrentTransaction () from C:\WINDOWS\SYSTEM32\ntdll.dll
#4  0x77bf9e1f in ntdll!RtlSetCurrentTransaction () from C:\WINDOWS\SYSTEM32\ntdll.dll
#5  0x00000000 in ?? ()

Thread 7 (Thread 7972.0x23e4):
#0  0x77c090bc in ntdll!ZwWaitForMultipleObjects () from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x76881426 in WaitForMultipleObjectsEx () from C:\WINDOWS\SYSTEM32\KernelBase.dll
#2  0x74e0a49b in USER32!MsgWaitForMultipleObjectsEx () from C:\WINDOWS\SYSTEM32\user32.dll
#3  0x66b389c9 in ?? () from C:\Program Files (x86)\gImageReader\bin\Qt5Core.dll
#4  0x66ae318e in ?? () from C:\Program Files (x86)\gImageReader\bin\Qt5Core.dll
#5  0x6695c125 in ?? () from C:\Program Files (x86)\gImageReader\bin\Qt5Core.dll
#6  0x6695fe1e in ?? () from C:\Program Files (x86)\gImageReader\bin\Qt5Core.dll
#7  0x76af7196 in msvcrt!_beginthreadex () from C:\WINDOWS\SYSTEM32\msvcrt.dll
#8  0x76af7261 in msvcrt!_endthreadex () from C:\WINDOWS\SYSTEM32\msvcrt.dll
#9  0x76363744 in KERNEL32!BaseThreadInitThunk () from C:\WINDOWS\SYSTEM32\kernel32.dll
#10 0x77bf9e54 in ntdll!RtlSetCurrentTransaction () from C:\WINDOWS\SYSTEM32\ntdll.dll
#11 0x77bf9e1f in ntdll!RtlSetCurrentTransaction () from C:\WINDOWS\SYSTEM32\ntdll.dll
#12 0x00000000 in ?? ()

Thread 6 (Thread 7972.0x16c8):
#0  0x77c090bc in ntdll!ZwWaitForMultipleObjects () from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x76881426 in WaitForMultipleObjectsEx () from C:\WINDOWS\SYSTEM32\KernelBase.dll
#2  0x765d146b in combase!CleanupTlsOleState () from C:\WINDOWS\SYSTEM32\combase.dll
#3  0x765d133c in combase!CleanupTlsOleState () from C:\WINDOWS\SYSTEM32\combase.dll
#4  0x765a07b1 in combase!CoGetCallContext () from C:\WINDOWS\SYSTEM32\combase.dll
#5  0x765d4ccf in combase!IsErrorPropagationEnabled () from C:\WINDOWS\SYSTEM32\combase.dll
#6  0x765d4cb0 in combase!IsErrorPropagationEnabled () from C:\WINDOWS\SYSTEM32\combase.dll
#7  0x765d4cb0 in combase!IsErrorPropagationEnabled () from C:\WINDOWS\SYSTEM32\combase.dll
#8  0x044dff94 in ?? ()
#9  0x76363744 in KERNEL32!BaseThreadInitThunk () from C:\WINDOWS\SYSTEM32\kernel32.dll
#10 0x77bf9e54 in ntdll!RtlSetCurrentTransaction () from C:\WINDOWS\SYSTEM32\ntdll.dll
#11 0x77bf9e1f in ntdll!RtlSetCurrentTransaction () from C:\WINDOWS\SYSTEM32\ntdll.dll
#12 0x00000000 in ?? ()

Thread 5 (Thread 7972.0x32c):
#0  0x77c0a66c in ntdll!ZwWaitForWorkViaWorkerFactory () from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x77bd48b6 in ntdll!EtwNotificationRegister () from C:\WINDOWS\SYSTEM32\ntdll.dll
#2  0x76363744 in KERNEL32!BaseThreadInitThunk () from C:\WINDOWS\SYSTEM32\kernel32.dll
#3  0x77bf9e54 in ntdll!RtlSetCurrentTransaction () from C:\WINDOWS\SYSTEM32\ntdll.dll
#4  0x77bf9e1f in ntdll!RtlSetCurrentTransaction () from C:\WINDOWS\SYSTEM32\ntdll.dll
#5  0x00000000 in ?? ()

Thread 4 (Thread 7972.0x2764):
#0  0x77c0a66c in ntdll!ZwWaitForWorkViaWorkerFactory () from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x77bd48b6 in ntdll!EtwNotificationRegister () from C:\WINDOWS\SYSTEM32\ntdll.dll
#2  0x76363744 in KERNEL32!BaseThreadInitThunk () from C:\WINDOWS\SYSTEM32\kernel32.dll
#3  0x77bf9e54 in ntdll!RtlSetCurrentTransaction () from C:\WINDOWS\SYSTEM32\ntdll.dll
#4  0x77bf9e1f in ntdll!RtlSetCurrentTransaction () from C:\WINDOWS\SYSTEM32\ntdll.dll
#5  0x00000000 in ?? ()

Thread 3 (Thread 7972.0x222c):
#0  0x77c0a66c in ntdll!ZwWaitForWorkViaWorkerFactory () from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x77bd48b6 in ntdll!EtwNotificationRegister () from C:\WINDOWS\SYSTEM32\ntdll.dll
#2  0x76363744 in KERNEL32!BaseThreadInitThunk () from C:\WINDOWS\SYSTEM32\kernel32.dll
#3  0x77bf9e54 in ntdll!RtlSetCurrentTransaction () from C:\WINDOWS\SYSTEM32\ntdll.dll
#4  0x77bf9e1f in ntdll!RtlSetCurrentTransaction () from C:\WINDOWS\SYSTEM32\ntdll.dll
#5  0x00000000 in ?? ()

Thread 2 (Thread 7972.0x870):
#0  0x77c0a66c in ntdll!ZwWaitForWorkViaWorkerFactory () from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x77bd48b6 in ntdll!EtwNotificationRegister () from C:\WINDOWS\SYSTEM32\ntdll.dll
#2  0x76363744 in KERNEL32!BaseThreadInitThunk () from C:\WINDOWS\SYSTEM32\kernel32.dll
#3  0x77bf9e54 in ntdll!RtlSetCurrentTransaction () from C:\WINDOWS\SYSTEM32\ntdll.dll
#4  0x77bf9e1f in ntdll!RtlSetCurrentTransaction () from C:\WINDOWS\SYSTEM32\ntdll.dll
#5  0x00000000 in ?? ()

Thread 1 (Thread 7972.0x11fc):
#0  0x77c08b2c in ntdll!ZwWaitForSingleObject () from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x76878e99 in WaitForSingleObjectEx () from C:\WINDOWS\SYSTEM32\KernelBase.dll
#2  0x76878df2 in WaitForSingleObject () from C:\WINDOWS\SYSTEM32\KernelBase.dll
#3  0x66a9bc4b in ?? () from C:\Program Files (x86)\gImageReader\bin\Qt5Core.dll
#4  0x66a31219 in ?? () from C:\Program Files (x86)\gImageReader\bin\Qt5Core.dll
#5  0x00433f55 in _gnu_exception_handler@4 ()
#6  0x76898f91 in UnhandledExceptionFilter () from C:\WINDOWS\SYSTEM32\KernelBase.dll
#7  0x0029c104 in ?? ()
#8  0x77bf9e8e in ntdll!RtlSetCurrentTransaction () from C:\WINDOWS\SYSTEM32\ntdll.dll
#9  0x77bf9e1f in ntdll!RtlSetCurrentTransaction () from C:\WINDOWS\SYSTEM32\ntdll.dll
#10 0x00000000 in ?? ()

**Comment by achimwagenknecht** [comment]
Has nothing to do with the scanner. Crashes also, when image is loaded from hard disk. Seems to be an issue with the german language file: https://github.com/tesseract-ocr/tessdata/blob/master/deu.traineddata
With english language, the program does not crash. (But the results are poor for german texts, of course.)

**Comment by manisandro** [comment]
Problem is that the trainneddata is for a newer version of tesseract than the version gImageReader bundles. I need to do a rebuild against the newest tesseract, or else any Windows user will keep hitting this issue...

**Comment by manisandro** [comment]
Could you please test one of:

https://smani.fedorapeople.org/tmp/gImageReader_3.1.2_qt5_i686.exe
https://smani.fedorapeople.org/tmp/gImageReader_3.1.2_qt5_x86_64.exe

**Comment by achimwagenknecht** [comment]
Does not crash any more. Now it says: "Erkennungsfehler sind aufgetreten. Folgende Fehler sind aufgetreten: Tesseract konnte nicht initialisiert werden"
-> "Recognition errors appeared. The following erros appeared: Tesseract could not be initialized"

**Comment by manisandro** [comment]
Okay I'll need to look into that.

**Comment by manisandro** [comment]
Works here. Are you sure you are using a traineddata for tesseract 3.04.00?

**Comment by achimwagenknecht** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Am 15.02.2016 um 13:24 schrieb Sandro Mani:
>
> Works here. Are you sure you are using a traineddata for tesseract
3.04.00?
>
Sorry, I switched to VietOCR in the meantime. No errors there.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.22 (GNU/Linux)

iEYEARECAAYFAlbDAyAACgkQJq391i+1U0ZT8wCcCkD+AvGEt5rDk++rxUFhlEFD
e9MAnRCK0eEqPKTWCcITEfzrbsxoiZGX
=khT2
-----END PGP SIGNATURE-----

**Comment by manisandro** [comment]
Okay.
