### ISSUE TITLE
Complete translation of UI in Hindi is attached

### ISSUE THREAD

**Issue by Shreeshrii** [manisandro/gImageReader#490]
[Ravi Ratlami](raviratlami@gmail.com), a member of [Technical Hindi](https://groups.google.com/g/technical-hindi/c/g4WD0noeQSI/m/XMy0-JPqAwAJ) group has translated the UI for Hindi. The Gimagereader UI Hindi Localized file (hi.po) is attached. I would appreciate if it can be included in the new CI builds. Thanks.

[gimagereader-hi.po.txt](https://github.com/manisandro/gImageReader/files/5897596/gimagereader-hi.po.txt)

**Comment by fitojb** [comment]
After applying Ravi’s translation, there are still 38 untranslated strings. Please go here to edit them:
https://hosted.weblate.org/projects/gimagereader/translations/hi/

**Comment by fitojb** [comment]
Thank you @Shreeshrii! This issue is now done and may be closed

**Comment by Shreeshrii** [comment]
Thanks!

Does this mean that the new CI version will have support for Hindi UI now?

**Comment by fitojb** [comment]
It should :)
