### ISSUE TITLE
Authentication is required Agent PolicyKit every start on KDE

### ISSUE THREAD

**Issue by omega3** [manisandro/gImageReader#491]
When I start gimagereader-gtk or gimagereader-qt I get pop-up to enter password:
https://i.imgur.com/gUZqx6a.png

Operating System: Manjaro Linux
KDE Plasma Version: 5.20.5
KDE Frameworks Version: 5.78.0
Qt Version: 5.15.2
Kernel Version: 5.10.7-3-MANJARO
OS Type: 64-bit
Graphics Processor: NVA8

**Comment by manisandro** [comment]
Not sure where this comes from, you might want to check the system logs to figure out which service is being started here.

**Comment by omega3** [comment]
```
09.02.2021 14:06	su	pam_unix(su:auth): authentication failure; logname= uid=1000 euid=0 tty=pts/1 ruser=omega3 rhost=  user=root

09.02.2021 14:06	audit	USER_AUTH pid=7368 uid=1000 auid=1000 ses=1 msg='op=PAM:authentication grantors=? acct="root" exe="/usr/bin/su" hostname=omega3-pc addr=? terminal=pts/1 res=failed'

09.02.2021 14:06	kernel	audit: type=1100 audit(1612875999.162:82): pid=7368 uid=1000 auid=1000 ses=1 msg='op=PAM:authentication grantors=? acct="root" exe="/usr/bin/su" hostname=omega3-pc addr=? terminal=pts/1 res=failed'

09.02.2021 14:06	su	FAILED SU (to root) omega3 on pts/1

09.02.2021 14:06	systemd	app-gimagereader\x2dqt5-9045f611ed904c359a28937b6ed37126.scope: Succeeded.

09.02.2021 14:06	kwin_x11	qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 64661, resource id: 77594673, major code: 18 (ChangeProperty), minor code: 0
```

Maybe it has something to do with installation process? I installed from community repository version 3.3.1-2?

**Comment by manisandro** [comment]
Don't think this is related to gImageReader - feel free to reopen if still an issue though.
