### ISSUE TITLE
No tesseract languages are avaiable for use. Recognition will not work.

### ISSUE THREAD

**Issue by vpapaioannou** [manisandro/gImageReader#492]
**System**
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

**Installed tesseract 5.0.0**
`sudo add-apt-repository ppa:alex-p/tesseract-ocr-devel`
`sudo apt-get update`
`sudo apt-get install tesseract-ocr`

**Installed gImageReader 3.3.1**
`sudo add-apt-repository ppa:sandromani/gimagereade`
`sudo apt-get update`
`sudo apt-get install gimagereader`

**Error**
![image](https://user-images.githubusercontent.com/6065702/106646014-2315e980-655b-11eb-851f-4c8a63aacf98.png)

**Comment by Shreeshrii** [comment]
You also need to install the language packs - see details of tesseract-lang

tesseract-ocr-osd
tesseract-ocr-eng

**Comment by manisandro** [comment]
Thanks @Shreeshrii 

Also note, if you install a version of tesseract different from the one gImageReader was compiled against, the program will likely not work correctly. You'll need to recompile the program from source.

**Comment by vpapaioannou** [comment]
Thanks!
