### ISSUE TITLE
Windows installs gImageReader_3.3.1_qt5_x86_64.exe in C:\Program Files NOT C:\Program Files (x86)

### ISSUE THREAD

**Issue by NationalReset** [manisandro/gImageReader#493]
I see a prev. issue that looks like this but I do not see that it has been fixed.  Will Windows 10 still run the program properly from this location??  Is there a more up--to-date *.exe for Win 10??

**Comment by manisandro** [comment]
The install location is correct, if you install the x86_64 build, it will end up in `C:\Program Files`. If you install the i686 build, it will end up in `C:\Program Files (x86)`.

**Comment by NationalReset** [comment]
Thanks. Which version should I install for Windows 10?

Phumbles by iPhone

**Comment by NationalReset** [comment]
Cool, thanks!

For some reason, now I can't find the  >share drive and the app (which
installed, and opens, and seems to work (on Greek), can't find the latin
info

Is it too late to do that step?  I know I copied into the assigned
directory before I installed it.

--
Debra Biasca,
*Human Being*

*sick [sic] semper tyrannis*


                 *
Technical Communications Consultant
Writing . Editing . Translation
Boulder, CO
303.946.3280 (mobile)
http://www.linkedin.com/in/biasca

Scientific and Academic Writing, Editing, & Coaching . Translation of
Archival Yiddish Documents

**Comment by manisandro** [comment]
Not following what you mean by the last part?

**Comment by NationalReset** [comment]
Found it -- hidden file found!

Best,

Debra
--
Debra Biasca,
*Human Being*

Genus est mortis male vīvere - Ovid
To live wickedly is a kind of death


                 *
Technical Communications Consultant
Writing . Editing . Translation
Boulder, CO
303.946.3280 (mobile)
http://www.linkedin.com/in/biasca

Scientific and Academic Writing, Editing, & Coaching . Translation of
Archival Yiddish Documents
