### ISSUE TITLE
How do I change the User Interface Language?

### ISSUE THREAD

**Issue by Shreeshrii** [manisandro/gImageReader#495]
I want to try out gImageReader using the newly contributed hi.po file. However I can's seem to find a way to change the User Interface Language. I have installed the latest CI version of the program on Windows 10 with `intl`.

**Comment by Shreeshrii** [comment]
Is this dependent on Windows locale? I use en_IN by default.

**Comment by manisandro** [comment]
You should be able to do `set LANG=<lang code>` in a cmd shell and then launch the program from that shell, and it should pick of the locale code you chose.

**Comment by Shreeshrii** [comment]
That worked. Thank you.

![gimagereader-hi](https://user-images.githubusercontent.com/5095331/107309916-5e5f6d80-6ab1-11eb-8eec-879e3d4d28c9.png)
