### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by DonnKey** [manisandro/gImageReader#497]
The sequence in the Wiki for building on Windows with docker isn't working. I've hunted around some, and my best guess is that the docker image gimagereader_buildenv  is not (is no longer) there, or there's some further qualifier needed to find it. I did log in to docker, which had no effect.  The message is:
```
/mnt/d/VSWorkspace/gImageReader$ docker run -v $PWD:/workspace gimagereader packaging/win32/makeinstaller.sh x86_64 qt5
Unable to find image 'gimagereader:latest' locally
docker: Error response from daemon: pull access denied for gimagereader, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```
For my purposes, I don't really need to build using docker, but I haven't figured out how to make cmake happy either.  (Still looking for PkgConfig).

**Comment by manisandro** [comment]
I guess you forgot 

    docker build -t gimagereader_buildenv packaging/win32
