### ISSUE TITLE
Speeding up OCR

### ISSUE THREAD

**Issue by mzguy** [manisandro/gImageReader#501]
I'd like to use gImageReader to process OCR for many PDFs. I have an 8 core, 16 thread processor that is being underutilized when running gImageReader.

I understand that Tesseract will only use up to 4 threads. However, I'd like to open multiple instances of gImageReader and manually launch recognition on each, but I can't figure out how. Is this possible? It appears that whenever I launch gimagereader-gtk from a terminal, it closes itself immediately if I already have an instance open.

Alternatively, is there some other way to speed up OCR by better utilizing my hardware?

**Comment by manisandro** [comment]
gImageReader is indeed a singleton application - as far as performance improvements are concerned, this (if in any way) should be adressed in tesseract itself.
