### ISSUE TITLE
Add release file for ubuntu Groovy 20.10 in ppa

### ISSUE THREAD

**Issue by thecoder-001** [manisandro/gImageReader#503]
Hello!
Just stumbled across this repo today and it seems to be an exact fit what I was looking for.
However, on trying to add ppa on ubuntu groovy, apt gives the following error:
```
E: The repository 'http://ppa.launchpad.net/sandromani/gimagereader/ubuntu groovy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
suggesting that the package isn't available for groovy.
Hopefully you can add packages for Groovy as keeping track and compiling new releases can get tedious if you need to do so for lots of packages.

Thanks for maintaining such as awesome project.

**Comment by manisandro** [comment]
PPA is updated with gimagereader-3.4.0.
