### ISSUE TITLE
[Ubuntu 20.10] doc name too long forces programm window larger then screen size

### ISSUE THREAD

**Issue by hollisticated-horse** [manisandro/gImageReader#504]
Hi, 
love the software ! It's much better then what i wiped up on my own (crashed systematically because of mishandling images).
[Ubuntu 20.10]
However, when i entered a file with a particular long name, it forced the window far larger then my screen size. Thankfully, I have a few screens, but it is a bit annoying: 

![2021-03-23_13-20 (copy)](https://user-images.githubusercontent.com/76632257/112145865-2df40e80-8bdb-11eb-8c45-3ffaafd833eb.png)

**Comment by manisandro** [comment]
Thanks, fixed in https://github.com/manisandro/gImageReader/commit/300492121d9dda9b1454d91f49e8d39cd3c1605f
