### ISSUE TITLE
BUG: In hOCRed text, some words overlap the previous word; as if there is no space between them 

### ISSUE THREAD

**Issue by raindropsfromsky** [manisandro/gImageReader#507]
In hOCR mode, some words overlap the previous word, as if there is no space between them.
Although gImageReader treats them as independently detected words, they appear joined to the reader.

In the following example, I have selected the "Show preview" button, and then taken a screenshot.
the words "17" and "of" appear joined, but the spellcheck does not see them as "17of", and so it does not flag it as a spelling error.

![image](https://user-images.githubusercontent.com/9047168/113811957-d2a14f00-978a-11eb-8762-948cb4174d3d.png)

However, if I export this file as pdf, the resultant pdf has a combined word "17of" (without a space between them). 

Therefore, the user has to look for all such errors and correct them.

![image](https://user-images.githubusercontent.com/9047168/113811758-6b839a80-978a-11eb-8d32-0080906b37f5.png)

**Desired:** The algorithm should calculate when the bounding boxes of two consecutive words overlap; and separate them by inserting a small distance that is visually equivalent to a space character.

**Comment by manisandro** [comment]
The bbox comes directly from the tesseract hOCR output, it isn't computed by gImageReader. You should get the same result when invoking the tesseract executable directly.

**Comment by raindropsfromsky** [comment]
Can you please share the version of Tesseract you are using?
I need it to file a bug with Tesseract's GitHub.

Thanks in advance!
