### ISSUE TITLE
Ubuntu 20.04 package not available in PPA (failed to build)

### ISSUE THREAD

**Issue by adrienbeau** [manisandro/gImageReader#508]
Trying to install gImageReader from the PPA, I see *focal* in the list of available versions, however it seems the build failed (also failed for *eoan*), so no deb files are available.

The build error seems to be "Missing build dependencies: libquazip5-headers"

* https://launchpad.net/~sandromani/+archive/ubuntu/gimagereader/+packages
* https://launchpad.net/~sandromani/+archive/ubuntu/gimagereader/+build/18866169
* https://launchpadlibrarian.net/470040236/buildlog_ubuntu-focal-amd64.gimagereader_3.3.1-1~focalppa1_BUILDING.txt.gz

**Comment by manisandro** [comment]
PPA is updated with gimagereader-3.4.0.
