### ISSUE TITLE
very good ocr, but formatting problems

### ISSUE THREAD

**Issue by DoctorSubtilis** [manisandro/gImageReader#510]
I noticed today that the new release of gImageReader works very, very well with pdf-image in English: congratulations! And many thanks! In my opinion better than Adobe.  
But with pdf-image in Italian I have a good ocr (almost no errors), but some formatting problems, mainly with the footnotes (with smaller text). Footnotes are bad formatted (in Italian, unlike in English): too narrowed, without spaces between words and often with letters over other letters.
I tried to change something in settings, but so far unsuccessfully.
In my KDE Neon I have installed all Italian *spell* possible (at least, I believe).
Can you help me?

**Comment by manisandro** [comment]
gImageReader is just a front-end to tesseract [1], if the italian traineddata does not work to your satisfaction, you might want to read through the tesseract manual [2], in particular the training part, to learn how to improve the recognition result.

[1] https://github.com/tesseract-ocr/tesseract
[2] https://tesseract-ocr.github.io/tessdoc/

**Comment by DoctorSubtilis** [comment]
> gImageReader is just a front-end to tesseract [1], if the italian traineddata does not work to your satisfaction, you might want to read through the tesseract manual [2], in particular the training part, to learn how to improve the recognition result.
> 
> [1] https://github.com/tesseract-ocr/tesseract
> [2] https://tesseract-ocr.github.io/tessdoc/

Thank you. But I think that the problem could be not tesseact, because it is not a _recognition_'s problem, but a _formatting_'s one.  
A workaround could be a search and replace function: f.i. convert all 6 (font) size to 5 (font) size. I noticed that the existent S&R works only for the content, but not for the source code (formatting).  
Adding this new feature could help top resolve the misformatting, so to say, errors.
Thanks!

**Comment by manisandro** [comment]
tesseract outputs a hOCR document which is recognition + layout. gImageReader does not do any layouting itself, it just allows you to edit the layout post recognition.

**Comment by DoctorSubtilis** [comment]
OK, but it would technically impossible (/too difficult) give a S&R (of the _source code_) to edit layout post recognition?

**Comment by manisandro** [comment]
what do you mean by s&r?

**Comment by DoctorSubtilis** [comment]
Search and replace.

**Comment by manisandro** [comment]
Well you could select an entire text block in the ouput tree and change the font-size as necessary.

**Comment by DoctorSubtilis** [comment]
Yes, you're right. Even it is a bit boring, if you have a big book ;) (until tesseract learn to recognize correctly the size of the word).
