### ISSUE TITLE
Crash on write PDF

### ISSUE THREAD

**Issue by Tafnab** [manisandro/gImageReader#513]
Running **3.3.0** on **MX Linux 19.2.**  Can't run 3.3.1 because Debian (Buster) is so far behind in library updates.

The OCR of a very large imported PDF file (200 pages of images) results in a **successful OCR**, but **writing the PDF** with hidden text **crashes**.

I tried to fix by **backporting libpodofo to upgrade to 0.9.7**.  This somewhat fixes the problem. I can write the OCR'ed PDF file, but it's huge, enourmous and takes a long time to open in all of my PDF readers. **The written PDF file is basically unusable**.

After trying to write to PDF with different options to improve the situation, the program still crashes. The PDF it generates during the crash is corrupted. I suspect gImageReader is retaining some state and not clearing itself between runs. 

**Are there any other libraries that I should backport that might help?**  
Options:
libdjvulibre21
libenchant-2-2
libjpeg62-turbo
libjson-glib

At some point I'll be building v. 3.3.1, but I'm not sure this will fix the problem.

The only reason I'm asking is because gImageReader was the only Linux package to even make it through an OCR of this file without crashing. So, it's the best option available for OCR. But even the best is useless if it can't output a searchable document.

**Any recommendations for settings in gImageReader to improve my odds?**

**Comment by manisandro** [comment]
Can you share a stacktrace of the crash?

**Comment by Tafnab** [comment]
What sort of stacktrace can I get. There aren't any debugging symbols in the production version. 
Do you have a tool in mind?

> Can you share a stacktrace of the crash?

**Comment by mattia-b89** [comment]
Is this issue still present?

**Comment by Tafnab** [comment]
Sorry, I gave up trying to get it to run. 
Just run it on a large multi-page PDF. That should show the problem. Hope you find what's up with it.

I use gImageReader for other things, but I had to move on from the testing OCR because I needed get some work done. 

See my review: https://phpbb.valzorex.com/viewtopic.php?f=3&t=29&sid=be20d7ee505463af2476c741aa8c47b6

**Comment by manisandro** [comment]
Not much I can do here realistically without a stacktrace. If you'd still like to investigate, feel free to reopen and I can help you with the stacktrace.
