### ISSUE TITLE
How to run source code locally

### ISSUE THREAD

**Issue by rangewr** [manisandro/gImageReader#515]
I want to run the source code of the project on my windows machine, but I can't find the program entrance. Which IDE is more suitable for QT language? Is there any command line operation from hocr file to PDF file supported

If anyone knows how to solve it, please tell me how to operate it. Thank you very much

**Comment by manisandro** [comment]
> Which IDE is more suitable for QT language?

Qt Creator is a good choice, but you'll also need all the build dependencies. It's probably much easier on Linux.

>  Is there any command line operation from hocr file to PDF file supported

No, but you can invoke the tesseract executable from command line to do this
