### ISSUE TITLE
OCRing Old Texts: Spaces are missing

### ISSUE THREAD

**Issue by ReaderGuy42** [manisandro/gImageReader#519]
For a project, I'm working on old texts, i.e. the newer ones are from 19th, but also earlier than that. The scans are pretty good but due to printing, I guess, the lettering is sometimes smudgy etc. 

Interestingly though, the letters are not at all a problem for gImageReader, but pretty consistently the spaces (as in the thing between words) are absent for a few lines, then they're there again. This is sort of annoying when trying to copy excerpts.

Any advice on how to rectify this?
Thanks :)

**Comment by AvtechScientific** [comment]
It's a problem of Tesseract. gImageReader is just a GUI for it.

**Comment by ReaderGuy42** [comment]
> 
> 
> It's a problem of Tesseract. gImageReader is just a GUI for it.

Interestingly, over at the Tesseract Github, someone said that the exporting PDF function was done by gImageReader. And that's when the issue occurs, that the spaces in the invisible text layer over the PDF disappear.

**Comment by amitdo** [comment]
https://github.com/manisandro/gImageReader/blob/7d0076bb384b/qt/src/hocr/HOCRPdfExporter.cc

https://github.com/manisandro/gImageReader/blob/7d0076bb384b/gtk/src/hocr/HOCRPdfExporter.cc

gImageReader use the hocr output from Tesseract to export to PDF. Tesseract build the PDF directly using the API.

**Comment by manisandro** [comment]
Probably just a matter of picking a font for the output which does not overflow the boundingboxes of the respective words.
