### ISSUE TITLE
After new install can't find export to pdf function

### ISSUE THREAD

**Issue by ReaderGuy42** [manisandro/gImageReader#522]
I've been using gImageReader for a few years and I've always used it to export the OCR'ed text as an invisible text layer over the existing pdf scan, resulting in a searchable pdf file, which is useful for research, working with the text etc.

I was doing this on Windows 10, and recently installed a dual boot with Linux Mint and reinstalled Windows due to slow-down. Now I reinstalled gImageReader and I can no longer find the option to export to PDF with text layer. In fact I'm having trouble even finding much mention of said function online. I don't know if I originally installed some fork or beta or what, but the way the (probably) official version of the program looks is not what I'd been using so far.
In fact the Output panel looks different as well. Previously, it had had looked as is visible on the right of this image https://github.com/manisandro/gImageReader/issues/488#issuecomment-775855514. 
Now it looks like a regular txt file.

I was always able to set certain post-production parameters, such as size of the invisible text etc.

Any ideas where I could find that version again? I'd prefer a Linux Mint compatible version, but Windows would also be fine, if that's the only one.
Thanks!

**Comment by manisandro** [comment]
The latest released version has that option, or any newer git snapshot if you compile from source.

**Comment by ReaderGuy42** [comment]
> The latest released version has that option, or any newer git snapshot if you compile from source.

I've tried installing 3.3.1 several times now, but it does not appear to have that function. Am I doing something wrong? I've tried installing through the Linux Mint Software Manager, and just now via `apt-get install gimagereader tesseract-ocr`.
I've tried downloading directly from your Launchpad, but I can't figure out how to install that.
I apologize, I'm very new to Linux.
Any chance you could help me out? Thanks!
