### ISSUE TITLE
Frequent Crashes in Linux (Mint)

### ISSUE THREAD

**Issue by ReaderGuy42** [manisandro/gImageReader#525]
I'd been using the program in Win10 for years and never had this many crashes. Sometimes they occur multiple times in one session.
I'm not sure if there's a way to see the logs.
I'm also not sure what exactly does it, though it might be the long documents (several hundred pages)?
Any advice?
Thanks :)

**Comment by manisandro** [comment]
Try running from the command line or better, inside gdb, and post the stack trace
