### ISSUE TITLE
tesseract language 

### ISSUE THREAD

**Issue by narayaan** [manisandro/gImageReader#53]
A small correction.

The README of the tesseract language defenitions folder currently says:

"this folder contains tesseract language definitions.To add additional language definitions:
Visit http://code.google.com/p/tesseract-ocr/downloads/list"

However the language data can't be found on google code anymore and have been moved to this github adress:
https://github.com/tesseract-ocr/tessdata

**Comment by manisandro** [comment]
Yep, it's on my list of things to fix for the next version.

**Comment by manisandro** [comment]
Committed to master, and also fixed in respun 3.1.2 Windows builds.
