### ISSUE TITLE
The gImageReader's own GUI blocks the view for the screenshot function! 

### ISSUE THREAD

**Issue by raindropsfromsky** [manisandro/gImageReader#530]
When we take a screenshot with gImageReader, its own GUI should momentarily minimize itself, so that the user can capture the screen below it.

But once the Screenshot option is chosen, the GUI does not minimize. As a result, it always captures its own GUI.

This is not useful at all.

Reporting for the latest (1b5c448) version of gImageReader CI build released on 8th July (GTK version) on Windows 10, Home 64 bit. I guess the QT version would have the same logic (not checked)

**Comment by manisandro** [comment]
https://github.com/manisandro/gImageReader/commit/5f37349bae2406f7516dfb4de35f003ed484b27b

**Comment by raindropsfromsky** [comment]
I checked out the Qt version. It does not have this issue.
