### ISSUE TITLE
Crash in multipage scanning

### ISSUE THREAD

**Issue by chopinesque** [manisandro/gImageReader#536]
When I use multiple pages or a multipage pdf (Windows, 3.3.1, 2 language scanning Ancient Greek and English), the program crashes before completing the OCR.
![2021-08-11_092814](https://user-images.githubusercontent.com/10416842/128980889-0dade847-cf89-4b6b-8438-fa4a960ed64b.png)

**Comment by manisandro** [comment]
Unfortunately there is no way to debug this without more information, it might also be a crash in the scanner driver. If you can, please reopen with a stacktrace.

**Comment by chopinesque** [comment]
Thanks! Not sure how to obtain a stack trace for this. Care to explain? I did not use a scanner, just a pdf file. So not sure how the scanner driver could be involved.

**Comment by manisandro** [comment]
Oh right, misinterpreted "scanning".

For a stacktrace, open cmd, then

    cd ..\path\to\gImageReader\bin
    gdb gimagereader-qt5.exe
    run

Reproduce the crash, then

   thread apply all backtrace

and post the output here
