### ISSUE TITLE
Cannot download spellcheck dictionary for Russian

### ISSUE THREAD

**Issue by Pehat** [manisandro/gImageReader#54]
Hello!

gImageReader found my Russian traineddata file, but I forgot to install spellcheck. gImageReader gently reminded me about that and suggested to install spellcheck dictionary automatically, then showed me the error:
```
Could not read http://cgit.freedesktop.org/libreoffice/dictionaries/tree/.
```
I've tried to go to the URL above by myself and found there all the files I need. Anyway, the URL uses https, not http. May it be the source of the error?

**Comment by manisandro** [comment]
Yep, looks like the switch to https is causing the issue. I'll look at doing a respin of the Windows builds with that issue fixed.

**Comment by manisandro** [comment]
Respun Windows builds for version 3.1.2 have been posted. Also fixed in master.
