### ISSUE TITLE
WebP image format support

### ISSUE THREAD

**Issue by papojari** [manisandro/gImageReader#545]
WebP is a fairly new open image format by Google with smaller file sizes than JPEG in lossy (same quality) and smaller file sizes than PNG in lossless mode. It would be great to see it supported in this application.

**Comment by manisandro** [comment]
Should already be supported via qt5-qtimageformats for the Qt interface, For Gtk, you'll want to use [1].

[1] https://github.com/aruiz/webp-pixbuf-loader
