### ISSUE TITLE
Scanners without single page source - e.g. fujitsu fi-7160

### ISSUE THREAD

**Issue by smooker** [manisandro/gImageReader#55]
Unable to set single page source, please file a bug
Unable to set Gray mode, please file a bug

**Comment by smooker** [comment]
Option 10: name='br-x' title='Bottom-right x' type=fixed size=4 unit=mm min=0, max=215.872, quant=1387 cap=soft-select,soft-detect,
  Description: Bottom-right x position of scan area.
Option 11: name='br-y' title='Bottom-right y' type=fixed size=4 unit=mm min=0, max=279.364, quant=1387 cap=soft-select,soft-detect,

It's nice to set these options too with page_width/page_height sanesetoption.

**Comment by manisandro** [comment]
Please better describe what is the actual issue/request.

**Comment by manisandro** [comment]
Closing since no reply. Feel free to reopen with more detailed info.
