### ISSUE TITLE
'Long s problem' in 18th century French texts

### ISSUE THREAD

**Issue by fremont444** [manisandro/gImageReader#551]
Anyone found a solution to the 'long s' problem when OCR-ing early French texts?  i.e. 'long s' comes out as an 'f'

If you copy and paste text from pdfs in Okular this problem disappears. Anyone know why?

**Comment by manisandro** [comment]
This is related to tesseract resp. the tessdatas, gImageReader is just a front-end and does not do any recognition itself.
