### ISSUE TITLE
[Feature request] UI enhancements

### ISSUE THREAD

**Issue by mattia-b89** [manisandro/gImageReader#553]
I want to propose two UI improvements:

1. make progress bar bigger
2. align window title to the right

see the screenshot attached below:
![Screenshot from 2021-11-23 12-40-37](https://user-images.githubusercontent.com/545463/143020091-98f8cabe-6ebc-413f-91f9-6b5493da0517.png)

today there is a plenty of horizontal space thanks to widescreens, so there is no reason to keep a tiny progress bar(2) neither to condense the window's title near the buttons(1) making thus a more polish UI

**Comment by manisandro** [comment]
Thanks for the feedback - These are all stock Gtk widgets - so it's pretty much standard behaviour for Gtk applications, and I'd rather stay consistent.
