### ISSUE TITLE
Linux Mint, Export as "PDF with invisible text overlay" option not available in spanish language system

### ISSUE THREAD

**Issue by yohore** [manisandro/gImageReader#554]
Sir:
I can't find the option of the subject in my version of your application. My version is 3.3.1(). 
I'm using Linux Mint Kernel: 5.4.0-90-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 5.0.7  wm: muffin dm: LightDM Distro: Linux Mint 20.2 Uma base: Ubuntu 20.04 focal
The only options available are:
Exportar a texto sin formato
Exportar a PDF
Exportar a ODT
Am I missing anything?.
Thank you so much for your work.
![imagen](https://user-images.githubusercontent.com/80649619/143483780-5a61403d-298c-4ee8-aa97-7590be4998c5.png)

**Comment by linwaytin** [comment]
I have the same problem.

**Comment by manisandro** [comment]
The option is in the export dialog, not in the toplevel export menu:

![image](https://user-images.githubusercontent.com/1298852/149629919-1a60fc2d-1b68-4b19-b42a-58b40fe897ab.png)
