### ISSUE TITLE
Recent updates?

### ISSUE THREAD

**Issue by EligoQuodVideo** [manisandro/gImageReader#555]
Hello.

This isn't an issue but a question: Is this project actively mantained? The last update is from 2 years and a half. Are there recent versions to install somewere else? My distro's package manager and also the Releases section here on GH show v. 3.3.1, from mid 2019 as the most recent.

Thank you.

**Comment by eighttails** [comment]
Tesseract 5.0.0 is finally out on Dec. 1st.
https://github.com/tesseract-ocr/tesseract/releases/tag/5.0.0

gImageReader 3.3.1 is not compatible with Tesseract5 but latest master is.
It's time to consider new stable release.

**Comment by manisandro** [comment]
So I've had very little time to work on gImageReader over the past months, I'm giving it a push now to finally push out a new stable release - basically bringing the Gtk interface more or less to feature parity with the Qt one.

**Comment by manisandro** [comment]
I'm planning to release version 3.4.0 in about a week, I'd apprechiate if you could take some time to test the current master.

**Comment by alerque** [comment]
Tesseract 5 and about half a dozen other packages dependent on it are being held up by this in Arch Linux official repositories.

**Comment by manisandro** [comment]
You can apply [1] in the meantime. Remember that I'm doing this in my spare time (among many other things), I asked for some help with testing above and well not exactly a lot or response...

[1] https://src.fedoraproject.org/rpms/gimagereader/blob/rawhide/f/gimagereader-tesseract5.patch

**Comment by alerque** [comment]
Sorry if that came off as pushy, I meant a friendly poke that there was more riding on this that just local users. I package in my spare time too.

Thanks for the pointer on the patch, I probably will apply that so we can move forward (and I can stop getting complaints about Tesseract 5). I'm sorry I'm not actually a user of gImageReader so I'm not a great one to test HEAD.

**Comment by manisandro** [comment]
It's alright - yes pelase apply the patch. I'm testing through as time allows, but I still find the occasional larger issue so I'd still like to get a bit more testing done before going for release. But at some point I'll just end up releasing, probably the only way to get wider testing.

**Comment by manisandro** [comment]
What distro are you using?

**Comment by manisandro** [comment]
I've released 3.4.0
