### ISSUE TITLE
Select and ignore headers, footers, pages, etc

### ISSUE THREAD

**Issue by bxb2world** [manisandro/gImageReader#562]
For days I wanted to exclude/ignore from the OCR process some parts that are repeated in documents such as headers, footers or pagination, in order to avoid deleting them later. I think it would be very helpful if this feature could be added to the program.
Thank you.

**Comment by hendrack** [comment]
If you select an area on the page it will use this area for the whole document. If the pages do line up consistently you can exclude stuff like headers and footers that way.

**Comment by manisandro** [comment]
Yes, the best way is just to select the desired area of the document. If the pages do not line up consistently, you'd also have a hard time defining an excluded area.
