### ISSUE TITLE
Imagclass changed icons for apps in start menu

### ISSUE THREAD

**Issue by dgonyier** [manisandro/gImageReader#564]
I am seeing this strange issue after installing ImageGlass where windows apps (just App store ones I think) show the ImageGlass icon when I search for apps with the search bar. I have tried reseting the Windows icon cache already, but that does not help. Rebooting didn't help either.

See attached example images.

![calculator](https://user-images.githubusercontent.com/7379714/151221784-901e78ab-97e8-43af-869b-5eed872b2af3.png)
![weather](https://user-images.githubusercontent.com/7379714/151221787-6fb62a96-52f4-4648-95c5-ea5852316c64.png)

**Comment by manisandro** [comment]
This does not seem to be related to gImageReader

**Comment by dgonyier** [comment]
Sorry, wrong project
