### ISSUE TITLE
Crash with new 3.4.0 release and Tesseract 5

### ISSUE THREAD

**Issue by alerque** [manisandro/gImageReader#567]
I'm trying to update the Arch Linux packages for Tesseract to 5. With the new v3.4.0 release here I have rebuilt tesseract at 5.0.1, then rebuilt gimagereader packages against that. I am not super familiar with the usage of this app, but I ran `gimagereader-gtk`, opened a raster image, selected a box on the screen, and then hit the "recognize" button in the toolbar. This seemed like it should test the Tesseract interface.

I was greeted with a "The application has crashed" messag. It said it saved a crash report text file, but the file is empty (2 blank lines). It also says it failed to obtain a backtrace. I do have `gdb` installed but I assume that is because the default package build options don't have debug symbols enabled.

**Comment by alerque** [comment]
Exact same crash sequence with `gimagereader-qt5`.

**Comment by alerque** [comment]
From `coredumpctl dump`, possibly relevant excerpt. If longer is useful let me know.

```
Module libtesseract.so.5 with build-id be8642f09250c8e71f2e9d2f7954bd850bcb075c
Module gimagereader-gtk with build-id a04150283a9442d963d308bfea8c62512b9a70a6
Stack trace of thread 724753:
#0  0x00007f517e9eb070 _ZN9tesseract9Tesseract15recog_all_wordsEPNS_8PAGE_RESEPNS_10ETEXT_DESCEPKNS_4TBOXEPKci (libtesseract.so.5 + 0xb7070)
#1  0x00007f517e9c36cb _ZN9tesseract11TessBaseAPI9RecognizeEPNS_10ETEXT_DESCE (libtesseract.so.5 + 0x8f6cb)
#2  0x00005610e75bcbad _ZZN10Recognizer9recognizeERKSt6vectorIiSaIiEEbENKUlvE_clEv (gimagereader-gtk + 0xc3bad)
#3  0x00005610e75cdf8e _ZN4sigc8internal10slot_call0IZN5Utils8busyTaskERKSt8functionIFbvEERKN4Glib7ustringEEUlvE_vE7call_itEPNS0_8slot_repE (gimagereader-gtk + 0xd4f8e)
#4  0x00007f517d7bb51a n/a (libglibmm-2.4.so.1 + 0x5051a)
#5  0x00007f517d613845 n/a (libglib-2.0.so.0 + 0x84845)
#6  0x00007f517cbd6259 start_thread (libpthread.so.0 + 0x9259)
#7  0x00007f517caff5e3 __clone (libc.so.6 + 0xfe5e3)
```

**Comment by manisandro** [comment]
A full backtrace with gdb + debug symbols of gimagereader and tesseract would be useful yes, though it is likely a crash in tesseract itself. Have you also tried with other traineddatas?

**Comment by alerque** [comment]
This is a terreract vs. data issue, not gimagereader. Thanks for the pointer, and expect Arch packages to be updated soon.

**Comment by manisandro** [comment]
Thanks - and thanks for packaging!
