### ISSUE TITLE
Add file message

### ISSUE THREAD

**Issue by FTno** [manisandro/gImageReader#568]
In the old version 3.3.1 (qt - Windows), when I opened a normal PDF file a message appeared stating that the PDF file already contains text. When opening a scanned PDF file the message did not appear. This is correct behaviour, but in the new version 3.4.0 that message appears in both cases!

**Comment by manisandro** [comment]
Thanks, fixed in https://github.com/manisandro/gImageReader/commit/018c2198ce51581b76d04bb523bb051771e42538
