### ISSUE TITLE
Text editor context menu

### ISSUE THREAD

**Issue by FTno** [manisandro/gImageReader#569]
In the context menu in the text editor most strings are not translatable; Copy, Paste and more.
(3.4.0 - qt - Windows)

**Comment by manisandro** [comment]
Looking good here, did you install the localized version of gImageReader?

![image](https://user-images.githubusercontent.com/1298852/152030116-7b04b705-9252-47fa-8c64-3e98097f1bc0.png)

**Comment by FTno** [comment]
Using the norwegian localisation.

Could not find 'Select All", 'Cut', 'Copy' at Weblate.
Found 'Paste', 'Delete', 'Undo', 'Redo' at Weblate and they are translated, but don't appear in context menu as seen in the screenshot.

![screen](https://user-images.githubusercontent.com/16176811/152045247-713e1783-89f0-4342-a42c-2c294d491529.png)


(But translations of 'Undo', 'Redo' appear in the tooltips for the toolbar buttons)

**Comment by manisandro** [comment]
Those strings actually come from Qt directly, they are not part of the strings translated by gImageReader. Indeed there is not Norsk Qt translation in `<ProgramFiles>\gImageReader\share\qt5\translations`. Looks like no Norsk Qt translation was submitted so far [1].

[1] https://bugreports.qt.io/browse/QTBUG-5883

**Comment by FTno** [comment]
Thanks for the info. Since the strings in question are directly related to Qt and not the translation work from Weblate, I close this issue.
