### ISSUE TITLE
The proofread widget and Keyboard Shortcut windows are not showing up well

### ISSUE THREAD

**Issue by do2or** [manisandro/gImageReader#570]
The Proofreading widget is only displayed in the first word
and Keyboard Shortcut also has very small windows 
see the attached pictures 
![SHORTCUTS_WINDOW_SO_SMALL](https://user-images.githubusercontent.com/10603352/152139205-fab922bf-fac6-42fe-8da3-b879a1cdd00d.PNG)

![roofreading widget](https://user-images.githubusercontent.com/10603352/152139165-bd4c93e5-10f6-4579-aa16-f2141442b3ec.PNG)

**Comment by AvtechScientific** [comment]
@do2or - you might want to take this [Rashi script model](https://gitlab.com/pninim.org/tessdata_heb_rashi) for this text. If you can provide a feedback on how it compares to ABBYY FineReader or any other OCR software - it would be great.

@manisandro - do you plan to add the proofreading widget to the GTK interface within your current effort or will it wait till next major release?

**Comment by manisandro** [comment]
I've had one similar report about the shortcuts dialog being too small (also on Wndows). Can't reporduce it myself, but I guess I could just set a minimum size constraint for the dialog.

Regarding the incomplete widget, I guess it must have something to do with RTL text...

@AvtechScientific 
Regarding GTK: I have some code lying around, but I basically gave up, with GTK it seems pretty impossible to have an absolutely positioned floating widget within a parent widget, except if you go down all the way to overriding the painter level to draw the child widget into the parent widget, and then you also have to reimplement all the event handling for focus etc accordingly... The effort is just too large for the time I can invest. If you want, I can give upload the currrent state of the code, if you want to give it a go.

**Comment by AvtechScientific** [comment]
@manisandro - I'm interested in the implementation of the [plain text proofreading](https://github.com/manisandro/gImageReader/issues/472). I'm not sure, but it sounds like in that approach there will not be the problem you've faced, as no overlapping of widgets should be required... But I think it is a good idea to upload your code in a separate branch anyway, as it can be used to borrow ideas common to both approaches.

**Comment by manisandro** [comment]
Actually I see now that I already accidentally committed the files: https://github.com/manisandro/gImageReader/tree/master/gtk/src/hocr/wip_proofreadwidget

**Comment by AvtechScientific** [comment]
P.S.: @manisandro - why haven't you released the GTK windows executables with 3.4.0? Even without the proof-reading widget the update is quite significant...

**Comment by manisandro** [comment]
I prefer to keep the official windows build Qt only.

**Comment by manisandro** [comment]
Thanks - if you'd like to open a PR for the shortcut handling, I'd certainly be happy to merge it.

**Comment by manisandro** [comment]
https://github.com/manisandro/gImageReader/pull/577 since merged.
