### ISSUE TITLE
[Qt] Output pane does not respect font setting.

### ISSUE THREAD

**Issue by eighttails** [manisandro/gImageReader#571]
OS:Windows 10
gImageReader version:3.4.0
Qt:5.15.2

When I set "output pane font" as "MS 明朝"(Japanese Serif font) output pane always displayed in Sans serif font.
![image](https://user-images.githubusercontent.com/4285709/152779284-ec8572c3-b236-417a-b173-ad83dec2eb63.png)
![image](https://user-images.githubusercontent.com/4285709/152778976-bc68b4e0-926e-40eb-8546-9bec5c7a854c.png)
Any font change in setting dialog was not applied to output pane.

**Comment by manisandro** [comment]
Thanks for the report, fixed in https://github.com/manisandro/gImageReader/commit/5c04281d3b660308bcf3638c6e6a9da75675e432
