### ISSUE TITLE
Superuser permissions asked on Debian GNU/Linux 11

### ISSUE THREAD

**Issue by narcisgarcia** [manisandro/gImageReader#572]
I've installed gImageReader from Debian Stable (bullseye) repositories: v3.3.1
When I launch application, it presents main screen and asks user authentication for system modification permissions.

**Comment by manisandro** [comment]
I can't imagine this coming from gImageReader itself.

**Comment by manisandro** [comment]
Closing, feel free to reopen if you can add more info.

**Comment by narcisgarcia** [comment]
How can I look for what is triggering privileged actions?
```
$ which gimagereader-gtk
/usr/bin/gimagereader-gtk

$ file /usr/bin/gimagereader-gtk
/usr/bin/gimagereader-gtk: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=3e6e89165d7e97b81e3a4e3409d6bba9cd27586d, for GNU/Linux 3.2.0, stripped
```
