### ISSUE TITLE
Mixed language text recognition

### ISSUE THREAD

**Issue by arleenlasleur** [manisandro/gImageReader#573]
It it possible to implement foreign words/abbreviations catch if any in main language text? As it made in Finereader. Primarily interested in russian-english mode as this kind of texts is frequent. For now, in Russian mode OCR reads word "USB" as "И5В".

**Comment by manisandro** [comment]
You'd need to ask this in the tesseract forum [1], gImageReader is merely a frontend for tesseract (the OCR engine).

[1] https://groups.google.com/g/tesseract-ocr?pli=1
