### ISSUE TITLE
ubuntu 20.04 ppa still shows old version (3.3.1)

### ISSUE THREAD

**Issue by invasi0n** [manisandro/gImageReader#575]
Hello,

Just tried to install the new version, 3.4.0 but the ppa still shows the old one...
Thanks~
![Screenshot-202202222356-802x372](https://user-images.githubusercontent.com/10316162/155226647-24d5f951-cca7-4fb3-a93f-f1c655241f66.png)

**Comment by manisandro** [comment]
Did you actually add the PPA? The package is definitely there [1]

[1] https://launchpad.net/~sandromani/+archive/ubuntu/gimagereader/+packages

**Comment by invasi0n** [comment]
Of course, the PPA was added.
The package is there but don't know why I can't install it. Also tried to download from the main server not from the mirror, but no success... I'm wondering if others have the same problem.
![Screenshot-202202230005-1210x55](https://user-images.githubusercontent.com/10316162/155227469-26f78369-8079-457f-b195-6fb420f80f16.png)

**Comment by manisandro** [comment]
Acutally your comment in #574 probably explains it: the PPA has gimagereader-gtk and gimagereader-qt, gimagereader (without suffix) is the standard ubuntu package.

**Comment by invasi0n** [comment]
Yes, you're right :))

sudo apt -y install gimagereader-gtk installed version 3.4.0

Thank you very much!

**Comment by manisandro** [comment]
welcome!
