### ISSUE TITLE
Recognizing multiple pages from PDF recognizes current page multiple times

### ISSUE THREAD

**Issue by pbella** [manisandro/gImageReader#58]
1) Open a PDF file via the file folder (add images) shortcut in the files tab of the output pane
2) Confirm that pages are available by using the page spinner in toolbar to go forward/backward pages
3) Click on 'Recognize all English (en_US)' button
4) Select 'Multipl Pages...' from the drop down menu
5) Enter a page range (i.e. 1-10) and leave Recognition area set to 'Entire page'

Results in whatever page is currently visible being repeatedly recognized for as many pages as have been selected (i.e. if pages 1-10 were given as the range, the currently visible page will be recognized 10 times)

Running gImageReader 3.1.2 on Debian testing

**Comment by manisandro** [comment]
Odd, never saw that one before. Wonder if it is perhaps related to #37. Could you try with the latest master, or at least by backporting daf6280d711538dd755d93db7f8d62cafd261e13?

Thanks.

**Comment by manisandro** [comment]
Realize now that you must be using the Gtk interface. Indeed, can reproduce the issue there. Looking into it.

**Comment by manisandro** [comment]
Fixed in 8d939aca4de6cbc705ed79c1dbc42ce7e15d93ad
