### ISSUE TITLE
'Autodetect Layout' don't have an option to increase margins of selections

### ISSUE THREAD

**Issue by LifeWatcher123** [manisandro/gImageReader#580]
Hi. The program keeps running into situations where it can't recognize texts properly because the selections don't have enough margins inside for the text. For testing, please refer to the image attached below.

**Image used for Testing**

![Image used for testing](https://user-images.githubusercontent.com/43345572/155876083-372bbd87-8e0b-41fe-ada1-21dba5913254.png)

**Initial Result using Autodetect Layout**

![Result without adjustments](https://user-images.githubusercontent.com/43345572/155876201-3e91c71d-e1a6-4fb0-8cce-7aca0b548923.png)

Notice that without selection adjustments, the 'Question 1' text is recognized as only 'Question'. But after increasing it's selection size, the text is recognized properly.

**Result with size adjustments**

![Result with adjustments](https://user-images.githubusercontent.com/43345572/155876378-0ecb09fc-3d48-4b84-b969-2040126e39a4.png)

**Comment by AgostinoSturaro** [comment]
I am experiencing a similar issue.
For instance, I had an all-caps text, and I had "O" turned into "C" because the border at the margin of the page was too narrow.
I've also seen "q" and "g" getting confused with each-other.

**Comment by manisandro** [comment]
Should be fixed by https://github.com/manisandro/gImageReader/commit/c285fe5da11e189dd0c08e555ed137ab70c890a9.

**Comment by AgostinoSturaro** [comment]
@manisandro Can you provide a build with this fix?
Also, looking at the code, could the +/- 2px go outside of bounds if the box is very close to the borders?
Thank you.
