### ISSUE TITLE
Qt version's controls in titlebar don't appear in KWin Wayland

### ISSUE THREAD

**Issue by skierpage** [manisandro/gImageReader#583]
I ran the Fedora 35 gimagereader-qt package (gimagereader-3.4.0-1.fc35.src.rpm) for the first time in several months and had a hard time figuring out how to work it. Then I realized, based on the screenshots in https://itsfoss.com/gimagereader-ocr/ , that a lot of its UI is controls in its titlebar. But for some reason, on
KDE Plasma Version: 5.24.3
KDE Frameworks Version: 5.91.0
Qt Version: 5.15.2 on Wayland
none of these controls appear:
![gImageReader-qt no titlebar controls](https://user-images.githubusercontent.com/1303668/159193759-e5a50fdf-fad1-40f7-b2ea-85cfa0abe537.png)
I'm sure there used to be more controls in the app before, but I can't remember its old appearance.  [Here is the console output when I run it](https://github.com/manisandro/gImageReader/files/8312669/img_reader2_qt.txt); maybe output like`Wayland Interface:  zxdg_decoration_manager_v1 / 7 / 1` is significant.

I tried forcing the app to run using X11 with `env --unset=WAYLAND_DISPLAY && QT_QPA_PLATFORM=xcb  gimagereader-qt5` ; if that worked, its behavior didn't change. GTK apps like gnome-abrt continue to display controls in their titlebar fine on KWin Wayland. 

As a workaround, I installed the GTK version with `sudo dnf install gimagereader-gtk` and that shows all the controls in its titlebar. But it pulled in 15 MB of unneeded libraries.

**Comment by manisandro** [comment]
Can you try deleting `$HOME/.config/gImageReader/gImageReader.conf`, perhaps the window geometry stored therein is messed up. Otherwise I can't really think of anyway gImageReader can control this, most likely an issue with Qt/Wayland.

**Comment by skierpage** [comment]
Thanks for responding.
> Can you try deleting `$HOME/.config/gImageReader/gImageReader.conf`

I tried, didn't help.

**Comment by manisandro** [comment]
I don't think there is anything I can do about this on gImageReader side.
