### ISSUE TITLE
How do I add a new dictionary (Urdu)?

### ISSUE THREAD

**Issue by ReaderGuy42** [manisandro/gImageReader#584]
I've searched online about this a lot, but I can't find much that applies; I'm not sure if in the newer versions of gImageReader something changed, because in an older issue you mention that the traineddata needs to be put in the tessdata within a gImageReader, but I can find no such folder to begin with. Only the tessdata in tesseract. I'm on Linux Mint if that makes a difference.

Then I put the .aff and .dic file in MySpell (which was a chore because I had a hard time finding the files for Urdu), but gImageReader doesn't seem to find the files, because the popup is still telling me that the Spelling dictionary is missing.

The OCR seems to work moderately well, I chose the BEST version of the traineddata, but I can't read enough Urdu to make certain, which is why a spellchecker would come in handy.

What am I doing wrong?
Thanks :)

**Comment by manisandro** [comment]
Where did you place the .dic and .aff files? If you look ath the gImageReader configuration dialog, you'll see where it is looking for the files. Also, make sure the files are named correctly according to the language code of the language, and that the language is configured in the configuration dialog.

**Comment by ReaderGuy42** [comment]
The files are in `/usr/share/myspell/dicts`.

I've named them both `ur_PK`. Is that correct?

**Comment by ReaderGuy42** [comment]
I'm not sure I understand that. What do you mean by config dialog? Do you mean the Preferences window? If so, then yes there's an entry for Urdu, saying the Code is `ur`:
![image](https://user-images.githubusercontent.com/71895400/160440922-90960514-fdf0-4a0f-846c-64cb03d5e834.png)

Why is gImageReader not finding the dictionary files then?

**Comment by manisandro** [comment]
Does it find other files in /usr/share/myspell? Do you have /usr/share/hunspell?

**Comment by ReaderGuy42** [comment]
I do have the hunspell folder as well.
I'm not sure if it finds the other files in myspell. I tried finding an Arabic dictionary file, but I can't find one, even though gImageReader has Arabic listed as a language, so I may have just installed that via gImageReader directly, if that's possible? I don't remember. So I can't really tell if it's finding other things in myspell (or hunspell for that matter).

**Comment by manisandro** [comment]
You are using the system-wide folder configuration, right?

Also try the hunspell folder. Distros are moving away from /usr/share/myspell in favour of /usr/share/hunspell.

**Comment by ReaderGuy42** [comment]
yes, it's set to "System-wide paths". I just sym-linked the two Urdu dictionary files into the hunspell folder and now the popup in gImageReader went away. But now it's no longer recognizing the Urdu alphabet at all, which is weird since in an earlier test it did work. 

I've only been messing with the dictionary files, _not_ the traineddata. Any ideas what may have changed there?

**Comment by ReaderGuy42** [comment]
Wait, nevermind, I guess it just didn't like the title pages. So it works now, though I'm not sure how well the OCR'ing of Urdu works. Thanks for the help!!
