### ISSUE TITLE
Empty OCR result when trying to make more than one scan on image

### ISSUE THREAD

**Issue by AKmatiAK** [manisandro/gImageReader#586]
When I scan one selection it goes well, but when I try to scan second column it just doesn't work - progress bar for a while shows 0%, then disappear and there's no result. When I scan by right-click on selection there is only image path in result.
Log file is empty.

**Comment by manisandro** [comment]
You'll need to provide more info, ideally a screen recording.

**Comment by AKmatiAK** [comment]
Happens only at dpi different than 100, also, when I change dpi to other than 100 contrast and brightness adjustments doesn't work

**Comment by AKmatiAK** [comment]
PNG image, Windows 10 x64, Polish language, 270deg image rotation, plain text ocr, 600% scale, brightness and contrast - 0

**Comment by manisandro** [comment]
Probably the 600% upscaled image ends up hitting some image size constraint.
