### ISSUE TITLE
Is it possible to use the latest version with Tesseract 4?

### ISSUE THREAD

**Issue by rframil** [manisandro/gImageReader#587]
I have been using gImageReader 3.3.0 for a while and OCR works beautifully. I want to upgrade to the latest version to take advantage of the new proof reading feature, but unfortunately OCR became much worse for me after upgrading.

I believe the problem is Tesseract 5, because I've tried using exactly the same tessdata files, also different ones and played around with settings, and nothing seems to work except downgrading gImageReader to 3.3.0.

I can't figure out how to force gImageReader 3.4.0 to use Tesseract 4, if that's possible.

Thanks!

**Comment by manisandro** [comment]
I'm afraid the only way is to recompile gImageReader from source against tesseract 4.

**Comment by rframil** [comment]
Thanks, I'll try to do that.

**Comment by rframil** [comment]
Thanks. I'll do that.
