### ISSUE TITLE
worse results than previous version

### ISSUE THREAD

**Issue by u6aab** [manisandro/gImageReader#588]
I'm getting a bunch of random letters and symbols included in my results after upgrading from 3.3.1 to 3.4.0, both times using default options running on windows 10. it seems to have something to do with image quality (maybe sensitivity to grain/noise?) since running a screenshot of a pdf through doesn't produce the same issues.

![3 4 0](https://user-images.githubusercontent.com/92043407/162580069-f05234ea-92cd-497f-aab2-e0b360d9cc12.PNG)
![3 3 1](https://user-images.githubusercontent.com/92043407/162580070-f5445cde-2f50-41fb-8e43-9d73b553414f.PNG)

**Comment by Jossi2** [comment]
I am encountering exactly the same problem. I use gImageReader for OCR of old German (Fraktur) texts. I expected some improvement with version 3.4.0, but while I get almost 100% correct results with version 3.3.1, version 3.4.0 delivers lots of mistakes - with the same image to read, the same *.traineddata file and the same program options. Is there a possible reason for this, e.g. the change from tessdata 4 to tessdata 5?
Result with 3.3.1:

![OCR 3 3 1](https://user-images.githubusercontent.com/45576243/184953088-aa3ecd22-cc0b-4cd0-becb-d0ebcb4ebab6.png)

Result with 3.4.0:
![OCR 3 4 0](https://user-images.githubusercontent.com/45576243/184953100-ed895285-969e-40c0-9eed-35cc8dba8a44.png)

**Comment by hendrack** [comment]
I can't tell from the screenshots, are you using the Windows version? I use version 3.4 in linux and I have no issues, but the portable windows version produces the bad OCR results, with the same source material.

**Comment by Jossi2** [comment]
Issue seems to be solved with version 3.4.1. Almost faultless results again. Thank you for taking the trouble to further improve this excellent program!

**Comment by manisandro** [comment]
Thanks for your feedback!
