### ISSUE TITLE
Crash when deleting screenshot

### ISSUE THREAD

**Issue by Golddouble** [manisandro/gImageReader#596]
GImageReader version 3.4.0 ()

**How to reproduce:**

1. insert a 25-page PDF with "add image"
2. create a screenshot
3. select the screenshot
4. delete screenshot (recycle bin)
5. -> Crash

First I noticed this bug in MX Linux 19 (Debian 10 based, Xfce).
Then I tested the same in Debian Sid. 

In Debian Sid I have installed the following packages:
![k20220701-143052](https://user-images.githubusercontent.com/13977359/176907949-de0e8902-24d0-42c4-9963-963138035e20.jpg)

I noticed, that I have 2 entries for GImageReader Start menu in Debian Sid.
If I start GImageReader through the menu entry created by the package "gimagereader", then the crash also happens in Debian Sid.
But if I start GImageReader with the menu entry that was created through the package "gimagereader-qt5", then the crash does not occur.

![k20220701-142104](https://user-images.githubusercontent.com/13977359/176908399-1b24c417-a67a-4f52-970d-9e45ff2a0384.jpg)

**Comment by manisandro** [comment]
Should be fixed by 171f31822dfa5ae839758753e8f8abed05a40b5a

**Comment by Golddouble** [comment]
Thank you. I will try this out as soon as I have it in the repo.
