### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by DoozyDoz** [manisandro/gImageReader#601]
- what are the best settings to get text from for example 
![2jee](https://user-images.githubusercontent.com/98877504/189346602-1e8d8daf-c343-430c-9e0a-83033d0c6125.jpg)

**Comment by manisandro** [comment]
There is documentation on how you can train tesseract (the OCR engine) here: https://tesseract-ocr.github.io/tessdoc/tess4/TrainingTesseract-4.00.html
