### ISSUE TITLE
Adding languages

### ISSUE THREAD

**Issue by rulet** [manisandro/gImageReader#603]
How to add additional languages for ocr?
It's on Windows 10, 64bit
![Tesseract](https://user-images.githubusercontent.com/2847261/195000804-899afdaa-8c00-47b9-b770-da018c9dcb7c.png)

**Comment by AgostinoSturaro** [comment]
I had the same issue. Try running the application as administrator or download and copy the files manually.

**Comment by manisandro** [comment]
Have you tried switching to user paths in the settings dialog as hinted in the error dialog?

**Comment by manisandro** [comment]
Closing, please reopen if still relevant and if you can provide more information.
