### ISSUE TITLE
hOCR export issues

### ISSUE THREAD

**Issue by Hellzevir** [manisandro/gImageReader#607]
OS : Ubuntu 22.10 Kinetic Kudu
Version : gimagereader 3.4.0

When trying to export an hOCR result:
- in txt: error message saying it is impossible to write the output file
- in odt: no error message but anything is written

Only PDF and HTML exports seems to work.
![Capture d’écran du 2022-12-02 11-59-54](https://user-images.githubusercontent.com/109814855/205278006-debe004f-cf8e-4e60-a868-dee3fc306d0f.png)

**Comment by manisandro** [comment]
This error comes directly from Qt resp from the file system level that the file cannot be opened for writing. Make sure you have write permissions in the selected folder. There is nothing I can do about this in gImageReader.

**Comment by Hellzevir** [comment]
OK thanks for the prompt answer and sorry for the inconvenience.
I tried to write in my home directory, so I guessed I had permissions. I'll try to investigate.

**Comment by Hellzevir** [comment]
I provide extra informations after several tests on different Linux VMs : Fedora Gnome 37 ; Linux Mint 21 Cinnamon; Xubuntu 22.10 ; KDE Neon ; Debian Gnome 10...

I conclude that txt and odt exports are not functional **with the GTK version** of gImageReader.
On the opposite, the qt5 version can perfectly export on txt and odf...
The last GTK version of gImageReader that has a functionnal export is the 3.3.0 one (tested on Debian 10).

I don't really know how to solve the problem, but it seems clearly related to the interface version (GTK or QT5).
A workaround can be to install the qt5 version instead of the GTK one, even on a GTK based desktop environment (it was successful for me in Cinnamon for instance).

**Comment by manisandro** [comment]
Aha, I had mistaken the screenshot for the Qt version! Indeed, there is a a bug in the Gtk version... Fixed in 93aa47db5c105c06714592314eed5527f10a2f29

**Comment by Hellzevir** [comment]
Great!! Thanks for maintaining such a nice and useful tool!
