### ISSUE TITLE
Set language definition path manually

### ISSUE THREAD

**Issue by SaFi2266** [manisandro/gImageReader#608]
Hi,
I recently upgraded tesseract-ocr to version 5, So gImageReader stopped recognizing tessdata even by the setting up variable `TESSDATA_PREFIX` to `/usr/share/tesserarct-ocr/5/tessdata/`, Therefore I did a workaround by making a link to tessdata in `/usr/share/tesseract-ocr/4.00/tessdata/`, So is there a way to set manual tessdata in-app preferences or suggest a better solution?
OS: Ubuntu 22.04 
TIA

**Comment by manisandro** [comment]
You'll need to recompile gimagereader against the tesseract 5.
