### ISSUE TITLE
after upgrade to 3.1.90 on Linux Mint 17.3 exception starting gimagereader-gtk

### ISSUE THREAD

**Issue by antondie** [manisandro/gImageReader#61]
Upgraded 2 days ago from via PPA to new release, since then program no longer starts. When string from terminal there are several GTK warnings and at the end an exception:

---
.....
(gimagereader-gtk:14520): Gtk-WARNING **: /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcontainer.c:1166: child property `position' of container class `gtkmm__GtkHeaderBar' is not writable

(gimagereader-gtk:14520): Gtk-WARNING **: /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcontainer.c:1166: child property `position' of container class `gtkmm__GtkHeaderBar' is not writable

(gimagereader-gtk:14520): Gtk-WARNING **: /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcontainer.c:1166: child property `position' of container class `gtkmm__GtkHeaderBar' is not writable

(gimagereader-gtk:14520): glibmm-CRITICAL **: 
unhandled exception (type Glib::Error) in signal handler:
domain: gtk-builder-error-quark
code  : 2
what  : <resource>/org/gnome/gimagereader/editor_text.ui:187:1 <object> requires attribute "id"
-----------

possibly one of the GTK libraries not yet upgraded ??

**Comment by manisandro** [comment]
The GTK version in Ubuntu 14.04 (on which Mint 17.3 is based) is too old. I'm looking at making the code compatible with that version. In the meantime, plase use gimagereader-qt. As soon as I've found a solution, I'll update the PPA package.

**Comment by manisandro** [comment]
Fixed in c9c2b18d7f59fe63bfe351b05b74baf9567a7635, `gimagereader - 3.1.90-1~trustyppa4` is building.

**Comment by antondie** [comment]
Thanks for the quick fix, the updated version now works fine.
