### ISSUE TITLE
Wrong compilation manual

### ISSUE THREAD

**Issue by Antiwhore** [manisandro/gImageReader#610]
My dear developers, you've written bullshit in the compilation manual for Linux
[manual](https://github.com/manisandro/gImageReader/wiki/Compiling-gImageReader)
in section 3. If you follow these instructions, you get an error, because obviously cmake cannot find needed files in that empty build folder.
Please rewrite it properly.

**Comment by manisandro** [comment]
Please learn how to use cmake before making rude remarks. The `..` at the end refers to the parent directory, and this is the standard way to do an out of tree build.

**Comment by Antiwhore** [comment]
This is a right remark, because the way you've written it it creates an impression that these two dots designate cmake configuration options mentioned in the next paragraph, which are optional.
So insert a remark before that paragraph in bold font which clarifies that two dots literally mean two dots.
And by the way I'm not obliged to know how cmake works. The manual must work for all users including those who don't know this.
