### ISSUE TITLE
Explosive file sizes

### ISSUE THREAD

**Issue by Antiwhore** [manisandro/gImageReader#612]
I've recently recognized a small pdf document of 5 pages and exported it to pdf with default options expecting that I'd get something like the source, but with a text layer.
I got something. But it was not like the source. Size of the source file was 2.4 MB. And SIZE OF THE OUTPUT WAS 166.8 MB!
When I changed the settings to lossy compression and lowered the quality level, I managed to reduce this size to 17,3 MB, still it's a multiplication of size BY SEVEN!
Other options were useless.
In addition to that unlike the source this file opens in several pdf viewers TERRIBLY SLOWLY!
Tell me please, in what universe is an increase of file size by 7 to 70 times is considered a success?

**Comment by manisandro** [comment]
https://docs.github.com/en/site-policy/github-terms/github-community-code-of-conduct

**Comment by Antiwhore** [comment]
You can wipe your @$$ with this code of conduct. You are $h|t and so is your program.
