### ISSUE TITLE
Recent versions don’t export to odt

### ISSUE THREAD

**Issue by matc63famcoud** [manisandro/gImageReader#614]
I tried on two different distributions (Ubuntu 22.04 and Debian testing) : when I use "export to odt format", gImageReader is processing but no odt file is generated.
Have I done something wrong?

**Comment by manisandro** [comment]
So do I understand correctly that with your custom built from source the export works correctly? Possibly the packaged version is an older version of gImageReader?

**Comment by manisandro** [comment]
No feedback, please reopen if still relevant.
