### ISSUE TITLE
Cannot install international version

### ISSUE THREAD

**Issue by Jossi2** [manisandro/gImageReader#617]
In the installation process of version 3.4.1_qt5_x86_64 under Windows 10 Pro (system language German), it is not possible to change the status of the check box "intl". It stays unchecked no matter how often I click into the box. So I can only install the program with English as UI language. This is no big matter for me as I'm fluent in English, but is it necessary to download an additional language pack or what else could be the reason?

**Comment by manisandro** [comment]
I agree that the installer UI is not very intuitive here, but you need to pick the install mode from the combobox above:

![image](https://user-images.githubusercontent.com/1298852/215354882-426d3b66-6e9f-433a-90a1-7dad6ae1fd69.png)

**Comment by Jossi2** [comment]
Thank you, I shoiuld have remembered this from previous installations...
