### ISSUE TITLE
Small spelling corrections in the new version

### ISSUE THREAD

**Issue by narayaan** [manisandro/gImageReader#62]
Hi, I'm trying out the newest version of gImagereader and I like it! There are some small corrections I would like to suggest:

"Sources" at the left upper corner is misspelled as "so&urces".

In the list of installed languages Dutch is present as "Nederlandse". The correct Dutch word to mention the Dutch language however is "Nederlands".

"Output" at the right side of the screen is misspelled as "&Output".

**Comment by manisandro** [comment]
Hi
Thanks for the report.
I suppose you are using the Windows version. Not sure why, but it the & (which Qt automatically adds) are not rendered correctly under Windows - they should simply underline the following character.

The Nederlandse typo is fixed in b9a3306ebd3d3bd53b5bb190c8024f7749e06f57.

**Comment by narayaan** [comment]
Hi, thankyou for the quick correction. I'm using Win7 indeed.

Regarding the "&", so this is an upstream bug then?

**Comment by manisandro** [comment]
Yeah I suppose so. Annoying thing is that qt-designer keeps adding the & even if I explicitly remove them.

**Comment by manisandro** [comment]
Looks like this one: https://bugreports.qt.io/browse/QTBUG-15580

**Comment by manisandro** [comment]
Workaround implemented in 1716f5dd16b80d4757ee55d30e78a3f54d4b825d

**Comment by narayaan** [comment]
I guess it will indeed be that one. Bug filed in 2010, I don't think we'll see a solution soon. This issue May Be closed over here as it's an upstream bug.
