### ISSUE TITLE
gimagereader-gtk is slow on ubuntu

### ISSUE THREAD

**Issue by Dominik-rueth** [manisandro/gImageReader#622]
I was a happy user of gimagereader-gtk, but for a few month (I can't give a precise date), image processing is very slow on the latest gimagereader with the GTK frontend on Ubuntu (Kinetic).
We also tried using the lastest 3.4.1 from manisandro's PPA, to the same effect.
This problem does not occur with the QT5 frontend - which is fast.

Steps to reproduce: 
1. Install gimagereader on ubuntu-kinetic
2. Open a PNG file in gimagerader
3. click on "recognize all"
4. Note that the progress bar advances very slowly; even for a few lines, it takes a few minutes.

Is there any further information that we could supply to help debug this problem?

**Comment by Dominik-rueth** [comment]
cc @saraedum

**Comment by manisandro** [comment]
Does 

    $ export OMP_THREAD_LIMIT=1

before running `gimagereader-gtk` help?

**Comment by Dominik-rueth** [comment]
Yes, it does.
So I typed into the console:

(base) dominik@xps:~$ export OMP_THREAD_LIMIT=1
(base) dominik@xps:~$ gimagereader-gtk 

and then it processed the text quickly.

**Comment by Dominik-rueth** [comment]
Thank you for the quick reply!

**Comment by manisandro** [comment]
You should ask the ubuntu tesseract maintainer to compile tesseract with OpenMP support disabled.
