### ISSUE TITLE
Words aren't shown under the lines in result pane after you merge paragraphs 

### ISSUE THREAD

**Issue by bicolino34** [manisandro/gImageReader#626]
I made an OCR (Ukrainian language) for PDF scan and then started fixing some recognition mistakes. It made an incorrect segmentation on the first page. So, I merged two paragraphs but the words, under the lines in editing pane disappeared. After I tried to add word to the line they became visible again, but only for this specific line that I added word to. It also happens when you merge text blocks, but in that case not only words but also lines disappear 
OS: Linux Mint
Version of gImageReader 3.4.1 (8a046ec)
Installed from Flatpak

**Comment by manisandro** [comment]
Fixed in https://github.com/manisandro/gImageReader/commit/cb1d85181b77a9227f73c54fc0bfff8297c02212
