### ISSUE TITLE
after each line in paragraph automaticaly insert <CR> (Enter)

### ISSUE THREAD

**Issue by RoDanny2021** [manisandro/gImageReader#627]
After recognizing the text, it is divided into paragraphs and lines.
I did not find the possibility that <CR> should not be inserted at the end of each line
It would be useful to be able to tell the program that a paragraph is written without any <enter> at the end of the line
I have latest version ...
gImageReader 3.4.1 (Jan 29 2023) for windows 
Can make some change?

For translating? how can proceed? I  want translate into Romanian.

**Comment by manisandro** [comment]
There is an option in the plain-text editor to strip line-breaks of recognized text. As far as tesseract itself is concerned, there is no such option according to [1].

Regarding translations: please use [Weblate](https://hosted.weblate.org/engage/gimagereader/?utm_source=widget).

[1] https://groups.google.com/g/tesseract-ocr/c/mFA_bUNMQN8?pli=1
