### ISSUE TITLE
Spelling dictionary missing on Windows versions

### ISSUE THREAD

**Issue by aliron19** [manisandro/gImageReader#628]
Hi,

I think I've found a small bug on gImageReader v3.4.1 for Windows (both portable and installer). I'm using them on a Win64 Pro (Spanish localized version).

It seems that gImageReader expects the dictionaries to be under `gImageReader\share\myspell\`, while it actually uses them from `gImageReader\share\hunspell`

While the default installation places the `en_US.aff` and `en_US.dic` files in the `gImageReader\share\hunspell` folder, if you try to install any additional dictionaries from the program itself, they will be placed under `gImageReader\share\myspell\`. For some reason gImageReader cannot find them there (an error message will appear, as shown below), but if you move them to `hunspell` they will work perfectly fine.

![2023-04-17_22_03_46-Window](https://user-images.githubusercontent.com/47508555/232598304-22dec59b-328f-4896-bb06-f0f98234a884.png)

Let me know if you need any more details to debug this issue.

Anyway, thanks a lot for coding such a great tool.

**Comment by indigodelta** [comment]
I have exactly this issue too, and after copying the files to the other directory like described above it works as expected, but this seems to be some kind of small bug that you have to do this manually or it's not recognising stuff it downloads into the other folder.

Also my thanks for making this programme.

**Comment by manisandro** [comment]
Thanks for the report, should be fixed by a4820ebb8f8f05086f11c310c3f55a6ff5903f3e.
