### ISSUE TITLE
Crash when correcting words in hOCR output

### ISSUE THREAD

**Issue by narayaan** [manisandro/gImageReader#63]
When I try to correct a word in the output pane, gImagereader freezes and crashes. I tried this with different documents.

I'm using the newest version of gImagereader on Win7.

**Comment by manisandro** [comment]
Yep, ugly one, fixed in 127637b0eb28c3a1c3797f02a651c11c836e580a. Please use
https://smani.fedorapeople.org/tmp/gImageReader_3.1.91_qt5_x86_64.exe
in the meantime. Official builds will follow shortly.
