### ISSUE TITLE
Please merge complete Hungarian (magyar) translation from Weblate

### ISSUE THREAD

**Issue by ovari** [manisandro/gImageReader#632]
@manisandro are there any other files that need updating once translations from Weblate have been merge to enable the GUI to be shown in Hungarian (magyar)?

Thank you

**Comment by manisandro** [comment]
No in theory gImageReader should start in the system locale, and if the translation is available, it should get used. What OS are you using?

**Comment by ovari** [comment]
Have to wait for the Flathub update with Hungarian to check.

OS: Linux Mint 21.1 Cinnamon

**Comment by ovari** [comment]
Closing as:

> No in theory gImageReader should start in the system locale, and if the translation is available, it should get used.
