### ISSUE TITLE
Cannot build against pododo 0.10.0

### ISSUE THREAD

**Issue by alerque** [manisandro/gImageReader#633]
Arch Linux is in the process of updating podofo to v0.10.0. The libpodofo module has some APIs that have been renamed. Here is the migration guide:

https://github.com/podofo/podofo/wiki/PoDoFo-API-migration-guide

As of now gImageReader 3.4.1 does not build against the new library. It is now holding up the release of packages for other projects that *do* support it, like the latest release of Calibre, etc.

I looked through the master branch and I don't see anything related to this yet. It would be good to get it addressed soon. Even if there isn't a release immanent, if there was a development branch that supported it we would try backporting the patches to get the current version working again.

**Comment by manisandro** [comment]
I've started looking into it, it's not trivial though

**Comment by manisandro** [comment]
I've pushed support for podofo 0.10.x for the Qt interface here [1], now I'll work on the Gtk interface. Additional testing very welcome in the meantime!

[1] https://github.com/manisandro/gImageReader/commit/7a162b831855827dbc86d470ebd0ba85116d7daa

**Comment by manisandro** [comment]
Since also added to Gtk in https://github.com/manisandro/gImageReader/commit/54b7b9cf5917a353c04a4ca0d24f3b6797fa1a41

**Comment by alerque** [comment]
Hurray. Will be looking forward to this in the next release.
