### ISSUE TITLE
Inconsistent results

### ISSUE THREAD

**Issue by KarellenX** [manisandro/gImageReader#636]
Hello,

I have been using your software for less than a year. I use it occasionally to OCR text from books.

The problem I encounter is such extreme and inconsistent results. It ranges from wow this is pretty good all the way to where did this nonsensical garbage come from. It also misses a lot of the text. 

I guess I am doing something wrong, but I have no idea what! My scans seem pretty good and clear.
I can drop the same image into a 2009 version of Readiris Pro11 and I have remarkably better results using it.

Is there some dummies guide on how to improve the results? Should scans be of a certain resolution, dpi?

Any feedback will be appreciated.

![ocr1](https://github.com/manisandro/gImageReader/assets/44626605/9c6257a8-af93-422a-9ae5-c96114987405)

**Comment by KarellenX** [comment]
Is this project not supported anymore?

**Comment by Feli07notoldman** [comment]
Hier noch ein Auszug aus dem Scan, den ich für obiges Ergebnis verwendet habe
![In](https://github.com/manisandro/gImageReader/assets/138296531/59427736-2efd-449b-93d2-56ee71781afe)
Liebe Grüsse

**Comment by adrienbeau** [comment]
I do all my text recognition at 300 dpi, which works fine for me.

I also used to have mixed results, things are better now. I am now very careful about having perfectly horizontal text. I find the slightest rotation can decrease text recognition dramatically.

I use the automatic rotation button of gImageReader, but I also zoom and then draw a selection rectangle over a wide area of text. I check that the bottom or top of the rectangle is precisely aligned with the baseline of the characters over the whole width of the page. I correct the rotation if this is not the case.

**Comment by Feli07notoldman** [comment]
The program **ScanTailor Advanced**, as I mention before in my first comment above, will do this rotation and much more automatically for me. E.g. rotation and deskewing, split of scan into two separately pictures, one for each book page.
https://github.com/4lex4/scantailor-advanced
It is my **post processor** for scans and can be used also as a **preprocessor** for any OCR program, to prepare the scans for better OCR results.
You can use it as a batch processor for a bunch of scans.
I am using it since some years.

**Comment by KarellenX** [comment]
Thank you for your advice @Feli07notoldman and @adrienbeau 
I will try out the methods you outlined and hopefully have consistently better results. 

Out of curiosity, is this software still being maintained? I don't see a lot of activity here.

Regards

**Comment by adrienbeau** [comment]
Yes it is. It is a small, mature project, so don't expect a lot of activity.

**Comment by KarellenX** [comment]
Ok, thank you :)

**Comment by KarellenX** [comment]
Hello all, I just wanted to finish off and close this report with my experience after all the advice here and also at the mobilereads.com forum. 

In case anybody else is a bit clueless like me, the following is what I did and the software I used. The results have improved dramatically, and I have no complaints.

1. I needed better scanner software for my WIA compliant scanner. I installed the following software. It is simple and easy to use. The BEST feature is that it can batch scan. Enter how many scans to make, how many seconds between scans (6 sec in my case) and press Start. All you need to worry about is turning pages in that 6 seconds... https://www.naps2.com/
2. And if you are after software for very fast and easy screen captures... https://github.com/greenshot/greenshot
3. Scan Tailor Advanced for fixing scanned images. Installed from this repo... https://github.com/4lex4/scantailor-advanced
4. Then this gImageReader for OCR.

Thanks again for pointing me in the right direction :)
