### ISSUE TITLE
Complete Arabic Translation for gImageReader UI

### ISSUE THREAD

**Issue by MrkGameDev** [manisandro/gImageReader#639]
### Topic Description & Event

After finishing the remaining untranslated strings in [the arabic translation](https://hosted.weblate.org/projects/gimagereader/translations/ar) of gImageReader, and numerous checks/re-checks of the translations... I'm proud to say, That after years of inactive changes... it's finally done! 🎊 🎊 😄

-----------
### Credits

Huge thanks to the Contributors of the Arabic Translation, which are (Order of Oldest Contributor to Newest):

1. [bmwmy](https://hosted.weblate.org/user/bmwmy/)
2. [Riyadh](https://hosted.weblate.org/user/Riyadh/)
3. [Mr.k](https://hosted.weblate.org/user/Mr.k/)

-----------

### Issue Main Request

Can you please merge the Arabic translation on Weblate to this repo, so newer version(s) of the software have full Arabic support? @manisandro

**Comment by MrkGameDev** [comment]
## Screenshot after compiling from source
![image](https://github.com/manisandro/gImageReader/assets/70659536/e893244d-1e71-4fea-9247-ddd348e6c995)

**Comment by manisandro** [comment]
Weblate automatically pushed the changes to the repo, AFAICS this has since already happened for the arabic translations, hence closing this ticket. Thanks for your work!
