### ISSUE TITLE
Error: Failed to initialize tesseract

### ISSUE THREAD

**Issue by Nishya** [manisandro/gImageReader#64]
I installed the fresh binary Windows version 3.1.91 (gImageReader_3.1.91_qt5_x86_64.exe). Dictionary and trained tessdata files are on place. I can select any .PDF file, but when I click to Recognize -> Current Page I get the following error message:

> Recognition errors occurred
> The following errors occurred:
> Failed to initialize tesseract

I have Tesseract-OCR (V3.02) installed at 'C:\Program Files (x86)\Tesseract-OCR' and had it add the program to path. 

I tried to read the code files to see where gImageReader would be looking for tesseract, but I couldn't find it (I'm also no programmer atm).

I previously (2-3 months ago) had gImageReader working on my computer, but had to uninstall it. Now I found I needed it again, and any help would be very appreciated.

**Comment by manisandro** [comment]
gImageReader bundles its own version of tesseract. How did you install the tesseract language packs? In the gImageReader folder in the Start Menu there is also a link to the location where gImageReader stores the tesseract files it uses. Which files are in there?

**Comment by Nishya** [comment]
OK, I installed tesseract separately because I wasn't sure that gImageReader as a front-end would need or not the original program to refer to.

I saved the files in the gImageReader own folders:

```
PS C:\Program Files (x86)\gImageReader\share> dir .\tessdata\

Diretório: C:\Program Files (x86)\gImageReader\share\tessdata

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       03/05/2016     13:36          33583 deu.traineddata
-a----       03/05/2016     13:36          33519 deu_frak.traineddata
-a----       25/06/2015     00:25       21876550 eng.traineddata
-a----       03/05/2016     13:36          33583 jpn.traineddata
-a----       03/05/2016     13:36          32400 lat.traineddata
-a----       03/05/2016     13:36          33583 por.traineddata
-a----       03/05/2016     16:26            517 README.txt

PS C:\Program Files (x86)\gImageReader\share> dir .\myspell\dicts\

Diretório: C:\Program Files (x86)\gImageReader\share\myspell\dicts

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       03/05/2016     13:39          52174 de_DE_frami.aff
-a----       03/05/2016     13:39       14680196 de_DE_frami.dic
-a----       20/02/2016     03:58           3115 en_US.aff
-a----       20/02/2016     03:58         539608 en_US.dic
-a----       03/05/2016     13:39        2069438 pt_BR.aff
-a----       03/05/2016     13:40       17749502 pt_BR.dic
-a----       03/05/2016     16:26            369 README.txt
```
It seems that the language packs are fine, since they all properly show on GUI (or that is my guess).

And thanks for the quick reply!

**Comment by manisandro** [comment]
With which language does the error occur? For instance,
    25/06/2015     00:25       21876550 eng.traineddata
is rather old. The problem is that old traineddata files are incompatible with newer tesseract version. Try updating the traineddata files for which the error occurs. You can also just remove them and add them again via the tessdata manager in gimagereader.

I suppose I should introduce a mechanism for automatically updating the traineddata files when a new version of gImageReader is installed. Now, it simply transfers all previously installed traineddata and spelling files to the new installation. But if, as is probably your case, the tessdata files are incompatible with the new tesseract version, then the user will get a cryptic error...

**Comment by Nishya** [comment]
I updated the  eng.traineddata file to the latest available, opened gImageReader and ran 'Redetect Languages'. Loaded the same test file and the error persists.

BTW, I'm trying to OCR a german text, but tried other languages settings and PDF files and the same error occurs.

**Comment by manisandro** [comment]
Judging from the file sizes it looks like you downloaded the HTML pages instead of the actual binary blob from the tessdata github page. I.e. for german, you'd need

https://github.com/tesseract-ocr/tessdata/raw/master/deu.traineddata

**Comment by Nishya** [comment]
That was the problem! 

When I previously tried to download the files, I didn't see any "download file" button, so I just right-clicked the file name and saved it. Now I see I had to "open" the file and click on "raw" to save the actual content. Thank you very much!

On another note, all this happened because I first tried to download the files through 'Tessdata Manager' box, but couldn't do it because of permission errors and then resorted to manually downloading the (wrong) files. Just to check, should permission errors happen even though I'm the single user and administrator of the system (Windows 10)?

**Comment by manisandro** [comment]
Hmm I'll need to look at that, perhaps the security features of recent windows versions are preventing the application from doing any changes on the filesystem.

**Comment by manisandro** [comment]
If you run the program as administrator (rightclick the shortcut -> run as admin) does it work?

**Comment by manisandro** [comment]
Looks like I need to do something like this: http://stackoverflow.com/questions/7744410/how-to-execute-an-app-without-elevation

**Comment by Nishya** [comment]
Running it as administrator via right-click does the trick.

**Comment by manisandro** [comment]
I'll make a note in the release notes, and implement it properly for 3.2.0.
