### ISSUE TITLE
Unclear instructions on how to adjust Brightness / Contrast of multiple sources

### ISSUE THREAD

**Issue by Kobayen** [manisandro/gImageReader#646]
Case: I have 90 individual JPEGs. gImageReader 3.4.1 / included Tesseract  (under Windows) parses the images with plenty of glitched junk, unless I set said pages to a specific Brightness and Contrast value.

The changelog notes that I should be able to set them to the entire lot (gImageReader 3.2.1, " * Make brightness/contrast/resolution changes affect all selected sources " but so far, it only allows me to apply those settings to individual JPEGs, even if it remembers what specific Brightness and Contrast values were set to that specific image in the current session.

Either the documentation isnt clear how these settings can be applied, or the feature got broken at some point.

**Comment by manisandro** [comment]
This was a bug indeed, fixed in https://github.com/manisandro/gImageReader/commit/5825021eeef3e8981fa95b6d3a932530d23fe01c
