### ISSUE TITLE
install instructions for rocky linux 9?

### ISSUE THREAD

**Issue by thistleknot** [manisandro/gImageReader#647]
I tried the fc instructions, get stuck on enchant, despite having it installed
--   Package 'enchant', required by 'virtual:world', not found
CMake Error at /home/user/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/cmake/data/share/cmake-3.25/Modules/FindPkgConfig.cmake:607 (message):
  A required package was not found
Call Stack (most recent call first):
  /home/user/oobabooga_linux/installer_files/env/lib/python3.10/site-packages/cmake/data/share/cmake-3.25/Modules/FindPkgConfig.cmake:829 (_pkg_check_modules_internal)
  CMakeLists.txt:84 (PKG_CHECK_MODULES)

-- Configuring incomplete, errors occurred!

**Comment by manisandro** [comment]
Looks like you are missing the enchant devel package (which I suppose might be called something like `enchant-devel`, `enchant-dev` or `libenchant-dev`)
