### ISSUE TITLE
Failure to download and install dictionary

### ISSUE THREAD

**Issue by AgostinoSturaro** [manisandro/gImageReader#649]
@manisandro I installed gImageReader in the `C:/Program Files/gImageReader` folder.
It says I should install the spellchecking dictionary.

![2023-09-02 14_08_52-gImageReader](https://github.com/manisandro/gImageReader/assets/1441393/c3d1c96d-a916-470f-a037-1e5617bc346b)

However, when I try, it fails to download with this error

![2023-09-02 14_11_29-Error](https://github.com/manisandro/gImageReader/assets/1441393/6477cb08-47cb-4288-a9f6-c673e2576122)

I am connected to the Internet and I saw no firewall popup, so it's likely a folder permission issue.

I tried to run it as Administrator. Then it seemed to work, but it actually did not.

![2023-09-02 14_12_23-gImageReader](https://github.com/manisandro/gImageReader/assets/1441393/a2ea8182-734a-41e5-b44f-df546b6077f9)

After that, I still get the same error about missing dictionaries.
In fact, I see a mismatch between the `myspell` folder and the `hunspell` folder.

![2023-09-02 14_15_21-hunspell](https://github.com/manisandro/gImageReader/assets/1441393/17904ff8-4fa5-44af-8f71-90d44ff37488)
![2023-09-02 14_14_52-myspell](https://github.com/manisandro/gImageReader/assets/1441393/b2168e11-e5e9-4ce0-8b0e-75602cca40cb)

**Comment by manisandro** [comment]
Are you using an up-to-date version of gimagereader?

**Comment by AgostinoSturaro** [comment]
If you mean the latest stable version, 3.4.1, yes.
Please note the installation folder.

**Comment by manisandro** [comment]
I believe this has been fixed in https://github.com/manisandro/gImageReader/commit/a4820ebb8f8f05086f11c310c3f55a6ff5903f3e, which is not yet part of a released stable version. Can you try with the latest master snapshot build?

**Comment by AgostinoSturaro** [comment]
I've run a scan of the file `gImageReader_latest_qt5_x86_64.exe` in the releases page and it looks infected.
https://www.virustotal.com/gui/file/f5acd4954907c334c77766dfcc7d12168fc67d1bbcd537a3491a0dd9a1f425f4

It could be a false positive, but since Avast, AVG and McAffee are all complaining about it, you might want to find out why.

**Comment by manisandro** [comment]
The only possible action here is to find out how to contact the respective companies and warn them about the false positives. There is no way to know exactly what is triggering a match in their signatures. Alternatively you can try the portable version, or even compile yourself.

**Comment by manisandro** [comment]
Should be fixed with https://github.com/manisandro/gImageReader/commit/a4820ebb8f8f05086f11c310c3f55a6ff5903f3e
