### ISSUE TITLE
Failure with the dictionary of the Polish language

### ISSUE THREAD

**Issue by Pawwwle** [manisandro/gImageReader#650]
If I use a Polish language dictionary, the program closes automatically every time. :(

<img width="266" alt="Zrzut ekranu 2023-08-29 124356" src="https://github.com/manisandro/gImageReader/assets/115624603/efb925dd-8af9-42be-99c5-cd25cb4b40c9">

**Comment by tyrell-wallace** [comment]
this happened to me while doing a japanese OCR. it failed to install the japanese dictionary and, when doing the OCR, it crashed. the generated .txt contains no text at all in my case.

**Comment by tyrell-wallace** [comment]
also, this is related to https://github.com/manisandro/gImageReader/issues/649, and we 3 are all on windows. maybe an windows issue, then?

**Comment by manisandro** [comment]
Cannot reproduce with 3.4.2, please retest and reopen if still relevant.
