### ISSUE TITLE
Does not detect white text on a blue/purple background

### ISSUE THREAD

**Issue by Pawwwle** [manisandro/gImageReader#651]
The application does not detect white text on a blue/purple background.

![Zrzut ekranu 2023-08-27 194802_blue](https://github.com/manisandro/gImageReader/assets/115624603/a8bc8660-7d58-4d4d-8fbb-b5ccd576535f)

**Comment by manisandro** [comment]
This is a matter for tesseract, nothing gimagereader cad do about this. You can try training your own tesseract traineddata.
