### ISSUE TITLE
No option to download openSUSE package in OBS GUI.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [manisandro/gImageReader#653]
https://github.com/manisandro/gImageReader/blob/7bf08cb0f4dae70820e29055c5630fecde3fb06c/README.md#installation states that https://build.opensuse.org/project/show/home:sandromani is the place to go for the openSUSE package. Usually, this would be perfect, but there's no Download button, presumably because of the obvious compilation failure.

**Comment by manisandro** [comment]
OpenSUSE packages should be fixed now.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/manisandro/gImageReader/issues/653#issuecomment-1924795023

Thanks, @manisandro. I still couldn't find it using https://github.com/manisandro/gImageReader/blob/1daebd14d9e112c7541f6d66c96c6ba5a537831b/README.md#installation at https://build.opensuse.org/project/show/home:sandromani, but its compiled packages are available at https://software.opensuse.org/download/package?package=gimagereader&project=home%3Asandromani.
