### ISSUE TITLE
No executables (released/compiled on Nov/7/2023) on Windows [10] are working.

### ISSUE THREAD

**Issue by mxav1111** [manisandro/gImageReader#658]
It seems none of the windows executable are working. I attempted all GTK, QT , 686, x86_64, portables and they all give the same error or they just don't start. The ones that gives error code is 0x000142 and such like corrupt executable.
If the compiled/tested can be uploaded/provided, I am available to assist in QA if that helps.

**Comment by MartinW2** [comment]
Same here... - there is no log file gimagereader.log in the corresponding directory that could be shared. Programm crashes immediately at start. Previously installation uninstalled. Rebooted. Fresh install. No chance ... - please check/help. Thanks!

**Comment by manisandro** [comment]
Should be fixed by https://github.com/manisandro/gImageReader/commit/80277ba04547584147a6603b7070d246bc13db20

**Comment by MartinW2** [comment]
Confirmed to work - thank you!
