### ISSUE TITLE
Latin script or Trained data makes it crash each time.

### ISSUE THREAD

**Issue by Faster22** [manisandro/gImageReader#663]
So when i try using Latina it just crashes, i check the crash dumpfile and its empty. 

Also when  i try to add the spelling dictionaries for Lat ( the program forces me to use swedish).
Anyway when i try to add the extra data it just says dont find anything  for  "la" which is weird because in the yellow bar its called [lat].

![image](https://github.com/manisandro/gImageReader/assets/58865387/4cf665b3-69c8-46b7-979a-5aacd0d4add7)

**Comment by manisandro** [comment]
What does the error message read in english?
