### ISSUE TITLE
gimagereader-gtk: symbol lookup error

### ISSUE THREAD

**Issue by FabsMuller** [manisandro/gImageReader#664]
Hi Sandro and folks. Please I had gimagereader working fine on my Kubuntu 20.04,  upgraded to 22.04, workedn for some time and now  it stopped working. Try to reinstall, uninstall, install again, and use Sandro PPA (before I was using ubuntu default repo), but now always getting the same error: gimagereader-gtk: symbol lookup error: /lib/x86_64-linux-gnu/libgtkmm-3.0.so.1: undefined symbol: _ZN3Atk11ImplementorC2EOS0_ .I can confirm that is installing 3.4.1.1~jamyppa1 now but problem persist. Probably some GTK thing but what ? Any idea of whats happening ?  Thanks in advance.

**Comment by manisandro** [comment]
Does your `libgtkmm-3.0` package come from the correct distribution repos? The reported issue is that the `libgtkmm-3.0.so.1` which is shipped by `libgtkmm-3.0` contains an undefined symbol against `Atk::Implementor::Implementor(Atk::Implementor&&)`, which is typically found in `libatkmm-1.6.so`. The only explanation I have is that your `libgtkmm-3.0.so.1` was not build correctly. This is unrelated to gImageReader however.

**Comment by FabsMuller** [comment]
> Does your `libgtkmm-3.0` package come from the correct distribution repos? The reported issue is that the `libgtkmm-3.0.so.1` which is shipped by `libgtkmm-3.0` contains an undefined symbol against `Atk::Implementor::Implementor(Atk::Implementor&&)`, which is typically found in `libatkmm-1.6.so`. The only explanation I have is that your `libgtkmm-3.0.so.1` was not build correctly. This is unrelated to gImageReader however.

Thanks for the explanation Sandro, I tried to reinstall all libs related to libgtkmm-3.0 and libatkmm-1.6 with apt and official Ubuntu repos, which I found at the respective Ubuntu lib pages, but it didn't solve the problem. Same error message. I'm writing to the Ubuntu forum now to see if I can get any light. Unfortunately, I don't have a machine available right now to compile a qt5 version from the source and try to make a .deb package from it maybe I'll try to make it that later this year, as GTK is always a complicated thing to deal with. Anyway thanks again for the help. Brgds...
