### ISSUE TITLE
Instant crash on Ubuntu 16.04

### ISSUE THREAD

**Issue by pepa65** [manisandro/gImageReader#67]
First installed from the standard repo; then from the ppa (as mentioned in the README)

Output:
gimagereader-gtk: symbol lookup error: gimagereader-gtk: undefined symbol: _ZN9tesseract11TessBaseAPI13AnalyseLayoutEv

So, clone this git repo, do `cmake .` gives:
```
-- GSettings schemas will be installed locally.
-- GSettings shemas will be compiled.
-- qt5 interface will be built
-- Checking for module 'sane-backends'
--   No package 'sane-backends' found
CMake Error at CMakeLists.txt:109 (FIND_PACKAGE):
  By not providing "FindQt5DBus.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5DBus", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5DBus" with any
  of the following names:

    Qt5DBusConfig.cmake
    qt5dbus-config.cmake

  Add the installation prefix of "Qt5DBus" to CMAKE_PREFIX_PATH or set
  "Qt5DBus_DIR" to a directory containing one of the above files.  If
  "Qt5DBus" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!
See also "/home/pp/git/gImageReader/CMakeFiles/CMakeOutput.log".

```

Installing the qt5 version from the PPA works though!

**Comment by manisandro** [comment]
Looks like you are using a version of tesseract different from that in the repos. Can you check where you installed it from resp. try installing the version from the repos?
As for the build, you need all the correct build dependencies. For ubuntu, these are

    cmake,
    libgtkspellmm-3.0-dev,
    libgtkmm-3.0-dev,
    libgtksourceviewmm-3.0-dev,
    libcairomm-1.0-dev,
    libpoppler-glib-dev,
    libtesseract-dev,
    libsane-dev,
    qtbase5-dev,
    qttools5-dev,
    qttools5-dev-tools,
    libqtspell-qt5-dev,
    libpoppler-qt5-dev,
    libjson-glib-dev,
    libxml++2.6-dev

**Comment by pepa65** [comment]
Thanks for listing the build dependencies. I removed all traces of tesseract, I had 2 different libraries for it. Then installed the dependencies. When run with `TESSDATA_PREFIX=/usr/share/tesseract-ocr ./gimagereader-qt5` it works. (I don't seem to have a gtk version.)

**Comment by pepa65** [comment]
I'm guessing it should work from the repos now too.

**Comment by manisandro** [comment]
The repos have both Gtk and Qt version, if you build from source you can choose which one to build by setting `INTERFACE_TYPE` when running cmake, i.e. see

    SET(INTERFACE_TYPE "qt5" CACHE STRING "Select interface type: qt4/qt5/gtk")

in CMakeLists.txt

**Comment by pepa65** [comment]
The gtk version doesn't compile, can't find `/usr/include/poppler/glib/poppler-document.h`
```
...
[ 56%] Building CXX object CMakeFiles/gimagereader.dir/gtk/src/DisplayRenderer.cc.o
/home/pp/git/gImageReader/gtk/src/DisplayRenderer.cc:23:30: fatal error: poppler-document.h: No such file or directory
compilation terminated.
CMakeFiles/gimagereader.dir/build.make:167: recipe for target 'CMakeFiles/gimagereader.dir/gtk/src/DisplayRenderer.cc.o' failed
make[2]: *** [CMakeFiles/gimagereader.dir/gtk/src/DisplayRenderer.cc.o] Error 1
CMakeFiles/Makefile2:136: recipe for target 'CMakeFiles/gimagereader.dir/all' failed
make[1]: *** [CMakeFiles/gimagereader.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by manisandro** [comment]
Check that you are running from a clean build directory and that all necessary dev packages are installed. In the PPA I've built the gtk version without issues on 16.04.
