### ISSUE TITLE
Qt version does not offer "JPG" for open, only "jpg"

### ISSUE THREAD

**Issue by lionkmp** [manisandro/gImageReader#671]
Hi,
A minor issue... new user here...
This is on Ubuntu, and the deb packaged **3.4.0-2**, so this may have been fixed meanwhile...?

When I try to open files, my files are uppercase "JPG" (made with camera in my DIY-bookscanner), they are not visible in the File Open dialog, in Qt version. If I rename to "jpg" the files appear OK.

On GTK version both "JPG" and "jpg" are visible.

(As a quick workaround I can drag&drop files to the program. Or rename them...)

Thanks in advance if this can be fixed sometime..

**Comment by manisandro** [comment]
Hmm working fine here (qt5/qt6)

**Comment by lionkmp** [comment]
Tested 3.4.1-1 Debian package on Debian 12 and that works fine. So I think this can be closed. Probably not an error in original source code.
