### ISSUE TITLE
Private API enchant-provider.h, no more available since enchant 2.7

### ISSUE THREAD

**Issue by david-geiger** [manisandro/gImageReader#673]
Hi,

Since enchant 2.7 series the private API enchant-provider.h is no more available, so now build fails with:

`/home/pterjan/rpmbuild/BUILD/gimagereader-3.4.2/gtk/src/Config.cc:27:10: fatal error: enchant-provider.h: No such file or directory
   27 | #include <enchant-provider.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/gimagereader.dir/build.make:194: CMakeFiles/gimagereader.dir/gtk/src/Config.cc.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....`

**Comment by david-geiger** [comment]
kvirc fixes this kind of issue:

https://github.com/kvirc/KVIrc/pull/2636

**Comment by manisandro** [comment]
Thanks, I'll look into it

**Comment by manisandro** [comment]
Fixed in https://github.com/manisandro/gImageReader/commit/e72d657a408dc6b77c48c086feede31e08700b4c

**Comment by david-geiger** [comment]
Confirmed, thanks!
