### ISSUE TITLE
Help for gimageReader 3.1.90 spelling dictionaries download.

### ISSUE THREAD

**Issue by mikpalos** [manisandro/gImageReader#68]
I installed gimageReader on a non-connected notebook running win xp sp2 and it was smooth except that at the page https://cgit.freedesktop.org/libreoffice/dictionaries/tree/ I am at loss cause I read the link to the wanted dictionary, https://cgit.freedesktop.org/libreoffice/dictionaries/tree/Dictionary_el.mk, but I do not see how to download it (no button shown). On the other side I could easily download the greek language definitions. --- Thanks for your care, mik.

**Comment by manisandro** [comment]
Hi mik
For greek, you'll want to download the *.dic and *.aff files in el_GR, i.e. here:

https://cgit.freedesktop.org/libreoffice/dictionaries/tree/el_GR

Specifically, the links are:
https://cgit.freedesktop.org/libreoffice/dictionaries/plain/el_GR/el_GR.aff
and
https://cgit.freedesktop.org/libreoffice/dictionaries/plain/el_GR/el_GR.dic

Hope this helps
Sandro

**Comment by manisandro** [comment]
And note for the tessdata file: make sure you downloaded the actual raw file and not the github html page, i.e. that you downloaded
https://github.com/tesseract-ocr/tessdata/raw/master/ell.traineddata

**Comment by mikpalos** [comment]
Thank so much Sandro !
But that's what I had just done, repeatedly, with no effect, before writing you. I believe my Chrome on win 8.1 64 bit doesn't show any download button or link for virtually each of the files in the page.
On the other hand I could begin to smoothly (cause I'm arranging short excerpts only) work with my original download of tessdata and thank you in advance for what I'll be likely able to do even without the spellchecker.
In my share\tessdata the file you linked me to in your other message is already there with its 5296 KB in company with the grc one with its 8534 KB (which I don't know if really needed for ancient greek, I believe not).
Now my problem should be clearer and a way out easier.
I'm not in a hurry, anyway, and wish you
good job and good time
mik


----Messaggio originale----

Da: "Sandro Mani" <notifications@github.com>

Data: 14/06/2016 23.31

A: "manisandro/gImageReader"<gImageReader@noreply.github.com>

Cc: "mikpalos"<mpalos@libero.it>, "Author"<author@noreply.github.com>

Ogg: Re: [manisandro/gImageReader] Help for gimageReader 3.1.90 spelling dictionaries download. (#68)




Hi mik

For greek, you'll want to download the *.dic and *.aff files in el_GR, i.e. here:


https://cgit.freedesktop.org/libreoffice/dictionaries/tree/el_GR


Specifically, the links are:

https://cgit.freedesktop.org/libreoffice/dictionaries/plain/el_GR/el_GR.aff

and

https://cgit.freedesktop.org/libreoffice/dictionaries/plain/el_GR/el_GR.dic


Hope this helps

Sandro

**Comment by manisandro** [comment]
Whether your browser offers to download the file or displays the file directly depends on your settings I suppose. But if for instance the el_GR.aff is displayed directly as a text file inside the browser, just hit CTRL+S and save it to the harddrive.

**Comment by mikpalos** [comment]
Fine ! (never met a similar occasion before)

Best wishes --- mik

**Comment by mikpalos** [comment]
Caro! 

Ho  scoperto un negozio con un sacco di sorprendenti novità, dai un'occhiata, ve ne innamorerete <http://fede.simplysoho.com/pia>


Velocemente, mpalos Paloscia
