### ISSUE TITLE
How to compile it in windows?

### ISSUE THREAD

**Issue by sunshinfight** [manisandro/gImageReader#70]
Thanks for the amazing software.
There is no wiki for compile it in windows.I want to learn how it work.
Sorry for my bad English.
Thanks.

**Comment by manisandro** [comment]
Hi
I cross-compile the Windows build from Fedora (Linux), I've never compiled natively on Windows.
I suppose it should be possible to compile natively on Windows, you'll need to install MinGW and then find all the required dependencies (i.e. more or less what is listed as BuildRequires here [1]). Then you can proceed similarly to what the makeinstaller.sh script [2] does (which is what I use for cross-compilation on Fedora).

[1] https://github.com/manisandro/gImageReader/blob/master/packaging/gimagereader.spec.in
[2] https://github.com/manisandro/gImageReader/blob/master/packaging/win32/makeinstaller.sh

**Comment by sunshinfight** [comment]
Thanks a million!

**Comment by sunshinfight** [comment]
I can help you improve your software,but I am so busy now.I may have time neither next week or this week.
Sorry for my strange heavily-accented English. hahahah.....

**Comment by manisandro** [comment]
Feel free to reopen if questions arise.
