### ISSUE TITLE
unmodified source image as background 

### ISSUE THREAD

**Issue by fji88764** [manisandro/gImageReader#71]
When processing a 1bpp tiff file with about 50 kb size, GImagereader creates a pdf with invisible text overlay with about 675 kb size. I believe GImageReader actually changed the source image to a 8bpp JFIF image. Is it possible to change somewhere settings so that GImageReader really uses the unmodified source image (as tesseract does)?

Kind Regards,
D.

**Comment by manisandro** [comment]
Currently it re-renders the document. I have to check to what extent the Qt PDF printer allows flexibility here.

**Comment by manisandro** [comment]
Tracking this in #75, see latest comment there. The new PDF rendering library supports color/gray/mono image formats and should produce smaller files.
