### ISSUE TITLE
Cannot activate German Fraktur OCR on gImageReader

### ISSUE THREAD

**Issue by wally53** [manisandro/gImageReader#72]
Hi Sandro,
I am using gImageReader 3.1.91 with Tesseract 3.05.00 under Windows 7.
I am trying to do OCR with German Fraktur. I followed the dictionary installation instructions of an article of a German magazine, and installed the following:
1) copied the deu-frak.traineddata into the Tesseract language definitions folder 
2) copied the *.aff and *.dic files into the gImageReader folder 
They are there along with the en_US files. But when I try to select "German" with "Recognize selection", even after "Redetect Languages" I can't select "German" (or "Deutsch"). There is just "English" -> "English (United States)". This siituation was also previously addressed by other users - so I am probably missing something important somehow.

**Comment by narayaan** [comment]
I had the same problem which originated from not downloading the proper traineddata files. Is this solved for you by now?

**Comment by manisandro** [comment]
Closing due to no reply.
