### ISSUE TITLE
Icon is missing in Xfce4

### ISSUE THREAD

**Issue by wronguser** [manisandro/gImageReader#73]
Hi!

Some of gImageReader-3.1.91 icons have disappeared (a binary gimagereader-qt4 compiled from source):
![gimagereader-3 1 91](https://cloud.githubusercontent.com/assets/20736143/17268611/0b143b72-5640-11e6-9873-5d6eeb0dba90.png)

**Comment by manisandro** [comment]
Uhm that is the standard "document-edit" icon from the icon theme. Perhaps your theme is missing that icon?

**Comment by wronguser** [comment]
Yes, that could be it.

I found KDE Plasma 5:
![gimagereader-3 1 91-plasma5](https://cloud.githubusercontent.com/assets/20736143/17272499/a09ae5b6-56a8-11e6-9a2d-46c81195b6df.png)

**Comment by manisandro** [comment]
I'll close this, feel free to reopen if you think this is not related to the icon theme.

**Comment by manisandro** [comment]
I'll look into it as time allows, I suppose the best approach would be to adding the custom icons as the tutorial you link describes and have these as fallback. Currently I don't have much time to work on gImageReader though unfortunately, hence PRs welcome.

**Comment by manisandro** [comment]
Fixed in 4351602
