### ISSUE TITLE
Tif with 10 pages

### ISSUE THREAD

**Issue by Golddouble** [manisandro/gImageReader#74]
Hello,

I am in possession of a tif document with 10 pages.
I wanted to open it with gImageReader. But pImageReader shows only the first page. There is not a function to brows through the pages like in pdf- Files and so I also can not run the ocr- function through all pages. It's a pity.

Version 3.1.91 (beta)

**Comment by manisandro** [comment]
I currently use the Qt resp. Gdk pixbuf tif backends for reading such files, and it is indeed very likely that they don't support tifs with multiple directories. The only solution I guess would be to implement a new tif image reader based directly on libtiff which also handles directories. I wonder however how common such multi-directory tiff images are? Its the first time in many years a user has raised this issue.

**Comment by Golddouble** [comment]
Why was I trying to run OCR through a tif with multible pages?
Answer: I wanted to scan a book as s/w 1bit. But the scanning software of my scanner was not able to save s/w 1bit. But it was able to scan tif s/w 1bit. So this was the format in which I was scanning.

But in the meantime I have a solution (it takes one step more).
I scan the tif s/w 1bit. Then I use the software PDFill to convert the multipage tif s/w into a PDF s/w. But then there is another problem. See

**Comment by manisandro** [comment]
Ok so if this works for you I'd rather focus on the PDF size issue.

**Comment by Golddouble** [comment]
Yes, I agree.

**Comment by manisandro** [comment]
Main part is pending upstream review at [1]. At gImageReader level, support is added in 4413bfd6c4ffbcec698d2a3dc3ccf140592671e8 

[1] https://codereview.qt-project.org/#/c/181043/

**Comment by Golddouble** [comment]
> Main part is pending upstream review at [1]. At gImageReader level, support is added in 4413bfd

Does this mean, that now this is implemented?
I did not found this in version 3.2.1

I have tried a Tif- File with 10 pages. But gImageReader does still only recognize one page. (?)

**Comment by manisandro** [comment]
It will only be available once Qt-5.9 is released. Currently scheduled for May 31st.

**Comment by Golddouble** [comment]
Thank you.
