### ISSUE TITLE
pdf before: 0.8MB; after 20MB

### ISSUE THREAD

**Issue by Golddouble** [manisandro/gImageReader#75]
Hello,

I had a PDF- Document **black/white 1bit** with 18 pages. It was 827KB.
I opened it in gImageReader. Then I choose OCR modus hOCR, PDF. Then I run the automatic OCR through all of the 18 pages. Then I saved the result as PDF with text overlay. Now I got a PDF with 20MB.

My expectation was that I now get a PDF with about 1.1MB (827KB+some text), but not that 20MB big document. This will take a lot of needless harddisc space.

Version 3.1.91 (beta)

**Comment by manisandro** [comment]
Yes this is an issue I'm aware of: the Qt PDF printing classes offer no way to handle compression of the PDF result. I'll have to use another library to write the PDF which gives me more flexibility. This is something I'm looking at for version 3.2.0.

**Comment by Golddouble** [comment]
Thank you.

**Comment by Golddouble** [comment]
Version in use: preview from 2016-08-14 (Windows 7, 32bit)

Thank you for implementing the greystyle option. 

Now, for example, from an original tif-file of 51KB I can generate a file with 131KB (PDF, greystyle, with unvisible text) instead of 1227KB (color). 
The text component of the 131KB file is 3KB (according to a txt-file which I created by copy paste the text into.)

This is a great progress. But would be great to have also the 1bit option. So I would expect then a file with about 54KB.

**Comment by manisandro** [comment]
Qt does not offer a 1-bit option, so the only way to properly fix this is still to implement a custom PDF generation backend, which is some work.

**Comment by CharlesNepote** [comment]
Here is my experience if it can help.
* 12 pages scaned in TIFF 600 dpi format 95 MB each = 1,1 GB
* converted with Image Magick for **print usages**: `convert *.tiff -auto-orient -format pdf -compress jpeg -units PixelsPerInch -quality 90 document_print.pdf` => 110 MB
* converted with Image Magick for **screen usages**: `convert *.tiff -auto-orient -format pdf -compress jpeg -units PixelsPerInch -resample 150x150 -quality 85 document_screen.pdf` => 5,5 MB 
* gImageReader ouput from document_print.pdf: 30 MB colour PDF file.

What I would like:
* gImageReader should keep the original compression of the input pdf file
* gImageReader should be able to merge an hOCR file with another PDF; in my case document_screen.pdf because I want to produce two documents, one for screen and the other one to print usages.

**Comment by manisandro** [comment]
Merging files in another issue and in my view not something which directly integrates with the application, there are many existing tools to do so.

File size: I'm working on replacing the PDF generation library now and I hope to be able to offer various compression options to reduce the file size.

**Comment by CharlesNepote** [comment]
If you're working on PDF generation, could you think about generating PDF/A files (like https://github.com/jbarlow83/OCRmyPDF ), and not just PDF.

See https://en.wikipedia.org/wiki/PDF/A

Thanks a lot for all the good work Sandro! Tell me if I can help.

**Comment by manisandro** [comment]
I'm experimenting with PDFHummus [1]. If you have C++ experience and want to do some testing with that library (or any other C/C++ PDF library, though there are not so many open source ones), in particular as far as compressing the images in the PDF goes, I surely wouldn't mind ;)

[1] https://github.com/galkahana/PDF-Writer

**Comment by CharlesNepote** [comment]
Unfortunatly I'm not a programmer at all... just a bit of scripting in Bash and Perl, sorry. But I can help testing and writing.

**Comment by manisandro** [comment]
I've now implemented rendering with the PoDoFo PDF library (Qt version only atm, Gtk will follow). Could you give it some testing? In particular document size and whether various special characters are correctly rendered (keeping in mind that some fonts don't offer some characters though).
When building on Linux, remember to install libpodofo-dev / podofo-devel
Windows builds are here:
- 32bit: https://smani.fedorapeople.org/tmp/gImageReader_3.1.91_qt5_i686.exe
- 64bit: https://smani.fedorapeople.org/tmp/gImageReader_3.1.91_qt5_x86_64.exe

**Comment by CharlesNepote** [comment]
Build on Ubuntu Linux 16.04 with last git sources. Tested with both pdf file and jpeg file in input:

- the weight of the file is bigger than before: 190 Mb instead of 30 Mb
- the images are slanting (see screenshot)

![ajeter](https://cloud.githubusercontent.com/assets/562352/18815230/3a3ff99c-832a-11e6-8568-22a0a8f55a8e.jpg)

**Comment by manisandro** [comment]
Indeed looks like the image gets distorted for certain document sizes.... And that the file is even bigger sucks. Well, need to investigate further I suppose...

**Comment by manisandro** [comment]
Image distortion is fixed in a68998a. I've dug into the PoDoFo PDF code, and realized that it only supports compressing images with Zip. Still, if you produce the PDF with monochrome images it should be considerably smaller than previously. For gray/color, the previous implementation (which used QPrinter) will still produce smaller files most of the time since it (by hard-coded default) uses JPG compression with 94% quality. So this is a bit of a headache.

**Comment by manisandro** [comment]
Latest master should be looking pretty good now (qt interface). Please give it a try. Windows test-builds at the usual location are also updated.

**Comment by CharlesNepote** [comment]
Great job Sandro! Works fine. Zip|Jpeg choice is a very good idea.

There is a small issue: the resolution produced is 72 dpi and it does respect the original resolution.

Here is my complete test if it can help.
* 12 pages scaned in TIFF 600 dpi format 95 MB each = 1,1 GB
* converted with Image Magick for **print usages**: `convert *.tiff -auto-orient -format pdf -compress jpeg -units PixelsPerInch -quality 90 document_print.pdf` => 110 MB
* converted with Image Magick for **screen usages**: `convert *.tiff -auto-orient -format pdf -compress jpeg -units PixelsPerInch -resample 150x150 -quality 85 document_screen.pdf` => 5,5 MB 
* gImageReader ouput from document_print.pdf:
    * => 3,6 MB colour PDF file with Jpeg 10 Compression quality option.
    * => 8,8 MB colour PDF file with Jpeg 50 Compression quality option.
    * => 23,6 MB colour PDF file with Jpeg 90 Compression quality option.
    * => 76,2 MB colour PDF file with Jpeg 100 Compression quality option.
    * => 195 MB colour PDF file with Zip option.

Notice that the weight of the Jpeg 100 is far less than the original file due to 600 dpi => 72 dpi conversion.

Here is a complete analysys of my PDF files.

This is the original file, the input for gImageReader. Notice the 600 dpi.
```
$ pdfimages ./document_print.pdf -list
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image    4962  6378  rgb     3   8  jpeg   no         8  0   601   601 9241K  10%
   2     1 image    4962  6378  rgb     3   8  jpeg   no        22  0   601   601 9856K  11%
   3     2 image    4962  6378  rgb     3   8  jpeg   no        36  0   601   601 9.97M  11%
   4     3 image    4962  6378  rgb     3   8  jpeg   no        50  0   601   601 9452K  10%
   5     4 image    4962  6378  rgb     3   8  jpeg   no        64  0   601   601 8131K 8.8%
   6     5 image    4962  6378  rgb     3   8  jpeg   no        78  0   601   601 10.7M  12%
   7     6 image    4962  6378  rgb     3   8  jpeg   no        92  0   601   601 6936K 7.5%
   8     7 image    4962  6378  rgb     3   8  jpeg   no       106  0   601   601 8193K 8.8%
   9     8 image    4962  6378  rgb     3   8  jpeg   no       120  0   601   601 7376K 8.0%
  10     9 image    4962  6378  rgb     3   8  jpeg   no       134  0   601   601 9351K  10%
  11    10 image    4962  6378  rgb     3   8  jpeg   no       148  0   601   601 8627K 9.3%
  12    11 image    4962  6378  rgb     3   8  jpeg   no       162  0   601   601 9750K  11%
```

Here is the file produced by gImageReader (Jpeg 100 Quality option). Notice that the resolution is now 72 dpi.
```
$ pdfimages ./document_print_aftergImageReader.pdf -list
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image    2480  3188  rgb     3   8  jpeg   no        15  0    72    72 6186K  27%
   2     1 image    2481  3189  rgb     3   8  jpeg   no        19  0    72    72 6533K  28%
   3     2 image    2481  3189  rgb     3   8  jpeg   no        23  0    72    72 6544K  28%
   4     3 image    2481  3189  rgb     3   8  jpeg   no        27  0    72    72 6452K  28%
   5     4 image    2481  3189  rgb     3   8  jpeg   no        31  0    72    72 5923K  26%
   6     5 image    2481  3189  rgb     3   8  jpeg   no        35  0    72    72 6731K  29%
   7     6 image    2481  3189  rgb     3   8  jpeg   no        39  0    72    72 5303K  23%
   8     7 image    2481  3189  rgb     3   8  jpeg   no        43  0    72    72 5809K  25%
   9     8 image    2481  3189  rgb     3   8  jpeg   no        47  0    72    72 5503K  24%
  10     9 image    2481  3189  rgb     3   8  jpeg   no        51  0    72    72 5938K  26%
  11    10 image    2481  3189  rgb     3   8  jpeg   no        55  0    72    72 6524K  28%
  12    11 image    2481  3189  rgb     3   8  jpeg   no        59  0    72    72 6702K  29%
```

Just tell me if you want more tets or data.

**Comment by manisandro** [comment]
How does the `pdfinfo` output compare between `document_print.pdf` and `document_print_aftergImageReader.pdf`?

**Comment by CharlesNepote** [comment]
```
$ pdfinfo ./document_print.pdf
Title:          document
Producer:       ImageMagick 6.8.9-9 Q16 x86_64 2016-06-01 http://www.imagemagick.org
CreationDate:   Sun Sep  4 22:35:42 2016
ModDate:        Sun Sep  4 22:35:42 2016
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          12
Encrypted:      no
Page size:      595.44 x 765.36 pts
Page rot:       0
File size:      110741763 bytes
Optimized:      no
PDF version:    1.3

$ pdfinfo ./document_print_aftergImageReader.pdf
Producer:       PoDoFo - http://podofo.sf.net
CreationDate:   Fri Sep 30 10:13:18 2016
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          12
Encrypted:      no
Page size:      2480 x 3188 pts
Page rot:       0
File size:      76195473 bytes
Optimized:      no
PDF version:    1.3
```

**Comment by manisandro** [comment]
Ok should be fixed in latest master: it now correctly sizes the PDF paper size and preserves the dpi of the images. I did some testing and it seemed to work, but I'd appreciate further testing, in particular stuff like mixing documents with different resolutions.

**Comment by CharlesNepote** [comment]
From a PDF document 150 dpi, gImageReader, with Jpeg 100 option, produce a document at 300 dpi.
```
$ pdfinfo document_screen.pdf
Title:          document
Producer:       ImageMagick 6.8.9-9 Q16 x86_64 2016-06-01 http://www.imagemagick.org
CreationDate:   Sat Sep  3 16:34:54 2016
ModDate:        Sat Sep  3 16:34:54 2016
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          12
Encrypted:      no
Page size:      595.68 x 765.6 pts
Page rot:       0
File size:      5490886 bytes
Optimized:      no
PDF version:    1.3

$ pdfimages document_screen.pdf -list
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image    1241  1595  rgb     3   8  jpeg   no         8  0   150   150  445K 7.7%
   2     1 image    1241  1595  rgb     3   8  jpeg   no        22  0   150   150  502K 8.6%
   3     2 image    1241  1595  rgb     3   8  jpeg   no        36  0   150   150  477K 8.2%
   4     3 image    1241  1595  rgb     3   8  jpeg   no        50  0   150   150  501K 8.6%
   5     4 image    1241  1595  rgb     3   8  jpeg   no        64  0   150   150  418K 7.2%
   6     5 image    1241  1595  rgb     3   8  jpeg   no        78  0   150   150  490K 8.4%
   7     6 image    1241  1595  rgb     3   8  jpeg   no        92  0   150   150  301K 5.2%
   8     7 image    1241  1595  rgb     3   8  jpeg   no       106  0   150   150  401K 6.9%
   9     8 image    1241  1595  rgb     3   8  jpeg   no       120  0   150   150  314K 5.4%
  10     9 image    1241  1595  rgb     3   8  jpeg   no       134  0   150   150  331K 5.7%
  11    10 image    1241  1595  rgb     3   8  jpeg   no       148  0   150   150  573K 9.9%
  12    11 image    1241  1595  rgb     3   8  jpeg   no       162  0   150   150  563K 9.7%

$ pdfinfo document_screen_after_gImageReader.pdf
Producer:       PoDoFo - http://podofo.sf.net
CreationDate:   Sat Oct  1 10:08:39 2016
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          12
Encrypted:      no
Page size:      595.44 x 765.6 pts
Page rot:       0
File size:      41343021 bytes
Optimized:      no
PDF version:    1.3

$ pdfimages document_screen_after_gImageReader.pdf -list
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image    2481  3190  rgb     3   8  jpeg   no        15  0   301   300 3420K  15%
   2     1 image    2482  3190  rgb     3   8  jpeg   no        19  0   300   300 3591K  15%
   3     2 image    2482  3190  rgb     3   8  jpeg   no        23  0   300   300 3505K  15%
   4     3 image    2482  3190  rgb     3   8  jpeg   no        27  0   300   300 3677K  16%
   5     4 image    2482  3190  rgb     3   8  jpeg   no        31  0   300   300 3206K  14%
   6     5 image    2482  3190  rgb     3   8  jpeg   no        35  0   300   300 3559K  15%
   7     6 image    2482  3190  rgb     3   8  jpeg   no        39  0   300   300 2676K  12%
   8     7 image    2482  3190  rgb     3   8  jpeg   no        43  0   300   300 3063K  13%
   9     8 image    2482  3190  rgb     3   8  jpeg   no        47  0   300   300 2709K  12%
  10     9 image    2482  3190  rgb     3   8  jpeg   no        51  0   300   300 2749K  12%
  11    10 image    2482  3190  rgb     3   8  jpeg   no        55  0   300   300 3994K  17%
  12    11 image    2482  3190  rgb     3   8  jpeg   no        59  0   300   300 3959K  17%
```

**Comment by CharlesNepote** [comment]
From a PDF document 600 dpi, gImageReader, with Jpeg 100 option, produce a document at 300 dpi.
```
$ pdfimages document_print.pdf -list
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image    4962  6378  rgb     3   8  jpeg   no         8  0   601   601 9241K  10%
   2     1 image    4962  6378  rgb     3   8  jpeg   no        22  0   601   601 9856K  11%
   3     2 image    4962  6378  rgb     3   8  jpeg   no        36  0   601   601 9.97M  11%
   4     3 image    4962  6378  rgb     3   8  jpeg   no        50  0   601   601 9452K  10%
   5     4 image    4962  6378  rgb     3   8  jpeg   no        64  0   601   601 8131K 8.8%
   6     5 image    4962  6378  rgb     3   8  jpeg   no        78  0   601   601 10.7M  12%
   7     6 image    4962  6378  rgb     3   8  jpeg   no        92  0   601   601 6936K 7.5%
   8     7 image    4962  6378  rgb     3   8  jpeg   no       106  0   601   601 8193K 8.8%
   9     8 image    4962  6378  rgb     3   8  jpeg   no       120  0   601   601 7376K 8.0%
  10     9 image    4962  6378  rgb     3   8  jpeg   no       134  0   601   601 9351K  10%
  11    10 image    4962  6378  rgb     3   8  jpeg   no       148  0   601   601 8627K 9.3%
  12    11 image    4962  6378  rgb     3   8  jpeg   no       162  0   601   601 9750K  11%
  
$ pdfimages document_print_after_gImageReader.pdf -list
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image    2480  3188  rgb     3   8  jpeg   no        15  0   301   300 6186K  27%
   2     1 image    2481  3189  rgb     3   8  jpeg   no        19  0   301   301 6533K  28%
   3     2 image    2481  3189  rgb     3   8  jpeg   no        23  0   301   301 6544K  28%
   4     3 image    2481  3189  rgb     3   8  jpeg   no        27  0   301   301 6452K  28%
   5     4 image    2481  3189  rgb     3   8  jpeg   no        31  0   301   301 5923K  26%
   6     5 image    2481  3189  rgb     3   8  jpeg   no        35  0   301   301 6731K  29%
   7     6 image    2481  3189  rgb     3   8  jpeg   no        39  0   301   301 5303K  23%
   8     7 image    2481  3189  rgb     3   8  jpeg   no        43  0   301   301 5809K  25%
   9     8 image    2481  3189  rgb     3   8  jpeg   no        47  0   301   301 5503K  24%
  10     9 image    2481  3189  rgb     3   8  jpeg   no        51  0   301   301 5938K  26%
  11    10 image    2481  3189  rgb     3   8  jpeg   no        55  0   301   301 6524K  28%
  12    11 image    2481  3189  rgb     3   8  jpeg   no        59  0   301   301 6702K  29%
```

**Comment by manisandro** [comment]
gImageReader renders the document at 300dpi by default (in the imaging controls toolbar, you can select which dpi to use).

Note that a PDF document does not have a dpi per-se (dpi makes no sense for vector objects such as text). Images within a PDF document have a resolution, but that resolution can vary from image to image.

**Comment by CharlesNepote** [comment]
Here is another interesting test.

* 12 pages scaned in TIFF 600 dpi format 95 MB each = 1,1 GB
* converted to PDF with Image Magick for **print usages** with **lossless compression**: `convert *.tiff -auto-orient -format pdf -compress ZIP -units PixelsPerInch document_print.pdf` => 650,2 MB
* gImageReader ouput from document_print.pdf (600dpi):
    * => 11,2 MB colour PDF file with Jpeg 10 Compression quality option.
    * => 54 MB colour PDF file with Jpeg 85 Compression quality option.
    * => 69 MB colour PDF file with Jpeg 90 Compression quality option.
    * => 240,1 MB colour PDF file with Jpeg 100 Compression quality option.
    * => 737 MB colour PDF file with Zip Compression quality option.

The last one shouldn't be very different from the original PDF file isn't it? But 737 MB is far bigger than 650 MB.
And Jpeg 100 Compression quality option should produce a file bigger than 240 MB (it should be around 330 MB if I compress by hand each original tiff file to Jpeg 100).

**Comment by manisandro** [comment]
One would need to compare the internal structure of the PDF files to understand the reasons for the size differences. However, it's unlikely that I would be able to influence that from gImageReader itself since it is in the domain of the PDF library (PoDoFo).

**Comment by manisandro** [comment]
I think all issues here should be addressed now. Thanks for testing!
