### ISSUE TITLE
best Text recognition

### ISSUE THREAD

**Issue by Golddouble** [manisandro/gImageReader#77]
Am I right if I assume that the text recognition ist best with C) below?

A) 300dpi black/white 1bit (compression withpout loss)
B) 300dpi grey 8bit (jpg, standard compression)
C) 300dpi colour 24bit (jpg, standard compression)

Am I right if I assume that the text recognition is fastest with A) above?

Thank you for answering.

**Comment by manisandro** [comment]
About compression: lossy compression will always to some degree deteriorate the image and affect the quality of the result. Performance of various formats depends on the work needed to decode the image into a raw image buffer. So it's to be expected that decoding a jpeg image is more work than i.e. an uncompressed TIFF image.

About dpi: this parameter will influence the result the most

About colormap / depth:
- As far as gImageReader is concerned, all images are decoded into a raw 32bit RGBA image buffer, so it makes no difference
- As far as using tesseract directly from the command line, I'm not really sure whether it makes a difference, I suspect it internally also just decodes the image and operates on a raw image buffer, but I haven't checked the source code.

(For clarity: tesseract is the OCR engine used by gImageReader)

**Comment by Golddouble** [comment]
Thank you.

**Comment by Golddouble** [comment]
Now I did a test of the following input:
![libra](https://cloud.githubusercontent.com/assets/13977359/17616567/ea9c4656-6075-11e6-9333-f7ef5b08a557.PNG)

I have scanned this text three times. Then I have made the following files:
A) Tif colour 24 bit 300dpi
B) Tif grey 8 bit 300dpi
C) Tif b/w 2 bit 300dpi

Output:
A)  wollten, die libm als Gewicht
B)  wollten, die libm als Gewicht
C)  wollten, die libra als Gewicht

Only C) is correct.
