### ISSUE TITLE
spaces between words

### ISSUE THREAD

**Issue by Golddouble** [manisandro/gImageReader#78]
Beta- Version in use

A) 
I extract with mark and copy paste a text of a document "hOCR, PD", and "PDF with hidden text". This text looks like the following:
fragment: 
56 ErsteRegel:Das »heilige«VorrechtderGoldmünzenprägung
fort die Bedeutung dieses Aktes und erklärten Abd-el—Malik den
Krieg, noch bevor Iustinian von dem Vorfall unterrichtet wurde.
Dieser Vorgang liefert plausible Argumente für einen institutionellen
bzw. gesetzlichenUrsprung des Geldes. Theodor Mommsen

B)
I extract with mark and copy paste a text of a document "hOCR, PDF" and "PDF with hidden text". This text looks like the following:
fragment: 
56 Erste Regel: Das »heilige« Vorrecht der Goldmünzenprägung
fort die Bedeutung dieses Aktes und erklärten Abd-el—Malik den
Krieg, noch bevor Iustinian von dem Vorfall unterrichtet wurde.
Dieser Vorgang liefert plausible Argumente für einen institutionellen
bzw. gesetzlichen Ursprung des Geldes. Theodor Mommsen

As you can see in A) sometimes there is no space between the words where a space must be. Whereas in B) the spaces are present.

If I make a plain text (notepad-text) the spaces are also present as in B).
If I make a text PDF the spaces are also present as in B).

Are you aware of the unwanted behavior in A)?

**Comment by Golddouble** [comment]
This was the document:
http://www.bilder-upload.eu/show.php?file=d3ccec-1470386079.png

**Comment by manisandro** [comment]
The issue is that while tesseract attempts to detect the font size of the word, there is guarantee that the font used for the invisible overlay text has metrics similar to the font of the document. So it can indeed happen that unluckily the overlay text words overflow the bounding boxes of the original words, resulting in the missing space. I'm working on adding a preview mode and allowing the user to select the font for the text overlay, so that such issues can be avoided. I should have something testable by the end of the week.

**Comment by Golddouble** [comment]
Thank you.

**Comment by manisandro** [comment]
Preview implemented in f2c7c6f, testable with this build:
http://smani.fedorapeople.org/tmp/gImageReader_3.1.91_qt5_x86_64.exe

**Comment by Golddouble** [comment]
Thank you for implementing this in the preview of 216-08-14.

**"Show preview" does his job great.** 

**Error?**
But notice: If I choose 
-Output mode: PDF
-Image format: Greyscale
-And then choose "show preview" it becomes just black instead of a preview.

**wondering:**
When I choose 
-automated font size and
-Uniformize line and word spacing
then I wonder how large the shift between the origianal lines and the hidden lines are:
![unbenannt](https://cloud.githubusercontent.com/assets/13977359/18206913/2a7a8986-7129-11e6-8804-0ab28f14bbef.PNG)

**paragraphs:**
Also with the settings above the paragraphs are not respected.

**Comment by manisandro** [comment]
Error:
Looks like you are right, I've also managed to reproduce this. I need to investigate

Wondering:
Well the algorithm simply evenly distributes the text lines within a text block. So only the bounding box of the text block is relevant, the original positions of the lines do not matter anymore. But this option is not really meant for use with overlay mode (at least, I can't think of a case where it makes sense to use). Rather, the font size is the interesting parameter in overlay mode.

Paragraphs:
Depends on how the text structure is recognized. Everything within a block of text is uniformized, so if a block of text does not match a paragraph, then yes, these will not be correctly handled.

**Comment by Golddouble** [comment]
Error:
Thank you.

Wondering:
OK. I understand that the option "uniformice  line and word spacing" is not meant together with "PDF with unvisible text overlay".

Paragraphs:
You understand? What I mean is the "insert- text- effect" at the beginning of a new paragraph. For example by 
"Dieser Vorgang..." or "Hingegen durftn..." or "Nicht einmal..." 

Here, with the other programme version (beta), this effect was kept: https://github.com/manisandro/gImageReader/issues/81

**Comment by manisandro** [comment]
Can you elaborate on the issue with Paragraphs resp. post a screenshot showing the issue?

**Comment by manisandro** [comment]
The grayscale corruption issue is fixed in b54849d

**Comment by manisandro** [comment]
Regarding the paragraphs indent issue: I understood now what you mean, the issue is simply the width of the space which is preserved when uniformizing (i.e. spaces wider than what width remain preserved). Before this amount was hard-coded to 4 chars, now with 17c7353 it is configurable.

**Comment by Golddouble** [comment]
Thank you for implementing this. With the preview it works. 
"Preserve spaces wider than 2 characters"
![gimagereader abschnitte works](https://cloud.githubusercontent.com/assets/13977359/18416245/c31cd14e-780e-11e6-8329-3373e7179e8c.PNG)
