### ISSUE TITLE
refinement- Button: plain text (notepad-Text)

### ISSUE THREAD

**Issue by Golddouble** [manisandro/gImageReader#79]
Beta- Version in use

Soetimes the function "put together divided words" seems not to work.

I have an example: http://www.bilder-upload.eu/show.php?file=d3ccec-1470386079.png

The german word prä-gen is not connected, whereas the other divided words were correct put togheter:

Fragment A) before:
_direkt untergeordneten Provinzen noch die mehr oder minder **un-
abhängigen**, an das Imperium angrenzenden Staaten den Versuch
unternahmen, Goldmünzen zu prägen.3_

_Hingegen durften lokale Herrscher Silbermünzen nach dem von
]ulius Cäsar eingeführten römischen Wertverhältnis von 12:1 **prä—
gen**.*_

Fragment A) after:
_direkt oder indirekt untergeordneten Provinzen noch die mehr oder minder **unabhängigen**, an das Imperium angrenzenden Staaten den Versuch unternahmen, Goldmünzen zu prägen.3 Hingegen durften lokale Herrscher Silbermünzen nach dem von ]ulius Cäsar eingeführten römischen Wertverhältnis von 12:1 **prä— gen**.*_

Why was the word prä-gen not put togheter?

**Comment by Golddouble** [comment]
A) I extract with mark and copy paste a text of a document hOCR, PDF and PDF with hidden text. This text looks like the following:
fragment: 
56 ErsteRegel:Das »heilige«VorrechtderGoldmünzenprägung
fort die Bedeutung dieses Aktes und erklärten Abd-el—Malik den
Krieg, noch bevor Iustinian von dem Vorfall unterrichtet wurde.
Dieser Vorgang liefert plausible Argumente für einen institutionellen
bzw. gesetzlichenUrsprung des Geldes. Theodor Mommsen

B) I extract with mark and copy paste a text of a document hOCR, PDF and PDF with hidden text. This text looks like the following:
fragment: 
56 Erste Regel: Das »heilige« Vorrecht der Goldmünzenprägung
fort die Bedeutung dieses Aktes und erklärten Abd-el—Malik den
Krieg, noch bevor Iustinian von dem Vorfall unterrichtet wurde.
Dieser Vorgang liefert plausible Argumente für einen institutionellen
bzw. gesetzlichen Ursprung des Geldes. Theodor Mommsen

As you can see in A) Sometimes there is no space between the words where a space must be. Whereas in B) the spaces are present.

If I make a plain text  the spaces are also present as in B).
If I make a text PDF the spaces are also present as in B).

Are you aware of the unwanted behaviour in A)?

**Comment by Golddouble** [comment]
http://www.bilder-upload.eu/show.php?file=d3ccec-1470386079.png

**Comment by manisandro** [comment]
I used the regex \w pattern, meaning [a-zA-Z], for detecting word characters, but the umlaut ä is not part of that set. I'll need to improve the logic to also handle non-ascii characters.

**Comment by Golddouble** [comment]
Thank you.

**Comment by manisandro** [comment]
Actually, my analysis was wrong here. The problem is that it is not using `-` as the hyphen, but rather `—`.

**Comment by manisandro** [comment]
Fixed in 6a9ce81

**Comment by Golddouble** [comment]
Thank you. In the preview of 2016-08-14 it works.
