### ISSUE TITLE
 refinement- Button: plain text (notepad-Text) passages

### ISSUE THREAD

**Issue by Golddouble** [manisandro/gImageReader#80]
Beta version in use.

Seems that the function "keep passages" does not work:

before:
```
56 Erste Regel: Das »heilige« Vorrecht der Goldmünzenprägung
fort die Bedeutung dieses Aktes und erklärten Abd-el—Malik den
Krieg, noch bevor Iustinian von dem Vorfall unterrichtet wurde.

Dieser Vorgang liefert plausible Argumente für einen institutio-
nellen bzw. gesetzlichen Ursprung des Geldes. Theodor Mommsen
schreibt in seiner Römischen Geschichte, die Goldprägung sei in den
Provinzen nicht erlaubt gewesen,2 und Lenormant weist darauf hin,
daß viele Jahrhunderte lang weder die dem Basileus direkt oder in-
direkt untergeordneten Provinzen noch die mehr oder minder un-
abhängigen, an das Imperium angrenzenden Staaten den Versuch
unternahmen, Goldmünzen zu prägen.3

Hingegen durften lokale Herrscher Silbermünzen nach dem von
]ulius Cäsar eingeführten römischen Wertverhältnis von 12:1 prä—
gen.* Del Mar zufolge blieb dieses Wertverhältnis bis 1204 in Kraftﬁ‘

Nicht einmal die Päpste wagten es nach ihrer Abspaltung vom
Oströrnischen Reich unter Stephan 11. (752—757), Goldmünzen zu
prägen. Dies änderte sich erst im Jahre 1204, als das Byzantinische
Reich im vierten Kreuzzug erobert wurde. Von diesem Zeitpunkt an
prägten lokale Herrscher überall in Europa Goldmünzen:
Europäische Goldmünzen nach dem Ende des Römischen Reiches
Zeitpunkt Ort Herrscher Bezeichnung Gewicht

der Münze
1225 Neapel Friedrich II. Aureus 81—82 Gran
1225 Lyon Alfonso Dukat 54 Gran
1250 Paris Ludwig IX. Ag’nel 63 Gran
1252 Florenz Republik Florin 56 Gran
1257 England Heinrich III. Penny 43 Gran
1284 Venedig Republik Dukat 56 Gran
1316 Avignon Papst Sequin 54 Gran
Iohannes XXII.
" Del Mar zeigte, daß die Forscher, die aus dem Codex Theodosianus ein Verhältnis von
14,4 : 1 nachweisen wollten, die lihra als Gewicht (anstatt als Zahlgeld) mißverstanden.
```

after:
`56 Erste Regel: Das »heilige« Vorrecht der Goldmünzenprägung fort die Bedeutung dieses Aktes und erklärten Abd-el—Malik den Krieg, noch bevor Justinian von dem Vorfall unterrichtet wurde. Dieser Vorgang liefert plausible Argumente für einen institutio- nellen bzw. gesetzlichen Ursprung des Geldes. Theodor Mommsen schreibt in seiner Römischen Geschichte, die Goldprägung sei in den Provinzen nicht erlaubt gewesen,2 und Lenormant weist darauf hin, daß viele Jahrhunderte lang weder die dem Basileus direkt oder in- direkt untergeordneten Provinzen noch die mehr oder minder un- abhängigen, an das Imperium angrenzenden Staaten den Versuch unternahmen, Goldmünzen zu prägen.3 Hingegen durften lokale Herrscher Silbermünzen nach dem von Julius Cäsar eingeführten römischen Wertverhältnis von 12:1 prä— gen.* Del Mar zufolge blieb dieses Wertverhältnis bis 1204 in Kraftﬁ‘ Nicht einmal die Päpste wagten es nach ihrer Abspaltung vom Oströrnischen Reich unter Stephan 11. (752—757), Goldmünzen zu prägen. Dies änderte sich erst im Jahre 1204, als das Byzantinische Reich im vierten Kreuzzug erobert wurde. Von diesem Zeitpunkt an prägten lokale Herrscher überall in Europa Goldmünzen: Europäische Goldmünzen nach dem Ende des Römischen Reiches Zeitpunkt Ort Herrscher Bezeichnung Gewicht der Münze 1225 Neapel Friedrich II. Aureus 81—82 Gran 1225 Lyon Alfonso Dukat 54 Gran 1250 Paris Ludwig IX. Ag’nel 63 Gran 1252 Florenz Republik Florin 56 Gran 1257 England Heinrich III. Penny 43 Gran 1284 Venedig Republik Dukat 56 Gran 1316 Avignon Papst Sequin 54 Gran Johannes XXII. " Del Mar zeigte, daß die Forscher, die aus dem Codex Theodosianus ein Verhältnis von 14,4 : 1 nachweisen wollten, die lihra als Gewicht (anstatt als Zahlgeld) mißverstanden.`

**Comment by manisandro** [comment]
I'll need to investigate.

**Comment by manisandro** [comment]
Fixed in eb69723

**Comment by Golddouble** [comment]
In the preview of 2016-08-14 it works.
