### ISSUE TITLE
PDF autoformated

### ISSUE THREAD

**Issue by Golddouble** [manisandro/gImageReader#82]
In the attached files you can see, that the text in the source document has always the same size. But in the output PDF (autoformated) document the size of the font changes between smaller and larger size.
Maybe there should be implemented an option to make the automated font size recognition less sensitive.

source File:
![ocr original](https://cloud.githubusercontent.com/assets/13977359/17545870/8000c34a-5edf-11e6-8753-b43fc752a2cd.PNG)

output File:
![ocr font-formating automatic](https://cloud.githubusercontent.com/assets/13977359/17545874/8eee5de0-5edf-11e6-8dae-2175e1e1ad47.PNG)

**Comment by manisandro** [comment]
This is also up to tesseract. You can edit the sizes in output attribute table. I could add the possibility to se the font-size for entire paragraphs though. But if you wish to have the font-size "correct" right-away after recognizing, you'll have to work with tesseract upstream.

**Comment by Golddouble** [comment]
Now in the preview of 216-08-14 it does not longer respect paragraphs with "uniforme line and word spacing":
![abschnitte](https://cloud.githubusercontent.com/assets/13977359/18207876/55bae024-712d-11e6-92f2-ec843c04847b.PNG)
