### ISSUE TITLE
language definitions; spelling dictionaries

### ISSUE THREAD

**Issue by Golddouble** [manisandro/gImageReader#84]
1) language definitions:
According to the "gImageReader 3.1.91 Manual" we have to copy the <lang>.traineddata files into Start→All Programs→gImageReader→Tesseract language definitions.
This would be in my case deu.traineddata and deu_frak.traineddata I guess.

So when I went to this folder there is actual only eng.traineddata inside it. So I thought that I have to copy the above files in this folder. But in the settings there is a section "predefined language definitions". And in this list also "Deutsch" and "Deutsch (Fraktur)" are listed. So are they always installed?
-> This looks for me like a contradiction. Have I now to copy the deu.traineddata and deu_frak.traineddata into the folder or not?

2) spelling dictionaries:
The spelling correction for German seems to work. But wehn I go to "Start→All Programs→gImageReader→Spelling dictionaries" there only is en_US.aff and en_US.dic. I was expecting, that there is also a German .aff and a German .dic.
-> This also confuses me.

Thank you for clearify this confusions.

**Comment by manisandro** [comment]
So, with regard to "predefined language definitions" in the settings: gImageReader needs to know how to map a tessdata to a spelling dictionary for the matching language. Unfortunately, tessdatas do not contain any metadata as to what language it was trained for, the only information one has is the prefix in the file, i.e. the deu in deu.traineddata. This *typically* is the 639-2 three-character language code, but variations can occur (such as the added _frak, or non-standard language codes). So the most robust way to ensure the correct tessdata -> spelling dictionary mapping is to list these mappings explicitly. For all know traineddatas, I've pre-configured the mapping in the program, and that is what you see under "predefined language definitions". If you come across some other traineddata, you can add the mapping in the are below the predefined section.

So with regards to 1). The "predefined language definitions" just lists all known mappings, but you do indeed have to explicitly download all traineddata files you wish to use for recognition.

With regard to 2), this confuses me also, I don't know how the spellchecker should be able to check german if no such dictionaries are installed. In the language menu next to the recognize button, does "German" have a submenu? Only languages for which spelling is installed have a submenu, from which you can choose between various dictionary flavours (i.e. swiss german or german german).

**Comment by Golddouble** [comment]
Thank you.

dics:
Now I found them. Insted of beeing in 
C:\Program Files\OCR (gImageReader)\share\myspell\dicts
(which is the folder to which there is a connection in the gImageReader menu),
they are in the folder
C:\Users\User1\AppData\Local\VirtualStore\Program Files\OCR (gImageReader)\share\myspell\dicts

(-> Windows 7)

So my question is:
Doesn't it matter if I copy the dics into 
C:\Program Files\OCR (gImageReader)\share\myspell\dicts or
C:\Users\User1\AppData\Local\VirtualStore\Program Files\OCR (gImageReader)\share\myspell\dicts?
Can I copy some to C:\Program Files\OCR (gImageReader)\share\myspell\dicts and others to C:\Users\User1\AppData\Local\VirtualStore\Program Files\OCR (gImageReader)\share\myspell\dicts?

The same question with tessdata:
Can I copy them eigther to C:\Program Files\OCR (gImageReader)\share\tessdata or to C:\Users\User1\AppData\Local\VirtualStore\Program Files\OCR (gImageReader)\share\tessdata

**Comment by manisandro** [comment]
Well essentially it depends where you installed the application to (i.e. which path you or whoever installed the application chose in the installer). It looks like you picked `C:\Users\User1\AppData\Local\VirtualStore\Program Files\OCR (gImageReader)`, so the files will have to be installed in the subdirectories therein. Now if the links in the start menu pointed to the wrong location, that would be a bug I'd need to look at.

**Comment by Golddouble** [comment]
What you write is not fully correct.

One part is in the
C:\Program Files\OCR (gImageReader)
Another part is in the
C:\Users\User1\AppData\Local\VirtualStore\Program Files\OCR (gImageReader)\

As you can see in the picture:
![folders gimagereader](https://cloud.githubusercontent.com/assets/13977359/17569323/fc4da3ec-5f47-11e6-8030-a99e5e892144.PNG)

**Comment by manisandro** [comment]
Ah looks like this `VirtualStore` is a Windows feature which allows applications to deal with folders which would require admin-privileges for writing by using instead corresponding folders in the user profile dir, where the user has writing permissions.

Sorry, I'm not a Windows user, so I don't know precisely how this feature is supposed to work. But it looks like the folders in VirtualStore are simply complementary to the files under %ProgramFiles% where you don't have writing permissions by default.

**Comment by Golddouble** [comment]
Yes, I think you are right. 
I now have added in the gImageReader menu the two connections into the virtualStore folder.

**Comment by manisandro** [comment]
Concering VirtualStore, does the integrated tessdata manger (i.e. the "Manage Languages..." entry in the language selection menu) work? Some people reported it didn't work on Windows Vista and newer due to UAC blocking access to %ProgramFiles%, but VirtualStore should be able to work around this issue? (Next question then would be if this VirtualStore is enabled by default or not).

**Comment by Golddouble** [comment]
1.
Installing tessaract language definitions with the manager works. The _dan.traineddata_ goes to the VirtualStore. And after, it is in the menu.
But there is an error when the manager tries to install the dic.

2.
Not shure about this because I can't remember me for shure: But when I was installing gImageReader it was asking me, if I want to use the virtuelStore because of the blocking issue.

**Comment by manisandro** [comment]
Uhm what kind of error? Basically the same code is used for saving traineddata files as is for dic/aff files. Unless of course it cannot find an appropriate spelling dictionary, in that case the error would be expected.

**Comment by Golddouble** [comment]
Yes, I think it cannot find an appropriate spelling dictionary.

I have made a little Gif- animation for you:
http://www.bilder-upload.eu/show.php?file=6be415-1470917233.gif

**Comment by manisandro** [comment]
Ok thanks, I've debugged it and noticed that the application searches for `da` but the repository has the files under `da_DK`. I'll improve the logic - I'll send you a test version this weekend with the PDF export preview functionality which I've almost finished.

Closing this particular ticket since I think the questions are answered?

**Comment by Golddouble** [comment]
Perhaps we can keep in mind to add the following connections in the start menu by the installations process, when it is a windows installation:
-C:\Users\User1\AppData\Local\VirtualStore\Program Files\OCR (gImageReader)\share\myspell\dicts
-C:\Users\User1\AppData\Local\VirtualStore\Program Files\OCR (gImageReader)\share\tessdata
(?)

**Comment by manisandro** [comment]
I'm not really sure which version of Windows are affected in which way, so it is not that simple... But if the tessdata manager is working, ideally users shouldn't need to worry about where exactly to place the files. But sure, I can add a node in the manual.
