### ISSUE TITLE
Add possibility to manually define graphic regions in hOCR mode

### ISSUE THREAD

**Issue by Golddouble** [manisandro/gImageReader#85]
In plaintext modus we can use the wand for automatic layout recognition.

Why can't we use the wand  for automatic layout recognition when we want to make a PDF without invisibly text-overlay?

**Comment by manisandro** [comment]
How should the wand behave in your view in hOCR mode?
Plain text mode is text-block oriented, i.e. you define the selection you want to recognize.
hOCR mode is page-oriented, i.e. the entire page is recognized and the result structured into paragraphs, lines, words, etc, and then you can select which blocks you want to export.

**Comment by Golddouble** [comment]
OK.
I thought if the input- document has sections with text-picture and sections with picture-pictures (which can not be recognized as text) the wand could also find the text sections and the picture sections. Then he can recognize the text sections and structure them into paragraphs, lines, words, etc, and between them he can insert the picture-picture sections.

It was only a thought. I do not know how exactly it works and what can be done or not.

**Comment by manisandro** [comment]
I'm not sure I understand what you mean.
In hOCR mode, tesseract does indeed distinguish between text sections and picture sections, and lists them accordingly in the output tree. If you are looking for a way to actually re-format the document, this is another story. Of course one could add a rich-text editor mode for this, but then the risk is turning the application into yet another word-processor, and that is re-inventing the wheel. I'd rather plan on having rtf export or something similar, so that you can import the result in a word processor and edit further there.

**Comment by manisandro** [comment]
Closing, feel free to ask if further questions.

**Comment by Golddouble** [comment]
> I'm not sure I understand what you mean.

For better understanding here is an example:

Input:
It contains picture- text and two picture- pictures:
![input](https://cloud.githubusercontent.com/assets/13977359/17615385/4813314e-606e-11e6-89fa-4e7861b1e963.PNG)

Output hOCR, PDF without invisibl text overlay:
It contains only the text- text without picture- pitures:
![output hocr pdf without invisibl text overlay](https://cloud.githubusercontent.com/assets/13977359/17615436/9a191fd0-606e-11e6-807d-b4ea490b03d7.PNG)

So I understand now what you mean with 
> tesseract does indeed distinguish between text sections and picture sections

I get the same result as with the plain text OCR modus.
My thought was: When using the plain text modus it is not possible to keep the picture- pictures because the txt- format does not allow this. But when it is generating a PDF it could transfer the picture- pictures- sections as pictures and integrate it in the PDF.

**Comment by manisandro** [comment]
tesseract does segmentize the image and typically is able to detect graphics. However, in some occasion it indeed fails to do so (especially with diagrams and sketches like the above). I suppose the solution here would be to add a function in the hOCR editor to manually define an image region. Would that solve your problem?

**Comment by Golddouble** [comment]
Yes, this would be helpful.

Do I understand correct. Tesseract is basically able to detect graphics and to integrate it in an "hOCR, PDF without invisibl text overlay"? I did not find any example, to get this.

**Comment by manisandro** [comment]
First, the PDF processing is done by gImageReader, not by tesseract. What tesseract does give me is the hOCR document (which you can see in the "source" tab of the output editor), from which I can read all document structure and content related information.

Non-text areas are described in the hOCR document as boxes without text content. These areas will appear as Graphic items in the document structure in the tree of the output editor.

Based on the document structure in the output editor tree, gImageReader generates a PDF.

**Comment by manisandro** [comment]
Implemented in 2a4e8f6

**Comment by Golddouble** [comment]
I did not found this feature in the preview. Am I missing something?

**Comment by manisandro** [comment]
The preview builds were from yesterday, i.e. too old. I've updated them now.
