### ISSUE TITLE
Can't run the gImageReader on Win7 32 bit

### ISSUE THREAD

**Issue by falcet** [manisandro/gImageReader#86]
Can't run a program in Windows 7 32 bit. After trying to start a program from the Start menu I got a message window "This version of file is not compatible with that version of Windows. Define a version of Windows (32 or 64 bit) and ask a supported version of file from distributor". The problem is in fact that distributive has only one version (x86_64).
![win7_32bit](https://cloud.githubusercontent.com/assets/20971504/17591316/4b30d260-5fe6-11e6-8128-a31cfc8d4b1f.png)

I've tested gImageReader with Win7 64bit and Win10 64 bit and it works fine.

**Comment by manisandro** [comment]
Uhm, but did you install the 32bit version on the 32bit OS?

**Comment by falcet** [comment]
But there is only one version of installation file is available (x86_64).
Where could I find installation file for the x86 architecture only?

**Comment by manisandro** [comment]
https://github.com/manisandro/gImageReader/releases/download/v3.1.91/gImageReader_3.1.91_qt5_i686.exe is the 32bit version (listed in the Releases page as gImageReader_3.1.91_qt5_i686.exe)

**Comment by falcet** [comment]
Thank you! Sorry, it wasn't obviously for me.

**Comment by manisandro** [comment]
Yeah suppose I should make it clearer which is which... Next release ;)
