### ISSUE TITLE
gImageReader under Win10

### ISSUE THREAD

**Issue by Henry-HC** [manisandro/gImageReader#87]
I just installed gImagereader under Win 10. The installation ran without any problem. When try to start the program I get the message "This app can't be executed on your PC" (message is in German, since I have installed the German version).

Doea anybody know what went wrong and what I can do?
Henry

**Comment by manisandro** [comment]
Hi,
Possibly you installed the 64bit version (x86_64) on a 32-bit os?

**Comment by manisandro** [comment]
Closing since no reply.
