### ISSUE TITLE
Idea: change the name of the hocr pdf output

### ISSUE THREAD

**Issue by narayaan** [manisandro/gImageReader#88]
If I process a file with eg the name "test" and use the hOCR mode  I have the ability to export to pdf.  The standard name that is used is just "output". I know I can change this while saving, but it would make the workflow quicker if the filename of the output automaticly became output_test or maybe even better: gImagereader_test (like in pdfSAM for example).

**Comment by manisandro** [comment]
Thanks for the suggestion.
