### ISSUE TITLE
Detect layout button at the wrong place?

### ISSUE THREAD

**Issue by CharlesNepote** [manisandro/gImageReader#89]
(First of all thank you for the great job!)
I'm using 3.1.91 on Ubuntu 16/04.

"Detect layout" button (hope it's the right name -- "Détecter la mise en page" in french) has no relationship with "hOCR, PDF|Text" and "Recognize selection" buttons, right? From my point of view, it shouldn't be standing between these two last buttons. And it should be separated from those buttons by a space.
So "hOCR, PDF|Text" and "Recognize selection" buttons should be more closed to each other, because "Recognize selection" action depend on "hOCR, PDF|Text" choice.

When I selected the "Detect layout" button, I was thinking that the next step would be then to select "Recognize selection", but this latter function use its own "detect layout" algorithm isn't it?

Charles.

**Comment by manisandro** [comment]
Hi
No the "Autodetect layout" button is very tightly related to the recognize button. In plain text mode (and only in this mode the button is visible), you can pick the recognition in three different ways
- Simply press the recognize button, and the entire page will be recognized
- Manually define the regions in the canvas, and then press the recognize button
- Press the autodetect layout button, which will result in sensible areas getting selected, and then press the recognize button.

So from my point of view the position is consistent with the workflow:
1. You first choose the OCR mode
2. In plain text mode, you then define the recognition area
3. As final step, you launch recognition

Feel free to reopen if I misunderstood something.

**Comment by CharlesNepote** [comment]
Thanks for your clear reply.

For me the button is not only visible in "plain text" mode.
1. I choose the "plain text" mode => the "autodetect layout" button appear
2. Get back to "hOCR" mode => the "autodetect layout" button doesn't disappear, shouldn't it?

I can send you more details and a picture if necessary.

**Comment by manisandro** [comment]
I recall fixing something like this just a few weeks ago, so it likely is a bug in the latest beta which is fixed in master.
