### ISSUE TITLE
file access

### ISSUE THREAD

**Issue by Golddouble** [manisandro/gImageReader#91]
Version in use: preview from 2016-08-14 (Windows 7, 32bit)

**How to reproduce:**
1. I have the PDF- File "Name1" open in the acrobat Reader.
2. I export a new PDF from gImageReader with the name "Name1" to the same folder.
3. I close file "Name1" in Acrobat Reader.
4. I open the file "Name1" in Acrobat Reader. 
So my expection was that now the file is from 2. but it is still from 1..

**Suggestion:** gImageReader should show a message, if it can not overwrite a file.

**Comment by manisandro** [comment]
Fixed in 636983a.

**Comment by Golddouble** [comment]
Thank you for implementing this. 

It works with the preview.

**Comment by manisandro** [comment]
Is the file in use by another application?

**Comment by Golddouble** [comment]
No.

**Comment by Golddouble** [comment]
Sorry. I tried it now again. And now it works as expected. Thank you.
