### ISSUE TITLE
Merge boxes in hOCR

### ISSUE THREAD

**Issue by CharlesNepote** [manisandro/gImageReader#92]
Sometimes the OCR fails to identify a whole word on a given line. There is two boxes for a word:
* BULLE"...
* N
instead of "BULLETIN".

In 3.1.91 version, it's not possible to merge the two boxes and correct BULLE"...N into BULLETIN.
I understand it's probably not simple. A simple way to do it would be to select a box and, with mouse right-button, select "merge with next block". The new block would heritate its properties from the first one except the merged contents and limits.

**Comment by manisandro** [comment]
Do you mean merging two text blocks in hOCR mode?

**Comment by CharlesNepote** [comment]
Yes I mean merging two text blocks in hOCR mode, because a word is incorrectly splited into two blocks. See the example below: the word "BULLETIN" is splited into two blocks or boxes (I don't how to call it). Here the letter "N" should be in the latter block.
![test](https://cloud.githubusercontent.com/assets/562352/18234056/b819c57e-72f8-11e6-9b98-a82c811fda9d.jpg)

I know I can do it by hand, playing with metadata of each block but it's a pain.

**Comment by manisandro** [comment]
Sure makes sense, I'll look into it.

**Comment by manisandro** [comment]
Implemented in f0aa402
