### ISSUE TITLE
Compilation howto

### ISSUE THREAD

**Issue by CharlesNepote** [manisandro/gImageReader#95]
I would like to help testing last commits but I don't know how to install gImageReader from the sources.
Could you write a short howto for that? It doesn't have to be perfect at the first time. I will test this howto and give you feedbacks.
But for the moment I don't have any idea where to start.

Thanks a lot Sandro !

**Comment by manisandro** [comment]
What platform are you on?

**Comment by CharlesNepote** [comment]
Ubuntu 16.04, 64bits.

**Comment by manisandro** [comment]
If you have my PPA enabled, something like

    sudo apt-get build-dep gimagereader-gtk

or

    sudo apt-get build-dep gimagereader-qt

will install all the necessary build dependencies (depending on whether you want the qt or gtk interface). Otherwise, they are listed in `packaging/debian/control`

Then, from the source directory:

    mkdir build
    cd build
    cmake -DINTERFACE_TYPE=gtk .. # or qt5 instead of gtk
    make

You can the run directly from the build directory, for the gtk interface:

   export XDG_DATA_DIRS=$PWD:$XDG_DATA_DIRS
   ./gimagereader-gtk

Or for the qt interface:

    ./gimagereader-qt

That should be it.

**Comment by CharlesNepote** [comment]
I had your ppa enabled so sudo apt-get build-dep gimagereader worked very well.
Then I:
```
mkdir gImageReader
cd gImageReader
git clone https://github.com/manisandro/gImageReader.git
cd gImageReader
mkdir build
cd build
cmake -DINTERFACE_TYPE=gtk ..
make
```

All command passed with no errors except "make" which complain a lot and failed... (I copied/pasted from the first block where I could read "error". I can send you the whole result by email.)
```
In file included from /media/charles/DONNEES/pr/gImageReader/gImageReader/gtk/src/Displayer.hh:23:0,
                 from /media/charles/DONNEES/pr/gImageReader/gImageReader/gtk/src/DisplayerToolHOCR.hh:23,
                 from /media/charles/DONNEES/pr/gImageReader/gImageReader/gtk/src/OutputEditorHOCR.cc:28:
/media/charles/DONNEES/pr/gImageReader/gImageReader/gtk/src/OutputEditorHOCR.cc: In lambda function:
/media/charles/DONNEES/pr/gImageReader/gImageReader/gtk/src/OutputEditorHOCR.cc:783:13: error: ‘class GtkSpell::Checker’ has no member named ‘add_to_dictionary’
     m_spell.add_to_dictionary((*it)[m_itemStoreCols.text]);
             ^
/media/charles/DONNEES/pr/gImageReader/gImageReader/gtk/src/common.hh:49:68: note: in definition of macro ‘CONNECT’
 #define CONNECT(src, signal, ...) (src)->signal_##signal().connect(__VA_ARGS__)
                                                                    ^
/media/charles/DONNEES/pr/gImageReader/gImageReader/gtk/src/OutputEditorHOCR.cc: In lambda function:
/media/charles/DONNEES/pr/gImageReader/gImageReader/gtk/src/OutputEditorHOCR.cc:789:13: error: ‘class GtkSpell::Checker’ has no member named ‘ignore_word’
     m_spell.ignore_word((*it)[m_itemStoreCols.text]);
             ^
/media/charles/DONNEES/pr/gImageReader/gImageReader/gtk/src/common.hh:49:68: note: in definition of macro ‘CONNECT’
 #define CONNECT(src, signal, ...) (src)->signal_##signal().connect(__VA_ARGS__)
                                                                    ^
CMakeFiles/gimagereader.dir/build.make:335 : la recette pour la cible « CMakeFiles/gimagereader.dir/gtk/src/OutputEditorHOCR.cc.o » a échouée
make[2]: *** [CMakeFiles/gimagereader.dir/gtk/src/OutputEditorHOCR.cc.o] Erreur 1
CMakeFiles/Makefile2:136 : la recette pour la cible « CMakeFiles/gimagereader.dir/all » a échouée
make[1]: *** [CMakeFiles/gimagereader.dir/all] Erreur 2
Makefile:127 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2
```
```

**Comment by manisandro** [comment]
Ah, right, you need a newer version of gtkspell and gtkspellmm... I'll submit these to the PPA tomorrow.

**Comment by manisandro** [comment]
Ok finally the packages are built in the PPA, with they hope they actually work... Give it a try.

**Comment by CharlesNepote** [comment]
Failed. What I have done:
```
sudo apt update
sudo apt upgrade # it upgraded gtkspell

```
Then controlled if right packages are installed:
```
dpkg-query -W -f='${Status} \t${binary:Package} \t${Version}\t${Maintainer}\n' 'libgtkspell*'

unknown ok not-installed 	libgtkspell-3-0 		
unknown ok not-installed 	libgtkspell-3-dev 		
install ok installed 	libgtkspell0 	2.0.16-1.1ubuntu1	Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
install ok installed 	libgtkspell3-3-0:amd64 	3.0.9-1~xenialppa2	Debian GNOME Maintainers <pkg-gnome-maintainers@lists.alioth.debian.org>
install ok installed 	libgtkspell3-3-dev:amd64 	3.0.9-1~xenialppa2	Debian GNOME Maintainers <pkg-gnome-maintainers@lists.alioth.debian.org>
unknown ok not-installed 	libgtkspellmm-1.0-doc 		
unknown ok not-installed 	libgtkspellmm-3.0-0 		
install ok installed 	libgtkspellmm-3.0-0v5:amd64 	3.0.5-1~xenialppa2	Sandro Mani <manisandro@gmail.com>
unknown ok not-installed 	libgtkspellmm-3.0-1 		
install ok installed 	libgtkspellmm-3.0-dev:amd64 	3.0.5-1~xenialppa2	Sandro Mani <manisandro@gmail.com>
```
Seems to be ok.
Then:
```
cd build
rm -R * # delete old data from previous compilation
cmake -DINTERFACE_TYPE=gtk ..
make # process succeded without errors
export XDG_DATA_DIRS=$PWD:$XDG_DATA_DIRS
./gimagereader-gtk 

(gimagereader-gtk:11823): GLib-GIO-ERROR **: Settings schema 'org.gnome.gimagereader' is not installed

Trace/breakpoint trap (core dumped)
```

Sorry not to help more, I'm not a programmer (but practicing Linux Debian/Ubuntu for 15+ years).

**Comment by manisandro** [comment]
The

    export XDG_DATA_DIRS=$PWD:$XDG_DATA_DIRS

line appears to not have worked. Verify that the `XDG_DATA_DIRS` environment variable contains the build directory.

**Comment by CharlesNepote** [comment]
```
$ pwd
/media/charles/DONNEES/pr/gImageReader/gImageReader/build

$ export | grep 'XDG_DATA_DIR'
declare -x XDG_DATA_DIRS="/media/charles/DONNEES/pr/gImageReader/gImageReader/build:/usr/share/xubuntu:/usr/share/xfce4:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop:/usr/share"
```
XDG_DATA_DIR seems ok but still "core dump".

**Comment by manisandro** [comment]
No idea what that should not work. Alternatively, just build the qt5 interface which does not require the schemas stuff.

**Comment by CharlesNepote** [comment]
The qt5 build works (even if I experiment strange things in gImageReader-qt: there's nearly no icons for buttons; there's only text buttons). May be some QT librairies are missing as I work with XFCE.

But it's ok to test some of the last functionnalities. Block merge works VERY well thanks a lot!

**Comment by manisandro** [comment]
The missing icons is an icon theme issue. Closing this ticket. Thanks for your testing feedback!

**Comment by CharlesNepote** [comment]
> The missing icons is an icon theme issue.

Do I have to install a particular Ubuntu package to solve the problem?

Do you want me to write the "compilation howto" documentation and publish it somewhere?

**Comment by manisandro** [comment]
If you start the application from the terminal you might get some warning messages about missing icons. You can the look for a package which provides these icons. I'm on Fedora, and here as far as Gnome/Gtk is concerned adwaita-icon-theme ships what is necessary. It might also be a theme issue rather than the icons missing though.

Howto: something like:

Compilation:
---------------
To build gImageReader from source on Linux, follow these steps:
  1. Install all required build dependencies.
    - For Fedora, they are listed as `BuildRequires` in `packaging/gimagereader.spec.in`
    - For Debian/Ubuntu, they are listed as `Build-Depends` in `packaging/debian/control`
  2. From within the source directory, type

          mkdir build
          cd build
          cmake -DINTERFACE_TYPE=<type>  # where type is one of gtk, qt4 or qt5
          make

  3. You can run the application directly from the build directory by typing

          export XDG_DATA_DIRS=$PWD:$XDG_DATA_DIRS  # needed for gtk interface only
          ./gimagereader-<type> # where type is one of gtk, qt4 or qt5

The Windows builds are currently cross-compiled from Fedora's MinGW
environment.
  - You will need to install the `mingw{32/64}-<pkgname>` packages
corresponding to those listed in `packaging/gimagereader.spec.in`.
  - Then, running `packaging/win32/makeinstaller.sh {i686/x86_64} {gtk/qt4/qt5}` will build the
Windows installer.


?

**Comment by CharlesNepote** [comment]
I'm still having problems to see icons in gimagereader-qt5 under Ubuntu 16.05.
But I've made some progresses. After installing libqt5libqgtk2 library, the majority of icons are here. But "Toggle output pane" icon is still missing.

At least, you should add libqt5libqgtk2 to requirements in https://github.com/manisandro/gImageReader/blob/master/packaging/debian/control isn't it?

**Comment by manisandro** [comment]
The toggle output pane icon is `insert-text`, it is possible that you theme does not provide that icon.

No, the `libqt5libqgtk2` dep is needed for the qt theme you are using. Applications never have requirements on a theme or its dependencies.
