### ISSUE TITLE
In "plain text" mode, spell checking return false errors with upper case

### ISSUE THREAD

**Issue by CharlesNepote** [manisandro/gImageReader#96]
A very small issue. See the picture below: BONJOUR MONSIEUR shouldn't be underligned in red y the spell checker.
![pasted_image](https://cloud.githubusercontent.com/assets/562352/18385775/deab8dec-7692-11e6-976a-0edc80add38f.png)

**Comment by manisandro** [comment]
This is up to the spellchecking library (i.e. enchant), not a gImageReader issue.
