### ISSUE TITLE
Tooltips for buttons in the "file" pane and the "output" pane

### ISSUE THREAD

**Issue by CharlesNepote** [manisandro/gImageReader#98]
There are few very small issues there.
* Mouse over the second button of the "file" pane (dropdown arrow => [ v ]) show "select language" tooltip
* Idem for the second and the fourth button of the "output" pane (dropdown arrow => [ v ])
* There is no tooltip when mouse come over "post-processing tools button"

**Comment by manisandro** [comment]
Sorry not following, could you post a screenshot.

**Comment by CharlesNepote** [comment]
Here is a screenshot (unfortunatly the mouse pointer is not shown but you guess it on the dropdown menu which is highlighted):
![capture d ecran_2016-09-09_23-09-15](https://cloud.githubusercontent.com/assets/562352/18403021/bc9f14ee-76e2-11e6-93c9-f30e2eb3edc8.png)
You can see that the tooltip is "Selectionner langue" ("select language") which is not correct here.

(For this screenshot I'm using gImageReader 3.1.91 under Xubuntu 16.04.)

**Comment by manisandro** [comment]
Oh, good catch! I was looking at the qt interface and didn't see any issue there, but yes, a classical copy-paste bug in the gtk interface! Fixed in 7c1033b.
